/**
 * Secteur « Administratif » — parcours (4 couches).
 *
 * sector:'admin', type ∈ {comportemental, technique, situation, actu}.
 * Une seule option correct:true, + explanation + tip. `context` optionnel.
 */
const base = { sector: 'admin' };

export default [
  // ══════════════ 🧠 COMPORTEMENTAL ══════════════
  {
    ...base, id: 'adm-cp-1', type: 'comportemental', difficulty: 1,
    situation: "« Pourquoi le métier de l'administratif vous attire-t-il ? »",
    question: "La motivation la plus crédible :",
    options: [
      { text: "« Parce que c'est un métier tranquille où il n'y a rien à faire »", correct: false },
      { text: "Le goût de l'organisation, de la rigueur et du rôle de soutien indispensable", correct: true },
      { text: "« Parce que je ne savais pas quoi faire d'autre »", correct: false },
      { text: "« Pour éviter le contact avec les gens »", correct: false },
    ],
    explanation: "L'administratif est la colonne vertébrale d'une organisation. On valorise le sens du service, l'organisation et la fiabilité — pas l'idée d'un métier « peinard ».",
    tip: "Mets en avant rigueur, organisation et esprit de service.",
  },
  {
    ...base, id: 'adm-cp-2', type: 'comportemental', difficulty: 2,
    situation: "« Comment gérez-vous plusieurs tâches en même temps ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Je fais tout en même temps, au hasard »", correct: false },
      { text: "Je priorise selon l'urgence et l'importance, et je planifie", correct: true },
      { text: "« Je traite uniquement ce qui me plaît »", correct: false },
      { text: "« J'attends qu'on me dise quoi faire »", correct: false },
    ],
    explanation: "La capacité à prioriser (urgent/important) et à s'organiser est LA compétence clé de l'administratif. On montre une méthode, pas de l'improvisation.",
    tip: "Cite une méthode : to-do list, matrice urgent/important.",
  },
  {
    ...base, id: 'adm-cp-3', type: 'comportemental', difficulty: 2,
    situation: "« La rigueur et le sens du détail, qu'en pensez-vous ? »",
    question: "La meilleure posture :",
    options: [
      { text: "« Les détails, ce n'est pas important »", correct: false },
      { text: "Essentiels : une petite erreur de saisie peut avoir de grosses conséquences", correct: true },
      { text: "« Je préfère aller vite quitte à faire des fautes »", correct: false },
      { text: "« La relecture, c'est une perte de temps »", correct: false },
    ],
    explanation: "Un IBAN, un montant ou une date erronés peuvent coûter cher. La rigueur et la relecture systématique sont au cœur du métier administratif.",
    tip: "Donne un exemple où ta rigueur a évité une erreur.",
  },
  {
    ...base, id: 'adm-cp-4', type: 'comportemental', difficulty: 2,
    situation: "Vous traitez des documents sensibles (RH, paie, contrats).",
    question: "Quelle qualité est attendue avant tout ?",
    options: [
      { text: "Partager les infos intéressantes avec ses collègues", correct: false },
      { text: "La discrétion et le respect strict de la confidentialité", correct: true },
      { text: "Commenter les salaires des autres", correct: false },
      { text: "Laisser les dossiers ouverts sur son bureau", correct: false },
    ],
    explanation: "L'administratif manipule des données confidentielles. La discrétion est non négociable : c'est une question de déontologie et de RGPD.",
    tip: "Confidentialité = règle d'or, sans exception.",
  },
  {
    ...base, id: 'adm-cp-5', type: 'comportemental', difficulty: 2,
    situation: "« Vous êtes souvent interrompu(e) dans votre travail. Comment réagissez-vous ? »",
    question: "La meilleure attitude :",
    options: [
      { text: "S'énerver contre les personnes qui dérangent", correct: false },
      { text: "Rester disponible et flexible, tout en sachant reprendre le fil de ses tâches", correct: true },
      { text: "Ignorer toutes les sollicitations", correct: false },
      { text: "Abandonner ce qu'on faisait définitivement", correct: false },
    ],
    explanation: "Les interruptions font partie du métier (accueil, sollicitations). On allie disponibilité et capacité à se replonger dans son travail sans tout laisser tomber.",
    tip: "Montre flexibilité ET capacité de concentration.",
  },
  {
    ...base, id: 'adm-cp-6', type: 'comportemental', difficulty: 2,
    situation: "« On vous confie des tâches très variées. Est-ce un problème ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Oui, je n'aime que la routine »", correct: false },
      { text: "Non, la polyvalence me plaît et me rend plus utile", correct: true },
      { text: "« Je refuse tout ce qui n'est pas dans ma fiche de poste »", correct: false },
      { text: "« Je fais une chose à la fois et tant pis pour le reste »", correct: false },
    ],
    explanation: "La polyvalence est très recherchée en administratif. Montrer qu'on l'apprécie et qu'on s'adapte est un vrai atout, surtout en PME.",
    tip: "La polyvalence est un argument, pas une contrainte.",
  },

  // ══════════════ 🛠️ TECHNIQUE MÉTIER ══════════════
  {
    ...base, id: 'adm-te-1', type: 'technique', difficulty: 1,
    situation: "Outils du quotidien.",
    question: "Quels outils maîtriser en priorité dans l'administratif ?",
    options: [
      { text: "Des logiciels de montage vidéo", correct: false },
      { text: "La suite bureautique : traitement de texte, tableur, messagerie, agenda", correct: true },
      { text: "Uniquement les réseaux sociaux", correct: false },
      { text: "Des logiciels de jeux", correct: false },
    ],
    explanation: "Word/Excel (ou Google Docs/Sheets), la messagerie et l'agenda sont la base. Une bonne maîtrise du tableur fait souvent la différence.",
    tip: "Excel/Sheets : maîtrise tri, filtre et formules de base.",
  },
  {
    ...base, id: 'adm-te-2', type: 'technique', difficulty: 2,
    situation: "Gestion documentaire.",
    question: "Qu'est-ce que la GED ?",
    options: [
      { text: "Un type de contrat", correct: false },
      { text: "La Gestion Électronique des Documents : numériser, classer et retrouver les documents", correct: true },
      { text: "Une réunion hebdomadaire", correct: false },
      { text: "Un logiciel de paie", correct: false },
    ],
    explanation: "La GED permet de dématérialiser, indexer et retrouver rapidement les documents. C'est un pilier de l'administration moderne (fin du tout-papier).",
    tip: "Connaître la GED montre que tu es à jour sur la dématérialisation.",
  },
  {
    ...base, id: 'adm-te-3', type: 'technique', difficulty: 2,
    situation: "Classement et archivage.",
    question: "Pourquoi respecter des durées légales de conservation ?",
    options: [
      { text: "Pour remplir les placards", correct: false },
      { text: "Parce que la loi impose de conserver certains documents un temps minimum (puis de les détruire)", correct: true },
      { text: "Il n'y a aucune règle, on garde tout à vie", correct: false },
      { text: "On peut tout jeter immédiatement", correct: false },
    ],
    explanation: "Bulletins de paie, factures, contrats… ont des durées légales de conservation (souvent 5 à 10 ans). Les connaître évite des risques juridiques.",
    tip: "Ex : factures conservées 10 ans en entreprise.",
  },
  {
    ...base, id: 'adm-te-4', type: 'technique', difficulty: 2,
    situation: "Organisation des réunions.",
    question: "Comment planifier efficacement une réunion ?",
    options: [
      { text: "Envoyer un message vague « on se voit un jour »", correct: false },
      { text: "Vérifier les disponibilités, envoyer une invitation agenda avec objet, lieu et ordre du jour", correct: true },
      { text: "Convoquer tout le monde sans prévenir", correct: false },
      { text: "Ne rien préparer", correct: false },
    ],
    explanation: "Une réunion bien planifiée a un créneau validé, un objet clair, un ordre du jour et les bonnes personnes invitées. C'est un savoir-faire administratif classique.",
    tip: "Toujours un ordre du jour : ça cadre la réunion.",
  },
  {
    ...base, id: 'adm-te-5', type: 'technique', difficulty: 2,
    situation: "Rédaction professionnelle.",
    question: "Qu'attend-on d'un compte-rendu de réunion ?",
    options: [
      { text: "Un roman détaillé de chaque phrase prononcée", correct: false },
      { text: "Une synthèse claire : décisions prises, actions, responsables et échéances", correct: true },
      { text: "Des opinions personnelles sur les participants", correct: false },
      { text: "Rien, on s'en souviendra", correct: false },
    ],
    explanation: "Un bon compte-rendu est synthétique et actionnable : ce qui a été décidé, qui fait quoi, pour quand. C'est un outil de suivi, pas une transcription.",
    tip: "Mets en avant « qui fait quoi pour quand ».",
  },
  {
    ...base, id: 'adm-te-6', type: 'technique', difficulty: 2,
    situation: "Accueil et standard.",
    question: "Quelle est la bonne pratique pour l'accueil téléphonique ?",
    options: [
      { text: "Répondre sèchement et raccrocher vite", correct: false },
      { text: "Se présenter, écouter, reformuler et orienter vers le bon interlocuteur", correct: true },
      { text: "Laisser sonner sans répondre", correct: false },
      { text: "Mettre en attente indéfiniment", correct: false },
    ],
    explanation: "L'accueil est la vitrine de l'entreprise. Présentation, écoute, reformulation et bonne orientation sont les réflexes attendus.",
    tip: "Souris au téléphone : ça s'entend.",
  },
  {
    ...base, id: 'adm-te-7', type: 'technique', difficulty: 3,
    situation: "Tableur.",
    question: "À quoi sert un filtre dans un tableur ?",
    options: [
      { text: "À changer la couleur de l'écran", correct: false },
      { text: "À n'afficher que les lignes correspondant à un critère donné", correct: true },
      { text: "À supprimer définitivement des données", correct: false },
      { text: "À imprimer le document", correct: false },
    ],
    explanation: "Le filtre permet d'isoler rapidement les données utiles (ex : tous les clients d'une ville). Avec le tri et la RECHERCHEV, c'est un basique très demandé.",
    tip: "Maîtrise tri, filtre et RECHERCHEV : ça impressionne.",
  },
  {
    ...base, id: 'adm-te-8', type: 'technique', difficulty: 2,
    situation: "Traitement du courrier.",
    question: "Qu'est-ce qu'un « parapheur » ?",
    options: [
      { text: "Un stylo spécial", correct: false },
      { text: "Un classeur (papier ou électronique) regroupant les documents à faire signer", correct: true },
      { text: "Une réunion de direction", correct: false },
      { text: "Un logiciel de paie", correct: false },
    ],
    explanation: "Le parapheur centralise les documents nécessitant une signature. Il existe désormais en version électronique (parapheur numérique).",
    tip: "Le parapheur électronique fluidifie les validations.",
  },
  {
    ...base, id: 'adm-te-9', type: 'technique', difficulty: 3,
    situation: "Envoi en nombre.",
    question: "À quoi sert le « publipostage » (mailing) ?",
    options: [
      { text: "À trier le courrier reçu", correct: false },
      { text: "À générer des documents personnalisés en série à partir d'une liste (ex : courriers nominatifs)", correct: true },
      { text: "À supprimer des emails", correct: false },
      { text: "À archiver des factures", correct: false },
    ],
    explanation: "Le publipostage fusionne un modèle (lettre, étiquette, email) avec une base de données pour personnaliser un envoi de masse. Un grand classique de la bureautique.",
    tip: "Word + Excel = publipostage, une compétence valorisée.",
  },

  // ══════════════ 🎭 MISE EN SITUATION ══════════════
  {
    ...base, id: 'adm-si-1', type: 'situation', difficulty: 2,
    context: "Il est 16h. Votre manager vous demande un dossier « pour tout de suite », pendant qu'un client au téléphone attend une réponse urgente.",
    situation: "Deux urgences en même temps.",
    question: "La meilleure réaction :",
    options: [
      { text: "Paniquer et ne rien faire", correct: false },
      { text: "Évaluer la priorité réelle, gérer l'immédiat et annoncer un délai clair pour l'autre", correct: true },
      { text: "Ignorer le client pour faire plaisir au manager", correct: false },
      { text: "Faire les deux à moitié, mal", correct: false },
    ],
    explanation: "On garde son calme, on hiérarchise, on traite ce qui ne peut pas attendre et on communique un délai pour le reste. Savoir dire « je m'en occupe dans 10 min » est pro.",
    tip: "Prioriser et communiquer un délai vaut mieux que tout bâcler.",
  },
  {
    ...base, id: 'adm-si-2', type: 'situation', difficulty: 2,
    context: "Vous trouvez sur l'imprimante commune un document RH confidentiel oublié par un collègue (un bulletin de salaire).",
    situation: "Document confidentiel laissé en évidence.",
    question: "La bonne réaction :",
    options: [
      { text: "Le lire par curiosité", correct: false },
      { text: "Le récupérer discrètement et le rendre à la personne concernée sans le diffuser", correct: true },
      { text: "Le laisser traîner", correct: false },
      { text: "En parler à toute l'équipe", correct: false },
    ],
    explanation: "On protège la confidentialité : récupérer le document et le restituer discrètement, sans le lire ni le commenter. C'est une question de déontologie et de RGPD.",
    tip: "Confidentiel = on protège, on ne diffuse jamais.",
  },
  {
    ...base, id: 'adm-si-3', type: 'situation', difficulty: 3,
    context: "Vous réalisez qu'un courrier officiel envoyé hier contenait une erreur de montant.",
    situation: "Erreur détectée dans un document déjà envoyé.",
    question: "La meilleure réaction :",
    options: [
      { text: "Ne rien dire et espérer que personne ne remarque", correct: false },
      { text: "Prévenir immédiatement son responsable et proposer une correction (rectificatif)", correct: true },
      { text: "Accuser un collègue", correct: false },
      { text: "Supprimer toute trace de l'envoi", correct: false },
    ],
    explanation: "On assume l'erreur vite : prévenir, proposer un rectificatif et corriger. La transparence limite les conséquences ; dissimuler les aggrave.",
    tip: "Une erreur signalée tôt se règle ; cachée, elle explose.",
  },
  {
    ...base, id: 'adm-si-4', type: 'situation', difficulty: 2,
    context: "Un visiteur se présente à l'accueil, agacé : son rendez-vous a du retard et il s'impatiente.",
    situation: "Visiteur mécontent à l'accueil.",
    question: "La bonne attitude :",
    options: [
      { text: "L'ignorer en attendant que ça passe", correct: false },
      { text: "L'accueillir avec calme, l'informer du délai et lui proposer de patienter confortablement", correct: true },
      { text: "Lui dire que ce n'est pas votre problème", correct: false },
      { text: "Hausser le ton à votre tour", correct: false },
    ],
    explanation: "On désamorce avec courtoisie : reconnaître l'attente, informer honnêtement et proposer une solution (café, salle d'attente). L'accueil reflète l'image de la structure.",
    tip: "Calme + information honnête = tension qui retombe.",
  },
  {
    ...base, id: 'adm-si-5', type: 'situation', difficulty: 3,
    context: "On vous demande d'organiser une réunion réunissant 8 personnes aux agendas très chargés, sous 10 jours.",
    situation: "Caler une réunion à 8 participants.",
    question: "La méthode la plus efficace :",
    options: [
      { text: "Proposer un seul créneau et tant pis pour les absents", correct: false },
      { text: "Utiliser un sondage de disponibilités / agendas partagés, puis confirmer le meilleur créneau", correct: true },
      { text: "Appeler chacun séparément sans rien noter", correct: false },
      { text: "Laisser les gens s'organiser entre eux", correct: false },
    ],
    explanation: "Un outil de disponibilités (Doodle, sondage Teams, agendas partagés) permet de trouver le créneau qui convient au plus grand nombre, puis on confirme officiellement.",
    tip: "Sondage de dispo > emails interminables.",
  },
  {
    ...base, id: 'adm-si-6', type: 'situation', difficulty: 2,
    context: "Votre boîte mail déborde : 60 messages non lus ce matin.",
    situation: "Surcharge de mails.",
    question: "La meilleure méthode de traitement :",
    options: [
      { text: "Tout lire dans le désordre sans rien traiter", correct: false },
      { text: "Trier par priorité, traiter le rapide immédiatement, planifier le reste, archiver", correct: true },
      { text: "Tout supprimer pour repartir à zéro", correct: false },
      { text: "Attendre que ça se calme tout seul", correct: false },
    ],
    explanation: "Une méthode type « traiter / déléguer / planifier / archiver » évite la noyade. On répond vite à ce qui prend 2 min, on planifie le reste.",
    tip: "Inspire-toi de la règle des 2 minutes.",
  },
  {
    ...base, id: 'adm-si-7', type: 'situation', difficulty: 3,
    context: "🏆 BOSS — Lundi 9h. Sur ton bureau : 3 dossiers urgents, 2 réunions à organiser, le téléphone qui sonne et ton manager qui veut un point.",
    situation: "Journée surchargée à organiser.",
    question: "Par quoi commencer ?",
    options: [
      { text: "Faire tout en même temps et au feeling", correct: false },
      { text: "Lister puis hiérarchiser (urgent/important), traiter dans l'ordre et communiquer les délais", correct: true },
      { text: "Commencer par les tâches les plus agréables", correct: false },
      { text: "Attendre que la pression retombe", correct: false },
    ],
    explanation: "Face à la surcharge, la clé est de poser à plat, hiérarchiser (matrice d'Eisenhower : urgent/important) et avancer méthodiquement en informant des délais. L'organisation bat la précipitation.",
    tip: "Urgent ET important d'abord ; le reste se planifie.",
  },

  // ══════════════ 📰 ACTU & TENDANCES (2026) ══════════════
  {
    ...base, id: 'adm-ac-1', type: 'actu', difficulty: 2,
    situation: "Grande tendance de fond.",
    question: "Que signifie la « dématérialisation » des process administratifs ?",
    options: [
      { text: "Supprimer les employés", correct: false },
      { text: "Remplacer le papier par des documents et circuits numériques", correct: true },
      { text: "Détruire tous les documents", correct: false },
      { text: "Travailler sans ordinateur", correct: false },
    ],
    explanation: "La dématérialisation (factures, contrats, signatures, archivage) accélère et sécurise les process. C'est la transformation majeure du métier administratif.",
    tip: "Montre que tu es à l'aise avec le « zéro papier ».",
  },
  {
    ...base, id: 'adm-ac-2', type: 'actu', difficulty: 3,
    situation: "Automatisation des tâches.",
    question: "Que permettent les outils « no-code » (Power Automate, Make, Zapier) ?",
    options: [
      { text: "Coder des logiciels complexes", correct: false },
      { text: "Automatiser des tâches répétitives sans savoir programmer", correct: true },
      { text: "Remplacer Excel par du papier", correct: false },
      { text: "Rien d'utile au bureau", correct: false },
    ],
    explanation: "Les outils no-code automatisent des enchaînements (ex : classer une pièce jointe, créer une tâche à partir d'un mail) sans programmer. L'assistant administratif gagne un temps précieux.",
    tip: "Savoir automatiser une tâche répétitive est un vrai plus en 2026.",
  },
  {
    ...base, id: 'adm-ac-3', type: 'actu', difficulty: 3,
    situation: "L'IA dans le bureau.",
    question: "Comment l'IA générative aide-t-elle un profil administratif ?",
    options: [
      { text: "Elle rend le métier inutile", correct: false },
      { text: "Elle assiste : résumés de réunions, rédaction de mails, tri et synthèse d'infos", correct: true },
      { text: "Elle ne sert qu'aux développeurs", correct: false },
      { text: "Elle fait le café", correct: false },
    ],
    explanation: "L'IA rédige des brouillons, résume, reformule, classe — l'humain garde le contrôle et la relation. Savoir l'utiliser comme assistant est désormais valorisé.",
    tip: "Positionne l'IA comme un assistant, pas une menace.",
  },
  {
    ...base, id: 'adm-ac-4', type: 'actu', difficulty: 2,
    situation: "Travail en équipe à distance.",
    question: "À quoi servent les outils collaboratifs (Teams, SharePoint, Notion) ?",
    options: [
      { text: "À jouer en ligne", correct: false },
      { text: "À partager documents, échanger et coordonner le travail en équipe, même à distance", correct: true },
      { text: "À remplacer le téléphone uniquement", correct: false },
      { text: "À stocker des photos personnelles", correct: false },
    ],
    explanation: "Le travail hybride a généralisé les espaces collaboratifs : documents partagés, suivi de tâches, communication. Les maîtriser est devenu indispensable.",
    tip: "Cite un outil collaboratif que tu sais utiliser.",
  },
  {
    ...base, id: 'adm-ac-5', type: 'actu', difficulty: 2,
    situation: "Protection des données.",
    question: "Pourquoi le RGPD concerne-t-il directement l'administratif ?",
    options: [
      { text: "Ça ne le concerne pas", correct: false },
      { text: "Parce qu'il manipule des données personnelles à protéger (clients, salariés)", correct: true },
      { text: "Parce qu'il interdit d'utiliser un ordinateur", correct: false },
      { text: "Parce qu'il oblige à tout imprimer", correct: false },
    ],
    explanation: "L'administratif traite quotidiennement des données personnelles : il doit en garantir la sécurité, la confidentialité et le bon usage, conformément au RGPD.",
    tip: "RGPD = réflexe sécurité/confidentialité au quotidien.",
  },
  {
    ...base, id: 'adm-ac-6', type: 'actu', difficulty: 2,
    situation: "Validation des documents.",
    question: "Qu'apporte la signature électronique ?",
    options: [
      { text: "Rien, elle n'a aucune valeur", correct: false },
      { text: "Une signature à valeur légale, plus rapide et sans impression papier", correct: true },
      { text: "Une simple image collée sans valeur", correct: false },
      { text: "Un risque juridique systématique", correct: false },
    ],
    explanation: "La signature électronique a une valeur juridique et fluidifie les circuits de validation (contrats, devis) sans papier. Elle s'est généralisée dans les organisations.",
    tip: "Connais des outils comme DocuSign / Yousign.",
  },
  {
    ...base, id: 'adm-ac-7', type: 'actu', difficulty: 3,
    situation: "Évolution du métier.",
    question: "Vers quel rôle évolue souvent l'assistant(e) administratif(ve) ?",
    options: [
      { text: "Vers la disparition pure et simple", correct: false },
      { text: "Vers l'« office manager » : plus de polyvalence, d'autonomie et de responsabilités", correct: true },
      { text: "Vers un poste sans aucune évolution", correct: false },
      { text: "Vers un métier 100 % manuel", correct: false },
    ],
    explanation: "À mesure que les tâches répétitives s'automatisent, le métier monte en valeur : coordination, gestion de projets internes, office management. Une vraie perspective d'évolution.",
    tip: "Parle d'« office manager » comme horizon de carrière.",
  },
  {
    ...base, id: 'adm-ac-8', type: 'actu', difficulty: 2,
    situation: "Nouvelle organisation du travail.",
    question: "Quel défi le travail hybride pose-t-il à l'administratif ?",
    options: [
      { text: "Aucun, rien ne change", correct: false },
      { text: "Coordonner et fluidifier l'info entre présentiel et distanciel (outils, process)", correct: true },
      { text: "Interdire toute réunion", correct: false },
      { text: "Supprimer les emails", correct: false },
    ],
    explanation: "Avec le présentiel/distanciel mêlés, l'administratif doit fiabiliser la circulation de l'information et l'usage d'outils communs. Un rôle de liant essentiel.",
    tip: "Mets en avant ton rôle de coordination de l'information.",
  },
];
