/**
 * Secteur « Administratif » — parcours (4 couches).
 *
 * sector:'admin', type ∈ {comportemental, technique, situation, actu}.
 * Une seule option correct:true, + explanation + tip. `context` optionnel.
 */
const base = { sector: 'admin' };

export default [
  // ══════════════ 🧠 COMPORTEMENTAL ══════════════
  {
    ...base, id: 'adm-cp-1', type: 'comportemental', difficulty: 1,
    situation: "« Pourquoi le métier de l'administratif vous attire-t-il ? »",
    question: "La motivation la plus crédible :",
    options: [
      { text: "« Parce que c'est un métier tranquille où il n'y a rien à faire »", correct: false },
      { text: "Le goût de l'organisation, de la rigueur et du rôle de soutien indispensable", correct: true },
      { text: "« Parce que je ne savais pas quoi faire d'autre »", correct: false },
      { text: "« Pour éviter le contact avec les gens »", correct: false },
    ],
    explanation: "L'administratif est la colonne vertébrale d'une organisation. On valorise le sens du service, l'organisation et la fiabilité — pas l'idée d'un métier « peinard ».",
    tip: "Mets en avant rigueur, organisation et esprit de service.",
  },
  {
    ...base, id: 'adm-cp-2', type: 'comportemental', difficulty: 2,
    situation: "« Comment gérez-vous plusieurs tâches en même temps ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Je fais tout en même temps, au hasard »", correct: false },
      { text: "Je priorise selon l'urgence et l'importance, et je planifie", correct: true },
      { text: "« Je traite uniquement ce qui me plaît »", correct: false },
      { text: "« J'attends qu'on me dise quoi faire »", correct: false },
    ],
    explanation: "La capacité à prioriser (urgent/important) et à s'organiser est LA compétence clé de l'administratif. On montre une méthode, pas de l'improvisation.",
    tip: "Cite une méthode : to-do list, matrice urgent/important.",
  },
  {
    ...base, id: 'adm-cp-3', type: 'comportemental', difficulty: 2,
    situation: "« La rigueur et le sens du détail, qu'en pensez-vous ? »",
    question: "La meilleure posture :",
    options: [
      { text: "« Les détails, ce n'est pas important »", correct: false },
      { text: "Essentiels : une petite erreur de saisie peut avoir de grosses conséquences", correct: true },
      { text: "« Je préfère aller vite quitte à faire des fautes »", correct: false },
      { text: "« La relecture, c'est une perte de temps »", correct: false },
    ],
    explanation: "Un IBAN, un montant ou une date erronés peuvent coûter cher. La rigueur et la relecture systématique sont au cœur du métier administratif.",
    tip: "Donne un exemple où ta rigueur a évité une erreur.",
  },
  {
    ...base, id: 'adm-cp-4', type: 'comportemental', difficulty: 2,
    situation: "Vous traitez des documents sensibles (RH, paie, contrats).",
    question: "Quelle qualité est attendue avant tout ?",
    options: [
      { text: "Partager les infos intéressantes avec ses collègues", correct: false },
      { text: "La discrétion et le respect strict de la confidentialité", correct: true },
      { text: "Commenter les salaires des autres", correct: false },
      { text: "Laisser les dossiers ouverts sur son bureau", correct: false },
    ],
    explanation: "L'administratif manipule des données confidentielles. La discrétion est non négociable : c'est une question de déontologie et de RGPD.",
    tip: "Confidentialité = règle d'or, sans exception.",
  },
  {
    ...base, id: 'adm-cp-5', type: 'comportemental', difficulty: 2,
    situation: "« Vous êtes souvent interrompu(e) dans votre travail. Comment réagissez-vous ? »",
    question: "La meilleure attitude :",
    options: [
      { text: "S'énerver contre les personnes qui dérangent", correct: false },
      { text: "Rester disponible et flexible, tout en sachant reprendre le fil de ses tâches", correct: true },
      { text: "Ignorer toutes les sollicitations", correct: false },
      { text: "Abandonner ce qu'on faisait définitivement", correct: false },
    ],
    explanation: "Les interruptions font partie du métier (accueil, sollicitations). On allie disponibilité et capacité à se replonger dans son travail sans tout laisser tomber.",
    tip: "Montre flexibilité ET capacité de concentration.",
  },
  {
    ...base, id: 'adm-cp-6', type: 'comportemental', difficulty: 2,
    situation: "« On vous confie des tâches très variées. Est-ce un problème ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Oui, je n'aime que la routine »", correct: false },
      { text: "Non, la polyvalence me plaît et me rend plus utile", correct: true },
      { text: "« Je refuse tout ce qui n'est pas dans ma fiche de poste »", correct: false },
      { text: "« Je fais une chose à la fois et tant pis pour le reste »", correct: false },
    ],
    explanation: "La polyvalence est très recherchée en administratif. Montrer qu'on l'apprécie et qu'on s'adapte est un vrai atout, surtout en PME.",
    tip: "La polyvalence est un argument, pas une contrainte.",
  },

  // ══════════════ 🛠️ TECHNIQUE MÉTIER ══════════════
  {
    ...base, id: 'adm-te-1', type: 'technique', difficulty: 1,
    situation: "Outils du quotidien.",
    question: "Quels outils maîtriser en priorité dans l'administratif ?",
    options: [
      { text: "Des logiciels de montage vidéo", correct: false },
      { text: "La suite bureautique : traitement de texte, tableur, messagerie, agenda", correct: true },
      { text: "Uniquement les réseaux sociaux", correct: false },
      { text: "Des logiciels de jeux", correct: false },
    ],
    explanation: "Word/Excel (ou Google Docs/Sheets), la messagerie et l'agenda sont la base. Une bonne maîtrise du tableur fait souvent la différence.",
    tip: "Excel/Sheets : maîtrise tri, filtre et formules de base.",
  },
  {
    ...base, id: 'adm-te-2', type: 'technique', difficulty: 2,
    situation: "Gestion documentaire.",
    question: "Qu'est-ce que la GED ?",
    options: [
      { text: "Un type de contrat", correct: false },
      { text: "La Gestion Électronique des Documents : numériser, classer et retrouver les documents", correct: true },
      { text: "Une réunion hebdomadaire", correct: false },
      { text: "Un logiciel de paie", correct: false },
    ],
    explanation: "La GED permet de dématérialiser, indexer et retrouver rapidement les documents. C'est un pilier de l'administration moderne (fin du tout-papier).",
    tip: "Connaître la GED montre que tu es à jour sur la dématérialisation.",
  },
  {
    ...base, id: 'adm-te-3', type: 'technique', difficulty: 2,
    situation: "Classement et archivage.",
    question: "Pourquoi respecter des durées légales de conservation ?",
    options: [
      { text: "Pour remplir les placards", correct: false },
      { text: "Parce que la loi impose de conserver certains documents un temps minimum (puis de les détruire)", correct: true },
      { text: "Il n'y a aucune règle, on garde tout à vie", correct: false },
      { text: "On peut tout jeter immédiatement", correct: false },
    ],
    explanation: "Bulletins de paie, factures, contrats… ont des durées légales de conservation (souvent 5 à 10 ans). Les connaître évite des risques juridiques.",
    tip: "Ex : factures conservées 10 ans en entreprise.",
  },
  {
    ...base, id: 'adm-te-4', type: 'technique', difficulty: 2,
    situation: "Organisation des réunions.",
    question: "Comment planifier efficacement une réunion ?",
    options: [
      { text: "Envoyer un message vague « on se voit un jour »", correct: false },
      { text: "Vérifier les disponibilités, envoyer une invitation agenda avec objet, lieu et ordre du jour", correct: true },
      { text: "Convoquer tout le monde sans prévenir", correct: false },
      { text: "Ne rien préparer", correct: false },
    ],
    explanation: "Une réunion bien planifiée a un créneau validé, un objet clair, un ordre du jour et les bonnes personnes invitées. C'est un savoir-faire administratif classique.",
    tip: "Toujours un ordre du jour : ça cadre la réunion.",
  },
  {
    ...base, id: 'adm-te-5', type: 'technique', difficulty: 2,
    situation: "Rédaction professionnelle.",
    question: "Qu'attend-on d'un compte-rendu de réunion ?",
    options: [
      { text: "Un roman détaillé de chaque phrase prononcée", correct: false },
      { text: "Une synthèse claire : décisions prises, actions, responsables et échéances", correct: true },
      { text: "Des opinions personnelles sur les participants", correct: false },
      { text: "Rien, on s'en souviendra", correct: false },
    ],
    explanation: "Un bon compte-rendu est synthétique et actionnable : ce qui a été décidé, qui fait quoi, pour quand. C'est un outil de suivi, pas une transcription.",
    tip: "Mets en avant « qui fait quoi pour quand ».",
  },
  {
    ...base, id: 'adm-te-6', type: 'technique', difficulty: 2,
    situation: "Accueil et standard.",
    question: "Quelle est la bonne pratique pour l'accueil téléphonique ?",
    options: [
      { text: "Répondre sèchement et raccrocher vite", correct: false },
      { text: "Se présenter, écouter, reformuler et orienter vers le bon interlocuteur", correct: true },
      { text: "Laisser sonner sans répondre", correct: false },
      { text: "Mettre en attente indéfiniment", correct: false },
    ],
    explanation: "L'accueil est la vitrine de l'entreprise. Présentation, écoute, reformulation et bonne orientation sont les réflexes attendus.",
    tip: "Souris au téléphone : ça s'entend.",
  },
  {
    ...base, id: 'adm-te-7', type: 'technique', difficulty: 3,
    situation: "Tableur.",
    question: "À quoi sert un filtre dans un tableur ?",
    options: [
      { text: "À changer la couleur de l'écran", correct: false },
      { text: "À n'afficher que les lignes correspondant à un critère donné", correct: true },
      { text: "À supprimer définitivement des données", correct: false },
      { text: "À imprimer le document", correct: false },
    ],
    explanation: "Le filtre permet d'isoler rapidement les données utiles (ex : tous les clients d'une ville). Avec le tri et la RECHERCHEV, c'est un basique très demandé.",
    tip: "Maîtrise tri, filtre et RECHERCHEV : ça impressionne.",
  },
  {
    ...base, id: 'adm-te-8', type: 'technique', difficulty: 2,
    situation: "Traitement du courrier.",
    question: "Qu'est-ce qu'un « parapheur » ?",
    options: [
      { text: "Un stylo spécial", correct: false },
      { text: "Un classeur (papier ou électronique) regroupant les documents à faire signer", correct: true },
      { text: "Une réunion de direction", correct: false },
      { text: "Un logiciel de paie", correct: false },
    ],
    explanation: "Le parapheur centralise les documents nécessitant une signature. Il existe désormais en version électronique (parapheur numérique).",
    tip: "Le parapheur électronique fluidifie les validations.",
  },
  {
    ...base, id: 'adm-te-9', type: 'technique', difficulty: 3,
    situation: "Envoi en nombre.",
    question: "À quoi sert le « publipostage » (mailing) ?",
    options: [
      { text: "À trier le courrier reçu", correct: false },
      { text: "À générer des documents personnalisés en série à partir d'une liste (ex : courriers nominatifs)", correct: true },
      { text: "À supprimer des emails", correct: false },
      { text: "À archiver des factures", correct: false },
    ],
    explanation: "Le publipostage fusionne un modèle (lettre, étiquette, email) avec une base de données pour personnaliser un envoi de masse. Un grand classique de la bureautique.",
    tip: "Word + Excel = publipostage, une compétence valorisée.",
  },

  // ══════════════ 🎭 MISE EN SITUATION ══════════════
  {
    ...base, id: 'adm-si-1', type: 'situation', difficulty: 2,
    context: "Il est 16h. Votre manager vous demande un dossier « pour tout de suite », pendant qu'un client au téléphone attend une réponse urgente.",
    situation: "Deux urgences en même temps.",
    question: "La meilleure réaction :",
    options: [
      { text: "Paniquer et ne rien faire", correct: false },
      { text: "Évaluer la priorité réelle, gérer l'immédiat et annoncer un délai clair pour l'autre", correct: true },
      { text: "Ignorer le client pour faire plaisir au manager", correct: false },
      { text: "Faire les deux à moitié, mal", correct: false },
    ],
    explanation: "On garde son calme, on hiérarchise, on traite ce qui ne peut pas attendre et on communique un délai pour le reste. Savoir dire « je m'en occupe dans 10 min » est pro.",
    tip: "Prioriser et communiquer un délai vaut mieux que tout bâcler.",
  },
  {
    ...base, id: 'adm-si-2', type: 'situation', difficulty: 2,
    context: "Vous trouvez sur l'imprimante commune un document RH confidentiel oublié par un collègue (un bulletin de salaire).",
    situation: "Document confidentiel laissé en évidence.",
    question: "La bonne réaction :",
    options: [
      { text: "Le lire par curiosité", correct: false },
      { text: "Le récupérer discrètement et le rendre à la personne concernée sans le diffuser", correct: true },
      { text: "Le laisser traîner", correct: false },
      { text: "En parler à toute l'équipe", correct: false },
    ],
    explanation: "On protège la confidentialité : récupérer le document et le restituer discrètement, sans le lire ni le commenter. C'est une question de déontologie et de RGPD.",
    tip: "Confidentiel = on protège, on ne diffuse jamais.",
  },
  {
    ...base, id: 'adm-si-3', type: 'situation', difficulty: 3,
    context: "Vous réalisez qu'un courrier officiel envoyé hier contenait une erreur de montant.",
    situation: "Erreur détectée dans un document déjà envoyé.",
    question: "La meilleure réaction :",
    options: [
      { text: "Ne rien dire et espérer que personne ne remarque", correct: false },
      { text: "Prévenir immédiatement son responsable et proposer une correction (rectificatif)", correct: true },
      { text: "Accuser un collègue", correct: false },
      { text: "Supprimer toute trace de l'envoi", correct: false },
    ],
    explanation: "On assume l'erreur vite : prévenir, proposer un rectificatif et corriger. La transparence limite les conséquences ; dissimuler les aggrave.",
    tip: "Une erreur signalée tôt se règle ; cachée, elle explose.",
  },
  {
    ...base, id: 'adm-si-4', type: 'situation', difficulty: 2,
    context: "Un visiteur se présente à l'accueil, agacé : son rendez-vous a du retard et il s'impatiente.",
    situation: "Visiteur mécontent à l'accueil.",
    question: "La bonne attitude :",
    options: [
      { text: "L'ignorer en attendant que ça passe", correct: false },
      { text: "L'accueillir avec calme, l'informer du délai et lui proposer de patienter confortablement", correct: true },
      { text: "Lui dire que ce n'est pas votre problème", correct: false },
      { text: "Hausser le ton à votre tour", correct: false },
    ],
    explanation: "On désamorce avec courtoisie : reconnaître l'attente, informer honnêtement et proposer une solution (café, salle d'attente). L'accueil reflète l'image de la structure.",
    tip: "Calme + information honnête = tension qui retombe.",
  },
  {
    ...base, id: 'adm-si-5', type: 'situation', difficulty: 3,
    context: "On vous demande d'organiser une réunion réunissant 8 personnes aux agendas très chargés, sous 10 jours.",
    situation: "Caler une réunion à 8 participants.",
    question: "La méthode la plus efficace :",
    options: [
      { text: "Proposer un seul créneau et tant pis pour les absents", correct: false },
      { text: "Utiliser un sondage de disponibilités / agendas partagés, puis confirmer le meilleur créneau", correct: true },
      { text: "Appeler chacun séparément sans rien noter", correct: false },
      { text: "Laisser les gens s'organiser entre eux", correct: false },
    ],
    explanation: "Un outil de disponibilités (Doodle, sondage Teams, agendas partagés) permet de trouver le créneau qui convient au plus grand nombre, puis on confirme officiellement.",
    tip: "Sondage de dispo > emails interminables.",
  },
  {
    ...base, id: 'adm-si-6', type: 'situation', difficulty: 2,
    context: "Votre boîte mail déborde : 60 messages non lus ce matin.",
    situation: "Surcharge de mails.",
    question: "La meilleure méthode de traitement :",
    options: [
      { text: "Tout lire dans le désordre sans rien traiter", correct: false },
      { text: "Trier par priorité, traiter le rapide immédiatement, planifier le reste, archiver", correct: true },
      { text: "Tout supprimer pour repartir à zéro", correct: false },
      { text: "Attendre que ça se calme tout seul", correct: false },
    ],
    explanation: "Une méthode type « traiter / déléguer / planifier / archiver » évite la noyade. On répond vite à ce qui prend 2 min, on planifie le reste.",
    tip: "Inspire-toi de la règle des 2 minutes.",
  },
  {
    ...base, id: 'adm-si-7', type: 'situation', difficulty: 3,
    context: "🏆 BOSS — Lundi 9h. Sur ton bureau : 3 dossiers urgents, 2 réunions à organiser, le téléphone qui sonne et ton manager qui veut un point.",
    situation: "Journée surchargée à organiser.",
    question: "Par quoi commencer ?",
    options: [
      { text: "Faire tout en même temps et au feeling", correct: false },
      { text: "Lister puis hiérarchiser (urgent/important), traiter dans l'ordre et communiquer les délais", correct: true },
      { text: "Commencer par les tâches les plus agréables", correct: false },
      { text: "Attendre que la pression retombe", correct: false },
    ],
    explanation: "Face à la surcharge, la clé est de poser à plat, hiérarchiser (matrice d'Eisenhower : urgent/important) et avancer méthodiquement en informant des délais. L'organisation bat la précipitation.",
    tip: "Urgent ET important d'abord ; le reste se planifie.",
  },

  // ══════════════ 📰 ACTU & TENDANCES (2026) ══════════════
  {
    ...base, id: 'adm-ac-1', type: 'actu', difficulty: 2,
    situation: "Grande tendance de fond.",
    question: "Que signifie la « dématérialisation » des process administratifs ?",
    options: [
      { text: "Supprimer les employés", correct: false },
      { text: "Remplacer le papier par des documents et circuits numériques", correct: true },
      { text: "Détruire tous les documents", correct: false },
      { text: "Travailler sans ordinateur", correct: false },
    ],
    explanation: "La dématérialisation (factures, contrats, signatures, archivage) accélère et sécurise les process. C'est la transformation majeure du métier administratif.",
    tip: "Montre que tu es à l'aise avec le « zéro papier ».",
  },
  {
    ...base, id: 'adm-ac-2', type: 'actu', difficulty: 3,
    situation: "Automatisation des tâches.",
    question: "Que permettent les outils « no-code » (Power Automate, Make, Zapier) ?",
    options: [
      { text: "Coder des logiciels complexes", correct: false },
      { text: "Automatiser des tâches répétitives sans savoir programmer", correct: true },
      { text: "Remplacer Excel par du papier", correct: false },
      { text: "Rien d'utile au bureau", correct: false },
    ],
    explanation: "Les outils no-code automatisent des enchaînements (ex : classer une pièce jointe, créer une tâche à partir d'un mail) sans programmer. L'assistant administratif gagne un temps précieux.",
    tip: "Savoir automatiser une tâche répétitive est un vrai plus en 2026.",
  },
  {
    ...base, id: 'adm-ac-3', type: 'actu', difficulty: 3,
    situation: "L'IA dans le bureau.",
    question: "Comment l'IA générative aide-t-elle un profil administratif ?",
    options: [
      { text: "Elle rend le métier inutile", correct: false },
      { text: "Elle assiste : résumés de réunions, rédaction de mails, tri et synthèse d'infos", correct: true },
      { text: "Elle ne sert qu'aux développeurs", correct: false },
      { text: "Elle fait le café", correct: false },
    ],
    explanation: "L'IA rédige des brouillons, résume, reformule, classe — l'humain garde le contrôle et la relation. Savoir l'utiliser comme assistant est désormais valorisé.",
    tip: "Positionne l'IA comme un assistant, pas une menace.",
  },
  {
    ...base, id: 'adm-ac-4', type: 'actu', difficulty: 2,
    situation: "Travail en équipe à distance.",
    question: "À quoi servent les outils collaboratifs (Teams, SharePoint, Notion) ?",
    options: [
      { text: "À jouer en ligne", correct: false },
      { text: "À partager documents, échanger et coordonner le travail en équipe, même à distance", correct: true },
      { text: "À remplacer le téléphone uniquement", correct: false },
      { text: "À stocker des photos personnelles", correct: false },
    ],
    explanation: "Le travail hybride a généralisé les espaces collaboratifs : documents partagés, suivi de tâches, communication. Les maîtriser est devenu indispensable.",
    tip: "Cite un outil collaboratif que tu sais utiliser.",
  },
  {
    ...base, id: 'adm-ac-5', type: 'actu', difficulty: 2,
    situation: "Protection des données.",
    question: "Pourquoi le RGPD concerne-t-il directement l'administratif ?",
    options: [
      { text: "Ça ne le concerne pas", correct: false },
      { text: "Parce qu'il manipule des données personnelles à protéger (clients, salariés)", correct: true },
      { text: "Parce qu'il interdit d'utiliser un ordinateur", correct: false },
      { text: "Parce qu'il oblige à tout imprimer", correct: false },
    ],
    explanation: "L'administratif traite quotidiennement des données personnelles : il doit en garantir la sécurité, la confidentialité et le bon usage, conformément au RGPD.",
    tip: "RGPD = réflexe sécurité/confidentialité au quotidien.",
  },
  {
    ...base, id: 'adm-ac-6', type: 'actu', difficulty: 2,
    situation: "Validation des documents.",
    question: "Qu'apporte la signature électronique ?",
    options: [
      { text: "Rien, elle n'a aucune valeur", correct: false },
      { text: "Une signature à valeur légale, plus rapide et sans impression papier", correct: true },
      { text: "Une simple image collée sans valeur", correct: false },
      { text: "Un risque juridique systématique", correct: false },
    ],
    explanation: "La signature électronique a une valeur juridique et fluidifie les circuits de validation (contrats, devis) sans papier. Elle s'est généralisée dans les organisations.",
    tip: "Connais des outils comme DocuSign / Yousign.",
  },
  {
    ...base, id: 'adm-ac-7', type: 'actu', difficulty: 3,
    situation: "Évolution du métier.",
    question: "Vers quel rôle évolue souvent l'assistant(e) administratif(ve) ?",
    options: [
      { text: "Vers la disparition pure et simple", correct: false },
      { text: "Vers l'« office manager » : plus de polyvalence, d'autonomie et de responsabilités", correct: true },
      { text: "Vers un poste sans aucune évolution", correct: false },
      { text: "Vers un métier 100 % manuel", correct: false },
    ],
    explanation: "À mesure que les tâches répétitives s'automatisent, le métier monte en valeur : coordination, gestion de projets internes, office management. Une vraie perspective d'évolution.",
    tip: "Parle d'« office manager » comme horizon de carrière.",
  },
  {
    ...base, id: 'adm-ac-8', type: 'actu', difficulty: 2,
    situation: "Nouvelle organisation du travail.",
    question: "Quel défi le travail hybride pose-t-il à l'administratif ?",
    options: [
      { text: "Aucun, rien ne change", correct: false },
      { text: "Coordonner et fluidifier l'info entre présentiel et distanciel (outils, process)", correct: true },
      { text: "Interdire toute réunion", correct: false },
      { text: "Supprimer les emails", correct: false },
    ],
    explanation: "Avec le présentiel/distanciel mêlés, l'administratif doit fiabiliser la circulation de l'information et l'usage d'outils communs. Un rôle de liant essentiel.",
    tip: "Mets en avant ton rôle de coordination de l'information.",
  },

  // ── 🧠 COMPORTEMENTAL (suite) ──
  {
    ...base, id: 'adm-cp-7', type: 'comportemental', difficulty: 2,
    situation: "« La rigueur, c'est important pour ce poste ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Bof, l'à-peu-près suffit »", correct: false },
      { text: "Essentielle : une erreur de saisie ou d'archivage peut bloquer tout un service", correct: true },
      { text: "« Je préfère aller vite, tant pis pour les détails »", correct: false },
      { text: "« Ce n'est pas mon problème »", correct: false },
    ],
    explanation: "L'administratif est le socle fiable de l'organisation : exactitude des données, des dossiers et des délais. La rigueur y est la qualité n°1.",
    tip: "Donne un exemple où ta rigueur a évité une erreur.",
  },
  {
    ...base, id: 'adm-cp-8', type: 'comportemental', difficulty: 3,
    situation: "Vous traitez des informations confidentielles (paie, contrats).",
    question: "La bonne attitude :",
    options: [
      { text: "En parler aux collègues curieux", correct: false },
      { text: "Garder une discrétion absolue, ne rien divulguer", correct: true },
      { text: "Laisser les documents en évidence", correct: false },
      { text: "Partager les infos « entre nous »", correct: false },
    ],
    explanation: "La discrétion et la confidentialité sont déontologiques en administratif/RH. Une fuite d'information détruit la confiance et peut être une faute grave.",
    tip: "« Ce que je vois reste confidentiel » : règle d'or.",
  },
  {
    ...base, id: 'adm-cp-9', type: 'comportemental', difficulty: 2,
    situation: "Trois personnes vous demandent quelque chose en même temps.",
    question: "La bonne réaction :",
    options: [
      { text: "Paniquer et tout faire dans le désordre", correct: false },
      { text: "Évaluer l'urgence, hiérarchiser et communiquer les délais à chacun", correct: true },
      { text: "Ne traiter que la demande du plus gradé", correct: false },
      { text: "Refuser tout en bloc", correct: false },
    ],
    explanation: "Savoir prioriser sous pression et tenir informés les demandeurs est central. La gestion des priorités fait gagner du temps à tout le service.",
    tip: "Hiérarchise selon urgence ET importance.",
  },
  {
    ...base, id: 'adm-cp-10', type: 'comportemental', difficulty: 1,
    situation: "Vous accueillez un visiteur à l'entreprise.",
    question: "La bonne posture :",
    options: [
      { text: "Le laisser attendre sans un mot", correct: false },
      { text: "Sourire, le saluer, l'orienter et le mettre à l'aise", correct: true },
      { text: "Continuer son travail sans le regarder", correct: false },
      { text: "« C'est pour quoi ? » sur un ton sec", correct: false },
    ],
    explanation: "L'assistant(e) est souvent la première image de l'entreprise. Un accueil chaleureux et professionnel donne le ton.",
    tip: "Tu incarnes la première impression de l'entreprise.",
  },
  {
    ...base, id: 'adm-cp-11', type: 'comportemental', difficulty: 2,
    situation: "Votre manager est débordé et n'a rien demandé.",
    question: "La qualité valorisée ici :",
    options: [
      { text: "Attendre les ordres sans rien faire", correct: false },
      { text: "La proactivité : anticiper les besoins et proposer son aide", correct: true },
      { text: "Faire semblant d'être occupé", correct: false },
      { text: "Partir plus tôt", correct: false },
    ],
    explanation: "Anticiper (préparer un dossier, relancer un fournisseur, classer) sans qu'on le demande est très apprécié d'un manager. La proactivité distingue un bon assistant.",
    tip: "« Voici ce que j'ai préparé en attendant » fait mouche.",
  },
  {
    ...base, id: 'adm-cp-12', type: 'comportemental', difficulty: 2,
    situation: "Un imprévu bouscule tout votre planning de la journée.",
    question: "La bonne attitude :",
    options: [
      { text: "Se bloquer et ne plus rien faire", correct: false },
      { text: "S'adapter, réorganiser ses priorités et garder son calme", correct: true },
      { text: "Se plaindre toute la journée", correct: false },
      { text: "Ignorer l'imprévu", correct: false },
    ],
    explanation: "L'adaptabilité est quotidienne en administratif : les urgences arrivent. Garder son sang-froid et réorganiser est essentiel.",
    tip: "La flexibilité fait partie du métier d'assistant.",
  },
  {
    ...base, id: 'adm-cp-13', type: 'comportemental', difficulty: 1,
    situation: "« Êtes-vous fiable sur les délais ? »",
    question: "La réponse la plus convaincante :",
    options: [
      { text: "« Ça dépend de mon humeur »", correct: false },
      { text: "Oui : je note tout, je planifie et j'alerte en amont si un délai est menacé", correct: true },
      { text: "« Je fais au mieux, sans garantie »", correct: false },
      { text: "« Les délais c'est indicatif »", correct: false },
    ],
    explanation: "La fiabilité sur les échéances est cruciale : on s'appuie sur l'assistant pour que rien ne passe à la trappe. Alerter en amont est un signe de professionnalisme.",
    tip: "Mieux vaut prévenir tôt d'un retard que de le subir.",
  },
  {
    ...base, id: 'adm-cp-14', type: 'comportemental', difficulty: 2,
    situation: "On vous confie des tâches très variées (courrier, saisie, accueil…).",
    question: "Comment le présenter comme un atout ?",
    options: [
      { text: "« Je n'aime pas changer de tâche »", correct: false },
      { text: "Valoriser sa polyvalence et sa capacité à jongler entre missions", correct: true },
      { text: "Se plaindre du manque de spécialisation", correct: false },
      { text: "Refuser certaines tâches", correct: false },
    ],
    explanation: "La polyvalence est le cœur du métier administratif. Savoir passer d'une mission à l'autre sans perdre en qualité est très recherché.",
    tip: "La polyvalence est une force, assume-la.",
  },
  {
    ...base, id: 'adm-cp-15', type: 'comportemental', difficulty: 2,
    situation: "Une collègue est absente, son travail s'accumule.",
    question: "La bonne attitude d'équipe :",
    options: [
      { text: "« Ce n'est pas mon travail »", correct: false },
      { text: "Proposer de prendre en charge l'essentiel le temps de l'absence", correct: true },
      { text: "Laisser tout en plan", correct: false },
      { text: "Critiquer son absence", correct: false },
    ],
    explanation: "L'esprit d'équipe et la solidarité sont valorisés : assurer la continuité du service en cas d'absence est un vrai plus.",
    tip: "Assurer la continuité = qualité d'équipe appréciée.",
  },
  {
    ...base, id: 'adm-cp-16', type: 'comportemental', difficulty: 1,
    situation: "Un interlocuteur au téléphone est confus et long.",
    question: "La bonne attitude :",
    options: [
      { text: "Le couper sèchement", correct: false },
      { text: "Écouter, reformuler sa demande et le réorienter clairement", correct: true },
      { text: "Raccrocher", correct: false },
      { text: "Le faire patienter indéfiniment", correct: false },
    ],
    explanation: "La patience et la clarté au téléphone reflètent le professionnalisme. Reformuler aide à cadrer une demande floue.",
    tip: "Reformuler = « si je comprends bien, vous souhaitez… ».",
  },
  {
    ...base, id: 'adm-cp-17', type: 'comportemental', difficulty: 2,
    situation: "Vous remarquez une erreur dans un document validé par votre supérieur.",
    question: "La bonne réaction :",
    options: [
      { text: "Ne rien dire pour ne pas le contrarier", correct: false },
      { text: "Le signaler discrètement et avec tact pour corriger à temps", correct: true },
      { text: "Le corriger en cachette sans prévenir", correct: false },
      { text: "En parler à tout le monde sauf à lui", correct: false },
    ],
    explanation: "Signaler une erreur avec tact évite des conséquences fâcheuses et montre de la fiabilité. La diplomatie est clé dans cette relation.",
    tip: "« J'ai peut-être mal lu, mais ce point me semble à vérifier… »",
  },
  {
    ...base, id: 'adm-cp-18', type: 'comportemental', difficulty: 2,
    situation: "Vous êtes interrompu en permanence dans une tâche qui demande de la concentration.",
    question: "La meilleure gestion :",
    options: [
      { text: "S'énerver contre les collègues", correct: false },
      { text: "Identifier les créneaux calmes pour les tâches de fond et cadrer les interruptions", correct: true },
      { text: "Bâcler la tâche", correct: false },
      { text: "Tout abandonner", correct: false },
    ],
    explanation: "Gérer les interruptions (créneaux dédiés, priorisation) permet de concilier disponibilité et qualité du travail de fond.",
    tip: "Réserve-toi des plages « sans interruption » pour les dossiers exigeants.",
  },
  {
    ...base, id: 'adm-cp-19', type: 'comportemental', difficulty: 1,
    situation: "Un collègue vous demande un service urgent alors que vous finissez votre journée.",
    question: "La réaction la plus pro :",
    options: [
      { text: "Évaluer si c'est vraiment urgent et faisable, et répondre clairement", correct: true },
      { text: "Refuser systématiquement", correct: false },
      { text: "Accepter puis partir sans le faire", correct: false },
      { text: "Ignorer la demande", correct: false },
    ],
    explanation: "Le sens du service, c'est savoir aider quand c'est justifié tout en posant des limites claires. Une réponse honnête vaut mieux qu'un faux oui.",
    tip: "Rendre service oui, mais avec une réponse claire et tenable.",
  },
  {
    ...base, id: 'adm-cp-20', type: 'comportemental', difficulty: 2,
    situation: "« Quelle est votre plus grande qualité d'assistant(e) ? »",
    question: "La réponse la plus pertinente :",
    options: [
      { text: "« Je suis sympa »", correct: false },
      { text: "Une qualité-clé du poste (organisation, fiabilité…) illustrée par un exemple", correct: true },
      { text: "« Aucune idée »", correct: false },
      { text: "Une liste de 15 qualités sans exemple", correct: false },
    ],
    explanation: "On choisit une qualité utile au poste et on la prouve par un fait concret. La preuve par l'exemple convainc, pas la liste.",
    tip: "Une qualité + une anecdote qui la démontre.",
  },

  // ── 🛠️ TECHNIQUE (suite) ──
  {
    ...base, id: 'adm-te-10', type: 'technique', difficulty: 2,
    situation: "Vous devez additionner et trier une longue liste de données.",
    question: "L'outil le plus adapté :",
    options: [
      { text: "Une calculatrice à la main", correct: false },
      { text: "Un tableur (Excel/Sheets) avec formules et tris", correct: true },
      { text: "Un document texte", correct: false },
      { text: "Le faire de mémoire", correct: false },
    ],
    explanation: "La maîtrise du tableur (formules, tris, filtres, tableaux croisés) est une compétence de base attendue en administratif.",
    tip: "Excel/Sheets : SOMME, RECHERCHEV, filtres = essentiels.",
  },
  {
    ...base, id: 'adm-te-11', type: 'technique', difficulty: 2,
    situation: "Vous gérez l'agenda complexe de plusieurs cadres.",
    question: "La bonne pratique :",
    options: [
      { text: "Planifier au hasard", correct: false },
      { text: "Centraliser, anticiper les conflits, prévoir les temps de trajet et confirmer", correct: true },
      { text: "Ne jamais bloquer de créneaux", correct: false },
      { text: "Laisser chacun gérer seul", correct: false },
    ],
    explanation: "La gestion d'agenda demande anticipation (conflits, déplacements, priorités) et rigueur de confirmation. C'est un pilier du rôle d'assistant de direction.",
    tip: "Toujours prévoir les temps de trajet entre rendez-vous.",
  },
  {
    ...base, id: 'adm-te-12', type: 'technique', difficulty: 1,
    situation: "Vous rédigez un email professionnel à un partenaire externe.",
    question: "La bonne pratique :",
    options: [
      { text: "Écrire en langage SMS", correct: false },
      { text: "Objet clair, formule de politesse, message concis et sans fautes", correct: true },
      { text: "Un pavé sans structure", correct: false },
      { text: "Aucune formule de politesse", correct: false },
    ],
    explanation: "Un email pro soigné (objet, structure, orthographe, politesse) reflète l'image de l'entreprise. La clarté et la correction priment.",
    tip: "Relis-toi : zéro faute, objet explicite.",
  },
  {
    ...base, id: 'adm-te-13', type: 'technique', difficulty: 2,
    situation: "Les documents s'accumulent et on perd du temps à les retrouver.",
    question: "La solution :",
    options: [
      { text: "Tout entasser au même endroit", correct: false },
      { text: "Un plan de classement/archivage logique et nommage cohérent des fichiers", correct: true },
      { text: "Jeter les documents anciens", correct: false },
      { text: "Tout imprimer", correct: false },
    ],
    explanation: "Un classement structuré (arborescence claire, nommage normalisé, archivage) fait gagner un temps précieux à tout le service.",
    tip: "Un bon nommage de fichiers = des heures économisées.",
  },
  {
    ...base, id: 'adm-te-14', type: 'technique', difficulty: 2,
    situation: "Après une réunion, on vous demande un compte-rendu.",
    question: "Un bon CR :",
    options: [
      { text: "Retranscrit tout mot à mot", correct: false },
      { text: "Synthétise décisions, actions, responsables et échéances", correct: true },
      { text: "Donne seulement la date", correct: false },
      { text: "Reste dans votre tête", correct: false },
    ],
    explanation: "Un compte-rendu efficace va à l'essentiel : décisions prises, qui fait quoi, pour quand. C'est un outil de suivi, pas une transcription.",
    tip: "Mets en avant les actions : qui / quoi / quand.",
  },
  {
    ...base, id: 'adm-te-15', type: 'technique', difficulty: 2,
    situation: "Vous organisez un déplacement professionnel pour un cadre.",
    question: "À gérer en priorité :",
    options: [
      { text: "Rien, il se débrouillera", correct: false },
      { text: "Transport, hébergement, planning, notes de frais et documents nécessaires", correct: true },
      { text: "Seulement le train", correct: false },
      { text: "Réserver au dernier moment", correct: false },
    ],
    explanation: "Organiser un déplacement demande de tout coordonner (transport, hôtel, agenda sur place, justificatifs) pour que le cadre n'ait qu'à se concentrer sur sa mission.",
    tip: "Prépare un « road-book » complet du déplacement.",
  },
  {
    ...base, id: 'adm-te-16', type: 'technique', difficulty: 2,
    situation: "Vous gérez la facturation et les bons de commande.",
    question: "La rigueur attendue :",
    options: [
      { text: "Approximer les montants", correct: false },
      { text: "Vérifier montants, références, échéances et rapprocher commande/facture", correct: true },
      { text: "Payer sans contrôler", correct: false },
      { text: "Classer sans lire", correct: false },
    ],
    explanation: "Le suivi facturation exige un contrôle précis (rapprochement bon de commande / livraison / facture) pour éviter litiges et erreurs de paiement.",
    tip: "Toujours rapprocher commande, livraison et facture.",
  },
  {
    ...base, id: 'adm-te-17', type: 'technique', difficulty: 1,
    situation: "Le téléphone sonne pendant que vous traitez un dossier.",
    question: "La bonne pratique d'accueil téléphonique :",
    options: [
      { text: "Laisser sonner", correct: false },
      { text: "Décrocher avec une formule d'accueil claire, identifier le besoin et noter le message", correct: true },
      { text: "Décrocher et raccrocher aussitôt", correct: false },
      { text: "Répondre en mangeant", correct: false },
    ],
    explanation: "L'accueil téléphonique suit des codes : formule d'accueil, identification du besoin, prise de message fiable. C'est une vitrine de l'entreprise.",
    tip: "« [Société] bonjour, [prénom] à votre écoute. »",
  },
  {
    ...base, id: 'adm-te-18', type: 'technique', difficulty: 2,
    situation: "On vous demande de préparer une présentation pour une réunion.",
    question: "La bonne approche :",
    options: [
      { text: "Copier-coller des pages de texte", correct: false },
      { text: "Structurer un support clair, lisible et synthétique (titres, visuels)", correct: true },
      { text: "Mettre le maximum de texte par slide", correct: false },
      { text: "Improviser sans support", correct: false },
    ],
    explanation: "Un support efficace est clair et synthétique : une idée par slide, des visuels, peu de texte. Il sert le message, pas l'inverse.",
    tip: "Une slide = une idée, pas un pavé.",
  },
  {
    ...base, id: 'adm-te-19', type: 'technique', difficulty: 2,
    situation: "Vous saisissez des données dans un fichier partagé.",
    question: "Le bon réflexe pour fiabiliser :",
    options: [
      { text: "Saisir vite sans relire", correct: false },
      { text: "Respecter un format cohérent, relire et éviter les doublons", correct: true },
      { text: "Inventer les valeurs manquantes", correct: false },
      { text: "Modifier les colonnes des autres", correct: false },
    ],
    explanation: "La qualité de la saisie (format homogène, relecture, pas de doublons) conditionne la fiabilité des données utilisées par tout le service.",
    tip: "Une donnée mal saisie pollue toute la base.",
  },
  {
    ...base, id: 'adm-te-20', type: 'technique', difficulty: 2,
    situation: "Votre équipe utilise des outils collaboratifs (Teams, Drive partagé).",
    question: "La bonne pratique :",
    options: [
      { text: "Tout garder en local sur son poste", correct: false },
      { text: "Partager au bon endroit, gérer les droits d'accès et tenir les fichiers à jour", correct: true },
      { text: "Envoyer chaque version par email", correct: false },
      { text: "Donner accès à tout le monde sans distinction", correct: false },
    ],
    explanation: "Bien utiliser les outils collaboratifs (versionnage, droits d'accès, organisation) évite les pertes de temps et les erreurs de version.",
    tip: "Une seule source de vérité partagée, pas dix copies par mail.",
  },

  // ── 🎭 MISE EN SITUATION (suite) ──
  {
    ...base, id: 'adm-si-8', type: 'situation', difficulty: 3,
    context: "Vous assistez deux managers. Tous deux vous confient une tâche « prioritaire » pour la même heure.",
    situation: "Deux priorités contradictoires en même temps.",
    question: "La meilleure démarche :",
    options: [
      { text: "Choisir au hasard sans rien dire", correct: false },
      { text: "Clarifier les enjeux/délais avec eux pour arbitrer ensemble la priorité", correct: true },
      { text: "Faire les deux à moitié", correct: false },
      { text: "Ne rien faire", correct: false },
    ],
    explanation: "Face à des priorités concurrentes, on ne décide pas seul en silence : on expose la situation et on fait arbitrer, en proposant éventuellement une solution.",
    tip: "Rends visible le conflit de priorités pour le faire arbitrer.",
  },
  {
    ...base, id: 'adm-si-9', type: 'situation', difficulty: 2,
    situation: "Un visiteur s'impatiente car son rendez-vous est en retard.",
    question: "La bonne attitude :",
    options: [
      { text: "L'ignorer", correct: false },
      { text: "S'excuser, l'informer du délai et lui proposer de patienter confortablement", correct: true },
      { text: "Lui dire « ce n'est pas ma faute »", correct: false },
      { text: "Le renvoyer chez lui", correct: false },
    ],
    explanation: "Gérer l'attente avec courtoisie (information, café, estimation) préserve l'image de l'entreprise et apaise l'impatience.",
    tip: "Informer sur le délai vaut mieux que laisser dans le flou.",
  },
  {
    ...base, id: 'adm-si-10', type: 'situation', difficulty: 2,
    situation: "Vous découvrez une faute importante dans un courrier déjà parti au client.",
    question: "La bonne réaction :",
    options: [
      { text: "Espérer que personne ne remarque", correct: false },
      { text: "Prévenir votre responsable et proposer un correctif rapide", correct: true },
      { text: "Accuser l'imprimante", correct: false },
      { text: "Supprimer toute trace", correct: false },
    ],
    explanation: "Assumer une erreur et proposer une correction (rectificatif, excuses) limite l'impact et montre du professionnalisme. La dissimulation aggrave toujours.",
    tip: "Signaler vite permet de corriger avant que ça dégénère.",
  },
  {
    ...base, id: 'adm-si-11', type: 'situation', difficulty: 3,
    context: "Un collègue vous demande d'accéder à un dossier RH confidentiel qui ne le concerne pas.",
    situation: "On vous demande une information confidentielle.",
    question: "La bonne réponse :",
    options: [
      { text: "Lui donner, c'est un collègue", correct: false },
      { text: "Refuser poliment en rappelant la règle de confidentialité", correct: true },
      { text: "Lui montrer en cachette", correct: false },
      { text: "Lui envoyer une copie", correct: false },
    ],
    explanation: "La confidentialité ne souffre pas d'exception « entre collègues ». On refuse avec tact en invoquant la règle ; rediriger vers la personne habilitée si besoin.",
    tip: "La confidentialité prime sur la pression amicale.",
  },
  {
    ...base, id: 'adm-si-12', type: 'situation', difficulty: 2,
    situation: "Deux réunions ont été réservées dans la même salle au même créneau.",
    question: "La gestion adaptée :",
    options: [
      { text: "Laisser les deux groupes se disputer la salle", correct: false },
      { text: "Identifier la priorité, trouver une salle alternative et prévenir les participants", correct: true },
      { text: "Annuler les deux", correct: false },
      { text: "Ne rien faire", correct: false },
    ],
    explanation: "Un conflit d'agenda se résout par l'anticipation et la communication : solution de repli + information rapide des concernés.",
    tip: "Anticipe une salle de repli et préviens vite.",
  },
  {
    ...base, id: 'adm-si-13', type: 'situation', difficulty: 2,
    situation: "Un appelant agressif exige de parler immédiatement au directeur, absent.",
    question: "La bonne réponse :",
    options: [
      { text: "Lui passer n'importe qui pour s'en débarrasser", correct: false },
      { text: "Rester calme, prendre ses coordonnées et garantir un rappel", correct: true },
      { text: "Raccrocher", correct: false },
      { text: "Mentir en disant que le directeur arrive", correct: false },
    ],
    explanation: "Face à l'agressivité, le sang-froid et un engagement concret (prise de message, rappel) désamorcent sans céder ni mentir.",
    tip: "Calme + engagement de rappel = désescalade.",
  },
  {
    ...base, id: 'adm-si-14', type: 'situation', difficulty: 2,
    context: "Fin de mois, clôture comptable. On vous demande un dossier complet pour le lendemain matin.",
    situation: "Délai très serré sur un dossier important.",
    question: "La meilleure approche :",
    options: [
      { text: "Promettre sans vérifier la faisabilité", correct: false },
      { text: "Évaluer le réalisable, prioriser l'essentiel et alerter tôt si un point bloque", correct: true },
      { text: "Bâcler pour rendre à l'heure", correct: false },
      { text: "Ignorer la demande", correct: false },
    ],
    explanation: "Sous deadline serrée, on sécurise l'essentiel et on communique tôt sur les éventuels manques. Mieux vaut un dossier fiable et un point signalé qu'un travail bâclé.",
    tip: "Priorise l'essentiel et signale tôt ce qui coince.",
  },
  {
    ...base, id: 'adm-si-15', type: 'situation', difficulty: 2,
    situation: "Votre manager vous demande une tâche que vous ne savez pas faire.",
    question: "La bonne réaction :",
    options: [
      { text: "Faire semblant et improviser", correct: false },
      { text: "Le dire honnêtement et proposer de l'apprendre ou de demander un appui", correct: true },
      { text: "Refuser net", correct: false },
      { text: "Ignorer la demande", correct: false },
    ],
    explanation: "Reconnaître une limite et montrer sa volonté d'apprendre est plus pro que bluffer. On propose une solution (formation rapide, aide ponctuelle).",
    tip: "« Je ne maîtrise pas encore, mais je peux apprendre / me faire aider. »",
  },
  {
    ...base, id: 'adm-si-16', type: 'situation', difficulty: 2,
    situation: "Vous recevez 60 emails par jour et l'inbox déborde.",
    question: "La méthode efficace :",
    options: [
      { text: "Tout laisser non lu", correct: false },
      { text: "Trier, traiter par priorité, classer et utiliser des dossiers/règles", correct: true },
      { text: "Répondre à tout dans le désordre", correct: false },
      { text: "Supprimer sans lire", correct: false },
    ],
    explanation: "Une gestion d'emails structurée (priorisation, dossiers, règles de tri) évite d'oublier l'important et réduit la charge mentale.",
    tip: "Traite par priorité, classe le reste, archive le traité.",
  },
  {
    ...base, id: 'adm-si-17', type: 'situation', difficulty: 3,
    context: "Votre supérieur vous demande de modifier une date sur un document officiel « pour arranger les choses ».",
    situation: "On vous demande quelque chose de limite éthiquement.",
    question: "La bonne attitude :",
    options: [
      { text: "Obéir sans réfléchir", correct: false },
      { text: "Exprimer poliment votre réserve et refuser ce qui n'est pas conforme", correct: true },
      { text: "Le faire en cachette", correct: false },
      { text: "En parler à tout le monde", correct: false },
    ],
    explanation: "On ne falsifie pas un document officiel, même sur demande. Exprimer une réserve avec tact et refuser protège l'entreprise et soi-même.",
    tip: "L'éthique passe avant l'obéissance aveugle.",
  },
  {
    ...base, id: 'adm-si-18', type: 'situation', difficulty: 1,
    situation: "Un fournisseur appelle pour un paiement en retard.",
    question: "La bonne réaction :",
    options: [
      { text: "Nier le retard", correct: false },
      { text: "Vérifier le dossier, donner une réponse factuelle et le délai de régularisation", correct: true },
      { text: "Promettre n'importe quoi", correct: false },
      { text: "Raccrocher", correct: false },
    ],
    explanation: "On traite une relance fournisseur avec sérieux : vérification, transparence et engagement réaliste préservent la relation commerciale.",
    tip: "Vérifie avant de répondre, puis engage un délai tenable.",
  },
  {
    ...base, id: 'adm-si-19', type: 'situation', difficulty: 2,
    situation: "Un nouvel arrivant ne sait pas où trouver les documents et procédures.",
    question: "La bonne attitude :",
    options: [
      { text: "Le laisser se débrouiller", correct: false },
      { text: "L'orienter, lui montrer l'organisation et rester disponible pour ses questions", correct: true },
      { text: "« Pas le temps »", correct: false },
      { text: "Lui donner de fausses infos", correct: false },
    ],
    explanation: "Faciliter l'intégration d'un nouveau (onboarding) reflète l'esprit d'équipe et la qualité d'organisation du service.",
    tip: "Un bon accueil du nouvel arrivant fait gagner tout le monde.",
  },
  {
    ...base, id: 'adm-si-20', type: 'situation', difficulty: 2,
    context: "Panne du logiciel de gestion en pleine journée chargée.",
    situation: "Un outil essentiel tombe en panne.",
    question: "La meilleure réaction :",
    options: [
      { text: "Attendre sans rien faire", correct: false },
      { text: "Prévenir le support IT, informer les collègues et basculer sur une solution de secours", correct: true },
      { text: "Paniquer et tout arrêter", correct: false },
      { text: "Bricoler au risque d'aggraver", correct: false },
    ],
    explanation: "Face à une panne, on alerte les bonnes personnes, on communique et on assure la continuité (procédure dégradée) le temps du rétablissement.",
    tip: "Alerte IT + plan B + information des collègues.",
  },

  // ── 📰 ACTU & TENDANCES (suite) ──
  {
    ...base, id: 'adm-ac-9', type: 'actu', difficulty: 2,
    situation: "Les entreprises dématérialisent leurs documents.",
    question: "Ce que la dématérialisation implique :",
    options: [
      { text: "Tout imprimer en double", correct: false },
      { text: "Numériser, classer électroniquement et réduire le papier (GED)", correct: true },
      { text: "Supprimer toute archive", correct: false },
      { text: "Garder uniquement le papier", correct: false },
    ],
    explanation: "La GED (gestion électronique des documents) structure les fichiers numériques pour les retrouver vite et réduire le papier. C'est devenu un standard.",
    tip: "Maîtriser la GED est un vrai atout administratif.",
  },
  {
    ...base, id: 'adm-ac-10', type: 'actu', difficulty: 2,
    situation: "Le télétravail hybride s'est installé.",
    question: "L'enjeu pour un assistant :",
    options: [
      { text: "Ne plus rien coordonner", correct: false },
      { text: "Fiabiliser la circulation de l'info et maîtriser les outils à distance", correct: true },
      { text: "Imposer le présentiel à tous", correct: false },
      { text: "Travailler sans jamais communiquer", correct: false },
    ],
    explanation: "En hybride, l'assistant joue un rôle de liant : coordination, partage d'information fluide et maîtrise des outils collaboratifs à distance.",
    tip: "À distance, sur-communique plutôt que sous-communique.",
  },
  {
    ...base, id: 'adm-ac-11', type: 'actu', difficulty: 2,
    situation: "Les outils collaboratifs (Teams, Slack, Notion) se généralisent.",
    question: "La bonne posture :",
    options: [
      { text: "Refuser de les utiliser", correct: false },
      { text: "Se former et les adopter pour mieux organiser le travail d'équipe", correct: true },
      { text: "Continuer tout par email uniquement", correct: false },
      { text: "Les utiliser sans aucune règle", correct: false },
    ],
    explanation: "L'aisance avec les outils collaboratifs est désormais attendue : ils structurent la communication et le suivi des tâches d'équipe.",
    tip: "Sois à l'aise avec au moins un outil collaboratif majeur.",
  },
  {
    ...base, id: 'adm-ac-12', type: 'actu', difficulty: 2,
    situation: "L'IA bureautique (rédaction, synthèse) se développe.",
    question: "Un usage pertinent pour un assistant :",
    options: [
      { text: "Lui faire signer les documents à votre place", correct: false },
      { text: "Aider à rédiger, résumer ou trier, en relisant toujours le résultat", correct: true },
      { text: "Lui faire gérer les données confidentielles sans contrôle", correct: false },
      { text: "Copier ses réponses sans vérifier", correct: false },
    ],
    explanation: "L'IA fait gagner du temps (brouillons, synthèses, tri) mais l'humain garde le contrôle : relecture, validation, confidentialité.",
    tip: "L'IA propose, tu vérifies et tu décides.",
  },
  {
    ...base, id: 'adm-ac-13', type: 'actu', difficulty: 2,
    situation: "La signature électronique remplace le papier.",
    question: "Son intérêt principal :",
    options: [
      { text: "Aucun, c'est moins sûr", correct: false },
      { text: "Gagner du temps et sécuriser/traçabiliser la validation des documents", correct: true },
      { text: "Empêcher de signer", correct: false },
      { text: "Obliger à tout réimprimer", correct: false },
    ],
    explanation: "La signature électronique accélère les circuits de validation tout en offrant traçabilité et valeur légale. Un standard en administratif moderne.",
    tip: "Signature électronique = rapidité + traçabilité.",
  },
  {
    ...base, id: 'adm-ac-14', type: 'actu', difficulty: 3,
    situation: "Le RGPD encadre le traitement des données personnelles.",
    question: "Le bon réflexe d'un assistant :",
    options: [
      { text: "Diffuser librement les données clients", correct: false },
      { text: "Limiter l'accès, ne collecter que le nécessaire et sécuriser les données", correct: true },
      { text: "Stocker tout sans limite", correct: false },
      { text: "Ignorer le sujet", correct: false },
    ],
    explanation: "Le RGPD impose minimisation, sécurité et accès restreint aux données personnelles. L'administratif y est en première ligne.",
    tip: "Ne collecte/partage que ce qui est strictement nécessaire.",
  },
  {
    ...base, id: 'adm-ac-15', type: 'actu', difficulty: 2,
    situation: "Beaucoup de tâches répétitives peuvent être automatisées.",
    question: "La bonne attitude :",
    options: [
      { text: "Refuser tout changement", correct: false },
      { text: "Repérer les tâches automatisables (modèles, règles, macros) pour se recentrer sur l'à-valeur", correct: true },
      { text: "Continuer tout à la main par principe", correct: false },
      { text: "Automatiser sans jamais vérifier", correct: false },
    ],
    explanation: "Automatiser le répétitif (modèles d'emails, règles de tri, publipostage) libère du temps pour les missions à plus forte valeur.",
    tip: "Gagne du temps sur le répétitif pour le mettre ailleurs.",
  },
  {
    ...base, id: 'adm-ac-16', type: 'actu', difficulty: 2,
    situation: "La cybersécurité concerne aussi l'administratif.",
    question: "Le bon réflexe face à un email suspect :",
    options: [
      { text: "Cliquer sur le lien pour voir", correct: false },
      { text: "Ne pas cliquer, vérifier l'expéditeur et signaler au service IT", correct: true },
      { text: "Transférer à tous les collègues", correct: false },
      { text: "Saisir ses identifiants « au cas où »", correct: false },
    ],
    explanation: "Le phishing vise souvent les fonctions support. Prudence (pas de clic, vérification, signalement) protège toute l'entreprise.",
    tip: "Dans le doute, ne clique pas et signale.",
  },
  {
    ...base, id: 'adm-ac-17', type: 'actu', difficulty: 1,
    situation: "Les entreprises cherchent à réduire leur empreinte écologique au bureau.",
    question: "Une bonne pratique administrative :",
    options: [
      { text: "Imprimer tout en couleur systématiquement", correct: false },
      { text: "Limiter les impressions, recto-verso, et privilégier le numérique", correct: true },
      { text: "Laisser les appareils allumés la nuit", correct: false },
      { text: "Gaspiller les fournitures", correct: false },
    ],
    explanation: "Des gestes simples (moins d'impressions, recto-verso, extinction des appareils) participent à la démarche écoresponsable de plus en plus valorisée.",
    tip: "Le « zéro papier » utile est un argument apprécié.",
  },
  {
    ...base, id: 'adm-ac-18', type: 'actu', difficulty: 2,
    situation: "Le métier d'assistant évolue vers plus de soft skills.",
    question: "Les compétences de plus en plus valorisées :",
    options: [
      { text: "Uniquement la frappe rapide", correct: false },
      { text: "Organisation, communication, adaptabilité et maîtrise des outils digitaux", correct: true },
      { text: "Aucune compétence relationnelle", correct: false },
      { text: "Seulement le classement papier", correct: false },
    ],
    explanation: "Au-delà de la technique, les recruteurs valorisent les soft skills (organisation, relationnel, adaptabilité) combinées à l'aisance numérique.",
    tip: "Mets en avant tes soft skills autant que tes outils.",
  },
  {
    ...base, id: 'adm-ac-19', type: 'actu', difficulty: 2,
    situation: "Les processus passent par des workflows numériques (validation en ligne).",
    question: "L'enjeu pour l'assistant :",
    options: [
      { text: "Tout refaire en papier", correct: false },
      { text: "Comprendre et faire avancer les circuits de validation digitaux", correct: true },
      { text: "Bloquer les validations", correct: false },
      { text: "Ignorer les notifications", correct: false },
    ],
    explanation: "Maîtriser les workflows numériques (relances de validation, suivi d'étapes) fluidifie les processus internes dont l'assistant est souvent le moteur.",
    tip: "Tu es souvent le moteur qui fait avancer les validations.",
  },
  {
    ...base, id: 'adm-ac-20', type: 'actu', difficulty: 1,
    situation: "On vous demande votre niveau sur les outils bureautiques en entretien.",
    question: "La meilleure réponse :",
    options: [
      { text: "« Je sais allumer un ordinateur »", correct: false },
      { text: "Préciser honnêtement votre niveau (Excel, Word, agenda…) avec des exemples d'usage", correct: true },
      { text: "Mentir en disant « expert en tout »", correct: false },
      { text: "« Je n'aime pas l'informatique »", correct: false },
    ],
    explanation: "On attend une auto-évaluation honnête et illustrée : quels outils, à quel niveau, pour quels usages concrets. Mieux vaut un niveau réel prouvé qu'un « expert » creux.",
    tip: "Illustre ton niveau par un usage concret réel.",
  },
];
