/**
 * Thème « Clôture & relance » — 20 scénarios.
 * Bien finir l'entretien, poser les bonnes questions et relancer avec tact.
 * Chaque question : exactement une option correct:true, + explanation + tip.
 */
export default [
  {
    id: 'clot-1', category: 'cloture', difficulty: 1,
    situation: "« Avez-vous des questions ? » en fin d'entretien.",
    question: "La meilleure attitude :",
    options: [
      { text: "« Non, tout est clair » et partir", correct: false },
      { text: "Poser 1-2 questions préparées et pertinentes", correct: true },
      { text: "Demander uniquement les congés et avantages", correct: false },
      { text: "Poser 15 questions pour montrer son intérêt", correct: false },
    ],
    explanation: "Ne pas avoir de question signale un manque d'intérêt. 1-2 questions pertinentes (équipe, enjeux du poste, prochaines étapes) montrent l'engagement.",
    tip: "Garde une question en réserve même si tout a été abordé.",
  },
  {
    id: 'clot-2', category: 'cloture', difficulty: 2,
    situation: "L'entretien est terminé depuis 2 jours, sans nouvelles.",
    question: "Quelle est la bonne pratique ?",
    options: [
      { text: "Relancer 10 fois par jour", correct: false },
      { text: "Envoyer un email de remerciement, puis relancer poliment après le délai annoncé", correct: true },
      { text: "Ne jamais relancer, attendre indéfiniment", correct: false },
      { text: "Appeler le soir sur le portable personnel du recruteur", correct: false },
    ],
    explanation: "Un mail de remerciement le jour même est un vrai plus. La relance se fait avec tact, après le délai indiqué, sans harceler.",
    tip: "Le mail de remerciement post-entretien est trop peu utilisé.",
  },
  {
    id: 'clot-3', category: 'cloture', difficulty: 2,
    situation: "Vous voulez poser une question en fin d'entretien.",
    question: "Quelle question fait la meilleure impression ?",
    options: [
      { text: "« Quels seraient mes premiers défis sur ce poste ? »", correct: true },
      { text: "« C'est quoi déjà votre entreprise ? »", correct: false },
      { text: "« On finit à quelle heure le vendredi ? »", correct: false },
      { text: "« Combien de congés dès le départ ? »", correct: false },
    ],
    explanation: "Une question tournée vers le poste et la contribution (défis, attentes, réussite à 6 mois) montre que tu te projettes déjà. Les questions centrées uniquement sur le confort personnel envoient un mauvais signal en fin d'entretien.",
    tip: "Garde les questions « congés/horaires » pour plus tard dans le process.",
  },
  {
    id: 'clot-4', category: 'cloture', difficulty: 1,
    situation: "Le recruteur n'a pas précisé la suite du processus.",
    question: "La bonne question de clôture :",
    options: [
      { text: "« Quelles sont les prochaines étapes et sous quel délai ? »", correct: true },
      { text: "Ne rien demander et rester dans le flou", correct: false },
      { text: "« Vous me prenez ou pas ? »", correct: false },
      { text: "« Vous appelez quand exactement, à l'heure près ? »", correct: false },
    ],
    explanation: "Demander les prochaines étapes et le délai est utile et professionnel : tu sais à quoi t'attendre et quand relancer. La formulation reste posée, sans exiger une réponse immédiate.",
    tip: "Connaître le délai annoncé te dit exactement quand relancer.",
  },
  {
    id: 'clot-5', category: 'cloture', difficulty: 2,
    situation: "Vous rédigez votre email de remerciement après l'entretien.",
    question: "Que doit-il contenir ?",
    options: [
      { text: "Un merci, un rappel de votre motivation et un point marquant de l'échange", correct: true },
      { text: "Une simple ligne « merci » sans rien d'autre", correct: false },
      { text: "Une relance pressante sur le salaire", correct: false },
      { text: "Un copier-coller générique envoyé partout", correct: false },
    ],
    explanation: "Un bon mail de remerciement est court, personnalisé et rappelle ta motivation en s'appuyant sur un moment précis de l'entretien. C'est ce qui le rend mémorable, pas un « merci » sec ou générique.",
    tip: "Cite un point concret de l'échange : ça prouve que tu étais attentif.",
  },
  {
    id: 'clot-6', category: 'cloture', difficulty: 1,
    situation: "Quand envoyer le mail de remerciement ?",
    question: "Le bon timing :",
    options: [
      { text: "Le jour même ou le lendemain matin", correct: true },
      { text: "Deux semaines après", correct: false },
      { text: "Jamais, ça ne sert à rien", correct: false },
      { text: "Dans la minute, depuis le hall", correct: false },
    ],
    explanation: "Le mail de remerciement a le plus d'impact envoyé le jour même ou le lendemain, tant que l'entretien est frais dans l'esprit du recruteur. Trop tard, il perd tout son effet.",
    tip: "Rédige-le le soir même, à tête reposée, et relis-toi avant d'envoyer.",
  },
  {
    id: 'clot-7', category: 'cloture', difficulty: 2,
    situation: "Le délai annoncé par le recruteur est dépassé d'une semaine.",
    question: "La bonne façon de relancer :",
    options: [
      { text: "Un email courtois rappelant votre intérêt et demandant où en est le process", correct: true },
      { text: "Plusieurs appels par jour", correct: false },
      { text: "Un message agressif réclamant une réponse", correct: false },
      { text: "Abandonner sans rien dire", correct: false },
    ],
    explanation: "Une fois le délai dépassé, une relance écrite, courtoise et brève est tout à fait légitime : elle rappelle ta motivation sans harceler. Le harcèlement ou l'agressivité te disqualifient.",
    tip: "Une seule relance bien faite vaut mieux que dix messages insistants.",
  },
  {
    id: 'clot-8', category: 'cloture', difficulty: 1,
    situation: "Vous avez oublié de demander quelque chose d'important pendant l'entretien.",
    question: "La meilleure solution :",
    options: [
      { text: "Le glisser poliment dans le mail de remerciement", correct: true },
      { text: "Rappeler dans l'heure en urgence", correct: false },
      { text: "Tant pis, ne jamais le demander", correct: false },
      { text: "Débarquer à nouveau dans les locaux", correct: false },
    ],
    explanation: "Le mail de suivi est l'occasion idéale pour poser une question oubliée, de façon brève et naturelle. Inutile de paniquer ou de rappeler en urgence pour un point qui peut attendre l'écrit.",
    tip: "Le mail de remerciement peut aussi servir à clarifier un point oublié.",
  },
  {
    id: 'clot-9', category: 'cloture', difficulty: 2,
    situation: "Le recruteur vous demande si vous avez d'autres pistes en cours.",
    question: "La meilleure réponse :",
    options: [
      { text: "Rester honnête et mesuré, sans bluffer ni se dévaloriser", correct: true },
      { text: "Mentir en disant avoir dix offres", correct: false },
      { text: "« Non, vous êtes mon dernier espoir »", correct: false },
      { text: "Refuser de répondre sèchement", correct: false },
    ],
    explanation: "On peut indiquer qu'on a d'autres pistes (c'est normal et plutôt valorisant) sans bluffer ni, à l'inverse, se présenter en situation de détresse. L'honnêteté mesurée inspire confiance.",
    tip: "Avoir d'autres pistes te valorise : reste factuel, sans en faire un chantage.",
  },
  {
    id: 'clot-10', category: 'cloture', difficulty: 1,
    situation: "En quittant la salle, le recruteur vous raccompagne.",
    question: "La bonne attitude :",
    options: [
      { text: "Le remercier, rester courtois et professionnel jusqu'à la porte", correct: true },
      { text: "Relâcher totalement, l'entretien est « fini »", correct: false },
      { text: "Lancer une blague familière", correct: false },
      { text: "Partir devant sans l'attendre", correct: false },
    ],
    explanation: "L'entretien n'est pas terminé tant que tu n'as pas quitté les lieux. Les derniers instants, plus informels, sont encore observés : reste cordial et professionnel jusqu'au bout.",
    tip: "Le trajet jusqu'à la sortie fait encore partie de l'entretien.",
  },
  {
    id: 'clot-11', category: 'cloture', difficulty: 3,
    context: "Fin d'un entretien qui s'est très bien passé pour un poste en marketing. Le recruteur sourit : « On vous tient au courant. »",
    situation: "Vous sentez un bon feeling et voulez marquer le coup à la fin.",
    question: "La meilleure dernière phrase :",
    options: [
      { text: "Réaffirmer clairement votre intérêt et votre envie de rejoindre l'équipe", correct: true },
      { text: "« Bon bah voilà, à plus alors »", correct: false },
      { text: "« Vous avez intérêt à me rappeler »", correct: false },
      { text: "Ne rien dire et partir", correct: false },
    ],
    explanation: "Conclure sur une affirmation sincère de motivation (« ce poste m'intéresse vraiment, j'aimerais beaucoup rejoindre votre équipe ») laisse une dernière impression forte. C'est souvent ce dont le recruteur se souvient.",
    tip: "Une phrase de motivation sincère en sortie peut faire pencher la balance.",
  },
  {
    id: 'clot-12', category: 'cloture', difficulty: 2,
    situation: "Vous recevez un refus après l'entretien.",
    question: "La meilleure réaction professionnelle :",
    options: [
      { text: "Remercier, demander un retour pour progresser et rester courtois", correct: true },
      { text: "Répondre un message agressif", correct: false },
      { text: "Ignorer totalement le refus", correct: false },
      { text: "Supplier de reconsidérer la décision", correct: false },
    ],
    explanation: "Un refus bien géré peut ouvrir des portes futures : remercier et demander un feedback constructif laisse une bonne image et t'aide à t'améliorer. Une réaction agressive ferme définitivement la porte.",
    tip: "Un refus géré avec classe peut déboucher sur une autre opportunité plus tard.",
  },
  {
    id: 'clot-13', category: 'cloture', difficulty: 2,
    situation: "On vous demande, pour finir, votre disponibilité.",
    question: "La meilleure réponse :",
    options: [
      { text: "Indiquer une date réaliste (préavis inclus) avec clarté", correct: true },
      { text: "« Quand vous voulez » sans réfléchir au préavis", correct: false },
      { text: "Promettre une disponibilité immédiate impossible à tenir", correct: false },
      { text: "Rester volontairement vague", correct: false },
    ],
    explanation: "Donner une disponibilité claire et tenable (en intégrant un éventuel préavis) montre ton sérieux et ta fiabilité. Promettre l'impossible ou rester flou crée des problèmes dès le départ.",
    tip: "Anticipe ton préavis pour annoncer une date que tu pourras vraiment respecter.",
  },
  {
    id: 'clot-14', category: 'cloture', difficulty: 1,
    situation: "Vous hésitez à poser une question sur le télétravail en fin d'entretien.",
    question: "La bonne approche :",
    options: [
      { text: "C'est une question légitime, posée avec tact parmi d'autres sur le poste", correct: true },
      { text: "Ne jamais oser parler des conditions de travail", correct: false },
      { text: "En faire votre seule et unique question", correct: false },
      { text: "Exiger 100 % de télétravail d'emblée", correct: false },
    ],
    explanation: "Les conditions de travail (dont le télétravail) sont des questions légitimes. L'important est l'équilibre : ne pas en faire ta seule préoccupation et le formuler avec tact, après les questions sur le poste.",
    tip: "Pose d'abord une question sur le poste, puis une sur les conditions.",
  },
  {
    id: 'clot-15', category: 'cloture', difficulty: 2,
    situation: "Plusieurs entretiens sont prévus (RH, puis manager).",
    question: "Après le premier, la bonne pratique :",
    options: [
      { text: "Remercier et confirmer votre intérêt pour la suite du processus", correct: true },
      { text: "Considérer que c'est gagné et se relâcher", correct: false },
      { text: "Zapper le mail de remerciement car « ce n'est que le début »", correct: false },
      { text: "Contacter directement le manager sans passer par les RH", correct: false },
    ],
    explanation: "Chaque étape compte : un mot de remerciement et la confirmation de ton intérêt entretiennent une bonne dynamique. On respecte le circuit prévu sans court-circuiter les interlocuteurs.",
    tip: "Soigne chaque étape comme si c'était la dernière.",
  },
  {
    id: 'clot-16', category: 'cloture', difficulty: 1,
    situation: "Vous n'avez vraiment aucune question spontanée en fin d'entretien.",
    question: "La meilleure solution :",
    options: [
      { text: "Avoir préparé 2-3 questions à l'avance pour ne jamais rester sans rien", correct: true },
      { text: "Dire « non, rien » et écourter", correct: false },
      { text: "Inventer une question absurde", correct: false },
      { text: "Demander pourquoi ils posent cette question", correct: false },
    ],
    explanation: "Ne jamais arriver sans questions préparées : c'est le filet de sécurité. Même si tout a été abordé, tu peux ressortir une question sur l'équipe, la culture ou les défis du poste.",
    tip: "Prépare 3 questions d'avance : tu en garderas toujours au moins une de côté.",
  },
  {
    id: 'clot-17', category: 'cloture', difficulty: 2,
    situation: "Vous voulez relancer mais craignez de « déranger ».",
    question: "La bonne perspective :",
    options: [
      { text: "Une relance courtoise après le délai est légitime et bien perçue", correct: true },
      { text: "Relancer est toujours mal vu", correct: false },
      { text: "Mieux vaut harceler pour être sûr d'être vu", correct: false },
      { text: "Ne jamais relancer pour ne déranger personne", correct: false },
    ],
    explanation: "Relancer poliment après le délai montre ta motivation et ton professionnalisme, loin de « déranger ». Le seul écueil serait l'excès : une relance bien dosée est toujours mieux que le silence passif.",
    tip: "Une relance espacée et polie est un signe de motivation, pas de gêne.",
  },
  {
    id: 'clot-18', category: 'cloture', difficulty: 2,
    situation: "Par quel canal relancer après un entretien ?",
    question: "Le choix le plus adapté :",
    options: [
      { text: "L'email, sauf si le recruteur a clairement proposé un autre moyen", correct: true },
      { text: "Les réseaux sociaux personnels du recruteur", correct: false },
      { text: "Un appel répété sur son portable privé", correct: false },
      { text: "En se présentant à l'accueil sans prévenir", correct: false },
    ],
    explanation: "L'email est le canal de relance par défaut : il laisse une trace et respecte le temps du recruteur. On évite les canaux intrusifs (réseaux perso, appels privés, visites surprises).",
    tip: "Réponds dans le fil de l'email d'origine : le recruteur retrouve le contexte.",
  },
  {
    id: 'clot-19', category: 'cloture', difficulty: 1,
    situation: "Le recruteur conclut : « Merci, c'était un plaisir. »",
    question: "La meilleure réponse :",
    options: [
      { text: "Lui retourner le compliment avec sincérité et le remercier de son temps", correct: true },
      { text: "Rester muet", correct: false },
      { text: "« Ouais, à la prochaine »", correct: false },
      { text: "Enchaîner sur une nouvelle question longue", correct: false },
    ],
    explanation: "Répondre chaleureusement et remercier le recruteur de son temps clôture l'échange sur une note positive et professionnelle. Le silence ou le ton trop familier gâchent cette dernière impression.",
    tip: "Un « merci pour votre temps et cet échange » fait toujours bonne impression.",
  },
  {
    id: 'clot-20', category: 'cloture', difficulty: 3,
    context: "Vous avez passé deux entretiens et la décision se prend cette semaine. Vous recevez entre-temps une autre offre avec une réponse à donner vite.",
    situation: "Vous devez gérer deux calendriers qui se chevauchent.",
    question: "La meilleure démarche :",
    options: [
      { text: "Informer avec tact l'entreprise préférée de votre échéance pour, si possible, accélérer", correct: true },
      { text: "Accepter l'autre offre puis se désister si la préférée répond", correct: false },
      { text: "Mentir aux deux pour gagner du temps", correct: false },
      { text: "Ne rien dire et espérer que tout s'aligne", correct: false },
    ],
    explanation: "Quand les calendriers se chevauchent, la transparence courtoise est la meilleure stratégie : informer l'entreprise préférée d'une échéance peut l'amener à accélérer. Jouer double jeu ou se désister après un « oui » abîme ta réputation.",
    tip: "Dire honnêtement « j'ai une échéance » est pro et peut accélérer une décision.",
  },
];
