/**
 * Secteur « Vente / Commerce » — parcours pilote (4 couches).
 *
 * Chaque question : sector:'commerce', type ∈ {comportemental, technique,
 * situation, actu}, une seule option correct:true, + explanation + tip.
 * `context` (optionnel) = mise en situation immersive.
 */
const base = { sector: 'commerce' };

export default [
  // ══════════════ 🧠 COMPORTEMENTAL ══════════════
  {
    ...base, id: 'com-cp-1', type: 'comportemental', difficulty: 1,
    situation: "« Pourquoi voulez-vous être commercial ? »",
    question: "La motivation la plus convaincante :",
    options: [
      { text: "« Pour gagner beaucoup d'argent rapidement »", correct: false },
      { text: "Le goût du contact, du challenge et de la conclusion d'un accord", correct: true },
      { text: "« Parce que je n'ai pas trouvé autre chose »", correct: false },
      { text: "« Pour ne pas rester derrière un bureau »", correct: false },
    ],
    explanation: "Un bon commercial est motivé par la relation, le défi et la performance — pas seulement par la prime. La rémunération variable est une conséquence, pas le moteur affiché.",
    tip: "Parle de relation client et de goût du résultat.",
  },
  {
    ...base, id: 'com-cp-2', type: 'comportemental', difficulty: 2,
    situation: "« Comment réagissez-vous face à un refus client ? »",
    question: "La meilleure attitude :",
    options: [
      { text: "Le prendre personnellement et se décourager", correct: false },
      { text: "Analyser le refus, en tirer une leçon et rebondir sur le suivant", correct: true },
      { text: "Insister lourdement jusqu'à agacer le client", correct: false },
      { text: "Abandonner définitivement ce prospect", correct: false },
    ],
    explanation: "Le refus fait partie du métier. La résilience et la capacité à analyser puis rebondir sont LA qualité n°1 attendue d'un commercial.",
    tip: "« Un non aujourd'hui n'est pas un non pour toujours. »",
  },
  {
    ...base, id: 'com-cp-3', type: 'comportemental', difficulty: 2,
    situation: "« Vous ratez votre objectif du mois. Que faites-vous ? »",
    question: "La réaction la plus pro :",
    options: [
      { text: "Trouver des excuses (marché, produit, concurrence)", correct: false },
      { text: "Analyser ses chiffres, identifier le point faible et ajuster son plan d'action", correct: true },
      { text: "Cacher ses résultats à son manager", correct: false },
      { text: "Se démotiver et lever le pied", correct: false },
    ],
    explanation: "On attend de la lucidité et de l'esprit d'analyse : revoir son pipe, son taux de transfo, sa prospection. Le commercial pilote ses chiffres, il ne les subit pas.",
    tip: "Montre que tu sais lire tes propres indicateurs.",
  },
  {
    ...base, id: 'com-cp-4', type: 'comportemental', difficulty: 2,
    situation: "« Êtes-vous plutôt esprit de compétition ou esprit d'équipe ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Compétition pure, les autres sont mes rivaux »", correct: false },
      { text: "Les deux : se dépasser tout en faisant progresser l'équipe", correct: true },
      { text: "« Équipe uniquement, la performance individuelle m'indiffère »", correct: false },
      { text: "« Ni l'un ni l'autre »", correct: false },
    ],
    explanation: "Les meilleures équipes commerciales combinent émulation individuelle et entraide. Montrer qu'on tire le collectif vers le haut rassure le recruteur.",
    tip: "Émulation oui, écrasement des collègues non.",
  },
  {
    ...base, id: 'com-cp-5', type: 'comportemental', difficulty: 3,
    situation: "« Racontez-moi une vente difficile que vous avez remportée. »",
    question: "Comment structurer la réponse ?",
    options: [
      { text: "Méthode STAR : contexte, enjeu, ce que tu as fait, le résultat obtenu", correct: true },
      { text: "Rester vague pour ne pas se tromper", correct: false },
      { text: "Tout attribuer à la chance", correct: false },
      { text: "Parler du produit sans parler de ton action", correct: false },
    ],
    explanation: "La méthode STAR met en valeur TON action et le résultat (chiffré si possible). C'est l'exercice favori des recruteurs commerciaux.",
    tip: "Finis par le chiffre : montant signé, % de marge, délai.",
  },
  {
    ...base, id: 'com-cp-6', type: 'comportemental', difficulty: 2,
    situation: "« Comment gérez-vous la pression des objectifs chiffrés ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« La pression me paralyse »", correct: false },
      { text: "En découpant l'objectif en actions quotidiennes mesurables", correct: true },
      { text: "« J'ignore les objectifs »", correct: false },
      { text: "« Je stresse mais je n'y peux rien »", correct: false },
    ],
    explanation: "Transformer un gros objectif en routine d'activité (nb d'appels, de RDV, de devis) rend la pression gérable et démontre une vraie méthode de travail.",
    tip: "Parle d'objectifs d'activité, pas seulement de résultat.",
  },

  // ══════════════ 🛠️ TECHNIQUE MÉTIER ══════════════
  {
    ...base, id: 'com-te-1', type: 'technique', difficulty: 1,
    situation: "Question technique de base.",
    question: "Qu'est-ce qu'un CRM ?",
    options: [
      { text: "Un logiciel de comptabilité", correct: false },
      { text: "Un outil de gestion de la relation et du suivi clients/prospects", correct: true },
      { text: "Un réseau social interne", correct: false },
      { text: "Un type de contrat commercial", correct: false },
    ],
    explanation: "Le CRM (Customer Relationship Management) centralise contacts, échanges, opportunités et pipeline. C'est l'outil quotidien du commercial (Salesforce, HubSpot, Pipedrive…).",
    tip: "Cite un CRM connu : tu montres que tu connais le terrain.",
  },
  {
    ...base, id: 'com-te-2', type: 'technique', difficulty: 2,
    situation: "Question sur le processus de vente.",
    question: "Qu'appelle-t-on le « cycle de vente » ?",
    options: [
      { text: "Le temps de pause entre deux ventes", correct: false },
      { text: "L'ensemble des étapes, du 1er contact à la signature (et au-delà)", correct: true },
      { text: "Le délai de livraison du produit", correct: false },
      { text: "La durée du contrat de travail", correct: false },
    ],
    explanation: "Le cycle de vente décrit les étapes : prospection → découverte → proposition → négociation → closing → fidélisation. En B2B il peut durer plusieurs mois.",
    tip: "En B2B, sais que le cycle est long et multi-interlocuteurs.",
  },
  {
    ...base, id: 'com-te-3', type: 'technique', difficulty: 2,
    situation: "Vocabulaire de la prospection.",
    question: "Quelle est la différence entre prospection « chaude » et « froide » ?",
    options: [
      { text: "La température du bureau", correct: false },
      { text: "Chaud = contact ayant déjà manifesté un intérêt ; froid = contact sans relation préalable", correct: true },
      { text: "Chaud = par téléphone, froid = par email", correct: false },
      { text: "Il n'y a aucune différence", correct: false },
    ],
    explanation: "Un lead « chaud » (a téléchargé un contenu, demandé un devis) convertit mieux qu'un contact « froid » jamais sollicité. La stratégie d'approche diffère totalement.",
    tip: "Priorise toujours les leads chauds dans ton pipe.",
  },
  {
    ...base, id: 'com-te-4', type: 'technique', difficulty: 2,
    situation: "Méthode de découverte client.",
    question: "À quoi sert la phase de « découverte des besoins » ?",
    options: [
      { text: "À présenter tout le catalogue d'emblée", correct: false },
      { text: "À questionner et écouter pour comprendre le vrai besoin avant de proposer", correct: true },
      { text: "À annoncer le prix immédiatement", correct: false },
      { text: "À parler de soi et de son entreprise", correct: false },
    ],
    explanation: "Découvrir avant de proposer est la base : on pose des questions ouvertes et on écoute (méthodes SONCAS, BANT, écoute active). Vendre sans découvrir, c'est vendre à l'aveugle.",
    tip: "Règle d'or : écouter 70 %, parler 30 %.",
  },
  {
    ...base, id: 'com-te-5', type: 'technique', difficulty: 3,
    situation: "Vocabulaire de la méthode de vente.",
    question: "Que vise la méthode SONCAS ?",
    options: [
      { text: "Calculer la marge d'une vente", correct: false },
      { text: "Identifier les motivations d'achat du client (Sécurité, Orgueil, Nouveauté, Confort, Argent, Sympathie)", correct: true },
      { text: "Organiser sa tournée commerciale", correct: false },
      { text: "Rédiger un contrat", correct: false },
    ],
    explanation: "SONCAS aide à cerner le levier psychologique du client pour adapter son argumentaire. C'est un classique des entretiens commerciaux.",
    tip: "Adapter son discours au profil SONCAS = vendre plus juste.",
  },
  {
    ...base, id: 'com-te-6', type: 'technique', difficulty: 2,
    situation: "Question sur la conclusion.",
    question: "Qu'est-ce que le « closing » ?",
    options: [
      { text: "La fermeture du magasin", correct: false },
      { text: "L'étape de conclusion où l'on amène le client à s'engager / signer", correct: true },
      { text: "L'annulation d'une commande", correct: false },
      { text: "La fin du contrat de travail", correct: false },
    ],
    explanation: "Le closing est l'art de conclure : repérer les signaux d'achat et proposer l'engagement au bon moment. Un bon commercial ose conclure sans forcer.",
    tip: "Sache repérer un signal d'achat et oser demander la signature.",
  },
  {
    ...base, id: 'com-te-7', type: 'technique', difficulty: 2,
    situation: "Stratégie de développement du chiffre.",
    question: "Quelle est la différence entre « up-sell » et « cross-sell » ?",
    options: [
      { text: "Up-sell = monter en gamme ; cross-sell = vendre un produit complémentaire", correct: true },
      { text: "Up-sell = vendre moins cher ; cross-sell = faire une remise", correct: false },
      { text: "Ce sont deux mots pour la même chose", correct: false },
      { text: "Up-sell = en ligne ; cross-sell = en magasin", correct: false },
    ],
    explanation: "Up-sell = proposer une version supérieure ; cross-sell = ajouter un produit lié (l'étui avec le téléphone). Deux leviers pour augmenter le panier moyen.",
    tip: "« Et avec ça ? » = du cross-sell qui ne dit pas son nom.",
  },
  {
    ...base, id: 'com-te-8', type: 'technique', difficulty: 3,
    situation: "Pilotage de la performance.",
    question: "Quel indicateur mesure l'efficacité commerciale ?",
    options: [
      { text: "Le nombre de pauses café", correct: false },
      { text: "Le taux de transformation (conversions / opportunités)", correct: true },
      { text: "La taille du bureau", correct: false },
      { text: "Le nombre d'emails reçus", correct: false },
    ],
    explanation: "Le taux de transformation (ou de conversion) est central, avec le panier moyen et la durée du cycle. Savoir piloter ses KPI distingue un commercial mature.",
    tip: "Connais 3 KPI : transfo, panier moyen, cycle de vente.",
  },
  {
    ...base, id: 'com-te-9', type: 'technique', difficulty: 2,
    situation: "Gestion des opportunités.",
    question: "Qu'est-ce que le « pipeline » (ou pipe) commercial ?",
    options: [
      { text: "Un outil de plomberie", correct: false },
      { text: "L'ensemble des opportunités en cours, réparties par étape d'avancement", correct: true },
      { text: "La liste des clients perdus", correct: false },
      { text: "Le planning des congés", correct: false },
    ],
    explanation: "Le pipeline visualise les affaires en cours et leur probabilité. Le gérer permet de prévoir le chiffre et de prioriser ses actions.",
    tip: "Un pipe bien tenu = des prévisions de vente fiables.",
  },

  // ══════════════ 🎭 MISE EN SITUATION ══════════════
  {
    ...base, id: 'com-si-1', type: 'situation', difficulty: 2,
    context: "Vous présentez votre offre à un prospect intéressé. Au moment du prix, il se redresse : « Houla, c'est beaucoup trop cher ! »",
    situation: "Le client lance l'objection prix.",
    question: "La meilleure réaction :",
    options: [
      { text: "Baisser immédiatement le prix pour ne pas perdre la vente", correct: false },
      { text: "Creuser : « Trop cher par rapport à quoi ? » puis revaloriser le bénéfice", correct: true },
      { text: "Se justifier en critiquant les concurrents", correct: false },
      { text: "Abandonner la vente", correct: false },
    ],
    explanation: "« Trop cher » est une objection à creuser, pas un refus. On comprend la référence du client, puis on réancre sur la valeur et le ROI avant de parler remise.",
    tip: "Ne brade jamais avant d'avoir défendu la valeur.",
  },
  {
    ...base, id: 'com-si-2', type: 'situation', difficulty: 2,
    context: "Fin de rendez-vous prometteur. Le client conclut : « C'est intéressant, je vais réfléchir et je reviens vers vous. »",
    situation: "Le client botte en touche.",
    question: "Le meilleur réflexe :",
    options: [
      { text: "« D'accord, à bientôt ! » et attendre sans rien faire", correct: false },
      { text: "Identifier ce qui le freine et convenir d'une date de relance précise", correct: true },
      { text: "Le relancer 5 fois le lendemain", correct: false },
      { text: "Considérer la vente comme perdue", correct: false },
    ],
    explanation: "« Je vais réfléchir » cache souvent un frein non exprimé. On le fait verbaliser et on verrouille une prochaine étape datée pour ne pas laisser l'affaire mourir.",
    tip: "Ne quitte jamais un RDV sans « next step » daté.",
  },
  {
    ...base, id: 'com-si-3', type: 'situation', difficulty: 3,
    context: "Un client fidèle vous appelle, très mécontent : sa commande est arrivée en retard et incomplète.",
    situation: "Client en colère au téléphone.",
    question: "La bonne attitude :",
    options: [
      { text: "Se justifier et rejeter la faute sur la logistique", correct: false },
      { text: "Écouter, reconnaître le problème, s'excuser et proposer une solution concrète", correct: true },
      { text: "Lui dire de rappeler plus tard", correct: false },
      { text: "Minimiser : « ce n'est pas si grave »", correct: false },
    ],
    explanation: "Un client mécontent bien traité devient souvent plus fidèle qu'avant. Écoute, empathie, responsabilité et solution : la réclamation est une occasion de fidéliser.",
    tip: "Un problème bien géré renforce la relation.",
  },
  {
    ...base, id: 'com-si-4', type: 'situation', difficulty: 2,
    context: "Vous relancez un prospect chaud depuis deux semaines : aucun retour à vos appels ni à vos mails.",
    situation: "Prospect devenu injoignable.",
    question: "La meilleure stratégie de relance :",
    options: [
      { text: "Appeler 3 fois par jour jusqu'à réponse", correct: false },
      { text: "Varier les canaux et apporter une nouvelle valeur (cas client, info utile)", correct: true },
      { text: "Le supprimer du CRM", correct: false },
      { text: "Envoyer un mail de reproche", correct: false },
    ],
    explanation: "La relance efficace n'est pas du harcèlement : on multiplie les canaux (mail, LinkedIn, tél) en apportant à chaque fois une raison nouvelle de répondre.",
    tip: "Chaque relance doit apporter de la valeur, pas juste « relancer ».",
  },
  {
    ...base, id: 'com-si-5', type: 'situation', difficulty: 3,
    context: "Le client est convaincu mais lâche : « Votre concurrent est 15 % moins cher. »",
    situation: "Comparaison avec un concurrent moins cher.",
    question: "La meilleure réponse :",
    options: [
      { text: "Dénigrer la qualité du concurrent", correct: false },
      { text: "Reconnaître l'écart et démontrer la valeur supérieure qui le justifie", correct: true },
      { text: "S'aligner immédiatement sur son prix", correct: false },
      { text: "« Alors allez chez lui »", correct: false },
    ],
    explanation: "On ne dénigre jamais un concurrent. On assume son prix en prouvant ce qui le justifie (service, garantie, accompagnement, ROI). Le prix se défend par la valeur.",
    tip: "Vends la différence, pas le rabais.",
  },
  {
    ...base, id: 'com-si-6', type: 'situation', difficulty: 2,
    context: "Premier rendez-vous avec un nouveau prospect. Vous vous installez.",
    situation: "Comment ouvrir un rendez-vous de découverte ?",
    question: "La meilleure entrée en matière :",
    options: [
      { text: "Dérouler tout de suite son argumentaire produit", correct: false },
      { text: "Poser des questions ouvertes pour comprendre son contexte et ses enjeux", correct: true },
      { text: "Annoncer son prix d'emblée", correct: false },
      { text: "Parler de la météo pendant 20 minutes", correct: false },
    ],
    explanation: "Un RDV de découverte s'ouvre par l'écoute : questions ouvertes sur le contexte, les enjeux, les priorités. On vend ensuite, en réponse à un besoin identifié.",
    tip: "« Parlez-moi de votre situation actuelle… » ouvre tout.",
  },
  {
    ...base, id: 'com-si-7', type: 'situation', difficulty: 3,
    context: "Négociation finale. Le client : « Faites un geste sur le prix et je signe aujourd'hui. »",
    situation: "Demande de remise contre signature immédiate.",
    question: "La meilleure approche :",
    options: [
      { text: "Accorder la remise sans contrepartie", correct: false },
      { text: "Négocier une contrepartie (volume, engagement, délai) en échange du geste", correct: true },
      { text: "Refuser sèchement toute discussion", correct: false },
      { text: "Doubler la remise pour être sûr de signer", correct: false },
    ],
    explanation: "Une remise se donne toujours contre quelque chose : volume supérieur, engagement plus long, paiement comptant. Concéder sans contrepartie dévalorise l'offre.",
    tip: "« Si je fais un geste, est-ce qu'on peut… ? » → contrepartie.",
  },
  {
    ...base, id: 'com-si-8', type: 'situation', difficulty: 3,
    context: "🏆 BOSS — Tu disposes de 30 secondes dans un ascenseur avec le décideur que tu cherches à joindre depuis des semaines.",
    situation: "Tu dois faire ton « elevator pitch ».",
    question: "Quelle structure de pitch est la plus efficace ?",
    options: [
      { text: "Lister toutes les fonctionnalités de ton produit", correct: false },
      { text: "Accroche → problème que tu résous → bénéfice concret → demande d'un RDV", correct: true },
      { text: "Raconter l'histoire complète de ton entreprise", correct: false },
      { text: "Demander directement de signer un contrat", correct: false },
    ],
    explanation: "Un elevator pitch va à l'essentiel : on accroche, on nomme le problème client, on promet un bénéfice mesurable, et on conclut par une demande simple (un rendez-vous). Pas de catalogue.",
    tip: "Objectif d'un pitch : décrocher la prochaine étape, pas tout vendre.",
  },

  // ══════════════ 📰 ACTU & TENDANCES (2026) ══════════════
  {
    ...base, id: 'com-ac-1', type: 'actu', difficulty: 2,
    situation: "Tendance majeure de la vente B2B.",
    question: "Qu'est-ce que le « social selling » ?",
    options: [
      { text: "Vendre uniquement en magasin", correct: false },
      { text: "Utiliser les réseaux (surtout LinkedIn) pour créer du lien et générer des opportunités", correct: true },
      { text: "Faire des soldes sur les réseaux sociaux", correct: false },
      { text: "Vendre à ses amis", correct: false },
    ],
    explanation: "Le social selling consiste à développer sa visibilité et ses relations sur LinkedIn pour attirer et engager des prospects. C'est devenu incontournable en B2B.",
    tip: "Un profil LinkedIn soigné est l'arme n°1 du commercial moderne.",
  },
  {
    ...base, id: 'com-ac-2', type: 'actu', difficulty: 3,
    situation: "L'IA transforme le métier de commercial.",
    question: "Comment l'IA aide-t-elle un commercial aujourd'hui ?",
    options: [
      { text: "Elle remplace totalement le commercial", correct: false },
      { text: "Elle automatise les tâches répétitives (saisie, scoring, mails) pour le recentrer sur la relation", correct: true },
      { text: "Elle ne sert à rien en vente", correct: false },
      { text: "Elle fixe les salaires", correct: false },
    ],
    explanation: "L'IA prend en charge le scoring des leads, la rédaction de mails, le résumé d'échanges, la prévision. Le commercial gagne du temps pour ce que l'IA ne fait pas : la relation humaine.",
    tip: "Sache dire comment l'IA te rend plus efficace, pas qu'elle te menace.",
  },
  {
    ...base, id: 'com-ac-3', type: 'actu', difficulty: 2,
    situation: "Évolution des attentes clients.",
    question: "Qu'oppose-t-on à la « vente transactionnelle » aujourd'hui ?",
    options: [
      { text: "La vente forcée", correct: false },
      { text: "La vente conseil / vente de valeur, centrée sur la réussite du client", correct: true },
      { text: "La vente au rabais", correct: false },
      { text: "La vente anonyme", correct: false },
    ],
    explanation: "Les clients fuient le « hard selling ». La tendance est à la vente conseil : comprendre, accompagner, apporter de la valeur sur la durée. Le commercial devient un partenaire.",
    tip: "Positionne-toi en conseiller, pas en vendeur de catalogue.",
  },
  {
    ...base, id: 'com-ac-4', type: 'actu', difficulty: 3,
    situation: "Organisation moderne des équipes.",
    question: "Que désigne l'alignement « sales & marketing » (smarketing) ?",
    options: [
      { text: "Fusionner les deux services en un seul bureau", correct: false },
      { text: "Faire travailler ventes et marketing main dans la main sur les leads et le discours", correct: true },
      { text: "Supprimer le marketing", correct: false },
      { text: "Vendre des produits marketing", correct: false },
    ],
    explanation: "Quand marketing et ventes partagent objectifs, définitions de leads et messages, la conversion grimpe. Cet alignement est une attente forte des entreprises en 2026.",
    tip: "Montre que tu sais collaborer avec le marketing.",
  },
  {
    ...base, id: 'com-ac-5', type: 'actu', difficulty: 2,
    situation: "Réalité de la vente B2B actuelle.",
    question: "Pourquoi les cycles de vente B2B se complexifient-ils ?",
    options: [
      { text: "Les clients décident plus vite et seuls", correct: false },
      { text: "Les décisions impliquent plus d'interlocuteurs et durent plus longtemps", correct: true },
      { text: "Il n'y a plus de concurrence", correct: false },
      { text: "Les prix sont devenus fixes partout", correct: false },
    ],
    explanation: "En B2B, on vend désormais à un comité d'achat (plusieurs décideurs) sur des cycles plus longs. Savoir cartographier les interlocuteurs est devenu clé.",
    tip: "Identifie tous les décideurs, pas juste ton contact.",
  },
  {
    ...base, id: 'com-ac-6', type: 'actu', difficulty: 2,
    situation: "Deux grandes stratégies d'acquisition.",
    question: "Quelle est la différence entre « inbound » et « outbound » ?",
    options: [
      { text: "Inbound = le client vient à toi (contenu, SEO) ; outbound = tu vas le chercher (prospection)", correct: true },
      { text: "Inbound = par téléphone ; outbound = par email", correct: false },
      { text: "Ce sont des synonymes", correct: false },
      { text: "Inbound = en France ; outbound = à l'étranger", correct: false },
    ],
    explanation: "Inbound : attirer via du contenu utile. Outbound : aller chercher activement (cold call, cold email). Les approches modernes combinent les deux.",
    tip: "Les meilleurs allient prospection active et attraction par le contenu.",
  },
  {
    ...base, id: 'com-ac-7', type: 'actu', difficulty: 3,
    situation: "Cadre légal de la prospection.",
    question: "En 2026, quelle règle encadre le cold emailing B2B en France ?",
    options: [
      { text: "Aucune, on peut écrire à n'importe qui", correct: false },
      { text: "Le RGPD : message en lien avec la fonction pro, mention de l'origine des données et droit d'opposition", correct: true },
      { text: "Il est totalement interdit", correct: false },
      { text: "Il faut l'accord écrit signé avant tout email", correct: false },
    ],
    explanation: "Le cold emailing B2B reste possible mais encadré par le RGPD : sollicitation cohérente avec la fonction du destinataire, transparence sur les données et possibilité de se désinscrire.",
    tip: "Prospecter oui, mais en respectant le RGPD.",
  },
  {
    ...base, id: 'com-ac-8', type: 'actu', difficulty: 2,
    situation: "Image du commercial sur le marché.",
    question: "Pourquoi le « personal branding » compte pour un commercial ?",
    options: [
      { text: "Pour avoir beaucoup de likes", correct: false },
      { text: "Parce qu'une réputation pro crédible attire la confiance et des opportunités", correct: true },
      { text: "Ça n'a aucun intérêt", correct: false },
      { text: "Pour devenir influenceur", correct: false },
    ],
    explanation: "Un commercial à la présence professionnelle soignée (LinkedIn, expertise partagée) inspire confiance et génère des contacts entrants. L'image personnelle est un actif commercial.",
    tip: "Ta crédibilité en ligne ouvre des portes hors ligne.",
  },

  // ── 🧠 COMPORTEMENTAL (suite) ──
  {
    ...base, id: 'com-cp-7', type: 'comportemental', difficulty: 2,
    situation: "« La pression des objectifs chiffrés, comment la vivez-vous ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Ça me stresse trop, j'évite d'y penser »", correct: false },
      { text: "Je m'en sers comme moteur et je découpe l'objectif en étapes hebdo", correct: true },
      { text: "« Les objectifs c'est du flicage »", correct: false },
      { text: "« Je fais semblant de les viser »", correct: false },
    ],
    explanation: "Un bon commercial transforme l'objectif en plan d'action concret. Montrer qu'on se l'approprie et qu'on le pilote rassure plus que « je gère ».",
    tip: "Décris ta méthode (objectif → étapes), pas juste ton ressenti.",
  },
  {
    ...base, id: 'com-cp-8', type: 'comportemental', difficulty: 2,
    situation: "Vous faites partie d'une équipe commerciale avec un classement interne.",
    question: "La bonne attitude vis-à-vis des collègues :",
    options: [
      { text: "Garder ses astuces pour soi et écraser les autres", correct: false },
      { text: "Être compétitif sainement tout en partageant les bonnes pratiques", correct: true },
      { text: "Saboter les leads des collègues", correct: false },
      { text: "Se désintéresser totalement du collectif", correct: false },
    ],
    explanation: "L'émulation est saine, mais une équipe qui partage performe mieux. Les recruteurs craignent les profils toxiques qui plombent l'ambiance.",
    tip: "Compétiteur OUI, mauvais joueur NON.",
  },
  {
    ...base, id: 'com-cp-9', type: 'comportemental', difficulty: 3,
    context: "Magasin de téléphonie. Un client revient, furieux, son forfait a mal été paramétré. Il hausse le ton devant les autres clients.",
    situation: "Le client vous parle agressivement alors que l'erreur vient d'un collègue.",
    question: "La meilleure réaction :",
    options: [
      { text: "« C'est pas moi, c'est mon collègue »", correct: false },
      { text: "Écouter, s'excuser au nom de l'enseigne, et proposer une solution immédiate", correct: true },
      { text: "Répondre sur le même ton", correct: false },
      { text: "L'ignorer en espérant qu'il parte", correct: false },
    ],
    explanation: "Face à un client mécontent, on représente l'enseigne : on assume collectivement, on désamorce par l'écoute et on agit. Se défausser sur un collègue aggrave tout.",
    tip: "« Je comprends, je règle ça tout de suite » désamorce 90 % des conflits.",
  },
  {
    ...base, id: 'com-cp-10', type: 'comportemental', difficulty: 2,
    situation: "Un client veut acheter un produit qui ne correspond pas vraiment à son besoin.",
    question: "La meilleure posture :",
    options: [
      { text: "Vendre quand même, c'est une vente de plus", correct: false },
      { text: "Le réorienter honnêtement vers ce qui lui convient, quitte à vendre moins cher", correct: true },
      { text: "Lui vendre le plus cher possible", correct: false },
      { text: "Le laisser se tromper sans rien dire", correct: false },
    ],
    explanation: "La vente durable repose sur la confiance : un client bien conseillé revient et recommande. L'honnêteté commerciale rapporte plus à long terme qu'une vente forcée.",
    tip: "Un client satisfait vaut dix ventes forcées.",
  },
  {
    ...base, id: 'com-cp-11', type: 'comportemental', difficulty: 1,
    situation: "« Qu'est-ce qui vous motive le plus dans la vente ? »",
    question: "La réponse la plus solide :",
    options: [
      { text: "« La prime, uniquement »", correct: false },
      { text: "Relever des défis, convaincre et voir un client satisfait", correct: true },
      { text: "« Ne rien faire de répétitif »", correct: false },
      { text: "« Avoir un titre de commercial »", correct: false },
    ],
    explanation: "La rémunération variable est un plus, mais le moteur durable est le goût du challenge et de la relation. Afficher l'argent comme seule motivation inquiète.",
    tip: "Le résultat financier est une conséquence, pas le discours.",
  },
  {
    ...base, id: 'com-cp-12', type: 'comportemental', difficulty: 2,
    situation: "Vous avez 15 clients à suivre et peu de temps.",
    question: "La bonne approche :",
    options: [
      { text: "Traiter au hasard ce qui vient", correct: false },
      { text: "Prioriser selon le potentiel et l'urgence, et planifier ses relances", correct: true },
      { text: "Ne s'occuper que des clients sympas", correct: false },
      { text: "Tout repousser à plus tard", correct: false },
    ],
    explanation: "L'organisation est une compétence commerciale clé : on priorise les comptes à fort potentiel et on tient un suivi rigoureux. Le talent ne remplace pas la méthode.",
    tip: "Un bon commercial est d'abord bien organisé.",
  },
  {
    ...base, id: 'com-cp-13', type: 'comportemental', difficulty: 2,
    situation: "Votre manager vous fait une remarque sur votre technique de closing.",
    question: "La meilleure réaction :",
    options: [
      { text: "Se vexer et se justifier longuement", correct: false },
      { text: "Écouter, remercier et tester le conseil sur le prochain rendez-vous", correct: true },
      { text: "Ignorer le conseil", correct: false },
      { text: "« De toute façon je vends bien »", correct: false },
    ],
    explanation: "Les meilleurs commerciaux progressent en continu. Accueillir un feedback et l'appliquer montre une vraie mentalité de croissance.",
    tip: "Le feedback du manager = un raccourci pour progresser.",
  },
  {
    ...base, id: 'com-cp-14', type: 'comportemental', difficulty: 2,
    situation: "Un prospect ne répond pas après deux relances.",
    question: "La bonne attitude :",
    options: [
      { text: "Abandonner immédiatement", correct: false },
      { text: "Relancer encore, autrement (canal/angle différent), puis espacer sans harceler", correct: true },
      { text: "Le harceler tous les jours", correct: false },
      { text: "Le supprimer du fichier", correct: false },
    ],
    explanation: "La majorité des ventes se font après plusieurs relances. La persévérance intelligente (varier l'approche, doser) distingue les bons commerciaux. Ni abandon, ni harcèlement.",
    tip: "Change d'angle à chaque relance plutôt que de répéter.",
  },
  {
    ...base, id: 'com-cp-15', type: 'comportemental', difficulty: 1,
    situation: "Un client commence à expliquer son besoin.",
    question: "Le bon réflexe :",
    options: [
      { text: "Lui couper la parole pour présenter le produit", correct: false },
      { text: "L'écouter activement, reformuler, puis proposer", correct: true },
      { text: "Penser déjà à l'argumentaire sans écouter", correct: false },
      { text: "Regarder son téléphone", correct: false },
    ],
    explanation: "L'écoute active est la base de la vente : comprendre avant de proposer. Reformuler montre qu'on a compris et crée la confiance.",
    tip: "On a deux oreilles et une bouche : écouter le double de ce qu'on parle.",
  },
  {
    ...base, id: 'com-cp-16', type: 'comportemental', difficulty: 2,
    situation: "« Êtes-vous sûr de vous en rendez-vous client ? »",
    question: "La réponse la plus juste :",
    options: [
      { text: "« Je suis le meilleur, personne ne me résiste »", correct: false },
      { text: "Confiant grâce à ma préparation, tout en restant à l'écoute", correct: true },
      { text: "« Pas trop en fait, ça dépend des jours »", correct: false },
      { text: "« Je récite mon texte par cœur »", correct: false },
    ],
    explanation: "La vraie confiance vient de la préparation, pas de l'arrogance. Assurance + écoute est l'équilibre gagnant ; l'excès dans un sens ou l'autre dessert.",
    tip: "La confiance se prépare, elle ne se claironne pas.",
  },
  {
    ...base, id: 'com-cp-17', type: 'comportemental', difficulty: 3,
    situation: "Vous perdez une grosse vente sur laquelle vous comptiez.",
    question: "La meilleure manière de réagir :",
    options: [
      { text: "Se démoraliser plusieurs jours", correct: false },
      { text: "Analyser ce qui a manqué, en tirer une leçon et repartir vite", correct: true },
      { text: "Blâmer le client ou le produit", correct: false },
      { text: "Faire comme si de rien n'était sans rien analyser", correct: false },
    ],
    explanation: "Encaisser un échec, l'analyser (debrief) et rebondir rapidement est une marque de maturité commerciale. La résilience se travaille.",
    tip: "Chaque vente perdue est une leçon pour la prochaine.",
  },
  {
    ...base, id: 'com-cp-18', type: 'comportemental', difficulty: 1,
    situation: "Un nouveau produit arrive dans votre gamme.",
    question: "Le bon réflexe :",
    options: [
      { text: "Attendre que les clients posent des questions", correct: false },
      { text: "Se former vite, le tester et préparer son argumentaire", correct: true },
      { text: "Continuer à vendre seulement l'ancien", correct: false },
      { text: "Improviser le jour J", correct: false },
    ],
    explanation: "La curiosité produit et la veille sont attendues : un commercial qui maîtrise son offre vend mieux et inspire confiance.",
    tip: "Connaître son produit à fond = arguments naturels.",
  },
  {
    ...base, id: 'com-cp-19', type: 'comportemental', difficulty: 1,
    situation: "Vous avez un rendez-vous client à 14h.",
    question: "Le comportement attendu :",
    options: [
      { text: "Arriver en avance, préparé, avec le dossier du client", correct: true },
      { text: "Arriver en retard « ça arrive »", correct: false },
      { text: "Venir sans avoir relu le dossier", correct: false },
      { text: "Décaler à la dernière minute par SMS", correct: false },
    ],
    explanation: "Ponctualité et préparation sont la base du sérieux commercial. Un rendez-vous raté ou bâclé peut coûter le client définitivement.",
    tip: "Relis la fiche client 10 min avant le rendez-vous.",
  },
  {
    ...base, id: 'com-cp-20', type: 'comportemental', difficulty: 2,
    situation: "Un collègue dépasse ses chiffres grâce à une nouvelle méthode.",
    question: "La bonne réaction :",
    options: [
      { text: "Le jalouser et le critiquer", correct: false },
      { text: "Lui demander de partager sa méthode et s'en inspirer", correct: true },
      { text: "Minimiser sa réussite", correct: false },
      { text: "Le copier en cachette sans rien dire", correct: false },
    ],
    explanation: "Apprendre des meilleurs est un accélérateur. L'humilité et la curiosité valent mieux que la jalousie, qui n'aide personne à progresser.",
    tip: "Entoure-toi des meilleurs et observe-les.",
  },

  // ── 🛠️ TECHNIQUE (suite) ──
  {
    ...base, id: 'com-te-10', type: 'technique', difficulty: 2,
    situation: "Vous démarrez un entretien de vente.",
    question: "Par quoi commencer pour bien vendre ?",
    options: [
      { text: "Dérouler tout de suite l'argumentaire produit", correct: false },
      { text: "La phase de découverte : poser des questions ouvertes sur le besoin", correct: true },
      { text: "Annoncer le prix d'emblée", correct: false },
      { text: "Parler de soi et de l'entreprise pendant 10 min", correct: false },
    ],
    explanation: "La découverte précède l'argumentation : les questions ouvertes (« comment », « pourquoi », « qu'attendez-vous ») révèlent le vrai besoin, base d'un argumentaire ciblé.",
    tip: "Pas de bon argumentaire sans bonne découverte.",
  },
  {
    ...base, id: 'com-te-11', type: 'technique', difficulty: 2,
    situation: "Le client émet une objection (« c'est compliqué à utiliser »).",
    question: "La bonne méthode de traitement :",
    options: [
      { text: "Contredire frontalement le client", correct: false },
      { text: "Accuser réception, creuser l'objection, puis y répondre avec une preuve", correct: true },
      { text: "Ignorer l'objection et continuer", correct: false },
      { text: "Baisser le prix immédiatement", correct: false },
    ],
    explanation: "Une objection est un signe d'intérêt. On l'accueille (« je comprends »), on la creuse pour la comprendre, puis on la traite avec un argument ou une démonstration.",
    tip: "Une objection traitée rapproche de la vente.",
  },
  {
    ...base, id: 'com-te-12', type: 'technique', difficulty: 3,
    situation: "Le client semble convaincu mais ne se décide pas.",
    question: "La bonne technique de closing :",
    options: [
      { text: "Attendre passivement qu'il dise oui", correct: false },
      { text: "Proposer une conclusion concrète (« on part sur le modèle X, livraison mardi ? »)", correct: true },
      { text: "Le presser agressivement", correct: false },
      { text: "Recommencer tout l'argumentaire", correct: false },
    ],
    explanation: "Le closing s'amorce par une proposition d'engagement claire (alternative, prochaine étape datée). Ne pas oser conclure fait perdre des ventes mûres.",
    tip: "Qui ne propose pas de conclure ne conclut pas.",
  },
  {
    ...base, id: 'com-te-13', type: 'technique', difficulty: 2,
    situation: "Un client achète un ordinateur portable.",
    question: "La vente additionnelle pertinente :",
    options: [
      { text: "Lui imposer 5 accessoires au hasard", correct: false },
      { text: "Proposer housse, garantie ou logiciel réellement utiles à SON usage", correct: true },
      { text: "Ne rien proposer du tout", correct: false },
      { text: "Lui vendre un produit sans aucun rapport", correct: false },
    ],
    explanation: "La vente additionnelle (cross-sell) augmente le panier ET la satisfaction quand elle est pertinente pour le besoin réel. Forcer des accessoires inutiles nuit à la confiance.",
    tip: "Vente additionnelle = service en plus, pas matraquage.",
  },
  {
    ...base, id: 'com-te-14', type: 'technique', difficulty: 2,
    situation: "Vous gérez un portefeuille de prospects.",
    question: "À quoi sert principalement un CRM ?",
    options: [
      { text: "À faire joli sur l'ordinateur", correct: false },
      { text: "À tracer les échanges, planifier les relances et ne rien oublier", correct: true },
      { text: "À surveiller les collègues", correct: false },
      { text: "À remplacer le commercial", correct: false },
    ],
    explanation: "Le CRM est la mémoire du commercial : historique, relances programmées, suivi du pipeline. Un suivi rigoureux évite les opportunités perdues.",
    tip: "Ce qui n'est pas dans le CRM finit par s'oublier.",
  },
  {
    ...base, id: 'com-te-15', type: 'technique', difficulty: 2,
    situation: "Vous présentez une caractéristique technique du produit.",
    question: "Comment la rendre vendeuse ?",
    options: [
      { text: "Énumérer les caractéristiques en rafale", correct: false },
      { text: "La traduire en avantage puis en bénéfice concret pour le client (méthode CAB)", correct: true },
      { text: "Utiliser un maximum de jargon technique", correct: false },
      { text: "Laisser le client deviner l'intérêt", correct: false },
    ],
    explanation: "La méthode CAB (Caractéristique → Avantage → Bénéfice) transforme une donnée technique en valeur perçue : « batterie 5000 mAh » → « deux jours sans recharge » → « tranquillité en déplacement ».",
    tip: "Le client achète un bénéfice, pas une fiche technique.",
  },
  {
    ...base, id: 'com-te-16', type: 'technique', difficulty: 3,
    context: "Prospection téléphonique. Vous appelez un décideur que vous ne connaissez pas.",
    situation: "Les 20 premières secondes de l'appel.",
    question: "La meilleure accroche :",
    options: [
      { text: "Réciter un script monotone sans respirer", correct: false },
      { text: "Se présenter, annoncer une raison d'appel orientée bénéfice, demander un court moment", correct: true },
      { text: "« Vous avez 5 minutes pour écouter mon offre ? »", correct: false },
      { text: "Parler 3 minutes sans laisser répondre", correct: false },
    ],
    explanation: "Au téléphone, l'accroche doit donner une raison d'écouter (bénéfice) et respecter le temps de l'interlocuteur. Le script récité et le monologue font raccrocher.",
    tip: "Capte l'intérêt en une phrase orientée bénéfice client.",
  },
  {
    ...base, id: 'com-te-17', type: 'technique', difficulty: 3,
    situation: "Le client demande une remise pour signer.",
    question: "La bonne pratique de négociation :",
    options: [
      { text: "Accorder la remise maximale tout de suite", correct: false },
      { text: "Défendre la valeur, et si on concède, demander une contrepartie", correct: true },
      { text: "Refuser sèchement toute discussion", correct: false },
      { text: "Casser le prix sans rien dire", correct: false },
    ],
    explanation: "Brader détruit la marge et la crédibilité. On rappelle d'abord la valeur ; toute concession s'échange contre une contrepartie (volume, engagement, délai).",
    tip: "Une remise se négocie, elle ne se donne pas.",
  },
  {
    ...base, id: 'com-te-18', type: 'technique', difficulty: 2,
    situation: "Vous recevez un nouveau lead.",
    question: "Que faut-il qualifier en priorité ?",
    options: [
      { text: "Sa couleur préférée", correct: false },
      { text: "Le besoin, le budget, le décideur et le délai (qualification)", correct: true },
      { text: "Rien, on vend à tout le monde pareil", correct: false },
      { text: "Uniquement son nom", correct: false },
    ],
    explanation: "Qualifier un lead (besoin, budget, décisionnaire, échéance — type BANT) évite de perdre du temps sur des pistes non mûres et permet d'adapter son approche.",
    tip: "Qualifier tôt = ne pas perdre de temps ensuite.",
  },
  {
    ...base, id: 'com-te-19', type: 'technique', difficulty: 2,
    situation: "Vous avez envoyé un devis il y a 5 jours, sans réponse.",
    question: "La bonne pratique :",
    options: [
      { text: "Attendre indéfiniment", correct: false },
      { text: "Relancer avec un message à valeur ajoutée (précision, échéance, dispo pour échanger)", correct: true },
      { text: "Renvoyer le même devis sans un mot", correct: false },
      { text: "Considérer la vente perdue", correct: false },
    ],
    explanation: "La relance post-devis fait partie du cycle de vente. Elle est plus efficace si elle apporte quelque chose (réponse à une question probable, rappel d'échéance) plutôt qu'un simple « alors ? ».",
    tip: "Relance utile > relance « vous avez vu mon devis ? ».",
  },
  {
    ...base, id: 'com-te-20', type: 'technique', difficulty: 2,
    situation: "Une vente vient d'être conclue.",
    question: "Que faire pour fidéliser ?",
    options: [
      { text: "Oublier le client, place au suivant", correct: false },
      { text: "Assurer le suivi (livraison, satisfaction) et rester disponible", correct: true },
      { text: "Ne le recontacter que pour revendre", correct: false },
      { text: "Disparaître après l'encaissement", correct: false },
    ],
    explanation: "La fidélisation se joue après la vente : un suivi attentif transforme un acheteur en client récurrent et en prescripteur. Le coût d'acquisition d'un nouveau client est bien plus élevé.",
    tip: "L'après-vente prépare la prochaine vente.",
  },

  // ── 🎭 MISE EN SITUATION (suite) ──
  {
    ...base, id: 'com-si-9', type: 'situation', difficulty: 2,
    context: "Concession automobile. Un client veut acheter mais exige 20 % de remise « sinon il va ailleurs ».",
    situation: "Le client met la pression sur le prix.",
    question: "La meilleure réponse :",
    options: [
      { text: "Céder immédiatement les 20 %", correct: false },
      { text: "Rappeler la valeur et les services inclus, proposer une contrepartie ou un geste mesuré", correct: true },
      { text: "« Allez ailleurs alors »", correct: false },
      { text: "Mentir sur le prix d'achat", correct: false },
    ],
    explanation: "On ne s'aligne pas par réflexe : on revalorise l'offre (garantie, services, reprise) et on négocie une contrepartie. Céder tout de suite signale que le prix était gonflé.",
    tip: "Avant de baisser le prix, ajoute de la valeur.",
  },
  {
    ...base, id: 'com-si-10', type: 'situation', difficulty: 2,
    situation: "Un client appelle, mécontent : le produit livré ne fonctionne pas.",
    question: "La bonne réaction :",
    options: [
      { text: "« Ce n'est pas mon problème, voyez le SAV »", correct: false },
      { text: "S'excuser, prendre en charge et proposer une solution rapide (échange, retour)", correct: true },
      { text: "Mettre en doute la parole du client", correct: false },
      { text: "Promettre sans jamais rappeler", correct: false },
    ],
    explanation: "Un problème bien géré fidélise plus qu'une vente sans accroc. On assume, on rassure et on résout vite : c'est ce dont le client se souviendra.",
    tip: "Un litige bien traité crée un client fidèle.",
  },
  {
    ...base, id: 'com-si-11', type: 'situation', difficulty: 3,
    context: "B2B. Un prospect très intéressé en rendez-vous ne donne plus de nouvelles depuis le devis.",
    situation: "Le prospect « ghoste » après une bonne réunion.",
    question: "La meilleure démarche :",
    options: [
      { text: "Le rayer du fichier", correct: false },
      { text: "Relancer avec tact, proposer un échange court pour lever un éventuel frein", correct: true },
      { text: "L'appeler 5 fois par jour", correct: false },
      { text: "Lui envoyer un message culpabilisant", correct: false },
    ],
    explanation: "Le silence cache souvent un frein non exprimé (budget, validation interne). Une relance bienveillante qui propose d'en parler permet de débloquer sans braquer.",
    tip: "Cherche le frein caché plutôt que de relancer « pour relancer ».",
  },
  {
    ...base, id: 'com-si-12', type: 'situation', difficulty: 2,
    situation: "Deux clients réclament votre attention en même temps en magasin.",
    question: "La bonne gestion :",
    options: [
      { text: "En ignorer un complètement", correct: false },
      { text: "Reconnaître les deux, faire patienter l'un avec courtoisie et le traiter ensuite", correct: true },
      { text: "Paniquer et bâcler les deux", correct: false },
      { text: "Servir uniquement celui qui semble le plus riche", correct: false },
    ],
    explanation: "On ne laisse jamais un client se sentir invisible : un mot, un regard, une estimation d'attente suffisent à le faire patienter sereinement.",
    tip: "« Je suis à vous dans un instant » change tout.",
  },
  {
    ...base, id: 'com-si-13', type: 'situation', difficulty: 2,
    situation: "Un client hésite longuement entre deux modèles.",
    question: "Comment l'aider à décider ?",
    options: [
      { text: "Décider à sa place autoritairement", correct: false },
      { text: "Reformuler son besoin et l'orienter vers le modèle le plus adapté", correct: true },
      { text: "Le pousser vers le plus cher quoi qu'il arrive", correct: false },
      { text: "Le laisser repartir sans rien", correct: false },
    ],
    explanation: "Face à l'indécision, on recadre sur le besoin prioritaire pour guider le choix. Le client veut être rassuré, pas manipulé ni abandonné.",
    tip: "Aide à choisir en revenant au besoin n°1.",
  },
  {
    ...base, id: 'com-si-14', type: 'situation', difficulty: 2,
    situation: "« Votre produit est trop cher », dit le client.",
    question: "La meilleure réponse :",
    options: [
      { text: "« Oui c'est vrai, c'est cher »", correct: false },
      { text: "Comprendre « trop cher par rapport à quoi ? » puis démontrer la valeur/ROI", correct: true },
      { text: "Baisser le prix aussitôt", correct: false },
      { text: "« Vous n'avez pas les moyens ? »", correct: false },
    ],
    explanation: "« Trop cher » est une objection à creuser : par rapport au budget, à un concurrent, à la valeur perçue ? On répond en démontrant le retour sur investissement.",
    tip: "« Trop cher par rapport à quoi ? » ouvre le vrai sujet.",
  },
  {
    ...base, id: 'com-si-15', type: 'situation', difficulty: 3,
    context: "Vous gérez un client fidèle depuis 3 ans. Il vous annonce qu'un concurrent lui fait une meilleure offre.",
    situation: "Un client clé menace de partir.",
    question: "La meilleure attitude :",
    options: [
      { text: "Le laisser partir sans réagir", correct: false },
      { text: "Comprendre ses griefs, valoriser la relation et construire une offre de rétention", correct: true },
      { text: "Le critiquer pour son ingratitude", correct: false },
      { text: "Dénigrer le concurrent agressivement", correct: false },
    ],
    explanation: "Retenir un client fidèle coûte moins cher que d'en conquérir un. On écoute ses raisons, on rappelle la valeur de la relation et on propose une solution adaptée.",
    tip: "Un client historique mérite un effort de rétention.",
  },
  {
    ...base, id: 'com-si-16', type: 'situation', difficulty: 2,
    situation: "Une erreur de livraison a livré le mauvais produit à un client.",
    question: "La bonne réaction :",
    options: [
      { text: "Attendre que le client s'en aperçoive", correct: false },
      { text: "Le prévenir de façon proactive, s'excuser et corriger immédiatement", correct: true },
      { text: "Rejeter la faute sur le transporteur", correct: false },
      { text: "Espérer qu'il ne remarque rien", correct: false },
    ],
    explanation: "La transparence proactive face à une erreur renforce la confiance. Prévenir avant que le client ne découvre le problème montre du professionnalisme.",
    tip: "Annonce le problème avant que le client ne le découvre.",
  },
  {
    ...base, id: 'com-si-17', type: 'situation', difficulty: 2,
    situation: "« Le concurrent est moins cher », dit le prospect.",
    question: "La meilleure réponse :",
    options: [
      { text: "Casser immédiatement votre prix", correct: false },
      { text: "Mettre en avant vos différenciateurs (qualité, service, garantie) qui justifient l'écart", correct: true },
      { text: "Dénigrer le concurrent", correct: false },
      { text: "« Alors achetez chez lui »", correct: false },
    ],
    explanation: "On ne se bat pas que sur le prix : on déplace le débat sur la valeur globale (qualité, accompagnement, fiabilité). Dénigrer un concurrent fait toujours mauvais effet.",
    tip: "Vends la valeur, pas le prix.",
  },
  {
    ...base, id: 'com-si-18', type: 'situation', difficulty: 3,
    context: "Acheteur professionnel aguerri, habitué à négocier dur. Il enchaîne les demandes de concessions.",
    situation: "Le client négocie de façon très agressive.",
    question: "La posture la plus efficace :",
    options: [
      { text: "Tout accepter pour ne pas le perdre", correct: false },
      { text: "Rester calme et ferme, chaque concession contre une contrepartie", correct: true },
      { text: "S'énerver à son tour", correct: false },
      { text: "Rompre l'échange immédiatement", correct: false },
    ],
    explanation: "Face à un négociateur dur, le sang-froid et la règle « donnant-donnant » protègent la marge et le respect mutuel. Tout céder t'affaiblit pour la suite.",
    tip: "Calme + fermeté + contrepartie systématique.",
  },
  {
    ...base, id: 'com-si-19', type: 'situation', difficulty: 2,
    situation: "On vous demande de vendre un produit dont vous doutez de la qualité.",
    question: "La meilleure attitude professionnelle :",
    options: [
      { text: "Le survendre quand même en cachant les défauts", correct: false },
      { text: "Faire remonter vos doutes en interne et rester honnête avec le client", correct: true },
      { text: "Refuser de travailler et claquer la porte", correct: false },
      { text: "Mentir sur ses caractéristiques", correct: false },
    ],
    explanation: "L'intégrité protège la relation client ET ta réputation. On alerte en interne et on reste honnête : un mensonge se paie tôt ou tard par des retours et du bouche-à-oreille négatif.",
    tip: "Ta réputation vaut plus qu'une vente douteuse.",
  },
  {
    ...base, id: 'com-si-20', type: 'situation', difficulty: 3,
    context: "Gros client stratégique. Il exige un délai de livraison que la logistique ne peut pas tenir.",
    situation: "Le client demande l'impossible sur les délais.",
    question: "La meilleure réponse :",
    options: [
      { text: "Promettre le délai impossible pour signer", correct: false },
      { text: "Être transparent sur le faisable et proposer une alternative crédible", correct: true },
      { text: "Refuser net sans alternative", correct: false },
      { text: "Ignorer la demande", correct: false },
    ],
    explanation: "Promettre l'impossible garantit un client furieux plus tard. Mieux vaut annoncer le réalisable et proposer une solution (livraison partielle, priorisation) qui préserve la relation.",
    tip: "Sous-promets et sur-livre, jamais l'inverse.",
  },

  // ── 📰 ACTU & TENDANCES (suite) ──
  {
    ...base, id: 'com-ac-9', type: 'actu', difficulty: 2,
    situation: "Le « social selling » se généralise.",
    question: "De quoi s'agit-il ?",
    options: [
      { text: "Vendre uniquement en magasin", correct: false },
      { text: "Utiliser les réseaux (LinkedIn…) pour créer du lien et générer des opportunités", correct: true },
      { text: "Faire de la pub télé", correct: false },
      { text: "Spammer les gens en message privé", correct: false },
    ],
    explanation: "Le social selling consiste à bâtir une relation et une crédibilité sur les réseaux pour attirer et engager des prospects. C'est du lien, pas du spam.",
    tip: "Apporte de la valeur en ligne avant de vendre.",
  },
  {
    ...base, id: 'com-ac-10', type: 'actu', difficulty: 2,
    situation: "L'IA s'invite dans les outils commerciaux.",
    question: "Un usage pertinent de l'IA pour un commercial :",
    options: [
      { text: "Remplacer totalement le commercial", correct: false },
      { text: "Aider à prioriser les leads, préparer les rendez-vous et automatiser les tâches répétitives", correct: true },
      { text: "Décider seule des remises", correct: false },
      { text: "Écrire des mensonges aux clients", correct: false },
    ],
    explanation: "L'IA augmente le commercial : scoring des leads, synthèses, rédaction d'emails, préparation. La relation humaine et la négociation restent au cœur du métier.",
    tip: "L'IA fait gagner du temps ; la relation reste humaine.",
  },
  {
    ...base, id: 'com-ac-11', type: 'actu', difficulty: 2,
    situation: "Les clients passent du magasin au site puis à l'appli.",
    question: "Comment appelle-t-on cette approche ?",
    options: [
      { text: "Le monocanal", correct: false },
      { text: "L'omnicanal : une expérience fluide entre tous les canaux", correct: true },
      { text: "Le hors-ligne uniquement", correct: false },
      { text: "Le démarchage à domicile", correct: false },
    ],
    explanation: "L'omnicanal offre une expérience cohérente quel que soit le canal (magasin, web, mobile, réseaux). Le client veut pouvoir commencer sur un canal et finir sur un autre.",
    tip: "Le client est omnicanal : sois présent partout, sans couture.",
  },
  {
    ...base, id: 'com-ac-12', type: 'actu', difficulty: 1,
    situation: "Beaucoup de rendez-vous commerciaux se tiennent en visioconférence.",
    question: "Le bon réflexe en visio :",
    options: [
      { text: "Couper sa caméra et lire ses notes", correct: false },
      { text: "Soigner cadre, lumière et regard caméra, et garder l'échange interactif", correct: true },
      { text: "Parler sans laisser le client réagir", correct: false },
      { text: "Faire autre chose en même temps", correct: false },
    ],
    explanation: "La vente à distance demande les mêmes codes que le présentiel, plus la maîtrise technique : image nette, contact visuel caméra et interactivité pour capter l'attention.",
    tip: "En visio, l'énergie et le regard caméra font la différence.",
  },
  {
    ...base, id: 'com-ac-13', type: 'actu', difficulty: 2,
    situation: "Les clients sont de plus en plus sensibles à la consommation responsable.",
    question: "La bonne attitude commerciale :",
    options: [
      { text: "Ignorer le sujet", correct: false },
      { text: "Connaître les engagements RSE de ses produits et savoir en parler sincèrement", correct: true },
      { text: "Faire du greenwashing", correct: false },
      { text: "Se moquer de ces préoccupations", correct: false },
    ],
    explanation: "L'argument responsable (origine, durabilité, réparabilité) compte de plus en plus. Il doit être sincère : le greenwashing se retourne contre la marque.",
    tip: "Maîtrise les arguments durables… sans surpromettre.",
  },
  {
    ...base, id: 'com-ac-14', type: 'actu', difficulty: 2,
    situation: "La personnalisation via les données client se développe.",
    question: "L'usage pertinent de la data client :",
    options: [
      { text: "Recommander des offres adaptées à l'historique et au besoin", correct: true },
      { text: "Espionner la vie privée sans consentement", correct: false },
      { text: "Envoyer les mêmes offres à tout le monde", correct: false },
      { text: "Revendre les données illégalement", correct: false },
    ],
    explanation: "Bien utilisée et dans le respect du RGPD, la data permet des recommandations pertinentes qui augmentent satisfaction et ventes. Le consentement et l'éthique sont incontournables.",
    tip: "Personnalise utile et respecte la vie privée (RGPD).",
  },
  {
    ...base, id: 'com-ac-15', type: 'actu', difficulty: 1,
    situation: "Les avis clients en ligne pèsent sur les décisions d'achat.",
    question: "La bonne pratique :",
    options: [
      { text: "Acheter de faux avis", correct: false },
      { text: "Encourager les clients satisfaits à laisser un avis et répondre aux avis négatifs", correct: true },
      { text: "Ignorer totalement les avis", correct: false },
      { text: "Supprimer tout avis critique", correct: false },
    ],
    explanation: "L'e-réputation se travaille : solliciter des avis authentiques et répondre avec professionnalisme aux critiques renforce la confiance. Les faux avis sont risqués et sanctionnés.",
    tip: "Réponds aux avis négatifs : ça rassure les futurs clients.",
  },
  {
    ...base, id: 'com-ac-16', type: 'actu', difficulty: 2,
    situation: "Des outils automatisent une partie de la prospection.",
    question: "Le bon équilibre :",
    options: [
      { text: "Tout automatiser et supprimer l'humain", correct: false },
      { text: "Automatiser les tâches répétitives, garder l'humain pour la relation", correct: true },
      { text: "Refuser tout outil par principe", correct: false },
      { text: "Envoyer des milliers de messages identiques", correct: false },
    ],
    explanation: "L'automatisation libère du temps sur les tâches à faible valeur, mais la relation, l'écoute et la négociation restent profondément humaines. Le mass-mailing impersonnel est contre-productif.",
    tip: "Automatise le répétitif, humanise la relation.",
  },
  {
    ...base, id: 'com-ac-17', type: 'actu', difficulty: 2,
    situation: "L'« expérience client » (CX) devient un facteur de différenciation majeur.",
    question: "Ce que cela signifie pour un commercial :",
    options: [
      { text: "Seul le produit compte, pas le ressenti", correct: false },
      { text: "Soigner chaque interaction, de l'accueil au suivi, pour marquer positivement", correct: true },
      { text: "Vendre vite et oublier le client", correct: false },
      { text: "Traiter les clients comme des numéros", correct: false },
    ],
    explanation: "À produit équivalent, c'est l'expérience (accueil, conseil, réactivité, suivi) qui fait revenir et recommander. Chaque point de contact compte.",
    tip: "On se souvient de comment on a été traité, pas que du prix.",
  },
  {
    ...base, id: 'com-ac-18', type: 'actu', difficulty: 2,
    situation: "Les marketplaces (Amazon, Cdiscount…) bouleversent la distribution.",
    question: "L'enjeu pour une marque qui y vend :",
    options: [
      { text: "Aucun enjeu, c'est magique", correct: false },
      { text: "Gagner en visibilité tout en soignant prix, avis et logistique face à la concurrence", correct: true },
      { text: "Ignorer totalement ce canal", correct: false },
      { text: "Y mettre n'importe quoi sans suivi", correct: false },
    ],
    explanation: "Les marketplaces offrent une vitrine énorme mais une concurrence féroce : la performance dépend du prix, des avis, de la disponibilité et de la qualité logistique.",
    tip: "Sur marketplace, avis et logistique font la vente.",
  },
  {
    ...base, id: 'com-ac-19', type: 'actu', difficulty: 2,
    situation: "Le modèle par abonnement (récurrence) se généralise.",
    question: "Son intérêt commercial principal :",
    options: [
      { text: "Encaisser une fois puis abandonner le client", correct: false },
      { text: "Des revenus récurrents et une relation durable à entretenir dans le temps", correct: true },
      { text: "Ne plus jamais avoir à fidéliser", correct: false },
      { text: "Bloquer le client contre son gré", correct: false },
    ],
    explanation: "L'abonnement crée un revenu prévisible mais exige de la valeur continue : un client mal suivi se désabonne. La fidélisation devient centrale.",
    tip: "En abonnement, la valeur doit se prouver chaque mois.",
  },
  {
    ...base, id: 'com-ac-20', type: 'actu', difficulty: 2,
    situation: "Avec l'inflation, les clients surveillent leur pouvoir d'achat.",
    question: "La bonne adaptation commerciale :",
    options: [
      { text: "Ignorer le contexte économique", correct: false },
      { text: "Mettre en avant le rapport qualité/prix, la durabilité et les solutions adaptées au budget", correct: true },
      { text: "Augmenter les prix sans rien expliquer", correct: false },
      { text: "Culpabiliser le client qui hésite", correct: false },
    ],
    explanation: "En période de tension sur le budget, l'argument valeur (durabilité, coût d'usage, ROI) et des solutions adaptées (options, facilités) rassurent et débloquent l'achat.",
    tip: "Parle « coût d'usage » et valeur, pas seulement prix d'achat.",
  },
];
