/**
 * Secteur « Vente / Commerce » — parcours pilote (4 couches).
 *
 * Chaque question : sector:'commerce', type ∈ {comportemental, technique,
 * situation, actu}, une seule option correct:true, + explanation + tip.
 * `context` (optionnel) = mise en situation immersive.
 */
const base = { sector: 'commerce' };

export default [
  // ══════════════ 🧠 COMPORTEMENTAL ══════════════
  {
    ...base, id: 'com-cp-1', type: 'comportemental', difficulty: 1,
    situation: "« Pourquoi voulez-vous être commercial ? »",
    question: "La motivation la plus convaincante :",
    options: [
      { text: "« Pour gagner beaucoup d'argent rapidement »", correct: false },
      { text: "Le goût du contact, du challenge et de la conclusion d'un accord", correct: true },
      { text: "« Parce que je n'ai pas trouvé autre chose »", correct: false },
      { text: "« Pour ne pas rester derrière un bureau »", correct: false },
    ],
    explanation: "Un bon commercial est motivé par la relation, le défi et la performance — pas seulement par la prime. La rémunération variable est une conséquence, pas le moteur affiché.",
    tip: "Parle de relation client et de goût du résultat.",
  },
  {
    ...base, id: 'com-cp-2', type: 'comportemental', difficulty: 2,
    situation: "« Comment réagissez-vous face à un refus client ? »",
    question: "La meilleure attitude :",
    options: [
      { text: "Le prendre personnellement et se décourager", correct: false },
      { text: "Analyser le refus, en tirer une leçon et rebondir sur le suivant", correct: true },
      { text: "Insister lourdement jusqu'à agacer le client", correct: false },
      { text: "Abandonner définitivement ce prospect", correct: false },
    ],
    explanation: "Le refus fait partie du métier. La résilience et la capacité à analyser puis rebondir sont LA qualité n°1 attendue d'un commercial.",
    tip: "« Un non aujourd'hui n'est pas un non pour toujours. »",
  },
  {
    ...base, id: 'com-cp-3', type: 'comportemental', difficulty: 2,
    situation: "« Vous ratez votre objectif du mois. Que faites-vous ? »",
    question: "La réaction la plus pro :",
    options: [
      { text: "Trouver des excuses (marché, produit, concurrence)", correct: false },
      { text: "Analyser ses chiffres, identifier le point faible et ajuster son plan d'action", correct: true },
      { text: "Cacher ses résultats à son manager", correct: false },
      { text: "Se démotiver et lever le pied", correct: false },
    ],
    explanation: "On attend de la lucidité et de l'esprit d'analyse : revoir son pipe, son taux de transfo, sa prospection. Le commercial pilote ses chiffres, il ne les subit pas.",
    tip: "Montre que tu sais lire tes propres indicateurs.",
  },
  {
    ...base, id: 'com-cp-4', type: 'comportemental', difficulty: 2,
    situation: "« Êtes-vous plutôt esprit de compétition ou esprit d'équipe ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Compétition pure, les autres sont mes rivaux »", correct: false },
      { text: "Les deux : se dépasser tout en faisant progresser l'équipe", correct: true },
      { text: "« Équipe uniquement, la performance individuelle m'indiffère »", correct: false },
      { text: "« Ni l'un ni l'autre »", correct: false },
    ],
    explanation: "Les meilleures équipes commerciales combinent émulation individuelle et entraide. Montrer qu'on tire le collectif vers le haut rassure le recruteur.",
    tip: "Émulation oui, écrasement des collègues non.",
  },
  {
    ...base, id: 'com-cp-5', type: 'comportemental', difficulty: 3,
    situation: "« Racontez-moi une vente difficile que vous avez remportée. »",
    question: "Comment structurer la réponse ?",
    options: [
      { text: "Méthode STAR : contexte, enjeu, ce que tu as fait, le résultat obtenu", correct: true },
      { text: "Rester vague pour ne pas se tromper", correct: false },
      { text: "Tout attribuer à la chance", correct: false },
      { text: "Parler du produit sans parler de ton action", correct: false },
    ],
    explanation: "La méthode STAR met en valeur TON action et le résultat (chiffré si possible). C'est l'exercice favori des recruteurs commerciaux.",
    tip: "Finis par le chiffre : montant signé, % de marge, délai.",
  },
  {
    ...base, id: 'com-cp-6', type: 'comportemental', difficulty: 2,
    situation: "« Comment gérez-vous la pression des objectifs chiffrés ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« La pression me paralyse »", correct: false },
      { text: "En découpant l'objectif en actions quotidiennes mesurables", correct: true },
      { text: "« J'ignore les objectifs »", correct: false },
      { text: "« Je stresse mais je n'y peux rien »", correct: false },
    ],
    explanation: "Transformer un gros objectif en routine d'activité (nb d'appels, de RDV, de devis) rend la pression gérable et démontre une vraie méthode de travail.",
    tip: "Parle d'objectifs d'activité, pas seulement de résultat.",
  },

  // ══════════════ 🛠️ TECHNIQUE MÉTIER ══════════════
  {
    ...base, id: 'com-te-1', type: 'technique', difficulty: 1,
    situation: "Question technique de base.",
    question: "Qu'est-ce qu'un CRM ?",
    options: [
      { text: "Un logiciel de comptabilité", correct: false },
      { text: "Un outil de gestion de la relation et du suivi clients/prospects", correct: true },
      { text: "Un réseau social interne", correct: false },
      { text: "Un type de contrat commercial", correct: false },
    ],
    explanation: "Le CRM (Customer Relationship Management) centralise contacts, échanges, opportunités et pipeline. C'est l'outil quotidien du commercial (Salesforce, HubSpot, Pipedrive…).",
    tip: "Cite un CRM connu : tu montres que tu connais le terrain.",
  },
  {
    ...base, id: 'com-te-2', type: 'technique', difficulty: 2,
    situation: "Question sur le processus de vente.",
    question: "Qu'appelle-t-on le « cycle de vente » ?",
    options: [
      { text: "Le temps de pause entre deux ventes", correct: false },
      { text: "L'ensemble des étapes, du 1er contact à la signature (et au-delà)", correct: true },
      { text: "Le délai de livraison du produit", correct: false },
      { text: "La durée du contrat de travail", correct: false },
    ],
    explanation: "Le cycle de vente décrit les étapes : prospection → découverte → proposition → négociation → closing → fidélisation. En B2B il peut durer plusieurs mois.",
    tip: "En B2B, sais que le cycle est long et multi-interlocuteurs.",
  },
  {
    ...base, id: 'com-te-3', type: 'technique', difficulty: 2,
    situation: "Vocabulaire de la prospection.",
    question: "Quelle est la différence entre prospection « chaude » et « froide » ?",
    options: [
      { text: "La température du bureau", correct: false },
      { text: "Chaud = contact ayant déjà manifesté un intérêt ; froid = contact sans relation préalable", correct: true },
      { text: "Chaud = par téléphone, froid = par email", correct: false },
      { text: "Il n'y a aucune différence", correct: false },
    ],
    explanation: "Un lead « chaud » (a téléchargé un contenu, demandé un devis) convertit mieux qu'un contact « froid » jamais sollicité. La stratégie d'approche diffère totalement.",
    tip: "Priorise toujours les leads chauds dans ton pipe.",
  },
  {
    ...base, id: 'com-te-4', type: 'technique', difficulty: 2,
    situation: "Méthode de découverte client.",
    question: "À quoi sert la phase de « découverte des besoins » ?",
    options: [
      { text: "À présenter tout le catalogue d'emblée", correct: false },
      { text: "À questionner et écouter pour comprendre le vrai besoin avant de proposer", correct: true },
      { text: "À annoncer le prix immédiatement", correct: false },
      { text: "À parler de soi et de son entreprise", correct: false },
    ],
    explanation: "Découvrir avant de proposer est la base : on pose des questions ouvertes et on écoute (méthodes SONCAS, BANT, écoute active). Vendre sans découvrir, c'est vendre à l'aveugle.",
    tip: "Règle d'or : écouter 70 %, parler 30 %.",
  },
  {
    ...base, id: 'com-te-5', type: 'technique', difficulty: 3,
    situation: "Vocabulaire de la méthode de vente.",
    question: "Que vise la méthode SONCAS ?",
    options: [
      { text: "Calculer la marge d'une vente", correct: false },
      { text: "Identifier les motivations d'achat du client (Sécurité, Orgueil, Nouveauté, Confort, Argent, Sympathie)", correct: true },
      { text: "Organiser sa tournée commerciale", correct: false },
      { text: "Rédiger un contrat", correct: false },
    ],
    explanation: "SONCAS aide à cerner le levier psychologique du client pour adapter son argumentaire. C'est un classique des entretiens commerciaux.",
    tip: "Adapter son discours au profil SONCAS = vendre plus juste.",
  },
  {
    ...base, id: 'com-te-6', type: 'technique', difficulty: 2,
    situation: "Question sur la conclusion.",
    question: "Qu'est-ce que le « closing » ?",
    options: [
      { text: "La fermeture du magasin", correct: false },
      { text: "L'étape de conclusion où l'on amène le client à s'engager / signer", correct: true },
      { text: "L'annulation d'une commande", correct: false },
      { text: "La fin du contrat de travail", correct: false },
    ],
    explanation: "Le closing est l'art de conclure : repérer les signaux d'achat et proposer l'engagement au bon moment. Un bon commercial ose conclure sans forcer.",
    tip: "Sache repérer un signal d'achat et oser demander la signature.",
  },
  {
    ...base, id: 'com-te-7', type: 'technique', difficulty: 2,
    situation: "Stratégie de développement du chiffre.",
    question: "Quelle est la différence entre « up-sell » et « cross-sell » ?",
    options: [
      { text: "Up-sell = monter en gamme ; cross-sell = vendre un produit complémentaire", correct: true },
      { text: "Up-sell = vendre moins cher ; cross-sell = faire une remise", correct: false },
      { text: "Ce sont deux mots pour la même chose", correct: false },
      { text: "Up-sell = en ligne ; cross-sell = en magasin", correct: false },
    ],
    explanation: "Up-sell = proposer une version supérieure ; cross-sell = ajouter un produit lié (l'étui avec le téléphone). Deux leviers pour augmenter le panier moyen.",
    tip: "« Et avec ça ? » = du cross-sell qui ne dit pas son nom.",
  },
  {
    ...base, id: 'com-te-8', type: 'technique', difficulty: 3,
    situation: "Pilotage de la performance.",
    question: "Quel indicateur mesure l'efficacité commerciale ?",
    options: [
      { text: "Le nombre de pauses café", correct: false },
      { text: "Le taux de transformation (conversions / opportunités)", correct: true },
      { text: "La taille du bureau", correct: false },
      { text: "Le nombre d'emails reçus", correct: false },
    ],
    explanation: "Le taux de transformation (ou de conversion) est central, avec le panier moyen et la durée du cycle. Savoir piloter ses KPI distingue un commercial mature.",
    tip: "Connais 3 KPI : transfo, panier moyen, cycle de vente.",
  },
  {
    ...base, id: 'com-te-9', type: 'technique', difficulty: 2,
    situation: "Gestion des opportunités.",
    question: "Qu'est-ce que le « pipeline » (ou pipe) commercial ?",
    options: [
      { text: "Un outil de plomberie", correct: false },
      { text: "L'ensemble des opportunités en cours, réparties par étape d'avancement", correct: true },
      { text: "La liste des clients perdus", correct: false },
      { text: "Le planning des congés", correct: false },
    ],
    explanation: "Le pipeline visualise les affaires en cours et leur probabilité. Le gérer permet de prévoir le chiffre et de prioriser ses actions.",
    tip: "Un pipe bien tenu = des prévisions de vente fiables.",
  },

  // ══════════════ 🎭 MISE EN SITUATION ══════════════
  {
    ...base, id: 'com-si-1', type: 'situation', difficulty: 2,
    context: "Vous présentez votre offre à un prospect intéressé. Au moment du prix, il se redresse : « Houla, c'est beaucoup trop cher ! »",
    situation: "Le client lance l'objection prix.",
    question: "La meilleure réaction :",
    options: [
      { text: "Baisser immédiatement le prix pour ne pas perdre la vente", correct: false },
      { text: "Creuser : « Trop cher par rapport à quoi ? » puis revaloriser le bénéfice", correct: true },
      { text: "Se justifier en critiquant les concurrents", correct: false },
      { text: "Abandonner la vente", correct: false },
    ],
    explanation: "« Trop cher » est une objection à creuser, pas un refus. On comprend la référence du client, puis on réancre sur la valeur et le ROI avant de parler remise.",
    tip: "Ne brade jamais avant d'avoir défendu la valeur.",
  },
  {
    ...base, id: 'com-si-2', type: 'situation', difficulty: 2,
    context: "Fin de rendez-vous prometteur. Le client conclut : « C'est intéressant, je vais réfléchir et je reviens vers vous. »",
    situation: "Le client botte en touche.",
    question: "Le meilleur réflexe :",
    options: [
      { text: "« D'accord, à bientôt ! » et attendre sans rien faire", correct: false },
      { text: "Identifier ce qui le freine et convenir d'une date de relance précise", correct: true },
      { text: "Le relancer 5 fois le lendemain", correct: false },
      { text: "Considérer la vente comme perdue", correct: false },
    ],
    explanation: "« Je vais réfléchir » cache souvent un frein non exprimé. On le fait verbaliser et on verrouille une prochaine étape datée pour ne pas laisser l'affaire mourir.",
    tip: "Ne quitte jamais un RDV sans « next step » daté.",
  },
  {
    ...base, id: 'com-si-3', type: 'situation', difficulty: 3,
    context: "Un client fidèle vous appelle, très mécontent : sa commande est arrivée en retard et incomplète.",
    situation: "Client en colère au téléphone.",
    question: "La bonne attitude :",
    options: [
      { text: "Se justifier et rejeter la faute sur la logistique", correct: false },
      { text: "Écouter, reconnaître le problème, s'excuser et proposer une solution concrète", correct: true },
      { text: "Lui dire de rappeler plus tard", correct: false },
      { text: "Minimiser : « ce n'est pas si grave »", correct: false },
    ],
    explanation: "Un client mécontent bien traité devient souvent plus fidèle qu'avant. Écoute, empathie, responsabilité et solution : la réclamation est une occasion de fidéliser.",
    tip: "Un problème bien géré renforce la relation.",
  },
  {
    ...base, id: 'com-si-4', type: 'situation', difficulty: 2,
    context: "Vous relancez un prospect chaud depuis deux semaines : aucun retour à vos appels ni à vos mails.",
    situation: "Prospect devenu injoignable.",
    question: "La meilleure stratégie de relance :",
    options: [
      { text: "Appeler 3 fois par jour jusqu'à réponse", correct: false },
      { text: "Varier les canaux et apporter une nouvelle valeur (cas client, info utile)", correct: true },
      { text: "Le supprimer du CRM", correct: false },
      { text: "Envoyer un mail de reproche", correct: false },
    ],
    explanation: "La relance efficace n'est pas du harcèlement : on multiplie les canaux (mail, LinkedIn, tél) en apportant à chaque fois une raison nouvelle de répondre.",
    tip: "Chaque relance doit apporter de la valeur, pas juste « relancer ».",
  },
  {
    ...base, id: 'com-si-5', type: 'situation', difficulty: 3,
    context: "Le client est convaincu mais lâche : « Votre concurrent est 15 % moins cher. »",
    situation: "Comparaison avec un concurrent moins cher.",
    question: "La meilleure réponse :",
    options: [
      { text: "Dénigrer la qualité du concurrent", correct: false },
      { text: "Reconnaître l'écart et démontrer la valeur supérieure qui le justifie", correct: true },
      { text: "S'aligner immédiatement sur son prix", correct: false },
      { text: "« Alors allez chez lui »", correct: false },
    ],
    explanation: "On ne dénigre jamais un concurrent. On assume son prix en prouvant ce qui le justifie (service, garantie, accompagnement, ROI). Le prix se défend par la valeur.",
    tip: "Vends la différence, pas le rabais.",
  },
  {
    ...base, id: 'com-si-6', type: 'situation', difficulty: 2,
    context: "Premier rendez-vous avec un nouveau prospect. Vous vous installez.",
    situation: "Comment ouvrir un rendez-vous de découverte ?",
    question: "La meilleure entrée en matière :",
    options: [
      { text: "Dérouler tout de suite son argumentaire produit", correct: false },
      { text: "Poser des questions ouvertes pour comprendre son contexte et ses enjeux", correct: true },
      { text: "Annoncer son prix d'emblée", correct: false },
      { text: "Parler de la météo pendant 20 minutes", correct: false },
    ],
    explanation: "Un RDV de découverte s'ouvre par l'écoute : questions ouvertes sur le contexte, les enjeux, les priorités. On vend ensuite, en réponse à un besoin identifié.",
    tip: "« Parlez-moi de votre situation actuelle… » ouvre tout.",
  },
  {
    ...base, id: 'com-si-7', type: 'situation', difficulty: 3,
    context: "Négociation finale. Le client : « Faites un geste sur le prix et je signe aujourd'hui. »",
    situation: "Demande de remise contre signature immédiate.",
    question: "La meilleure approche :",
    options: [
      { text: "Accorder la remise sans contrepartie", correct: false },
      { text: "Négocier une contrepartie (volume, engagement, délai) en échange du geste", correct: true },
      { text: "Refuser sèchement toute discussion", correct: false },
      { text: "Doubler la remise pour être sûr de signer", correct: false },
    ],
    explanation: "Une remise se donne toujours contre quelque chose : volume supérieur, engagement plus long, paiement comptant. Concéder sans contrepartie dévalorise l'offre.",
    tip: "« Si je fais un geste, est-ce qu'on peut… ? » → contrepartie.",
  },
  {
    ...base, id: 'com-si-8', type: 'situation', difficulty: 3,
    context: "🏆 BOSS — Tu disposes de 30 secondes dans un ascenseur avec le décideur que tu cherches à joindre depuis des semaines.",
    situation: "Tu dois faire ton « elevator pitch ».",
    question: "Quelle structure de pitch est la plus efficace ?",
    options: [
      { text: "Lister toutes les fonctionnalités de ton produit", correct: false },
      { text: "Accroche → problème que tu résous → bénéfice concret → demande d'un RDV", correct: true },
      { text: "Raconter l'histoire complète de ton entreprise", correct: false },
      { text: "Demander directement de signer un contrat", correct: false },
    ],
    explanation: "Un elevator pitch va à l'essentiel : on accroche, on nomme le problème client, on promet un bénéfice mesurable, et on conclut par une demande simple (un rendez-vous). Pas de catalogue.",
    tip: "Objectif d'un pitch : décrocher la prochaine étape, pas tout vendre.",
  },

  // ══════════════ 📰 ACTU & TENDANCES (2026) ══════════════
  {
    ...base, id: 'com-ac-1', type: 'actu', difficulty: 2,
    situation: "Tendance majeure de la vente B2B.",
    question: "Qu'est-ce que le « social selling » ?",
    options: [
      { text: "Vendre uniquement en magasin", correct: false },
      { text: "Utiliser les réseaux (surtout LinkedIn) pour créer du lien et générer des opportunités", correct: true },
      { text: "Faire des soldes sur les réseaux sociaux", correct: false },
      { text: "Vendre à ses amis", correct: false },
    ],
    explanation: "Le social selling consiste à développer sa visibilité et ses relations sur LinkedIn pour attirer et engager des prospects. C'est devenu incontournable en B2B.",
    tip: "Un profil LinkedIn soigné est l'arme n°1 du commercial moderne.",
  },
  {
    ...base, id: 'com-ac-2', type: 'actu', difficulty: 3,
    situation: "L'IA transforme le métier de commercial.",
    question: "Comment l'IA aide-t-elle un commercial aujourd'hui ?",
    options: [
      { text: "Elle remplace totalement le commercial", correct: false },
      { text: "Elle automatise les tâches répétitives (saisie, scoring, mails) pour le recentrer sur la relation", correct: true },
      { text: "Elle ne sert à rien en vente", correct: false },
      { text: "Elle fixe les salaires", correct: false },
    ],
    explanation: "L'IA prend en charge le scoring des leads, la rédaction de mails, le résumé d'échanges, la prévision. Le commercial gagne du temps pour ce que l'IA ne fait pas : la relation humaine.",
    tip: "Sache dire comment l'IA te rend plus efficace, pas qu'elle te menace.",
  },
  {
    ...base, id: 'com-ac-3', type: 'actu', difficulty: 2,
    situation: "Évolution des attentes clients.",
    question: "Qu'oppose-t-on à la « vente transactionnelle » aujourd'hui ?",
    options: [
      { text: "La vente forcée", correct: false },
      { text: "La vente conseil / vente de valeur, centrée sur la réussite du client", correct: true },
      { text: "La vente au rabais", correct: false },
      { text: "La vente anonyme", correct: false },
    ],
    explanation: "Les clients fuient le « hard selling ». La tendance est à la vente conseil : comprendre, accompagner, apporter de la valeur sur la durée. Le commercial devient un partenaire.",
    tip: "Positionne-toi en conseiller, pas en vendeur de catalogue.",
  },
  {
    ...base, id: 'com-ac-4', type: 'actu', difficulty: 3,
    situation: "Organisation moderne des équipes.",
    question: "Que désigne l'alignement « sales & marketing » (smarketing) ?",
    options: [
      { text: "Fusionner les deux services en un seul bureau", correct: false },
      { text: "Faire travailler ventes et marketing main dans la main sur les leads et le discours", correct: true },
      { text: "Supprimer le marketing", correct: false },
      { text: "Vendre des produits marketing", correct: false },
    ],
    explanation: "Quand marketing et ventes partagent objectifs, définitions de leads et messages, la conversion grimpe. Cet alignement est une attente forte des entreprises en 2026.",
    tip: "Montre que tu sais collaborer avec le marketing.",
  },
  {
    ...base, id: 'com-ac-5', type: 'actu', difficulty: 2,
    situation: "Réalité de la vente B2B actuelle.",
    question: "Pourquoi les cycles de vente B2B se complexifient-ils ?",
    options: [
      { text: "Les clients décident plus vite et seuls", correct: false },
      { text: "Les décisions impliquent plus d'interlocuteurs et durent plus longtemps", correct: true },
      { text: "Il n'y a plus de concurrence", correct: false },
      { text: "Les prix sont devenus fixes partout", correct: false },
    ],
    explanation: "En B2B, on vend désormais à un comité d'achat (plusieurs décideurs) sur des cycles plus longs. Savoir cartographier les interlocuteurs est devenu clé.",
    tip: "Identifie tous les décideurs, pas juste ton contact.",
  },
  {
    ...base, id: 'com-ac-6', type: 'actu', difficulty: 2,
    situation: "Deux grandes stratégies d'acquisition.",
    question: "Quelle est la différence entre « inbound » et « outbound » ?",
    options: [
      { text: "Inbound = le client vient à toi (contenu, SEO) ; outbound = tu vas le chercher (prospection)", correct: true },
      { text: "Inbound = par téléphone ; outbound = par email", correct: false },
      { text: "Ce sont des synonymes", correct: false },
      { text: "Inbound = en France ; outbound = à l'étranger", correct: false },
    ],
    explanation: "Inbound : attirer via du contenu utile. Outbound : aller chercher activement (cold call, cold email). Les approches modernes combinent les deux.",
    tip: "Les meilleurs allient prospection active et attraction par le contenu.",
  },
  {
    ...base, id: 'com-ac-7', type: 'actu', difficulty: 3,
    situation: "Cadre légal de la prospection.",
    question: "En 2026, quelle règle encadre le cold emailing B2B en France ?",
    options: [
      { text: "Aucune, on peut écrire à n'importe qui", correct: false },
      { text: "Le RGPD : message en lien avec la fonction pro, mention de l'origine des données et droit d'opposition", correct: true },
      { text: "Il est totalement interdit", correct: false },
      { text: "Il faut l'accord écrit signé avant tout email", correct: false },
    ],
    explanation: "Le cold emailing B2B reste possible mais encadré par le RGPD : sollicitation cohérente avec la fonction du destinataire, transparence sur les données et possibilité de se désinscrire.",
    tip: "Prospecter oui, mais en respectant le RGPD.",
  },
  {
    ...base, id: 'com-ac-8', type: 'actu', difficulty: 2,
    situation: "Image du commercial sur le marché.",
    question: "Pourquoi le « personal branding » compte pour un commercial ?",
    options: [
      { text: "Pour avoir beaucoup de likes", correct: false },
      { text: "Parce qu'une réputation pro crédible attire la confiance et des opportunités", correct: true },
      { text: "Ça n'a aucun intérêt", correct: false },
      { text: "Pour devenir influenceur", correct: false },
    ],
    explanation: "Un commercial à la présence professionnelle soignée (LinkedIn, expertise partagée) inspire confiance et génère des contacts entrants. L'image personnelle est un actif commercial.",
    tip: "Ta crédibilité en ligne ouvre des portes hors ligne.",
  },
];
