/**
 * Thème « Connaissance entreprise » — 20 scénarios.
 * Montrer qu'on s'est renseigné et qu'on vise CETTE entreprise précisément.
 * Chaque question : exactement une option correct:true, + explanation + tip.
 */
export default [
  {
    id: 'entr-1', category: 'entreprise', difficulty: 1,
    situation: "« Que savez-vous de notre entreprise ? »",
    question: "Avant l'entretien, vous auriez dû :",
    options: [
      { text: "Ne rien préparer, improviser sur le moment", correct: false },
      { text: "Lire le site, l'actu récente, les produits et la culture", correct: true },
      { text: "Apprendre par cœur le chiffre d'affaires uniquement", correct: false },
      { text: "Regarder seulement le logo", correct: false },
    ],
    explanation: "Se renseigner est non négociable. Connaître l'actualité récente, les produits et les valeurs montre un intérêt sincère et te démarque.",
    tip: "Note 2-3 faits récents à glisser pendant l'échange.",
  },
  {
    id: 'entr-2', category: 'entreprise', difficulty: 2,
    situation: "Le poste correspond à plusieurs entreprises où vous postulez.",
    question: "Comment éviter l'effet « candidature copiée-collée » ?",
    options: [
      { text: "Donner exactement les mêmes réponses partout", correct: false },
      { text: "Personnaliser : pourquoi CETTE entreprise précisément", correct: true },
      { text: "Dire qu'on postule partout pour maximiser ses chances", correct: false },
      { text: "Mentir en disant que c'est sa seule candidature", correct: false },
    ],
    explanation: "Le recruteur veut sentir un intérêt spécifique. Un argument propre à l'entreprise (mission, projet, valeurs) fait la différence.",
    tip: "Une phrase « ce qui m'attire chez VOUS, c'est… » personnalisée.",
  },
  {
    id: 'entr-3', category: 'entreprise', difficulty: 1,
    situation: "Vous préparez vos recherches sur l'entreprise.",
    question: "Quelles sources sont les plus utiles ?",
    options: [
      { text: "Site officiel, réseaux sociaux, presse récente, avis et page carrière", correct: true },
      { text: "Uniquement la page d'accueil du site", correct: false },
      { text: "Des rumeurs entendues entre amis", correct: false },
      { text: "Rien, on improvise", correct: false },
    ],
    explanation: "Croiser plusieurs sources (site, LinkedIn, articles, avis salariés) donne une vision réaliste : activité, actualité, ambiance. C'est ce qui nourrit des réponses précises.",
    tip: "Regarde la page LinkedIn de l'entreprise : les posts récents révèlent ses priorités.",
  },
  {
    id: 'entr-4', category: 'entreprise', difficulty: 2,
    situation: "« Selon vous, quel est notre cœur de métier ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "Décrire avec vos mots ce que fait l'entreprise et pour quels clients", correct: true },
      { text: "« Vous faites des trucs, non ? »", correct: false },
      { text: "Réciter mot à mot le slogan sans rien comprendre", correct: false },
      { text: "Avouer qu'on n'a pas regardé", correct: false },
    ],
    explanation: "Savoir reformuler l'activité avec tes propres mots prouve que tu as compris, pas seulement mémorisé. Mentionne les clients ou le marché visé pour aller plus loin.",
    tip: "Entraîne-toi à résumer l'activité de l'entreprise en une phrase claire.",
  },
  {
    id: 'entr-5', category: 'entreprise', difficulty: 2,
    situation: "« Qui sont nos principaux concurrents ? »",
    question: "Quelle attitude adopter ?",
    options: [
      { text: "Citer 1-2 concurrents et ce qui distingue l'entreprise d'eux", correct: true },
      { text: "« Aucune idée »", correct: false },
      { text: "Dire que l'entreprise n'a aucun concurrent", correct: false },
      { text: "Vanter les concurrents au détriment de l'entreprise", correct: false },
    ],
    explanation: "Connaître le marché montre un vrai intérêt. Cite quelques concurrents et surtout le facteur différenciant de l'entreprise : c'est ce qui prouve une compréhension fine.",
    tip: "Comprendre ce qui rend l'entreprise unique = argument en or pour la suite.",
  },
  {
    id: 'entr-6', category: 'entreprise', difficulty: 2,
    situation: "Vous avez lu une actualité récente de l'entreprise (nouveau produit, levée de fonds…).",
    question: "Comment l'utiliser ?",
    options: [
      { text: "La mentionner avec à-propos pour montrer votre veille et votre intérêt", correct: true },
      { text: "La garder pour soi, ça ne sert à rien", correct: false },
      { text: "La citer pour critiquer l'entreprise", correct: false },
      { text: "Prétendre l'avoir lue sans rien en dire", correct: false },
    ],
    explanation: "Glisser une actualité récente (« j'ai vu que vous veniez de lancer… ») prouve que ton intérêt est actuel et sérieux. C'est l'un des détails qui marquent le plus un recruteur.",
    tip: "Prépare UNE actu récente à placer naturellement dans l'échange.",
  },
  {
    id: 'entr-7', category: 'entreprise', difficulty: 1,
    situation: "« Pourquoi voulez-vous travailler ICI plutôt qu'ailleurs ? »",
    question: "La réponse la plus solide :",
    options: [
      { text: "Des raisons précises liées à l'entreprise (valeurs, projets, produits)", correct: true },
      { text: "« Parce que vous recrutez »", correct: false },
      { text: "« C'est près de chez moi »", correct: false },
      { text: "« J'ai postulé un peu partout »", correct: false },
    ],
    explanation: "La proximité ou le simple fait qu'ils recrutent ne sont pas des motivations. Le recruteur veut une raison qui ne vaut que pour SON entreprise.",
    tip: "Si ta réponse marche pour n'importe quelle boîte, c'est qu'elle est trop générique.",
  },
  {
    id: 'entr-8', category: 'entreprise', difficulty: 3,
    context: "PME familiale dans l'agroalimentaire. Le dirigeant, attaché aux valeurs maison, vous reçoit lui-même. « Qu'est-ce qui vous parle dans notre façon de travailler ? »",
    situation: "On vous interroge sur l'adéquation avec la culture de l'entreprise.",
    question: "La meilleure réponse :",
    options: [
      { text: "Relier une valeur concrète de l'entreprise à votre propre façon de travailler", correct: true },
      { text: "« Je sais pas trop, c'est une entreprise comme une autre »", correct: false },
      { text: "Parler uniquement du salaire", correct: false },
      { text: "Réciter les valeurs du site sans les relier à vous", correct: false },
    ],
    explanation: "Dans une PME à forte culture, l'adéquation aux valeurs est décisive. Montre que tu as compris leur état d'esprit et relie-le à un exemple de ta manière de travailler.",
    tip: "Valeur affichée + ton exemple personnel = match crédible.",
  },
  {
    id: 'entr-9', category: 'entreprise', difficulty: 1,
    situation: "Vous n'avez pas eu le temps de tout lire sur l'entreprise.",
    question: "La priorité absolue à connaître :",
    options: [
      { text: "Son activité, ses produits/services et son actualité récente", correct: true },
      { text: "Le prénom de tous les salariés", correct: false },
      { text: "L'historique complet depuis 1950", correct: false },
      { text: "La couleur exacte du logo", correct: false },
    ],
    explanation: "Si le temps manque, concentre-toi sur l'essentiel : ce que fait l'entreprise, pour qui, et une actu récente. C'est le socle minimum attendu en entretien.",
    tip: "Activité + clients + une actu : le trio de secours en 10 minutes.",
  },
  {
    id: 'entr-10', category: 'entreprise', difficulty: 2,
    situation: "« Quelles sont nos valeurs, d'après vous ? »",
    question: "La meilleure manière de répondre :",
    options: [
      { text: "Citer 1-2 valeurs vues dans vos recherches et illustrer pourquoi elles vous parlent", correct: true },
      { text: "Inventer des valeurs au hasard", correct: false },
      { text: "« Les valeurs, je m'en occupe pas »", correct: false },
      { text: "Lister 10 valeurs sans en comprendre aucune", correct: false },
    ],
    explanation: "Repère les valeurs affichées par l'entreprise et choisis-en une ou deux qui résonnent vraiment avec toi, avec un mot d'explication. La sincérité prime sur la quantité.",
    tip: "Mieux vaut une valeur sincère que cinq récitées.",
  },
  {
    id: 'entr-11', category: 'entreprise', difficulty: 2,
    situation: "Vous postulez dans une grande chaîne de magasins.",
    question: "Quel signe d'intérêt impressionne le plus ?",
    options: [
      { text: "Être allé en magasin / avoir testé le service avant l'entretien", correct: true },
      { text: "Ne jamais y avoir mis les pieds", correct: false },
      { text: "Dire « les magasins se valent tous »", correct: false },
      { text: "Critiquer l'organisation sans l'avoir vue", correct: false },
    ],
    explanation: "Pour un poste en contact client, avoir vécu l'expérience client est un atout énorme : tu peux parler concrètement de ce qui marche et proposer des idées.",
    tip: "Avant un entretien en boutique : va visiter, observe, note 2 remarques utiles.",
  },
  {
    id: 'entr-12', category: 'entreprise', difficulty: 1,
    situation: "« Comment avez-vous connu notre entreprise ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "Une réponse honnête et, si possible, reliée à un intérêt réel", correct: true },
      { text: "Mentir pour faire bonne impression", correct: false },
      { text: "« Par hasard, j'ai cliqué sans réfléchir »", correct: false },
      { text: "« Je sais plus du tout »", correct: false },
    ],
    explanation: "Question simple mais révélatrice : une réponse honnête, idéalement reliée à un intérêt (un produit que tu utilises, une réputation, une recommandation), renforce ta crédibilité.",
    tip: "Même « via l'annonce » se valorise : « et en me renseignant, j'ai accroché sur… ».",
  },
  {
    id: 'entr-13', category: 'entreprise', difficulty: 2,
    situation: "« Que pensez-vous de notre dernier produit / service ? »",
    question: "L'attitude la plus pertinente :",
    options: [
      { text: "Donner un avis sincère et constructif, points forts en tête", correct: true },
      { text: "Un compliment vide et exagéré", correct: false },
      { text: "Une critique frontale sans nuance", correct: false },
      { text: "« Je le connais pas »", correct: false },
    ],
    explanation: "Un avis sincère et nuancé (ce que tu apprécies, et éventuellement une piste d'amélioration formulée avec tact) montre du recul et un vrai intérêt, plus qu'une flatterie creuse.",
    tip: "Commence par le positif avant toute suggestion d'amélioration.",
  },
  {
    id: 'entr-14', category: 'entreprise', difficulty: 2,
    situation: "« Où voyez-vous notre entreprise dans quelques années ? »",
    question: "La meilleure réponse s'appuie sur :",
    options: [
      { text: "Les tendances du secteur et la direction prise par l'entreprise", correct: true },
      { text: "Une prédiction inventée au hasard", correct: false },
      { text: "« Aucune idée, c'est pas mon problème »", correct: false },
      { text: "Un pronostic pessimiste", correct: false },
    ],
    explanation: "On évalue ta compréhension du secteur et ta capacité à te projeter avec l'entreprise. Appuie-toi sur ce que tu sais de ses projets et des évolutions du marché.",
    tip: "Relie l'avenir de l'entreprise à la façon dont tu pourrais y contribuer.",
  },
  {
    id: 'entr-15', category: 'entreprise', difficulty: 1,
    situation: "Vous découvrez le nom du recruteur avant l'entretien.",
    question: "La bonne pratique :",
    options: [
      { text: "Regarder son rôle / parcours pour adapter votre discours, sans en faire trop", correct: true },
      { text: "Apprendre toute sa vie privée par cœur", correct: false },
      { text: "L'ignorer complètement", correct: false },
      { text: "Le contacter la veille à minuit", correct: false },
    ],
    explanation: "Connaître la fonction de ton interlocuteur (RH ? futur manager ? dirigeant ?) t'aide à adapter ton niveau de détail. On reste professionnel : pas d'intrusion dans sa vie privée.",
    tip: "Savoir si tu parles à un RH ou à un technicien change la façon de répondre.",
  },
  {
    id: 'entr-16', category: 'entreprise', difficulty: 2,
    situation: "« En quoi pouvez-vous contribuer à nos objectifs ? »",
    question: "La meilleure réponse suppose de :",
    options: [
      { text: "Avoir compris les enjeux de l'entreprise et relier vos compétences à ceux-ci", correct: true },
      { text: "Parler uniquement de ce que l'entreprise peut vous apporter", correct: false },
      { text: "Promettre des résultats irréalistes", correct: false },
      { text: "Rester vague : « je ferai de mon mieux »", correct: false },
    ],
    explanation: "Cette question récompense ceux qui ont compris les besoins de l'entreprise. Relie une compétence concrète à un enjeu réel (« vous développez le e-commerce, or j'ai… »).",
    tip: "Passe du « ce que je veux » au « ce que je peux apporter ».",
  },
  {
    id: 'entr-17', category: 'entreprise', difficulty: 1,
    situation: "Vous confondez l'entreprise avec une autre pendant l'entretien.",
    question: "Quel est le risque principal ?",
    options: [
      { text: "Montrer que vous n'avez pas vraiment ciblé cette entreprise", correct: true },
      { text: "Aucun, ça arrive à tout le monde", correct: false },
      { text: "Être trop bien préparé", correct: false },
      { text: "Paraître trop motivé", correct: false },
    ],
    explanation: "Confondre les entreprises (ou citer le nom d'une concurrente) est une erreur rédhibitoire : elle prouve une candidature de masse sans ciblage. Vérifie toujours où tu postules.",
    tip: "Avant d'entrer, relis le nom exact de l'entreprise et le poste visé.",
  },
  {
    id: 'entr-18', category: 'entreprise', difficulty: 2,
    situation: "L'entreprise a une mission affichée (ex. écologie, inclusion).",
    question: "Comment en parler ?",
    options: [
      { text: "Montrer une adhésion sincère, idéalement reliée à votre vécu", correct: true },
      { text: "Faire semblant d'y adhérer sans rien connaître", correct: false },
      { text: "Dire que ces missions sont du marketing", correct: false },
      { text: "Ignorer le sujet", correct: false },
    ],
    explanation: "Si une mission compte pour l'entreprise, elle comptera en entretien. Une adhésion sincère, appuyée par un exemple personnel, crée une vraie connexion. La fausse adhésion se repère vite.",
    tip: "N'invente pas un engagement : relie plutôt la mission à une valeur que tu portes déjà.",
  },
  {
    id: 'entr-19', category: 'entreprise', difficulty: 2,
    situation: "« Avez-vous des questions sur l'entreprise ? »",
    question: "La meilleure question à poser :",
    options: [
      { text: "Une question informée qui montre vos recherches (ex. sur un projet ou un enjeu)", correct: true },
      { text: "« Vous faites quoi exactement ? »", correct: false },
      { text: "Aucune question", correct: false },
      { text: "Uniquement une question sur les congés", correct: false },
    ],
    explanation: "Tes questions trahissent ton niveau de préparation. Une question fine sur un projet, le marché ou l'équipe prouve que tu as creusé. Demander l'activité de base montre l'inverse.",
    tip: "Prépare 2 questions qui prouvent que tu t'es renseigné.",
  },
  {
    id: 'entr-20', category: 'entreprise', difficulty: 3,
    context: "Start-up en forte croissance. La fondatrice cherche des gens qui comprennent son projet. « Pourquoi nous, alors qu'on est encore petits et incertains ? »",
    situation: "On vous teste sur votre compréhension du risque et de l'opportunité.",
    question: "La meilleure réponse :",
    options: [
      { text: "Montrer que vous comprenez le risque ET ce qui vous attire (impact, apprentissage, croissance)", correct: true },
      { text: "« Justement, si ça marche pas je partirai vite »", correct: false },
      { text: "Nier tout risque pour flatter", correct: false },
      { text: "« Je préfère la sécurité d'un grand groupe en fait »", correct: false },
    ],
    explanation: "Dans une start-up, on attend une lucidité sur le risque et une motivation pour l'aventure (responsabilités, apprentissage rapide, impact direct). Montrer qu'on a compris le contexte rassure énormément.",
    tip: "Assume le risque et transforme-le en raison d'y aller : « c'est là qu'on apprend le plus ».",
  },
];
