/**
 * Thème « Forces & faiblesses » — 20 scénarios.
 * Parler de ses qualités et de ses défauts avec lucidité, sans cliché ni excès.
 * Chaque question : exactement une option correct:true, + explanation + tip.
 */
export default [
  {
    id: 'faib-1', category: 'faiblesses', difficulty: 2,
    situation: "« Quel est votre principal défaut ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Je suis perfectionniste » (cliché déguisé en qualité)", correct: false },
      { text: "« Je n'ai aucun défaut »", correct: false },
      { text: "Un vrai défaut maîtrisé + ce qu'on fait pour progresser", correct: true },
      { text: "Un défaut rédhibitoire pour le poste", correct: false },
    ],
    explanation: "On veut de l'honnêteté et de la lucidité : un défaut réel mais non bloquant, accompagné d'une démarche d'amélioration. Les faux défauts sonnent faux.",
    tip: "Choisis un défaut sans rapport direct avec le cœur du poste.",
  },
  {
    id: 'faib-2', category: 'faiblesses', difficulty: 1,
    situation: "« Quelles sont vos forces ? »",
    question: "Comment les présenter ?",
    options: [
      { text: "Lister 10 qualités génériques en rafale", correct: false },
      { text: "2-3 forces clés illustrées par un exemple concret", correct: true },
      { text: "« Je suis le meilleur dans tout »", correct: false },
      { text: "Rester très modeste et n'en citer aucune", correct: false },
    ],
    explanation: "Mieux vaut 2-3 forces prouvées par un exemple qu'une liste creuse. La preuve par l'exemple est ce qui convainc.",
    tip: "Pour chaque force, prépare une mini-anecdote.",
  },
  {
    id: 'mes-3', category: 'faiblesses', difficulty: 3,
    context: "Poste de développeur junior. L'entretien est mené par le lead technique, plutôt direct. Après vos réponses techniques, il vous fixe : « Qu'est-ce qui vous met le plus en difficulté dans le code ? »",
    situation: "On vous demande une vraie faiblesse technique.",
    question: "La meilleure manière de répondre :",
    options: [
      { text: "« Rien, je gère tout »", correct: false },
      { text: "Citer un domaine précis encore en apprentissage + comment vous progressez", correct: true },
      { text: "« Je déteste les tests, je n'en fais jamais »", correct: false },
      { text: "Détourner la question vers vos points forts", correct: false },
    ],
    explanation: "Un technique senior valorise la lucidité et la capacité d'apprentissage plus que la perfection. Nommer une zone de progrès + sa démarche inspire confiance.",
    tip: "« En ce moment je monte en compétence sur… via… » montre une dynamique.",
  },
  {
    id: 'faib-4', category: 'faiblesses', difficulty: 2,
    situation: "« Citez-moi trois qualités. »",
    question: "Quelle sélection est la plus efficace ?",
    options: [
      { text: "Des qualités en lien avec le poste, que vous pouvez prouver", correct: true },
      { text: "« Gentil, sympa, cool »", correct: false },
      { text: "Des qualités au hasard sans rapport avec le job", correct: false },
      { text: "Les qualités que tout le monde cite, sans exemple", correct: false },
    ],
    explanation: "Choisis des qualités utiles au poste (rigueur pour un comptable, écoute pour un commercial) et adossées à un fait. « Gentil/sympa » ne sont pas des compétences professionnelles.",
    tip: "Relis l'annonce : les qualités attendues y sont souvent listées.",
  },
  {
    id: 'faib-5', category: 'faiblesses', difficulty: 2,
    situation: "Vous voulez dire « perfectionniste » comme défaut.",
    question: "Pourquoi est-ce risqué ?",
    options: [
      { text: "C'est un cliché qui sonne comme une fausse modestie", correct: true },
      { text: "C'est interdit par la loi", correct: false },
      { text: "C'est une qualité trop rare", correct: false },
      { text: "Ça n'a aucun sens", correct: false },
    ],
    explanation: "« Perfectionniste », « trop travailleur », « je m'investis trop » sont vus comme des défauts-qualités déguisés. Les recruteurs les repèrent immédiatement et y voient un manque de sincérité.",
    tip: "Si tu cites un vrai défaut, montre surtout comment tu le gères.",
  },
  {
    id: 'faib-6', category: 'faiblesses', difficulty: 1,
    situation: "« Vous êtes plutôt timide. C'est un problème pour ce poste de vente ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Oui, je suis nul avec les gens » (auto-sabotage)", correct: false },
      { text: "Reconnaître la timidité mais montrer comment vous la dépassez au contact des clients", correct: true },
      { text: "Nier en bloc alors que ça se voit", correct: false },
      { text: "« De toute façon la timidité ça se soigne pas »", correct: false },
    ],
    explanation: "On peut reconnaître un trait sans en faire un mur. Montre que tu connais ta timidité et que tu as des stratégies (préparation, mise en situation) pour l'apprivoiser au travail.",
    tip: "Transforme la faiblesse en preuve de connaissance de soi et d'effort.",
  },
  {
    id: 'faib-7', category: 'faiblesses', difficulty: 2,
    situation: "« En quoi êtes-vous différent des autres candidats ? »",
    question: "L'angle le plus pertinent :",
    options: [
      { text: "Une combinaison concrète de compétences/expériences propre à vous", correct: true },
      { text: "« Je sais pas, faut voir »", correct: false },
      { text: "« Je suis mieux que les autres »", correct: false },
      { text: "Critiquer les autres candidats", correct: false },
    ],
    explanation: "Cette question cherche ta valeur unique : un mélange d'expériences, de qualités et de motivation que toi seul possèdes. On se différencie par du concret, jamais en rabaissant les autres.",
    tip: "Prépare ta « signature » : ce qui te rend mémorable en une phrase.",
  },
  {
    id: 'faib-8', category: 'faiblesses', difficulty: 2,
    situation: "« Sur quoi devez-vous le plus progresser ? »",
    question: "La bonne approche :",
    options: [
      { text: "Nommer un axe de progrès réel + un plan d'action concret", correct: true },
      { text: "« Sur rien de particulier »", correct: false },
      { text: "Lister tous ses défauts d'un coup", correct: false },
      { text: "« Je préfère pas répondre »", correct: false },
    ],
    explanation: "Cette question, comme celle du défaut, teste ta capacité à t'auto-évaluer. Un axe précis + une action (formation, pratique, mentorat) montre une démarche de progression.",
    tip: "Un seul axe, bien expliqué, vaut mieux qu'une liste.",
  },
  {
    id: 'faib-9', category: 'faiblesses', difficulty: 1,
    situation: "Vous citez une force.",
    question: "Qu'est-ce qui la rend crédible ?",
    options: [
      { text: "Un exemple concret qui la démontre", correct: true },
      { text: "Le fait de la répéter plusieurs fois", correct: false },
      { text: "De parler fort en la disant", correct: false },
      { text: "De dire que vos amis le pensent aussi", correct: false },
    ],
    explanation: "Une force affirmée sans preuve reste une opinion. « Je suis organisé » devient crédible avec « par exemple, je tenais le planning de toute l'équipe lors de mon stage ».",
    tip: "Règle d'or : une affirmation = un exemple.",
  },
  {
    id: 'faib-10', category: 'faiblesses', difficulty: 3,
    context: "Poste en relation client. La recruteuse, posée, veut tester ton honnêteté. « Donnez-moi un défaut qui pourrait gêner sur ce poste. »",
    situation: "On vous pousse à citer un défaut potentiellement bloquant.",
    question: "La réponse la plus habile :",
    options: [
      { text: "Citer un défaut mineur pour le poste + montrer qu'il est sous contrôle", correct: true },
      { text: "« Je n'aime pas parler aux gens » (rédhibitoire pour de la relation client)", correct: false },
      { text: "« Je suis souvent en retard »", correct: false },
      { text: "Mentir en disant un faux défaut flatteur", correct: false },
    ],
    explanation: "Même quand on te pousse, ne cite jamais un défaut qui touche le cœur du poste. Choisis-en un secondaire, et prouve qu'il est maîtrisé. C'est un test de jugement.",
    tip: "Garde toujours le défaut loin de la compétence n°1 attendue.",
  },
  {
    id: 'faib-11', category: 'faiblesses', difficulty: 2,
    situation: "« Comment vos collègues vous décriraient-ils ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "Quelques traits réalistes, idéalement appuyés par un retour réel reçu", correct: true },
      { text: "« Aucune idée »", correct: false },
      { text: "Une liste de superlatifs invérifiables", correct: false },
      { text: "« Ils m'aiment pas trop en fait »", correct: false },
    ],
    explanation: "Cette question évalue ta conscience de l'image que tu renvoies. Cite des traits crédibles, surtout si tu peux les rattacher à un feedback réel (« on me dit souvent fiable »).",
    tip: "Un compliment qu'on t'a déjà fait est une réponse en or ici.",
  },
  {
    id: 'faib-12', category: 'faiblesses', difficulty: 1,
    situation: "Vous ne savez pas quelle force mettre en avant.",
    question: "Comment choisir avant l'entretien ?",
    options: [
      { text: "Croiser vos qualités avec les besoins de l'annonce", correct: true },
      { text: "Prendre la première qui vous vient", correct: false },
      { text: "Choisir la plus impressionnante même si elle est hors sujet", correct: false },
      { text: "Demander au recruteur ce qu'il préfère", correct: false },
    ],
    explanation: "La meilleure force est celle qui répond à un besoin du poste. Liste les compétences attendues dans l'annonce et sélectionne celles que tu possèdes vraiment.",
    tip: "L'annonce est ta meilleure antisèche pour préparer cette question.",
  },
  {
    id: 'faib-13', category: 'faiblesses', difficulty: 2,
    situation: "« Êtes-vous quelqu'un de stressé ? »",
    question: "La réponse la plus équilibrée :",
    options: [
      { text: "Reconnaître une dose de stress utile et expliquer comment vous le canalisez", correct: true },
      { text: "« Jamais, rien ne me touche »", correct: false },
      { text: "« Oui, je panique tout le temps »", correct: false },
      { text: "Éviter la question", correct: false },
    ],
    explanation: "Un peu de stress est normal et même moteur. L'idéal est de montrer que tu le reconnais et que tu as des méthodes pour le gérer (préparation, respiration, organisation).",
    tip: "« Le stress me rend vigilant, mais je le canalise en… » est une bonne formule.",
  },
  {
    id: 'faib-14', category: 'faiblesses', difficulty: 2,
    situation: "Vous voulez prouver votre rigueur.",
    question: "Quelle preuve est la plus parlante ?",
    options: [
      { text: "Un exemple où votre rigueur a évité une erreur ou amélioré un résultat", correct: true },
      { text: "Dire « je suis très rigoureux » trois fois", correct: false },
      { text: "Montrer un CV sans faute… après l'avoir dit", correct: false },
      { text: "« Tout le monde le dit »", correct: false },
    ],
    explanation: "La rigueur se prouve par un fait : une vérification qui a sauvé un dossier, un suivi sans oubli, une procédure respectée. L'exemple vaut mille adjectifs.",
    tip: "Pense « situation où ça a servi », pas « adjectif que je revendique ».",
  },
  {
    id: 'faib-15', category: 'faiblesses', difficulty: 1,
    situation: "« Vous manquez d'expérience pour ce poste. »",
    question: "La meilleure réaction :",
    options: [
      { text: "Reconnaître le point et valoriser votre motivation, votre capacité d'apprentissage et vos atouts", correct: true },
      { text: "« Ouais c'est vrai, j'ai rien à proposer »", correct: false },
      { text: "Se vexer et contredire agressivement", correct: false },
      { text: "Mentir sur son expérience", correct: false },
    ],
    explanation: "Le manque d'expérience se compense par la motivation, la formation et l'envie d'apprendre. Reconnais sans t'effondrer, puis recentre sur ce que tu apportes vraiment.",
    tip: "« C'est juste, et c'est pour ça que je suis prêt à m'investir à fond pour apprendre vite. »",
  },
  {
    id: 'faib-16', category: 'faiblesses', difficulty: 2,
    situation: "« Qu'est-ce qui vous agace le plus au travail ? »",
    question: "La réponse à éviter ABSOLUMENT :",
    options: [
      { text: "Cracher sur les collègues, les chefs ou les clients", correct: true },
      { text: "Citer un irritant en restant constructif", correct: false },
      { text: "Évoquer le manque d'organisation et comment vous y remédiez", correct: false },
      { text: "Donner un exemple mesuré", correct: false },
    ],
    explanation: "Cette question est un piège : dénigrer ouvertement révèle un mauvais esprit. Si tu cites un irritant, reste factuel et oriente vers la solution que tu apportes.",
    tip: "Transforme l'agacement en proposition : « ce qui me gêne, c'est X, donc je propose Y ».",
  },
  {
    id: 'faib-17', category: 'faiblesses', difficulty: 2,
    situation: "Vous hésitez entre paraître modeste ou ambitieux.",
    question: "Quel équilibre viser ?",
    options: [
      { text: "Une confiance posée : assumer ses forces sans arrogance", correct: true },
      { text: "Tout minimiser pour ne pas déranger", correct: false },
      { text: "Se survendre au maximum", correct: false },
      { text: "Laisser le recruteur deviner vos qualités", correct: false },
    ],
    explanation: "Trop de modestie te dessert, trop d'arrogance braque. Le bon ton : assumer calmement tes atouts, preuves à l'appui, sans te comparer ni te rabaisser.",
    tip: "Parle de tes réussites au passé et en faits : ça reste factuel, pas vantard.",
  },
  {
    id: 'faib-18', category: 'faiblesses', difficulty: 1,
    situation: "Le recruteur insiste : « Un autre défaut ? »",
    question: "Comment réagir ?",
    options: [
      { text: "Donner un second défaut maîtrisé, sans se dévaloriser", correct: true },
      { text: "« Là j'en ai plus »", correct: false },
      { text: "Paniquer et inventer un gros défaut", correct: false },
      { text: "Refuser de répondre", correct: false },
    ],
    explanation: "Mieux vaut avoir deux défauts préparés. Le second test vérifie que tu restes posé sous insistance. Reste dans la même logique : réel, secondaire, en cours d'amélioration.",
    tip: "Prépare toujours DEUX défauts : on te demande souvent le second.",
  },
  {
    id: 'faib-19', category: 'faiblesses', difficulty: 2,
    situation: "« Votre dernière évaluation, qu'est-ce qu'on vous a reproché ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "Citer un point d'amélioration reçu et ce que vous en avez fait", correct: true },
      { text: "« On m'a jamais évalué » alors que c'est faux", correct: false },
      { text: "« Que des compliments »", correct: false },
      { text: "Attaquer la personne qui vous a évalué", correct: false },
    ],
    explanation: "Référencer un vrai feedback et son suivi montre que tu utilises les retours pour progresser. Prétendre n'avoir eu que des éloges manque de crédibilité.",
    tip: "Relie toujours le reproche à une amélioration concrète.",
  },
  {
    id: 'faib-20', category: 'faiblesses', difficulty: 3,
    context: "Poste en équipe projet. Le manager veut des profils qui se connaissent bien. « Quelle est la faiblesse que vous combattez depuis le plus longtemps ? »",
    situation: "Question profonde sur un défaut récurrent.",
    question: "La réponse la plus convaincante :",
    options: [
      { text: "Un défaut ancien, les progrès déjà faits et ce qu'il reste à travailler", correct: true },
      { text: "« Aucun, j'ai tout réglé »", correct: false },
      { text: "Un défaut dramatisé pour faire de l'effet", correct: false },
      { text: "Changer de sujet vers ses qualités", correct: false },
    ],
    explanation: "Montrer un parcours de progression sur un défaut (et reconnaître qu'il reste du chemin) prouve de la maturité et de l'honnêteté. Prétendre tout avoir réglé sonne faux.",
    tip: "Le chemin parcouru compte autant que le défaut lui-même.",
  },
];
