/**
 * Secteur « Finance / Comptabilité » — parcours (4 couches).
 *
 * sector:'finance', type ∈ {comportemental, technique, situation, actu}.
 * Une seule option correct:true, + explanation + tip. `context` optionnel.
 */
const base = { sector: 'finance' };

export default [
  // ══════════════ 🧠 COMPORTEMENTAL ══════════════
  {
    ...base, id: 'fin-cp-1', type: 'comportemental', difficulty: 1,
    situation: "« Pourquoi la comptabilité / finance vous attire-t-elle ? »",
    question: "La motivation la plus crédible :",
    options: [
      { text: "« Parce que j'aime l'argent »", correct: false },
      { text: "Le goût des chiffres, de la rigueur et du rôle clé dans le pilotage de l'entreprise", correct: true },
      { text: "« Parce que c'est répétitif et sans surprise »", correct: false },
      { text: "« Pour ne parler à personne »", correct: false },
    ],
    explanation: "La compta/finance traduit la santé de l'entreprise en chiffres et aide à décider. On valorise la rigueur, la logique et l'intérêt pour le pilotage, pas le cliché du métier « ennuyeux ».",
    tip: "Mets en avant rigueur et rôle dans la prise de décision.",
  },
  {
    ...base, id: 'fin-cp-2', type: 'comportemental', difficulty: 2,
    situation: "« La fiabilité des chiffres, à quel point est-ce important ? »",
    question: "La meilleure posture :",
    options: [
      { text: "« Une petite erreur, ce n'est pas grave »", correct: false },
      { text: "Cruciale : une erreur fausse les comptes, les déclarations et les décisions", correct: true },
      { text: "« Mieux vaut aller vite que juste »", correct: false },
      { text: "« On corrigera plus tard, peut-être »", correct: false },
    ],
    explanation: "En compta, l'exactitude est primordiale : une erreur se propage (déclarations fiscales, bilan, décisions). Rigueur et contrôle systématique sont la base du métier.",
    tip: "Vérifier deux fois vaut mieux que corriger dix fois.",
  },
  {
    ...base, id: 'fin-cp-3', type: 'comportemental', difficulty: 2,
    situation: "Vous manipulez des données financières sensibles (salaires, marges, comptes).",
    question: "Quelle qualité est indispensable ?",
    options: [
      { text: "Commenter les chiffres avec n'importe qui", correct: false },
      { text: "Une confidentialité et une intégrité totales", correct: true },
      { text: "Partager les marges aux concurrents", correct: false },
      { text: "Laisser traîner les documents", correct: false },
    ],
    explanation: "Les données financières sont stratégiques et confidentielles. Discrétion et intégrité sont non négociables : c'est une question de déontologie et de confiance.",
    tip: "Confidentialité des chiffres = pilier du métier.",
  },
  {
    ...base, id: 'fin-cp-4', type: 'comportemental', difficulty: 2,
    situation: "« Comment gérez-vous la pression des échéances (clôtures, déclarations) ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Je rends en retard, l'administration attendra »", correct: false },
      { text: "Je m'organise en amont avec un rétroplanning pour tenir les délais légaux", correct: true },
      { text: "« Je travaille uniquement dans l'urgence »", correct: false },
      { text: "« J'ignore les dates limites »", correct: false },
    ],
    explanation: "Les échéances fiscales et sociales sont impératives (pénalités à la clé). L'anticipation et l'organisation sont essentielles pour tenir les délais sans stress destructeur.",
    tip: "Anticiper les échéances évite pénalités et panique.",
  },
  {
    ...base, id: 'fin-cp-5', type: 'comportemental', difficulty: 3,
    situation: "« Que faites-vous si on vous demande de présenter des comptes flatteurs mais inexacts ? »",
    question: "La bonne posture :",
    options: [
      { text: "Obéir sans discuter", correct: false },
      { text: "Refuser : l'éthique et la sincérité des comptes priment, et la loi l'exige", correct: true },
      { text: "Maquiller un peu, « juste cette fois »", correct: false },
      { text: "Démissionner sur-le-champ sans rien dire", correct: false },
    ],
    explanation: "La sincérité des comptes est une obligation légale et déontologique. Falsifier expose à de lourdes sanctions. L'intégrité du comptable protège l'entreprise et lui-même.",
    tip: "Sincérité des comptes : une ligne rouge à ne jamais franchir.",
  },
  {
    ...base, id: 'fin-cp-6', type: 'comportemental', difficulty: 2,
    situation: "« Votre métier se résume-t-il à de la saisie ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Oui, juste saisir des chiffres toute la journée »", correct: false },
      { text: "Non : au-delà de la saisie, j'analyse, je contrôle et j'apporte de l'aide à la décision", correct: true },
      { text: "« Je ne comprends pas ce que je saisis »", correct: false },
      { text: "« La saisie, c'est dépassé, je ne fais rien »", correct: false },
    ],
    explanation: "Avec l'automatisation, le métier se recentre sur l'analyse, le contrôle et le conseil. Montrer cet esprit d'analyse (au-delà de la saisie) est très valorisé.",
    tip: "Positionne-toi sur l'analyse, pas seulement la saisie.",
  },

  // ══════════════ 🛠️ TECHNIQUE MÉTIER ══════════════
  {
    ...base, id: 'fin-te-1', type: 'technique', difficulty: 2,
    situation: "Documents comptables.",
    question: "Qu'est-ce que le bilan comptable ?",
    options: [
      { text: "La liste des ventes du mois", correct: false },
      { text: "Une photo du patrimoine à un instant T : actif (ce qu'on possède) et passif (ce qu'on doit)", correct: true },
      { text: "Le salaire des dirigeants", correct: false },
      { text: "Un planning de réunions", correct: false },
    ],
    explanation: "Le bilan présente, à une date donnée, l'actif (emplois) et le passif (ressources). C'est une photographie du patrimoine, à distinguer du compte de résultat.",
    tip: "Bilan = photo à un instant T (actif = passif).",
  },
  {
    ...base, id: 'fin-te-2', type: 'technique', difficulty: 2,
    situation: "Documents comptables.",
    question: "Que montre le compte de résultat ?",
    options: [
      { text: "Le patrimoine de l'entreprise", correct: false },
      { text: "Les produits et les charges d'une période, et donc le bénéfice ou la perte", correct: true },
      { text: "La trésorerie disponible aujourd'hui", correct: false },
      { text: "La liste des salariés", correct: false },
    ],
    explanation: "Le compte de résultat retrace l'activité sur une période : produits − charges = résultat (bénéfice ou perte). C'est un « film » de l'activité, là où le bilan est une « photo ».",
    tip: "Compte de résultat = film de l'activité (produits − charges).",
  },
  {
    ...base, id: 'fin-te-3', type: 'technique', difficulty: 2,
    situation: "Principe fondamental.",
    question: "Que signifie la « comptabilité en partie double » ?",
    options: [
      { text: "Tout saisir deux fois pour vérifier", correct: false },
      { text: "Chaque opération est enregistrée au débit d'un compte et au crédit d'un autre", correct: true },
      { text: "Avoir deux comptables", correct: false },
      { text: "Doubler les montants", correct: false },
    ],
    explanation: "En partie double, toute écriture équilibre un débit et un crédit de même montant. C'est le socle de la comptabilité : le total des débits égale toujours le total des crédits.",
    tip: "Débit = crédit : l'équilibre, toujours.",
  },
  {
    ...base, id: 'fin-te-4', type: 'technique', difficulty: 2,
    situation: "Fiscalité courante.",
    question: "Comment fonctionne la TVA pour une entreprise ?",
    options: [
      { text: "L'entreprise garde toute la TVA encaissée", correct: false },
      { text: "Elle reverse la TVA collectée (ventes) moins la TVA déductible (achats)", correct: true },
      { text: "La TVA est un bénéfice", correct: false },
      { text: "La TVA ne concerne pas les entreprises", correct: false },
    ],
    explanation: "L'entreprise collecte la TVA sur ses ventes et déduit celle de ses achats ; elle reverse la différence à l'État. Elle joue un rôle de collecteur, la TVA n'est pas un produit.",
    tip: "TVA à payer = TVA collectée − TVA déductible.",
  },
  {
    ...base, id: 'fin-te-5', type: 'technique', difficulty: 3,
    situation: "Contrôle de cohérence.",
    question: "À quoi sert le « rapprochement bancaire » ?",
    options: [
      { text: "À ouvrir un nouveau compte", correct: false },
      { text: "À vérifier la concordance entre le compte banque en comptabilité et le relevé de la banque", correct: true },
      { text: "À calculer la paie", correct: false },
      { text: "À négocier un prêt", correct: false },
    ],
    explanation: "Le rapprochement bancaire confronte les écritures comptables au relevé bancaire pour détecter écarts, oublis ou erreurs. C'est un contrôle régulier essentiel.",
    tip: "Rapprochement = comptabilité vs relevé, on traque les écarts.",
  },
  {
    ...base, id: 'fin-te-6', type: 'technique', difficulty: 3,
    situation: "Étalement d'une dépense.",
    question: "Qu'est-ce qu'un « amortissement » ?",
    options: [
      { text: "Un remboursement de prêt uniquement", correct: false },
      { text: "La répartition du coût d'un bien sur sa durée d'utilisation (usure)", correct: true },
      { text: "Une remise commerciale", correct: false },
      { text: "Une prime aux salariés", correct: false },
    ],
    explanation: "L'amortissement constate la perte de valeur d'une immobilisation (machine, véhicule) en étalant son coût sur plusieurs années, plutôt qu'en une seule charge.",
    tip: "Amortir = étaler le coût d'un bien sur sa durée de vie.",
  },
  {
    ...base, id: 'fin-te-7', type: 'technique', difficulty: 2,
    situation: "Distinction clé.",
    question: "Quelle est la différence entre une charge et une immobilisation ?",
    options: [
      { text: "Aucune, c'est pareil", correct: false },
      { text: "La charge est consommée sur l'exercice ; l'immobilisation sert durablement (et s'amortit)", correct: true },
      { text: "La charge est un revenu", correct: false },
      { text: "L'immobilisation est une vente", correct: false },
    ],
    explanation: "Une charge (fournitures, loyer) est consommée sur la période ; une immobilisation (matériel durable) reste à l'actif et s'amortit. Bien les distinguer est essentiel.",
    tip: "Durable et coûteux → immobilisation, pas charge.",
  },
  {
    ...base, id: 'fin-te-8', type: 'technique', difficulty: 2,
    situation: "Pilotage de la trésorerie.",
    question: "Que désigne la « trésorerie » d'une entreprise ?",
    options: [
      { text: "Son bénéfice annuel", correct: false },
      { text: "L'argent réellement disponible (banque + caisse) à un moment donné", correct: true },
      { text: "La valeur de ses stocks", correct: false },
      { text: "Le total de ses ventes", correct: false },
    ],
    explanation: "La trésorerie, c'est le cash disponible. Une entreprise peut être rentable mais manquer de trésorerie (décalage encaissements/décaissements) : la suivre est vital.",
    tip: "Rentable ≠ avoir du cash : surveille la trésorerie.",
  },
  {
    ...base, id: 'fin-te-9', type: 'technique', difficulty: 1,
    situation: "Document commercial et légal.",
    question: "Quelle mention est obligatoire sur une facture ?",
    options: [
      { text: "La couleur préférée du client", correct: false },
      { text: "Le numéro de facture, les coordonnées, la date, le détail et les montants HT/TVA/TTC", correct: true },
      { text: "Rien n'est obligatoire", correct: false },
      { text: "Une photo du produit", correct: false },
    ],
    explanation: "Une facture doit comporter des mentions légales : identité des parties, numéro unique, date, désignation, montants HT, TVA et TTC. Leur absence expose à des sanctions.",
    tip: "Numéro unique + HT/TVA/TTC : mentions incontournables.",
  },

  // ══════════════ 🎭 MISE EN SITUATION ══════════════
  {
    ...base, id: 'fin-si-1', type: 'situation', difficulty: 2,
    context: "En relisant le journal, vous repérez une écriture saisie deux fois la semaine dernière.",
    situation: "Doublon de saisie détecté.",
    question: "La bonne réaction :",
    options: [
      { text: "Laisser, ça s'équilibrera tout seul", correct: false },
      { text: "Corriger par une écriture d'annulation/contre-passation et tracer la correction", correct: true },
      { text: "Supprimer discrètement sans rien noter", correct: false },
      { text: "Ignorer l'erreur", correct: false },
    ],
    explanation: "On corrige proprement (contre-passation) en gardant la traçabilité, jamais en effaçant. La piste d'audit doit rester intacte : c'est une exigence comptable.",
    tip: "On corrige par écriture, on n'efface jamais sans trace.",
  },
  {
    ...base, id: 'fin-si-2', type: 'situation', difficulty: 2,
    context: "Un fournisseur vous relance pour une facture qu'il dit impayée, alors que vous pensez l'avoir réglée.",
    situation: "Litige sur un paiement fournisseur.",
    question: "Le bon réflexe :",
    options: [
      { text: "Repayer immédiatement pour avoir la paix", correct: false },
      { text: "Vérifier dans la comptabilité et les relevés avant toute action", correct: true },
      { text: "Refuser de répondre", correct: false },
      { text: "Accuser le fournisseur de mentir", correct: false },
    ],
    explanation: "Avant d'agir, on contrôle : écriture du paiement, relevé bancaire, référence. Repayer sans vérifier crée un double décaissement. La preuve documentaire tranche.",
    tip: "Vérifie la preuve de paiement avant de re-régler.",
  },
  {
    ...base, id: 'fin-si-3', type: 'situation', difficulty: 3,
    context: "Votre rapprochement bancaire fait apparaître un écart de 240 € inexpliqué.",
    situation: "Écart au rapprochement bancaire.",
    question: "La meilleure méthode :",
    options: [
      { text: "Forcer l'équilibre en inventant une écriture", correct: false },
      { text: "Pointer ligne à ligne pour identifier l'opération oubliée ou erronée, puis régulariser", correct: true },
      { text: "Ignorer l'écart", correct: false },
      { text: "Changer les chiffres jusqu'à ce que ça tombe juste", correct: false },
    ],
    explanation: "Un écart se justifie toujours par une cause (chèque non débité, frais oubliés, erreur). On pointe méthodiquement puis on régularise. Jamais « forcer » l'équilibre.",
    tip: "Un écart a une cause : on la cherche, on ne la masque pas.",
  },
  {
    ...base, id: 'fin-si-4', type: 'situation', difficulty: 3,
    context: "Votre supérieur vous demande de comptabiliser une grosse charge le mois prochain plutôt que ce mois-ci, « pour que le résultat soit plus joli ».",
    situation: "Pression pour décaler une charge.",
    question: "La bonne réaction :",
    options: [
      { text: "Accepter, c'est le chef qui décide", correct: false },
      { text: "Rappeler le principe de rattachement à l'exercice et refuser de fausser les comptes", correct: true },
      { text: "Décaler sans rien dire", correct: false },
      { text: "Supprimer la charge", correct: false },
    ],
    explanation: "Une charge se rattache à l'exercice qui la concerne (principe de séparation des exercices). La décaler pour embellir le résultat fausse les comptes : c'est irrégulier.",
    tip: "Chaque charge sur son exercice : pas d'embellissement.",
  },
  {
    ...base, id: 'fin-si-5', type: 'situation', difficulty: 2,
    context: "Un client n'a toujours pas réglé sa facture, échue depuis 30 jours.",
    situation: "Relance d'un impayé client.",
    question: "La meilleure démarche :",
    options: [
      { text: "Attendre indéfiniment sans rien faire", correct: false },
      { text: "Relancer avec méthode : rappel courtois, puis relances graduées et tracées", correct: true },
      { text: "Insulter le client", correct: false },
      { text: "Annuler la créance immédiatement", correct: false },
    ],
    explanation: "On relance de façon graduée et professionnelle (rappel, mise en demeure si besoin), en gardant une trace. Une bonne gestion des impayés protège la trésorerie.",
    tip: "Relance graduée et tracée : la trésorerie en dépend.",
  },
  {
    ...base, id: 'fin-si-6', type: 'situation', difficulty: 3,
    context: "🏆 BOSS — Clôture mensuelle à rendre demain. Il reste des factures non saisies, un rapprochement non fait et un écart à expliquer.",
    situation: "Clôture sous deadline avec anomalies.",
    question: "Par quoi commencer ?",
    options: [
      { text: "Rendre la clôture telle quelle, anomalies comprises", correct: false },
      { text: "Prioriser : saisir le manquant, faire le rapprochement, justifier l'écart, puis contrôler", correct: true },
      { text: "Inventer des chiffres pour gagner du temps", correct: false },
      { text: "Repousser la clôture sans prévenir", correct: false },
    ],
    explanation: "Une clôture fiable exige d'avoir tout saisi, rapproché et justifié avant de contrôler la cohérence. On hiérarchise les tâches et on alerte si le délai est intenable — on ne bâcle pas.",
    tip: "Une clôture, c'est exhaustivité + contrôle, jamais l'à-peu-près.",
  },

  // ══════════════ 📰 ACTU & TENDANCES (2026) ══════════════
  {
    ...base, id: 'fin-ac-1', type: 'actu', difficulty: 3,
    situation: "LA grande réforme du moment.",
    question: "Qu'impose la réforme de la facturation électronique en France ?",
    options: [
      { text: "L'interdiction des factures", correct: false },
      { text: "Le passage progressif (2026-2027) à la facture électronique obligatoire entre entreprises", correct: true },
      { text: "La fin de la TVA", correct: false },
      { text: "Le retour au papier obligatoire", correct: false },
    ],
    explanation: "La réforme généralise progressivement la facturation électronique B2B (et le e-reporting) via des plateformes agréées. C'est LE sujet comptable du moment : un must à connaître en entretien.",
    tip: "Sache en parler : c'est la réforme comptable phare de 2026.",
  },
  {
    ...base, id: 'fin-ac-2', type: 'actu', difficulty: 3,
    situation: "Automatisation du métier.",
    question: "Comment l'IA et l'automatisation transforment-elles la comptabilité ?",
    options: [
      { text: "Elles suppriment totalement le métier", correct: false },
      { text: "Elles automatisent saisie, OCR et rapprochements, recentrant le comptable sur l'analyse et le conseil", correct: true },
      { text: "Elles n'ont aucun impact", correct: false },
      { text: "Elles obligent à tout faire à la main", correct: false },
    ],
    explanation: "OCR, saisie automatique et rapprochements intelligents libèrent du temps. Le comptable évolue vers l'analyse, le contrôle et le conseil : un « business partner », pas un simple saisisseur.",
    tip: "Le comptable devient analyste/conseil, pas remplacé.",
  },
  {
    ...base, id: 'fin-ac-3', type: 'actu', difficulty: 2,
    situation: "Outils modernes.",
    question: "Qu'apportent les logiciels comptables cloud (ex : Pennylane, Sage, Cegid) ?",
    options: [
      { text: "Rien de plus que le papier", correct: false },
      { text: "Un accès en temps réel, collaboratif et automatisé aux données comptables", correct: true },
      { text: "Une obligation de travailler sans internet", correct: false },
      { text: "La suppression de la comptabilité", correct: false },
    ],
    explanation: "Les outils cloud offrent données en temps réel, collaboration client-cabinet et automatisations. Maîtriser un de ces logiciels est un vrai atout en 2026.",
    tip: "Cite un logiciel cloud que tu connais (Pennylane, Sage…).",
  },
  {
    ...base, id: 'fin-ac-4', type: 'actu', difficulty: 3,
    situation: "Reporting extra-financier.",
    question: "Que demande la CSRD aux entreprises concernées ?",
    options: [
      { text: "De publier uniquement leur chiffre d'affaires", correct: false },
      { text: "De publier des informations de durabilité (environnement, social, gouvernance) auditées", correct: true },
      { text: "De supprimer leur comptabilité", correct: false },
      { text: "De payer plus d'impôts automatiquement", correct: false },
    ],
    explanation: "La CSRD impose un reporting extra-financier (ESG) structuré et vérifié. La finance est en première ligne pour collecter, fiabiliser et publier ces données.",
    tip: "ESG/CSRD : la finance fiabilise les données de durabilité.",
  },
  {
    ...base, id: 'fin-ac-5', type: 'actu', difficulty: 2,
    situation: "Évolution du rôle.",
    question: "Vers quoi évolue le métier de comptable ?",
    options: [
      { text: "Vers la pure saisie manuelle", correct: false },
      { text: "Vers un rôle de conseil et d'aide à la décision (« business partner »)", correct: true },
      { text: "Vers la disparition totale", correct: false },
      { text: "Vers un métier sans informatique", correct: false },
    ],
    explanation: "Libéré des tâches répétitives, le comptable apporte de plus en plus d'analyse, de pilotage et de conseil au dirigeant. La valeur se déplace de la saisie vers l'interprétation.",
    tip: "Valorise l'analyse et le conseil, l'avenir du métier.",
  },
  {
    ...base, id: 'fin-ac-6', type: 'actu', difficulty: 3,
    situation: "Risques financiers.",
    question: "Qu'est-ce que la « fraude au président » (ou au virement) ?",
    options: [
      { text: "Une élection en entreprise", correct: false },
      { text: "Une escroquerie où un imposteur usurpe un dirigeant pour obtenir un virement urgent", correct: true },
      { text: "Une prime versée au dirigeant", correct: false },
      { text: "Un type de TVA", correct: false },
    ],
    explanation: "La fraude au président se multiplie : un faux dirigeant exige un virement « urgent et confidentiel ». La finance doit appliquer des procédures de vérification strictes (double validation, rappel).",
    tip: "Virement urgent + confidentiel = signal d'alerte fraude.",
  },
  {
    ...base, id: 'fin-ac-7', type: 'actu', difficulty: 2,
    situation: "Données et pilotage.",
    question: "Pourquoi le « temps réel » change-t-il la finance ?",
    options: [
      { text: "Il n'apporte rien", correct: false },
      { text: "Des données à jour permettent de piloter et décider plus vite, sans attendre la clôture", correct: true },
      { text: "Il oblige à travailler la nuit", correct: false },
      { text: "Il supprime les bilans", correct: false },
    ],
    explanation: "Avec des outils connectés, le dirigeant suit sa trésorerie et ses indicateurs en continu. La finance devient un copilote réactif plutôt qu'un historien des chiffres.",
    tip: "Données en temps réel = pilotage proactif.",
  },
  {
    ...base, id: 'fin-ac-8', type: 'actu', difficulty: 2,
    situation: "Dématérialisation des justificatifs.",
    question: "Qu'autorise désormais la « facture/justificatif numérique » à valeur probante ?",
    options: [
      { text: "Rien, il faut garder tout le papier", correct: false },
      { text: "Conserver et archiver électroniquement les pièces, sans original papier, sous conditions", correct: true },
      { text: "Jeter toutes les pièces immédiatement", correct: false },
      { text: "Falsifier les justificatifs", correct: false },
    ],
    explanation: "La dématérialisation à valeur probante permet d'archiver numériquement les justificatifs (sous conditions de fiabilité), réduisant le papier. Elle accompagne la réforme e-invoicing.",
    tip: "Dématérialisation à valeur probante = fin du tout-papier.",
  },
];
