/**
 * Secteur « Finance / Comptabilité » — parcours (4 couches).
 *
 * sector:'finance', type ∈ {comportemental, technique, situation, actu}.
 * Une seule option correct:true, + explanation + tip. `context` optionnel.
 */
const base = { sector: 'finance' };

export default [
  // ══════════════ 🧠 COMPORTEMENTAL ══════════════
  {
    ...base, id: 'fin-cp-1', type: 'comportemental', difficulty: 1,
    situation: "« Pourquoi la comptabilité / finance vous attire-t-elle ? »",
    question: "La motivation la plus crédible :",
    options: [
      { text: "« Parce que j'aime l'argent »", correct: false },
      { text: "Le goût des chiffres, de la rigueur et du rôle clé dans le pilotage de l'entreprise", correct: true },
      { text: "« Parce que c'est répétitif et sans surprise »", correct: false },
      { text: "« Pour ne parler à personne »", correct: false },
    ],
    explanation: "La compta/finance traduit la santé de l'entreprise en chiffres et aide à décider. On valorise la rigueur, la logique et l'intérêt pour le pilotage, pas le cliché du métier « ennuyeux ».",
    tip: "Mets en avant rigueur et rôle dans la prise de décision.",
  },
  {
    ...base, id: 'fin-cp-2', type: 'comportemental', difficulty: 2,
    situation: "« La fiabilité des chiffres, à quel point est-ce important ? »",
    question: "La meilleure posture :",
    options: [
      { text: "« Une petite erreur, ce n'est pas grave »", correct: false },
      { text: "Cruciale : une erreur fausse les comptes, les déclarations et les décisions", correct: true },
      { text: "« Mieux vaut aller vite que juste »", correct: false },
      { text: "« On corrigera plus tard, peut-être »", correct: false },
    ],
    explanation: "En compta, l'exactitude est primordiale : une erreur se propage (déclarations fiscales, bilan, décisions). Rigueur et contrôle systématique sont la base du métier.",
    tip: "Vérifier deux fois vaut mieux que corriger dix fois.",
  },
  {
    ...base, id: 'fin-cp-3', type: 'comportemental', difficulty: 2,
    situation: "Vous manipulez des données financières sensibles (salaires, marges, comptes).",
    question: "Quelle qualité est indispensable ?",
    options: [
      { text: "Commenter les chiffres avec n'importe qui", correct: false },
      { text: "Une confidentialité et une intégrité totales", correct: true },
      { text: "Partager les marges aux concurrents", correct: false },
      { text: "Laisser traîner les documents", correct: false },
    ],
    explanation: "Les données financières sont stratégiques et confidentielles. Discrétion et intégrité sont non négociables : c'est une question de déontologie et de confiance.",
    tip: "Confidentialité des chiffres = pilier du métier.",
  },
  {
    ...base, id: 'fin-cp-4', type: 'comportemental', difficulty: 2,
    situation: "« Comment gérez-vous la pression des échéances (clôtures, déclarations) ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Je rends en retard, l'administration attendra »", correct: false },
      { text: "Je m'organise en amont avec un rétroplanning pour tenir les délais légaux", correct: true },
      { text: "« Je travaille uniquement dans l'urgence »", correct: false },
      { text: "« J'ignore les dates limites »", correct: false },
    ],
    explanation: "Les échéances fiscales et sociales sont impératives (pénalités à la clé). L'anticipation et l'organisation sont essentielles pour tenir les délais sans stress destructeur.",
    tip: "Anticiper les échéances évite pénalités et panique.",
  },
  {
    ...base, id: 'fin-cp-5', type: 'comportemental', difficulty: 3,
    situation: "« Que faites-vous si on vous demande de présenter des comptes flatteurs mais inexacts ? »",
    question: "La bonne posture :",
    options: [
      { text: "Obéir sans discuter", correct: false },
      { text: "Refuser : l'éthique et la sincérité des comptes priment, et la loi l'exige", correct: true },
      { text: "Maquiller un peu, « juste cette fois »", correct: false },
      { text: "Démissionner sur-le-champ sans rien dire", correct: false },
    ],
    explanation: "La sincérité des comptes est une obligation légale et déontologique. Falsifier expose à de lourdes sanctions. L'intégrité du comptable protège l'entreprise et lui-même.",
    tip: "Sincérité des comptes : une ligne rouge à ne jamais franchir.",
  },
  {
    ...base, id: 'fin-cp-6', type: 'comportemental', difficulty: 2,
    situation: "« Votre métier se résume-t-il à de la saisie ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Oui, juste saisir des chiffres toute la journée »", correct: false },
      { text: "Non : au-delà de la saisie, j'analyse, je contrôle et j'apporte de l'aide à la décision", correct: true },
      { text: "« Je ne comprends pas ce que je saisis »", correct: false },
      { text: "« La saisie, c'est dépassé, je ne fais rien »", correct: false },
    ],
    explanation: "Avec l'automatisation, le métier se recentre sur l'analyse, le contrôle et le conseil. Montrer cet esprit d'analyse (au-delà de la saisie) est très valorisé.",
    tip: "Positionne-toi sur l'analyse, pas seulement la saisie.",
  },

  // ══════════════ 🛠️ TECHNIQUE MÉTIER ══════════════
  {
    ...base, id: 'fin-te-1', type: 'technique', difficulty: 2,
    situation: "Documents comptables.",
    question: "Qu'est-ce que le bilan comptable ?",
    options: [
      { text: "La liste des ventes du mois", correct: false },
      { text: "Une photo du patrimoine à un instant T : actif (ce qu'on possède) et passif (ce qu'on doit)", correct: true },
      { text: "Le salaire des dirigeants", correct: false },
      { text: "Un planning de réunions", correct: false },
    ],
    explanation: "Le bilan présente, à une date donnée, l'actif (emplois) et le passif (ressources). C'est une photographie du patrimoine, à distinguer du compte de résultat.",
    tip: "Bilan = photo à un instant T (actif = passif).",
  },
  {
    ...base, id: 'fin-te-2', type: 'technique', difficulty: 2,
    situation: "Documents comptables.",
    question: "Que montre le compte de résultat ?",
    options: [
      { text: "Le patrimoine de l'entreprise", correct: false },
      { text: "Les produits et les charges d'une période, et donc le bénéfice ou la perte", correct: true },
      { text: "La trésorerie disponible aujourd'hui", correct: false },
      { text: "La liste des salariés", correct: false },
    ],
    explanation: "Le compte de résultat retrace l'activité sur une période : produits − charges = résultat (bénéfice ou perte). C'est un « film » de l'activité, là où le bilan est une « photo ».",
    tip: "Compte de résultat = film de l'activité (produits − charges).",
  },
  {
    ...base, id: 'fin-te-3', type: 'technique', difficulty: 2,
    situation: "Principe fondamental.",
    question: "Que signifie la « comptabilité en partie double » ?",
    options: [
      { text: "Tout saisir deux fois pour vérifier", correct: false },
      { text: "Chaque opération est enregistrée au débit d'un compte et au crédit d'un autre", correct: true },
      { text: "Avoir deux comptables", correct: false },
      { text: "Doubler les montants", correct: false },
    ],
    explanation: "En partie double, toute écriture équilibre un débit et un crédit de même montant. C'est le socle de la comptabilité : le total des débits égale toujours le total des crédits.",
    tip: "Débit = crédit : l'équilibre, toujours.",
  },
  {
    ...base, id: 'fin-te-4', type: 'technique', difficulty: 2,
    situation: "Fiscalité courante.",
    question: "Comment fonctionne la TVA pour une entreprise ?",
    options: [
      { text: "L'entreprise garde toute la TVA encaissée", correct: false },
      { text: "Elle reverse la TVA collectée (ventes) moins la TVA déductible (achats)", correct: true },
      { text: "La TVA est un bénéfice", correct: false },
      { text: "La TVA ne concerne pas les entreprises", correct: false },
    ],
    explanation: "L'entreprise collecte la TVA sur ses ventes et déduit celle de ses achats ; elle reverse la différence à l'État. Elle joue un rôle de collecteur, la TVA n'est pas un produit.",
    tip: "TVA à payer = TVA collectée − TVA déductible.",
  },
  {
    ...base, id: 'fin-te-5', type: 'technique', difficulty: 3,
    situation: "Contrôle de cohérence.",
    question: "À quoi sert le « rapprochement bancaire » ?",
    options: [
      { text: "À ouvrir un nouveau compte", correct: false },
      { text: "À vérifier la concordance entre le compte banque en comptabilité et le relevé de la banque", correct: true },
      { text: "À calculer la paie", correct: false },
      { text: "À négocier un prêt", correct: false },
    ],
    explanation: "Le rapprochement bancaire confronte les écritures comptables au relevé bancaire pour détecter écarts, oublis ou erreurs. C'est un contrôle régulier essentiel.",
    tip: "Rapprochement = comptabilité vs relevé, on traque les écarts.",
  },
  {
    ...base, id: 'fin-te-6', type: 'technique', difficulty: 3,
    situation: "Étalement d'une dépense.",
    question: "Qu'est-ce qu'un « amortissement » ?",
    options: [
      { text: "Un remboursement de prêt uniquement", correct: false },
      { text: "La répartition du coût d'un bien sur sa durée d'utilisation (usure)", correct: true },
      { text: "Une remise commerciale", correct: false },
      { text: "Une prime aux salariés", correct: false },
    ],
    explanation: "L'amortissement constate la perte de valeur d'une immobilisation (machine, véhicule) en étalant son coût sur plusieurs années, plutôt qu'en une seule charge.",
    tip: "Amortir = étaler le coût d'un bien sur sa durée de vie.",
  },
  {
    ...base, id: 'fin-te-7', type: 'technique', difficulty: 2,
    situation: "Distinction clé.",
    question: "Quelle est la différence entre une charge et une immobilisation ?",
    options: [
      { text: "Aucune, c'est pareil", correct: false },
      { text: "La charge est consommée sur l'exercice ; l'immobilisation sert durablement (et s'amortit)", correct: true },
      { text: "La charge est un revenu", correct: false },
      { text: "L'immobilisation est une vente", correct: false },
    ],
    explanation: "Une charge (fournitures, loyer) est consommée sur la période ; une immobilisation (matériel durable) reste à l'actif et s'amortit. Bien les distinguer est essentiel.",
    tip: "Durable et coûteux → immobilisation, pas charge.",
  },
  {
    ...base, id: 'fin-te-8', type: 'technique', difficulty: 2,
    situation: "Pilotage de la trésorerie.",
    question: "Que désigne la « trésorerie » d'une entreprise ?",
    options: [
      { text: "Son bénéfice annuel", correct: false },
      { text: "L'argent réellement disponible (banque + caisse) à un moment donné", correct: true },
      { text: "La valeur de ses stocks", correct: false },
      { text: "Le total de ses ventes", correct: false },
    ],
    explanation: "La trésorerie, c'est le cash disponible. Une entreprise peut être rentable mais manquer de trésorerie (décalage encaissements/décaissements) : la suivre est vital.",
    tip: "Rentable ≠ avoir du cash : surveille la trésorerie.",
  },
  {
    ...base, id: 'fin-te-9', type: 'technique', difficulty: 1,
    situation: "Document commercial et légal.",
    question: "Quelle mention est obligatoire sur une facture ?",
    options: [
      { text: "La couleur préférée du client", correct: false },
      { text: "Le numéro de facture, les coordonnées, la date, le détail et les montants HT/TVA/TTC", correct: true },
      { text: "Rien n'est obligatoire", correct: false },
      { text: "Une photo du produit", correct: false },
    ],
    explanation: "Une facture doit comporter des mentions légales : identité des parties, numéro unique, date, désignation, montants HT, TVA et TTC. Leur absence expose à des sanctions.",
    tip: "Numéro unique + HT/TVA/TTC : mentions incontournables.",
  },

  // ══════════════ 🎭 MISE EN SITUATION ══════════════
  {
    ...base, id: 'fin-si-1', type: 'situation', difficulty: 2,
    context: "En relisant le journal, vous repérez une écriture saisie deux fois la semaine dernière.",
    situation: "Doublon de saisie détecté.",
    question: "La bonne réaction :",
    options: [
      { text: "Laisser, ça s'équilibrera tout seul", correct: false },
      { text: "Corriger par une écriture d'annulation/contre-passation et tracer la correction", correct: true },
      { text: "Supprimer discrètement sans rien noter", correct: false },
      { text: "Ignorer l'erreur", correct: false },
    ],
    explanation: "On corrige proprement (contre-passation) en gardant la traçabilité, jamais en effaçant. La piste d'audit doit rester intacte : c'est une exigence comptable.",
    tip: "On corrige par écriture, on n'efface jamais sans trace.",
  },
  {
    ...base, id: 'fin-si-2', type: 'situation', difficulty: 2,
    context: "Un fournisseur vous relance pour une facture qu'il dit impayée, alors que vous pensez l'avoir réglée.",
    situation: "Litige sur un paiement fournisseur.",
    question: "Le bon réflexe :",
    options: [
      { text: "Repayer immédiatement pour avoir la paix", correct: false },
      { text: "Vérifier dans la comptabilité et les relevés avant toute action", correct: true },
      { text: "Refuser de répondre", correct: false },
      { text: "Accuser le fournisseur de mentir", correct: false },
    ],
    explanation: "Avant d'agir, on contrôle : écriture du paiement, relevé bancaire, référence. Repayer sans vérifier crée un double décaissement. La preuve documentaire tranche.",
    tip: "Vérifie la preuve de paiement avant de re-régler.",
  },
  {
    ...base, id: 'fin-si-3', type: 'situation', difficulty: 3,
    context: "Votre rapprochement bancaire fait apparaître un écart de 240 € inexpliqué.",
    situation: "Écart au rapprochement bancaire.",
    question: "La meilleure méthode :",
    options: [
      { text: "Forcer l'équilibre en inventant une écriture", correct: false },
      { text: "Pointer ligne à ligne pour identifier l'opération oubliée ou erronée, puis régulariser", correct: true },
      { text: "Ignorer l'écart", correct: false },
      { text: "Changer les chiffres jusqu'à ce que ça tombe juste", correct: false },
    ],
    explanation: "Un écart se justifie toujours par une cause (chèque non débité, frais oubliés, erreur). On pointe méthodiquement puis on régularise. Jamais « forcer » l'équilibre.",
    tip: "Un écart a une cause : on la cherche, on ne la masque pas.",
  },
  {
    ...base, id: 'fin-si-4', type: 'situation', difficulty: 3,
    context: "Votre supérieur vous demande de comptabiliser une grosse charge le mois prochain plutôt que ce mois-ci, « pour que le résultat soit plus joli ».",
    situation: "Pression pour décaler une charge.",
    question: "La bonne réaction :",
    options: [
      { text: "Accepter, c'est le chef qui décide", correct: false },
      { text: "Rappeler le principe de rattachement à l'exercice et refuser de fausser les comptes", correct: true },
      { text: "Décaler sans rien dire", correct: false },
      { text: "Supprimer la charge", correct: false },
    ],
    explanation: "Une charge se rattache à l'exercice qui la concerne (principe de séparation des exercices). La décaler pour embellir le résultat fausse les comptes : c'est irrégulier.",
    tip: "Chaque charge sur son exercice : pas d'embellissement.",
  },
  {
    ...base, id: 'fin-si-5', type: 'situation', difficulty: 2,
    context: "Un client n'a toujours pas réglé sa facture, échue depuis 30 jours.",
    situation: "Relance d'un impayé client.",
    question: "La meilleure démarche :",
    options: [
      { text: "Attendre indéfiniment sans rien faire", correct: false },
      { text: "Relancer avec méthode : rappel courtois, puis relances graduées et tracées", correct: true },
      { text: "Insulter le client", correct: false },
      { text: "Annuler la créance immédiatement", correct: false },
    ],
    explanation: "On relance de façon graduée et professionnelle (rappel, mise en demeure si besoin), en gardant une trace. Une bonne gestion des impayés protège la trésorerie.",
    tip: "Relance graduée et tracée : la trésorerie en dépend.",
  },
  {
    ...base, id: 'fin-si-6', type: 'situation', difficulty: 3,
    context: "🏆 BOSS — Clôture mensuelle à rendre demain. Il reste des factures non saisies, un rapprochement non fait et un écart à expliquer.",
    situation: "Clôture sous deadline avec anomalies.",
    question: "Par quoi commencer ?",
    options: [
      { text: "Rendre la clôture telle quelle, anomalies comprises", correct: false },
      { text: "Prioriser : saisir le manquant, faire le rapprochement, justifier l'écart, puis contrôler", correct: true },
      { text: "Inventer des chiffres pour gagner du temps", correct: false },
      { text: "Repousser la clôture sans prévenir", correct: false },
    ],
    explanation: "Une clôture fiable exige d'avoir tout saisi, rapproché et justifié avant de contrôler la cohérence. On hiérarchise les tâches et on alerte si le délai est intenable — on ne bâcle pas.",
    tip: "Une clôture, c'est exhaustivité + contrôle, jamais l'à-peu-près.",
  },

  // ══════════════ 📰 ACTU & TENDANCES (2026) ══════════════
  {
    ...base, id: 'fin-ac-1', type: 'actu', difficulty: 3,
    situation: "LA grande réforme du moment.",
    question: "Qu'impose la réforme de la facturation électronique en France ?",
    options: [
      { text: "L'interdiction des factures", correct: false },
      { text: "Le passage progressif (2026-2027) à la facture électronique obligatoire entre entreprises", correct: true },
      { text: "La fin de la TVA", correct: false },
      { text: "Le retour au papier obligatoire", correct: false },
    ],
    explanation: "La réforme généralise progressivement la facturation électronique B2B (et le e-reporting) via des plateformes agréées. C'est LE sujet comptable du moment : un must à connaître en entretien.",
    tip: "Sache en parler : c'est la réforme comptable phare de 2026.",
  },
  {
    ...base, id: 'fin-ac-2', type: 'actu', difficulty: 3,
    situation: "Automatisation du métier.",
    question: "Comment l'IA et l'automatisation transforment-elles la comptabilité ?",
    options: [
      { text: "Elles suppriment totalement le métier", correct: false },
      { text: "Elles automatisent saisie, OCR et rapprochements, recentrant le comptable sur l'analyse et le conseil", correct: true },
      { text: "Elles n'ont aucun impact", correct: false },
      { text: "Elles obligent à tout faire à la main", correct: false },
    ],
    explanation: "OCR, saisie automatique et rapprochements intelligents libèrent du temps. Le comptable évolue vers l'analyse, le contrôle et le conseil : un « business partner », pas un simple saisisseur.",
    tip: "Le comptable devient analyste/conseil, pas remplacé.",
  },
  {
    ...base, id: 'fin-ac-3', type: 'actu', difficulty: 2,
    situation: "Outils modernes.",
    question: "Qu'apportent les logiciels comptables cloud (ex : Pennylane, Sage, Cegid) ?",
    options: [
      { text: "Rien de plus que le papier", correct: false },
      { text: "Un accès en temps réel, collaboratif et automatisé aux données comptables", correct: true },
      { text: "Une obligation de travailler sans internet", correct: false },
      { text: "La suppression de la comptabilité", correct: false },
    ],
    explanation: "Les outils cloud offrent données en temps réel, collaboration client-cabinet et automatisations. Maîtriser un de ces logiciels est un vrai atout en 2026.",
    tip: "Cite un logiciel cloud que tu connais (Pennylane, Sage…).",
  },
  {
    ...base, id: 'fin-ac-4', type: 'actu', difficulty: 3,
    situation: "Reporting extra-financier.",
    question: "Que demande la CSRD aux entreprises concernées ?",
    options: [
      { text: "De publier uniquement leur chiffre d'affaires", correct: false },
      { text: "De publier des informations de durabilité (environnement, social, gouvernance) auditées", correct: true },
      { text: "De supprimer leur comptabilité", correct: false },
      { text: "De payer plus d'impôts automatiquement", correct: false },
    ],
    explanation: "La CSRD impose un reporting extra-financier (ESG) structuré et vérifié. La finance est en première ligne pour collecter, fiabiliser et publier ces données.",
    tip: "ESG/CSRD : la finance fiabilise les données de durabilité.",
  },
  {
    ...base, id: 'fin-ac-5', type: 'actu', difficulty: 2,
    situation: "Évolution du rôle.",
    question: "Vers quoi évolue le métier de comptable ?",
    options: [
      { text: "Vers la pure saisie manuelle", correct: false },
      { text: "Vers un rôle de conseil et d'aide à la décision (« business partner »)", correct: true },
      { text: "Vers la disparition totale", correct: false },
      { text: "Vers un métier sans informatique", correct: false },
    ],
    explanation: "Libéré des tâches répétitives, le comptable apporte de plus en plus d'analyse, de pilotage et de conseil au dirigeant. La valeur se déplace de la saisie vers l'interprétation.",
    tip: "Valorise l'analyse et le conseil, l'avenir du métier.",
  },
  {
    ...base, id: 'fin-ac-6', type: 'actu', difficulty: 3,
    situation: "Risques financiers.",
    question: "Qu'est-ce que la « fraude au président » (ou au virement) ?",
    options: [
      { text: "Une élection en entreprise", correct: false },
      { text: "Une escroquerie où un imposteur usurpe un dirigeant pour obtenir un virement urgent", correct: true },
      { text: "Une prime versée au dirigeant", correct: false },
      { text: "Un type de TVA", correct: false },
    ],
    explanation: "La fraude au président se multiplie : un faux dirigeant exige un virement « urgent et confidentiel ». La finance doit appliquer des procédures de vérification strictes (double validation, rappel).",
    tip: "Virement urgent + confidentiel = signal d'alerte fraude.",
  },
  {
    ...base, id: 'fin-ac-7', type: 'actu', difficulty: 2,
    situation: "Données et pilotage.",
    question: "Pourquoi le « temps réel » change-t-il la finance ?",
    options: [
      { text: "Il n'apporte rien", correct: false },
      { text: "Des données à jour permettent de piloter et décider plus vite, sans attendre la clôture", correct: true },
      { text: "Il oblige à travailler la nuit", correct: false },
      { text: "Il supprime les bilans", correct: false },
    ],
    explanation: "Avec des outils connectés, le dirigeant suit sa trésorerie et ses indicateurs en continu. La finance devient un copilote réactif plutôt qu'un historien des chiffres.",
    tip: "Données en temps réel = pilotage proactif.",
  },
  {
    ...base, id: 'fin-ac-8', type: 'actu', difficulty: 2,
    situation: "Dématérialisation des justificatifs.",
    question: "Qu'autorise désormais la « facture/justificatif numérique » à valeur probante ?",
    options: [
      { text: "Rien, il faut garder tout le papier", correct: false },
      { text: "Conserver et archiver électroniquement les pièces, sans original papier, sous conditions", correct: true },
      { text: "Jeter toutes les pièces immédiatement", correct: false },
      { text: "Falsifier les justificatifs", correct: false },
    ],
    explanation: "La dématérialisation à valeur probante permet d'archiver numériquement les justificatifs (sous conditions de fiabilité), réduisant le papier. Elle accompagne la réforme e-invoicing.",
    tip: "Dématérialisation à valeur probante = fin du tout-papier.",
  },

  // ── 🧠 COMPORTEMENTAL (suite) ──
  {
    ...base, id: 'fin-cp-7', type: 'comportemental', difficulty: 1,
    situation: "« Pourquoi la finance/comptabilité vous attire ? »",
    question: "La motivation la plus solide :",
    options: [
      { text: "« Parce que j'aime l'argent »", correct: false },
      { text: "Le goût des chiffres, de la rigueur et du rôle clé dans les décisions", correct: true },
      { text: "« C'est répétitif, ça me rassure »", correct: false },
      { text: "« Je n'ai pas trouvé mieux »", correct: false },
    ],
    explanation: "La finance pilote les décisions de l'entreprise : on attend un intérêt pour les chiffres, la rigueur et l'analyse, pas une simple attirance pour l'argent.",
    tip: "Parle de rigueur et d'aide à la décision.",
  },
  {
    ...base, id: 'fin-cp-8', type: 'comportemental', difficulty: 3,
    context: "Votre supérieur vous demande de « décaler » une charge sur l'exercice suivant pour améliorer le résultat affiché.",
    situation: "On vous pousse à arranger les comptes.",
    question: "La bonne réaction :",
    options: [
      { text: "Obéir pour faire plaisir", correct: false },
      { text: "Refuser : l'intégrité comptable et le respect des règles priment", correct: true },
      { text: "Le faire discrètement", correct: false },
      { text: "Falsifier en espérant que personne ne voie", correct: false },
    ],
    explanation: "La sincérité des comptes est un principe non négociable. Manipuler les écritures est une faute grave aux lourdes conséquences (légales, pénales).",
    tip: "L'intégrité comptable ne se négocie jamais.",
  },
  {
    ...base, id: 'fin-cp-9', type: 'comportemental', difficulty: 3,
    situation: "Vous avez accès aux salaires, marges et données sensibles.",
    question: "La règle absolue :",
    options: [
      { text: "En parler librement", correct: false },
      { text: "Confidentialité totale sur les données financières", correct: true },
      { text: "Partager « entre collègues »", correct: false },
      { text: "Laisser les fichiers ouverts", correct: false },
    ],
    explanation: "Les données financières sont stratégiques et confidentielles. Une fuite (marges, salaires, résultats) peut nuire gravement à l'entreprise.",
    tip: "Les chiffres sensibles restent strictement confidentiels.",
  },
  {
    ...base, id: 'fin-cp-10', type: 'comportemental', difficulty: 2,
    situation: "Une petite erreur s'est glissée dans une écriture.",
    question: "La qualité indispensable :",
    options: [
      { text: "« Une erreur, ce n'est pas grave »", correct: false },
      { text: "La rigueur : en compta, une erreur peut fausser tout un état financier", correct: true },
      { text: "Ignorer et passer à autre chose", correct: false },
      { text: "Arrondir au hasard", correct: false },
    ],
    explanation: "La précision est la première qualité du comptable : une erreur se propage (bilan, déclarations). On vérifie et on corrige systématiquement.",
    tip: "En compta, le détail n'est jamais un détail.",
  },
  {
    ...base, id: 'fin-cp-11', type: 'comportemental', difficulty: 2,
    situation: "La clôture mensuelle approche avec beaucoup à traiter.",
    question: "La qualité requise :",
    options: [
      { text: "Tout repousser au dernier jour", correct: false },
      { text: "L'organisation et le respect des échéances", correct: true },
      { text: "Travailler sans méthode", correct: false },
      { text: "Ignorer les délais", correct: false },
    ],
    explanation: "Les échéances comptables et fiscales sont impératives. L'organisation et l'anticipation évitent les retards et les pénalités.",
    tip: "Anticipe les clôtures, ne les subis pas.",
  },
  {
    ...base, id: 'fin-cp-12', type: 'comportemental', difficulty: 2,
    situation: "Un manager non financier ne comprend pas vos chiffres.",
    question: "La bonne attitude :",
    options: [
      { text: "« C'est technique, vous ne pouvez pas comprendre »", correct: false },
      { text: "Vulgariser et expliquer clairement ce que disent les chiffres", correct: true },
      { text: "Le noyer sous le jargon", correct: false },
      { text: "Refuser d'expliquer", correct: false },
    ],
    explanation: "Le financier moderne sait traduire les chiffres pour aider à décider. La pédagogie rend la finance utile aux autres services.",
    tip: "Un bon financier rend les chiffres compréhensibles.",
  },
  {
    ...base, id: 'fin-cp-13', type: 'comportemental', difficulty: 2,
    situation: "On vous confie une analyse à rendre vite.",
    question: "La qualité valorisée :",
    options: [
      { text: "Rendre vite mais faux", correct: false },
      { text: "Concilier fiabilité et respect du délai, en signalant toute incertitude", correct: true },
      { text: "Ne jamais rendre", correct: false },
      { text: "Inventer les chiffres manquants", correct: false },
    ],
    explanation: "En finance, la fiabilité prime, mais le délai compte aussi. On rend une analyse juste et on signale les hypothèses ou incertitudes éventuelles.",
    tip: "Mieux vaut juste avec réserves que rapide et faux.",
  },
  {
    ...base, id: 'fin-cp-14', type: 'comportemental', difficulty: 1,
    situation: "« Êtes-vous à l'aise avec la pression des deadlines fiscales ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Non, ça me paralyse »", correct: false },
      { text: "Oui : je planifie en amont pour absorber les pics (clôtures, déclarations)", correct: true },
      { text: "« Les délais sont indicatifs »", correct: false },
      { text: "« Je gère à l'arrache »", correct: false },
    ],
    explanation: "La fonction connaît des pics (clôtures, TVA, liasse). Montrer qu'on anticipe et qu'on s'organise rassure plus que « je gère le stress ».",
    tip: "Anticipation = meilleure arme contre la pression.",
  },
  {
    ...base, id: 'fin-cp-15', type: 'comportemental', difficulty: 2,
    situation: "Un chiffre vous semble incohérent dans un reporting.",
    question: "Le bon réflexe :",
    options: [
      { text: "Le recopier sans réfléchir", correct: false },
      { text: "Faire preuve d'esprit critique : vérifier la source et l'expliquer", correct: true },
      { text: "Le supprimer", correct: false },
      { text: "L'arrondir pour que ça colle", correct: false },
    ],
    explanation: "L'esprit d'analyse distingue un bon financier : un chiffre surprenant se vérifie et s'explique, jamais ne se maquille.",
    tip: "Un chiffre étrange = une vérification, pas une retouche.",
  },
  {
    ...base, id: 'fin-cp-16', type: 'comportemental', difficulty: 2,
    situation: "Vous travaillez avec les achats, les ventes et la direction.",
    question: "La compétence relationnelle utile :",
    options: [
      { text: "Rester isolé dans son bureau", correct: false },
      { text: "Collaborer et communiquer pour fiabiliser l'information financière", correct: true },
      { text: "Considérer les autres services comme des ennemis", correct: false },
      { text: "Ne jamais partager d'information", correct: false },
    ],
    explanation: "La finance dépend des données des autres services. Une bonne collaboration fiabilise les chiffres et fluidifie les clôtures.",
    tip: "La qualité des comptes dépend aussi des autres services.",
  },
  {
    ...base, id: 'fin-cp-17', type: 'comportemental', difficulty: 1,
    situation: "Vous ne maîtrisez pas une règle fiscale précise.",
    question: "La bonne attitude :",
    options: [
      { text: "Inventer une réponse", correct: false },
      { text: "Vérifier la réglementation ou demander avant d'agir", correct: true },
      { text: "Faire au hasard", correct: false },
      { text: "Ignorer la règle", correct: false },
    ],
    explanation: "La réglementation évolue ; une erreur fiscale coûte cher. On vérifie ses sources ou on demande plutôt que d'improviser.",
    tip: "Dans le doute fiscal, vérifie la source officielle.",
  },
  {
    ...base, id: 'fin-cp-18', type: 'comportemental', difficulty: 2,
    situation: "On vous propose un nouvel outil/ERP comptable.",
    question: "La posture attendue :",
    options: [
      { text: "Refuser tout changement", correct: false },
      { text: "Se former et s'adapter aux outils qui fiabilisent et accélèrent le travail", correct: true },
      { text: "Continuer tout à la main", correct: false },
      { text: "Bloquer le projet", correct: false },
    ],
    explanation: "La fonction finance se digitalise vite. L'adaptabilité et l'envie d'apprendre les outils sont devenues des atouts majeurs.",
    tip: "L'aisance avec les outils est un vrai différenciateur.",
  },
  {
    ...base, id: 'fin-cp-19', type: 'comportemental', difficulty: 2,
    situation: "Vous repérez une dépense anormale dans les comptes.",
    question: "La bonne réaction :",
    options: [
      { text: "Laisser passer", correct: false },
      { text: "Le signaler à la bonne personne et documenter le point", correct: true },
      { text: "En parler à tout le monde", correct: false },
      { text: "Supprimer la ligne", correct: false },
    ],
    explanation: "La vigilance face aux anomalies (fraude, erreur) fait partie du rôle. On alerte la hiérarchie et on documente, sans accuser ni dissimuler.",
    tip: "Signale et documente toute anomalie financière.",
  },
  {
    ...base, id: 'fin-cp-20', type: 'comportemental', difficulty: 2,
    situation: "« Quelle est la qualité n°1 d'un bon comptable ? »",
    question: "La réponse la plus juste :",
    options: [
      { text: "« La rapidité avant tout »", correct: false },
      { text: "La rigueur et la fiabilité, au service d'une information juste", correct: true },
      { text: "« Savoir arrondir »", correct: false },
      { text: "« Être discret pour cacher les erreurs »", correct: false },
    ],
    explanation: "La rigueur et la fiabilité sont au cœur du métier : on produit une information exacte sur laquelle l'entreprise s'appuie pour décider.",
    tip: "Fiabilité d'abord : c'est la base de la confiance.",
  },

  // ── 🛠️ TECHNIQUE (suite) ──
  {
    ...base, id: 'fin-te-10', type: 'technique', difficulty: 2,
    situation: "Vous enregistrez une opération en comptabilité.",
    question: "Le principe de base :",
    options: [
      { text: "Inscrire le montant une seule fois", correct: false },
      { text: "La partie double : tout débit a un crédit équivalent", correct: true },
      { text: "Arrondir à la dizaine", correct: false },
      { text: "Choisir débit ou crédit au hasard", correct: false },
    ],
    explanation: "La comptabilité en partie double équilibre chaque opération (débit = crédit). C'est le fondement qui garantit la cohérence des comptes.",
    tip: "Débit = Crédit, toujours.",
  },
  {
    ...base, id: 'fin-te-11', type: 'technique', difficulty: 2,
    situation: "Vous établissez une facture.",
    question: "La mention essentielle à ne pas oublier :",
    options: [
      { text: "Aucune mention obligatoire", correct: false },
      { text: "TVA (taux et montant), numéro, date et mentions légales", correct: true },
      { text: "Seulement le total", correct: false },
      { text: "Un dessin", correct: false },
    ],
    explanation: "Une facture conforme comporte des mentions obligatoires (numéro, date, TVA, identité). Une facture non conforme peut être rejetée ou sanctionnée.",
    tip: "TVA, numéro, date : mentions incontournables.",
  },
  {
    ...base, id: 'fin-te-12', type: 'technique', difficulty: 2,
    situation: "Vous vérifiez la concordance entre comptes et relevé bancaire.",
    question: "Comment s'appelle cette opération ?",
    options: [
      { text: "L'inventaire", correct: false },
      { text: "Le rapprochement bancaire", correct: true },
      { text: "La paie", correct: false },
      { text: "Le devis", correct: false },
    ],
    explanation: "Le rapprochement bancaire confronte la comptabilité au relevé de banque pour détecter écarts, oublis ou erreurs. C'est un contrôle de fiabilité essentiel.",
    tip: "Le rapprochement bancaire fiabilise la trésorerie.",
  },
  {
    ...base, id: 'fin-te-13', type: 'technique', difficulty: 3,
    situation: "On vous parle du « compte de résultat ».",
    question: "Ce qu'il présente :",
    options: [
      { text: "Le patrimoine à un instant T", correct: false },
      { text: "Les produits et charges de l'exercice (donc le bénéfice ou la perte)", correct: true },
      { text: "Le solde du compte courant", correct: false },
      { text: "La liste des salariés", correct: false },
    ],
    explanation: "Le compte de résultat retrace produits et charges sur une période et dégage le résultat (bénéfice/perte). Le bilan, lui, photographie le patrimoine à une date.",
    tip: "Compte de résultat = activité ; bilan = patrimoine.",
  },
  {
    ...base, id: 'fin-te-14', type: 'technique', difficulty: 2,
    situation: "Vous suivez les paiements clients.",
    question: "L'enjeu du recouvrement :",
    options: [
      { text: "Laisser les impayés s'accumuler", correct: false },
      { text: "Relancer les retards pour préserver la trésorerie", correct: true },
      { text: "Oublier les factures", correct: false },
      { text: "Payer à la place du client", correct: false },
    ],
    explanation: "Le suivi des encaissements et la relance des retards protègent la trésorerie, nerf de la guerre de l'entreprise. Un impayé non géré peut mettre en difficulté.",
    tip: "Une vente n'est finie qu'une fois encaissée.",
  },
  {
    ...base, id: 'fin-te-15', type: 'technique', difficulty: 2,
    situation: "On vous demande de manier de gros tableaux de données.",
    question: "La compétence attendue :",
    options: [
      { text: "Tout calculer de tête", correct: false },
      { text: "Maîtriser Excel (formules, TCD, RECHERCHEV) pour analyser efficacement", correct: true },
      { text: "Utiliser uniquement une calculatrice", correct: false },
      { text: "Éviter les tableurs", correct: false },
    ],
    explanation: "Excel reste l'outil quotidien du financier : formules, tableaux croisés dynamiques, recherches. Une bonne maîtrise fait gagner un temps considérable.",
    tip: "TCD et RECHERCHEV : indispensables en finance.",
  },
  {
    ...base, id: 'fin-te-16', type: 'technique', difficulty: 3,
    situation: "On vous parle de TVA collectée et déductible.",
    question: "Le principe :",
    options: [
      { text: "On garde toute la TVA encaissée", correct: false },
      { text: "On reverse la TVA collectée moins la TVA déductible à l'État", correct: true },
      { text: "La TVA n'existe plus", correct: false },
      { text: "On choisit le montant à payer", correct: false },
    ],
    explanation: "L'entreprise collecte la TVA sur ses ventes, déduit celle sur ses achats, et reverse la différence à l'État. Une erreur de TVA est vite sanctionnée.",
    tip: "TVA à payer = collectée − déductible.",
  },
  {
    ...base, id: 'fin-te-17', type: 'technique', difficulty: 2,
    situation: "Vous préparez un budget prévisionnel.",
    question: "Sa fonction principale :",
    options: [
      { text: "Décrire le passé", correct: false },
      { text: "Anticiper recettes et dépenses pour piloter et décider", correct: true },
      { text: "Remplacer la comptabilité", correct: false },
      { text: "Faire joli", correct: false },
    ],
    explanation: "Le budget prévisionnel projette l'activité future (recettes/dépenses) pour anticiper les besoins et piloter. C'est un outil de décision tourné vers l'avenir.",
    tip: "Le budget anticipe ; la compta enregistre.",
  },
  {
    ...base, id: 'fin-te-18', type: 'technique', difficulty: 3,
    situation: "En contrôle de gestion, on analyse un « écart ».",
    question: "De quoi s'agit-il ?",
    options: [
      { text: "La distance entre deux bureaux", correct: false },
      { text: "La différence entre le prévu (budget) et le réalisé, à expliquer", correct: true },
      { text: "Une erreur volontaire", correct: false },
      { text: "Un type de facture", correct: false },
    ],
    explanation: "L'analyse des écarts (budget vs réel) identifie les causes des dérives pour agir. C'est le cœur du contrôle de gestion.",
    tip: "Analyser l'écart, c'est comprendre pourquoi pour corriger.",
  },
  {
    ...base, id: 'fin-te-19', type: 'technique', difficulty: 2,
    situation: "On vous demande un reporting financier mensuel.",
    question: "Un bon reporting :",
    options: [
      { text: "Noyer le lecteur sous tous les chiffres", correct: false },
      { text: "Mettre en avant les indicateurs clés et les tendances, clairement", correct: true },
      { text: "Ne donner qu'un chiffre sans contexte", correct: false },
      { text: "Inventer les données manquantes", correct: false },
    ],
    explanation: "Un reporting efficace synthétise les KPI utiles à la décision (CA, marge, trésorerie, écarts) avec lisibilité. Trop de données tue l'information.",
    tip: "Mets en avant l'essentiel, pas tout.",
  },
  {
    ...base, id: 'fin-te-20', type: 'technique', difficulty: 3,
    situation: "On enregistre l'achat d'une machine coûteuse, utilisée plusieurs années.",
    question: "Le traitement comptable :",
    options: [
      { text: "Tout passer en charge la première année", correct: false },
      { text: "L'immobiliser et l'amortir sur sa durée d'utilisation", correct: true },
      { text: "Ne rien enregistrer", correct: false },
      { text: "L'enregistrer comme une vente", correct: false },
    ],
    explanation: "Un bien durable est immobilisé puis amorti sur sa durée d'usage, répartissant la charge sur les exercices. C'est un principe comptable clé.",
    tip: "Bien durable = immobilisation + amortissement.",
  },

  // ── 🎭 MISE EN SITUATION (suite) ──
  {
    ...base, id: 'fin-si-7', type: 'situation', difficulty: 3,
    context: "Le bilan doit être bouclé demain, mais un écart de 4 200 € reste inexpliqué.",
    situation: "Un écart inexpliqué bloque la clôture.",
    question: "La meilleure démarche :",
    options: [
      { text: "Forcer un ajustement pour équilibrer vite", correct: false },
      { text: "Investiguer méthodiquement (rapprochements, écritures récentes) pour trouver la cause", correct: true },
      { text: "Ignorer l'écart", correct: false },
      { text: "Masquer l'écart dans un autre compte", correct: false },
    ],
    explanation: "Un écart se résout par l'investigation rigoureuse, jamais par un ajustement arbitraire qui masque le problème. La sincérité des comptes l'exige.",
    tip: "On cherche la cause de l'écart, on ne le « bouche » pas.",
  },
  {
    ...base, id: 'fin-si-8', type: 'situation', difficulty: 2,
    situation: "Un fournisseur réclame un paiement que vous ne retrouvez pas dans vos comptes.",
    question: "La bonne réaction :",
    options: [
      { text: "Payer immédiatement sans vérifier", correct: false },
      { text: "Demander le justificatif et vérifier avant tout paiement", correct: true },
      { text: "Refuser sans explication", correct: false },
      { text: "Ignorer la relance", correct: false },
    ],
    explanation: "Avant de payer, on vérifie la réalité de la dette (facture, bon de commande, livraison). Payer sans contrôle expose aux erreurs et à la fraude.",
    tip: "Pas de paiement sans justificatif vérifié.",
  },
  {
    ...base, id: 'fin-si-9', type: 'situation', difficulty: 3,
    context: "Un commercial vous demande de comptabiliser une vente non encore réalisée pour « gonfler » le mois.",
    situation: "Pression pour anticiper une écriture.",
    question: "La bonne réponse :",
    options: [
      { text: "Accepter pour lui rendre service", correct: false },
      { text: "Refuser : on comptabilise selon la réalité et le bon exercice", correct: true },
      { text: "Le faire discrètement", correct: false },
      { text: "Antidater la facture", correct: false },
    ],
    explanation: "Le principe de séparation des exercices impose d'enregistrer chaque opération sur la bonne période, selon la réalité. Anticiper une vente fictive est une irrégularité.",
    tip: "On comptabilise le réel, sur le bon exercice.",
  },
  {
    ...base, id: 'fin-si-10', type: 'situation', difficulty: 2,
    situation: "Un justificatif manque pour une dépense déjà engagée.",
    question: "La bonne attitude :",
    options: [
      { text: "Inventer un faux justificatif", correct: false },
      { text: "Réclamer le document manquant et le tracer en attendant", correct: true },
      { text: "Ignorer la dépense", correct: false },
      { text: "Passer l'écriture sans aucune trace", correct: false },
    ],
    explanation: "Toute écriture doit s'appuyer sur une pièce justificative. On la réclame et on documente l'attente ; jamais on ne fabrique de faux.",
    tip: "Pas de pièce, pas d'écriture définitive.",
  },
  {
    ...base, id: 'fin-si-11', type: 'situation', difficulty: 2,
    situation: "La trésorerie devient tendue ce mois-ci.",
    question: "La bonne démarche :",
    options: [
      { text: "Ne rien dire et attendre", correct: false },
      { text: "Alerter, prioriser les paiements et accélérer les encaissements", correct: true },
      { text: "Tout payer d'un coup", correct: false },
      { text: "Cacher la situation", correct: false },
    ],
    explanation: "Une tension de trésorerie se gère activement : alerte précoce, priorisation des décaissements, relance des créances. L'anticipation évite la cessation de paiement.",
    tip: "Trésorerie tendue : alerter tôt et prioriser.",
  },
  {
    ...base, id: 'fin-si-12', type: 'situation', difficulty: 3,
    context: "Un email « du dirigeant » demande un virement urgent vers un nouveau compte. Le ton est pressant.",
    situation: "Tentative possible de fraude au virement.",
    question: "La bonne réaction :",
    options: [
      { text: "Virer immédiatement « car c'est urgent »", correct: false },
      { text: "Vérifier l'identité par un canal connu avant tout virement", correct: true },
      { text: "Répondre ses coordonnées bancaires", correct: false },
      { text: "Transférer l'email à tous", correct: false },
    ],
    explanation: "La fraude au président joue sur l'urgence. On applique la procédure : double vérification par un canal de confiance avant tout virement inhabituel.",
    tip: "Virement inhabituel = vérification par un canal connu.",
  },
  {
    ...base, id: 'fin-si-13', type: 'situation', difficulty: 2,
    situation: "Votre supérieur vous demande un point trésorerie « pour hier ».",
    question: "La meilleure réponse :",
    options: [
      { text: "Bâcler des chiffres approximatifs", correct: false },
      { text: "Fournir vite un état fiable des données disponibles, en signalant les réserves", correct: true },
      { text: "Refuser car c'est trop rapide", correct: false },
      { text: "Inventer un chiffre rond", correct: false },
    ],
    explanation: "Sous urgence, on privilégie la fiabilité du disponible et on précise les limites. Un chiffre faux en finance est pire que pas de chiffre.",
    tip: "Fiable et daté, avec les réserves utiles.",
  },
  {
    ...base, id: 'fin-si-14', type: 'situation', difficulty: 2,
    situation: "Un collègue vous demande l'accès au fichier des salaires « par curiosité ».",
    question: "La bonne réponse :",
    options: [
      { text: "Lui donner l'accès", correct: false },
      { text: "Refuser : donnée confidentielle réservée aux personnes habilitées", correct: true },
      { text: "Lui montrer rapidement", correct: false },
      { text: "Lui en envoyer une copie", correct: false },
    ],
    explanation: "Les rémunérations sont strictement confidentielles. L'accès est limité aux personnes habilitées et pour un motif légitime — pas la curiosité.",
    tip: "Confidentialité salariale = accès strictement réservé.",
  },
  {
    ...base, id: 'fin-si-15', type: 'situation', difficulty: 2,
    situation: "Vous découvrez une double facturation à un client.",
    question: "La bonne réaction :",
    options: [
      { text: "Laisser, le client paiera deux fois", correct: false },
      { text: "Corriger l'erreur, émettre un avoir et prévenir le client", correct: true },
      { text: "Espérer qu'il ne remarque rien", correct: false },
      { text: "Supprimer toute trace", correct: false },
    ],
    explanation: "L'honnêteté impose de corriger une erreur de facturation (avoir, régularisation) et d'en informer le client. C'est aussi une question de réputation.",
    tip: "Erreur de facturation = avoir + transparence.",
  },
  {
    ...base, id: 'fin-si-16', type: 'situation', difficulty: 3,
    context: "L'expert-comptable demande une pièce que vous ne retrouvez pas, en pleine révision des comptes.",
    situation: "Document introuvable lors d'un contrôle.",
    question: "La meilleure attitude :",
    options: [
      { text: "Fabriquer un document de remplacement", correct: false },
      { text: "Être transparent, chercher activement et proposer une preuve alternative", correct: true },
      { text: "Mentir sur son existence", correct: false },
      { text: "Ignorer la demande", correct: false },
    ],
    explanation: "Face à un contrôle, la transparence et la recherche active priment. On ne fabrique jamais de pièce ; on documente et on propose des justificatifs alternatifs.",
    tip: "Transparence totale avec l'expert-comptable et l'auditeur.",
  },
  {
    ...base, id: 'fin-si-17', type: 'situation', difficulty: 2,
    situation: "Une note de frais d'un manager semble exagérée.",
    question: "La bonne démarche :",
    options: [
      { text: "Valider sans regarder", correct: false },
      { text: "Vérifier la conformité aux règles et demander des précisions si besoin", correct: true },
      { text: "La refuser brutalement", correct: false },
      { text: "L'ignorer", correct: false },
    ],
    explanation: "Les notes de frais se contrôlent selon la politique interne, quel que soit le niveau hiérarchique. On demande des justificatifs avec tact et équité.",
    tip: "La règle s'applique à tous, managers compris.",
  },
  {
    ...base, id: 'fin-si-18', type: 'situation', difficulty: 2,
    situation: "Vous devez expliquer une baisse de marge à la direction.",
    question: "La bonne approche :",
    options: [
      { text: "Donner le chiffre sans explication", correct: false },
      { text: "Analyser les causes (coûts, prix, volumes) et proposer des pistes", correct: true },
      { text: "Cacher la baisse", correct: false },
      { text: "Blâmer un service au hasard", correct: false },
    ],
    explanation: "On ne se contente pas de constater : on explique le pourquoi (hausse des coûts, remises, mix) et on éclaire la décision. C'est le rôle d'aide au pilotage.",
    tip: "Explique les causes et propose, ne te contente pas du constat.",
  },
  {
    ...base, id: 'fin-si-19', type: 'situation', difficulty: 2,
    situation: "Un client important demande un délai de paiement supplémentaire.",
    question: "La bonne démarche :",
    options: [
      { text: "Refuser sans discussion", correct: false },
      { text: "Évaluer l'impact trésorerie et arbitrer avec le commercial/la direction", correct: true },
      { text: "Accepter tout sans condition", correct: false },
      { text: "Ignorer la demande", correct: false },
    ],
    explanation: "Un délai de paiement engage la trésorerie : on en mesure l'impact et on décide avec les parties concernées, en cadrant les conditions.",
    tip: "Un délai accordé a un coût de trésorerie : arbitre-le.",
  },
  {
    ...base, id: 'fin-si-20', type: 'situation', difficulty: 3,
    context: "En fin d'exercice, on vous suggère de « provisionner moins » pour afficher un meilleur résultat.",
    situation: "Pression sur l'évaluation des provisions.",
    question: "La bonne attitude :",
    options: [
      { text: "Sous-provisionner pour faire plaisir", correct: false },
      { text: "Provisionner selon les risques réels, conformément aux principes (prudence)", correct: true },
      { text: "Supprimer toutes les provisions", correct: false },
      { text: "Choisir un chiffre au hasard", correct: false },
    ],
    explanation: "Le principe de prudence impose de provisionner les risques connus. Minorer les provisions pour embellir le résultat fausse les comptes et trompe les tiers.",
    tip: "Principe de prudence : on provisionne les risques réels.",
  },

  // ── 📰 ACTU & TENDANCES (suite) ──
  {
    ...base, id: 'fin-ac-9', type: 'actu', difficulty: 3,
    situation: "La facturation électronique (e-invoicing) se généralise entre entreprises.",
    question: "Ce que cela change :",
    options: [
      { text: "Rien, on garde le papier", correct: false },
      { text: "L'émission/réception de factures sous format électronique normalisé via plateformes", correct: true },
      { text: "La fin des factures", correct: false },
      { text: "Le retour au fax", correct: false },
    ],
    explanation: "La réforme de la facturation électronique impose des factures dématérialisées normalisées transitant par des plateformes, avec transmission de données à l'administration. Un changement majeur pour la compta.",
    tip: "E-invoicing : facture normalisée + données à l'administration.",
  },
  {
    ...base, id: 'fin-ac-10', type: 'actu', difficulty: 2,
    situation: "L'IA et l'automatisation transforment la comptabilité.",
    question: "Un usage pertinent :",
    options: [
      { text: "Laisser l'IA valider seule les comptes", correct: false },
      { text: "Automatiser la saisie/lettrage et se concentrer sur l'analyse et le conseil", correct: true },
      { text: "Supprimer tout contrôle humain", correct: false },
      { text: "Falsifier plus vite", correct: false },
    ],
    explanation: "L'IA automatise les tâches répétitives (saisie, lettrage, rapprochements) et déplace la valeur du comptable vers l'analyse et le conseil. Le contrôle humain reste indispensable.",
    tip: "Moins de saisie, plus d'analyse : l'avenir du métier.",
  },
  {
    ...base, id: 'fin-ac-11', type: 'actu', difficulty: 2,
    situation: "Les ERP/outils cloud centralisent la gestion.",
    question: "Leur intérêt :",
    options: [
      { text: "Compliquer pour rien", correct: false },
      { text: "Centraliser données et process (compta, achats, ventes) en temps réel", correct: true },
      { text: "Remplacer les financiers", correct: false },
      { text: "Supprimer les contrôles", correct: false },
    ],
    explanation: "Les ERP intègrent les flux (achats, ventes, compta) pour une information unifiée et en temps réel, améliorant fiabilité et pilotage.",
    tip: "ERP = une seule source de données partagée.",
  },
  {
    ...base, id: 'fin-ac-12', type: 'actu', difficulty: 2,
    situation: "Le reporting extra-financier (ESG/CSRD) monte en puissance.",
    question: "Ce qu'il recouvre :",
    options: [
      { text: "Uniquement le bénéfice", correct: false },
      { text: "Des indicateurs environnementaux, sociaux et de gouvernance", correct: true },
      { text: "La météo", correct: false },
      { text: "Rien d'obligatoire jamais", correct: false },
    ],
    explanation: "Le reporting extra-financier (ESG) mesure la performance environnementale, sociale et de gouvernance, désormais encadré (CSRD) pour de nombreuses entreprises.",
    tip: "La finance intègre désormais l'ESG, pas que le profit.",
  },
  {
    ...base, id: 'fin-ac-13', type: 'actu', difficulty: 3,
    situation: "La cybersécurité est un enjeu fort en finance (fraudes).",
    question: "Le bon réflexe face à un virement suspect :",
    options: [
      { text: "Exécuter sans vérifier", correct: false },
      { text: "Appliquer la procédure de double validation et vérifier l'authenticité", correct: true },
      { text: "Communiquer les accès bancaires", correct: false },
      { text: "Désactiver les contrôles pour aller vite", correct: false },
    ],
    explanation: "Les services financiers sont des cibles privilégiées (fraude au virement, phishing). Les procédures de contrôle et la vigilance protègent l'entreprise.",
    tip: "Double validation des virements inhabituels.",
  },
  {
    ...base, id: 'fin-ac-14', type: 'actu', difficulty: 2,
    situation: "Le métier de comptable évolue vers le conseil.",
    question: "La compétence de plus en plus valorisée :",
    options: [
      { text: "Saisir le plus vite possible", correct: false },
      { text: "Analyser et conseiller à partir des chiffres (business partner)", correct: true },
      { text: "Rester cantonné à la saisie", correct: false },
      { text: "Éviter tout contact avec les opérationnels", correct: false },
    ],
    explanation: "Avec l'automatisation de la saisie, le comptable/financier devient un « business partner » qui éclaire les décisions. L'analyse et le relationnel prennent de la valeur.",
    tip: "Le financier de demain conseille, il ne fait pas que saisir.",
  },
  {
    ...base, id: 'fin-ac-15', type: 'actu', difficulty: 2,
    situation: "Les données financières sont de plus en plus analysées (data).",
    question: "L'apport de la data en finance :",
    options: [
      { text: "Aucun", correct: false },
      { text: "Mieux anticiper (prévisions, détection d'anomalies) grâce à l'analyse de données", correct: true },
      { text: "Remplacer la rigueur comptable", correct: false },
      { text: "Inventer des chiffres", correct: false },
    ],
    explanation: "L'analyse de données affine prévisions et détection d'anomalies/fraudes. Elle complète, sans la remplacer, la rigueur comptable.",
    tip: "La data renforce l'anticipation et le contrôle.",
  },
  {
    ...base, id: 'fin-ac-16', type: 'actu', difficulty: 2,
    situation: "La dématérialisation des justificatifs progresse.",
    question: "La bonne pratique :",
    options: [
      { text: "Jeter les pièces sans précaution", correct: false },
      { text: "Archiver numériquement à valeur probante, de façon sécurisée et accessible", correct: true },
      { text: "Tout garder uniquement en papier", correct: false },
      { text: "Stocker n'importe où", correct: false },
    ],
    explanation: "L'archivage électronique à valeur probante remplace progressivement le papier, sous conditions de sécurité et d'intégrité. Il fait gagner place et temps.",
    tip: "Archivage numérique sécurisé = conformité + gain de place.",
  },
  {
    ...base, id: 'fin-ac-17', type: 'actu', difficulty: 2,
    situation: "Le télétravail s'installe aussi en comptabilité.",
    question: "L'enjeu principal :",
    options: [
      { text: "Ne plus rien sécuriser", correct: false },
      { text: "Maintenir sécurité des données et fiabilité des process à distance", correct: true },
      { text: "Partager les accès librement", correct: false },
      { text: "Travailler sans aucun contrôle", correct: false },
    ],
    explanation: "Le travail à distance impose une vigilance accrue sur la sécurité des données sensibles et le maintien des contrôles internes.",
    tip: "À distance, la sécurité des données reste prioritaire.",
  },
  {
    ...base, id: 'fin-ac-18', type: 'actu', difficulty: 2,
    situation: "On vous interroge sur les crypto-actifs en entreprise.",
    question: "L'attitude prudente attendue :",
    options: [
      { text: "Investir la trésorerie sans réfléchir", correct: false },
      { text: "Connaître les risques (volatilité, fiscalité, réglementation) et rester prudent", correct: true },
      { text: "Ignorer totalement le sujet", correct: false },
      { text: "Promettre des gains garantis", correct: false },
    ],
    explanation: "Les crypto-actifs posent des questions de volatilité, de comptabilisation et de fiscalité. Le financier doit comprendre les risques et rester prudent.",
    tip: "Crypto = forte volatilité : prudence et cadre réglementaire.",
  },
  {
    ...base, id: 'fin-ac-19', type: 'actu', difficulty: 2,
    situation: "Les délais de paiement font l'objet d'une vigilance réglementaire.",
    question: "Le bon comportement :",
    options: [
      { text: "Payer les fournisseurs le plus tard possible", correct: false },
      { text: "Respecter les délais légaux de paiement (et les faire respecter)", correct: true },
      { text: "Ne jamais payer", correct: false },
      { text: "Payer au hasard", correct: false },
    ],
    explanation: "Les délais de paiement sont encadrés par la loi (LME). Les respecter évite des sanctions et préserve des relations commerciales saines.",
    tip: "Respecte les délais légaux de paiement.",
  },
  {
    ...base, id: 'fin-ac-20', type: 'actu', difficulty: 1,
    situation: "On vous demande votre niveau sur les outils en entretien finance.",
    question: "La meilleure réponse :",
    options: [
      { text: "« Je connais tout »", correct: false },
      { text: "Préciser honnêtement (Excel, logiciel compta, ERP) avec des exemples d'usage", correct: true },
      { text: "« Je n'aime pas les logiciels »", correct: false },
      { text: "Mentir sur sa maîtrise", correct: false },
    ],
    explanation: "On attend une auto-évaluation honnête et illustrée (quels outils, quel niveau, pour quoi). Un mensonge se révèle vite à l'épreuve du poste.",
    tip: "Illustre ton niveau d'outil par un usage concret.",
  },
];
