/**
 * Secteur « Marketing / Communication » — parcours (4 couches).
 *
 * sector:'marketing', type ∈ {comportemental, technique, situation, actu}.
 * Une seule option correct:true, + explanation + tip. `context` optionnel.
 */
const base = { sector: 'marketing' };

export default [
  // ══════════════ 🧠 COMPORTEMENTAL ══════════════
  {
    ...base, id: 'mkt-cp-1', type: 'comportemental', difficulty: 1,
    situation: "« Pourquoi le marketing / la communication vous attire-t-il ? »",
    question: "La motivation la plus crédible :",
    options: [
      { text: "« Pour faire de jolis visuels toute la journée »", correct: false },
      { text: "Allier créativité et stratégie pour faire connaître et vendre une offre", correct: true },
      { text: "« Parce que c'est facile »", correct: false },
      { text: "« Pour être célèbre sur les réseaux »", correct: false },
    ],
    explanation: "Le marketing mêle créativité ET stratégie orientée résultats. On valorise l'envie de comprendre une cible et de générer de l'impact, pas seulement « faire du beau ».",
    tip: "Montre que tu relies créativité et objectifs business.",
  },
  {
    ...base, id: 'mkt-cp-2', type: 'comportemental', difficulty: 2,
    situation: "« Créativité ou analyse de données : que privilégiez-vous ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« La créativité seule, les chiffres m'ennuient »", correct: false },
      { text: "Les deux : la créativité propose, la donnée valide et optimise", correct: true },
      { text: "« Les chiffres seuls, la créa ne sert à rien »", correct: false },
      { text: "« Ni l'un ni l'autre »", correct: false },
    ],
    explanation: "Le marketing moderne est « data-créatif » : on imagine, puis on mesure et on ajuste. Opposer créa et data est dépassé ; les meilleurs combinent les deux.",
    tip: "« Créer puis mesurer » : la posture gagnante.",
  },
  {
    ...base, id: 'mkt-cp-3', type: 'comportemental', difficulty: 2,
    situation: "Un de vos visuels est critiqué par le client ou la direction.",
    question: "La meilleure attitude :",
    options: [
      { text: "Se vexer et défendre sa création coûte que coûte", correct: false },
      { text: "Écouter le retour, questionner l'objectif et ajuster sans ego", correct: true },
      { text: "Refaire au hasard sans comprendre", correct: false },
      { text: "Abandonner le projet", correct: false },
    ],
    explanation: "En création, le feedback fait partie du jeu. On sépare l'ego du travail : on cherche à comprendre l'objectif et on itère. La maturité prime sur la susceptibilité.",
    tip: "Un bon créatif accueille le feedback sans se braquer.",
  },
  {
    ...base, id: 'mkt-cp-4', type: 'comportemental', difficulty: 2,
    situation: "« Comment gérez-vous les deadlines serrées de campagne ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Je travaille mieux dans la panique de dernière minute »", correct: false },
      { text: "Je planifie en amont, je rétro-planne et je garde une marge", correct: true },
      { text: "« Je rends en retard, ce n'est pas grave »", correct: false },
      { text: "« J'ignore les délais »", correct: false },
    ],
    explanation: "Le marketing vit au rythme des lancements. La capacité à planifier (rétroplanning) et tenir les délais sans sacrifier la qualité est très recherchée.",
    tip: "Parle de rétroplanning : ça rassure sur ta fiabilité.",
  },
  {
    ...base, id: 'mkt-cp-5', type: 'comportemental', difficulty: 2,
    situation: "« Le marketing évolue très vite. Comment restez-vous à jour ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Je ne fais pas de veille »", correct: false },
      { text: "Veille régulière : tendances, outils, concurrents, formats émergents", correct: true },
      { text: "« J'attends qu'on me forme »", correct: false },
      { text: "« Le marketing ne change jamais »", correct: false },
    ],
    explanation: "Curiosité et veille sont vitales dans un secteur qui bouge en permanence (IA, formats, plateformes). Montrer une routine de veille est un vrai signal positif.",
    tip: "Cite tes sources de veille : newsletters, comptes, blogs.",
  },
  {
    ...base, id: 'mkt-cp-6', type: 'comportemental', difficulty: 2,
    situation: "Le marketing travaille avec la vente, la direction, la technique…",
    question: "Quelle qualité est clé dans ce rôle transverse ?",
    options: [
      { text: "Travailler seul dans son coin", correct: false },
      { text: "Savoir collaborer et communiquer avec des interlocuteurs variés", correct: true },
      { text: "Imposer ses idées sans écouter", correct: false },
      { text: "Éviter les autres services", correct: false },
    ],
    explanation: "Le marketing est par nature transverse. Savoir dialoguer avec les ventes, la direction ou la technique et aligner tout le monde est une compétence centrale.",
    tip: "Mets en avant ton sens de la collaboration transverse.",
  },

  // ══════════════ 🛠️ TECHNIQUE MÉTIER ══════════════
  {
    ...base, id: 'mkt-te-1', type: 'technique', difficulty: 1,
    situation: "Notions de base.",
    question: "Quelle est la différence entre marketing et communication ?",
    options: [
      { text: "Ce sont des synonymes", correct: false },
      { text: "Le marketing définit l'offre et la stratégie ; la com diffuse le message", correct: true },
      { text: "La com s'occupe des ventes uniquement", correct: false },
      { text: "Le marketing ne sert qu'aux grandes entreprises", correct: false },
    ],
    explanation: "Le marketing analyse le marché et bâtit l'offre/la stratégie (produit, prix, cible) ; la communication porte le message vers le public. Complémentaires mais distincts.",
    tip: "Marketing = stratégie ; communication = diffusion.",
  },
  {
    ...base, id: 'mkt-te-2', type: 'technique', difficulty: 2,
    situation: "Référencement.",
    question: "Qu'est-ce que le SEO ?",
    options: [
      { text: "De la publicité payante", correct: false },
      { text: "L'optimisation pour apparaître haut dans les résultats naturels des moteurs de recherche", correct: true },
      { text: "Un réseau social", correct: false },
      { text: "Un logiciel de design", correct: false },
    ],
    explanation: "Le SEO (référencement naturel) vise à être bien positionné gratuitement sur Google via le contenu, les mots-clés et la technique. À distinguer du SEA (payant).",
    tip: "SEO = naturel/gratuit ; SEA = payant (Google Ads).",
  },
  {
    ...base, id: 'mkt-te-3', type: 'technique', difficulty: 2,
    situation: "Parcours client.",
    question: "Qu'est-ce qu'un « tunnel de conversion » (funnel) ?",
    options: [
      { text: "Un outil de design", correct: false },
      { text: "Le parcours du prospect, de la découverte jusqu'à l'achat (et la fidélisation)", correct: true },
      { text: "Un type de publicité TV", correct: false },
      { text: "Une réunion d'équipe", correct: false },
    ],
    explanation: "Le funnel décrit les étapes : notoriété → intérêt → considération → conversion → fidélité. L'analyser permet de repérer où l'on perd des prospects.",
    tip: "TOFU / MOFU / BOFU = haut, milieu, bas de tunnel.",
  },
  {
    ...base, id: 'mkt-te-4', type: 'technique', difficulty: 2,
    situation: "Connaissance de l'audience.",
    question: "Qu'est-ce qu'un « persona » ?",
    options: [
      { text: "Un vrai client unique", correct: false },
      { text: "Un portrait-type représentant un segment de cible (besoins, freins, habitudes)", correct: true },
      { text: "Un logiciel marketing", correct: false },
      { text: "Le nom d'une campagne", correct: false },
    ],
    explanation: "Le persona est une représentation fictive mais réaliste d'un client cible. Il guide les messages, les canaux et le ton. Mal cibler, c'est gaspiller son budget.",
    tip: "Bien connaître son persona = des messages qui touchent juste.",
  },
  {
    ...base, id: 'mkt-te-5', type: 'technique', difficulty: 3,
    situation: "Mesure de la performance.",
    question: "Que mesure le « taux de conversion » ?",
    options: [
      { text: "Le nombre de likes", correct: false },
      { text: "La part de visiteurs ayant réalisé l'action voulue (achat, inscription…)", correct: true },
      { text: "Le nombre d'abonnés", correct: false },
      { text: "La durée d'une vidéo", correct: false },
    ],
    explanation: "Le taux de conversion rapporte les actions réalisées au nombre de visiteurs. C'est un KPI central, plus parlant que les seuls « likes » (vanity metrics).",
    tip: "Distingue vanity metrics (likes) et vrais KPI (conversion, ROI).",
  },
  {
    ...base, id: 'mkt-te-6', type: 'technique', difficulty: 2,
    situation: "Acquisition payante.",
    question: "Que désigne le « SEA » ?",
    options: [
      { text: "Le référencement naturel", correct: false },
      { text: "La publicité payante sur les moteurs de recherche (ex : Google Ads)", correct: true },
      { text: "Un réseau social", correct: false },
      { text: "Un logiciel de mailing", correct: false },
    ],
    explanation: "Le SEA (Search Engine Advertising) achète de la visibilité sur les moteurs, souvent au coût par clic (CPC). Il complète le SEO pour des résultats rapides.",
    tip: "SEA = résultats rapides mais payants au clic.",
  },
  {
    ...base, id: 'mkt-te-7', type: 'technique', difficulty: 2,
    situation: "Stratégie de contenu.",
    question: "Quel est le principe de l'« inbound marketing » ?",
    options: [
      { text: "Harceler les prospects par téléphone", correct: false },
      { text: "Attirer le client avec du contenu utile plutôt que de le solliciter de force", correct: true },
      { text: "Acheter des listes d'emails", correct: false },
      { text: "Faire uniquement de la pub TV", correct: false },
    ],
    explanation: "L'inbound attire naturellement via du contenu de valeur (articles, guides, vidéos) qui répond aux besoins de la cible. Le prospect vient à soi.",
    tip: "Inbound = créer de la valeur pour attirer, pas interrompre.",
  },
  {
    ...base, id: 'mkt-te-8', type: 'technique', difficulty: 2,
    situation: "Email marketing.",
    question: "Que mesure le « taux d'ouverture » d'une newsletter ?",
    options: [
      { text: "Le nombre d'emails envoyés", correct: false },
      { text: "La part de destinataires ayant ouvert l'email", correct: true },
      { text: "Le nombre de désabonnements", correct: false },
      { text: "Le poids du fichier", correct: false },
    ],
    explanation: "Le taux d'ouverture (ouvertures / envois délivrés) reflète surtout l'efficacité de l'objet et la qualité de la base. Le taux de clic mesure ensuite l'engagement.",
    tip: "L'objet fait le taux d'ouverture ; le contenu fait le clic.",
  },
  {
    ...base, id: 'mkt-te-9', type: 'technique', difficulty: 2,
    situation: "Réseaux sociaux.",
    question: "Quelle est la différence entre portée « organique » et « payante » ?",
    options: [
      { text: "Organique = gratuite (sans pub) ; payante = via budget publicitaire", correct: true },
      { text: "Organique = sur mobile ; payante = sur ordinateur", correct: false },
      { text: "Ce sont des synonymes", correct: false },
      { text: "Organique = en vidéo ; payante = en photo", correct: false },
    ],
    explanation: "La portée organique vient des publications non sponsorisées ; la payante est obtenue via de la publicité. Les deux sont complémentaires dans une stratégie sociale.",
    tip: "Stratégie social media = mix organique + payant.",
  },

  // ══════════════ 🎭 MISE EN SITUATION ══════════════
  {
    ...base, id: 'mkt-si-1', type: 'situation', difficulty: 3,
    context: "Un post de la marque déclenche un flot de commentaires négatifs : c'est le début d'un bad buzz.",
    situation: "Bad buzz naissant sur les réseaux.",
    question: "La meilleure réaction :",
    options: [
      { text: "Supprimer le post en cachette et faire comme si de rien n'était", correct: false },
      { text: "Analyser vite, répondre avec transparence et, si erreur, l'assumer", correct: true },
      { text: "Répondre agressivement aux internautes", correct: false },
      { text: "Ignorer totalement et laisser enfler", correct: false },
    ],
    explanation: "Face à un bad buzz : réactivité, transparence et ton mesuré. Supprimer en douce ou s'énerver aggrave. Reconnaître une erreur sincèrement désamorce souvent la crise.",
    tip: "Transparence + réactivité > silence ou suppression.",
  },
  {
    ...base, id: 'mkt-si-2', type: 'situation', difficulty: 2,
    context: "Budget de communication limité. Vous devez choisir où le concentrer.",
    situation: "Arbitrage budgétaire entre canaux.",
    question: "La meilleure approche :",
    options: [
      { text: "Répartir un peu partout au hasard", correct: false },
      { text: "Prioriser les canaux où se trouve la cible et qui ont prouvé leur ROI", correct: true },
      { text: "Tout mettre sur le canal à la mode sans réfléchir", correct: false },
      { text: "Ne rien dépenser", correct: false },
    ],
    explanation: "Avec un budget serré, on concentre sur les canaux où la cible est présente et performants (ROI mesuré), plutôt que de saupoudrer. La donnée guide l'arbitrage.",
    tip: "Va là où est ta cible, pas où est la hype.",
  },
  {
    ...base, id: 'mkt-si-3', type: 'situation', difficulty: 2,
    context: "Votre responsable veut « un visuel qui claque » pour demain, sans plus de précisions.",
    situation: "Brief créatif trop vague.",
    question: "Le bon réflexe :",
    options: [
      { text: "Foncer sans poser de questions", correct: false },
      { text: "Reformuler le besoin : objectif, cible, message, support, contraintes", correct: true },
      { text: "Copier un visuel d'un concurrent", correct: false },
      { text: "Refuser la tâche", correct: false },
    ],
    explanation: "Sans brief clair, on produit à l'aveugle. Reformuler l'objectif, la cible et le message évite les allers-retours et garantit un résultat utile.",
    tip: "Pas de bon visuel sans bon brief : pose les questions.",
  },
  {
    ...base, id: 'mkt-si-4', type: 'situation', difficulty: 3,
    context: "Une campagne publicitaire en cours ne génère presque aucune conversion.",
    situation: "Campagne qui sous-performe.",
    question: "La meilleure démarche :",
    options: [
      { text: "Attendre la fin sans rien changer", correct: false },
      { text: "Analyser les données (ciblage, message, page d'arrivée) et tester des ajustements", correct: true },
      { text: "Doubler le budget sans rien changer", correct: false },
      { text: "Arrêter tout le marketing", correct: false },
    ],
    explanation: "On diagnostique : le ciblage est-il bon ? le message ? la landing page ? Puis on teste (A/B). Le marketing data-driven optimise en continu plutôt que de subir.",
    tip: "Mesurer, identifier le maillon faible, tester, recommencer.",
  },
  {
    ...base, id: 'mkt-si-5', type: 'situation', difficulty: 2,
    context: "Un internaute laisse un commentaire négatif mais légitime sous une publication de la marque.",
    situation: "Commentaire négatif public.",
    question: "La meilleure réponse en community management :",
    options: [
      { text: "Supprimer le commentaire", correct: false },
      { text: "Répondre poliment, publiquement, et proposer de régler le problème", correct: true },
      { text: "Répondre avec ironie", correct: false },
      { text: "Bloquer la personne", correct: false },
    ],
    explanation: "Une réponse publique, calme et orientée solution montre que la marque écoute. Supprimer ou ironiser nuit à l'image. On peut basculer en privé pour les détails.",
    tip: "Réponse publique + solution = image soignée.",
  },
  {
    ...base, id: 'mkt-si-6', type: 'situation', difficulty: 3,
    context: "Un influenceur partenaire publie un contenu maladroit qui ne respecte pas le brief et choque une partie de l'audience.",
    situation: "Dérapage d'un influenceur partenaire.",
    question: "La meilleure réaction :",
    options: [
      { text: "Faire comme si tout allait bien", correct: false },
      { text: "Échanger rapidement avec lui pour corriger/retirer et clarifier le cadre", correct: true },
      { text: "L'insulter publiquement", correct: false },
      { text: "Diffuser encore plus le contenu", correct: false },
    ],
    explanation: "On gère vite et professionnellement : contact direct, correction ou retrait, rappel du cadre. La marque reste responsable de ce que publient ses partenaires.",
    tip: "Cadre clair en amont, réaction rapide en cas de dérapage.",
  },
  {
    ...base, id: 'mkt-si-7', type: 'situation', difficulty: 3,
    context: "🏆 BOSS — On te confie le lancement d'une nouvelle offre. Tu pars d'une page blanche.",
    situation: "Construire une campagne de A à Z.",
    question: "Dans quel ordre raisonner ?",
    options: [
      { text: "Choisir un visuel d'abord, réfléchir au reste après", correct: false },
      { text: "Objectif → cible → message → canaux → budget → mesure", correct: true },
      { text: "Publier partout puis voir ce qui marche", correct: false },
      { text: "Copier la campagne d'un concurrent", correct: false },
    ],
    explanation: "Une campagne se construit dans l'ordre : fixer l'objectif, définir la cible, bâtir le message, choisir les canaux, allouer le budget et prévoir la mesure. Le visuel vient après la stratégie.",
    tip: "La stratégie d'abord, l'exécution ensuite.",
  },

  // ══════════════ 📰 ACTU & TENDANCES (2026) ══════════════
  {
    ...base, id: 'mkt-ac-1', type: 'actu', difficulty: 3,
    situation: "L'IA dans le marketing.",
    question: "Quel est l'enjeu de l'IA générative pour le contenu marketing ?",
    options: [
      { text: "Elle rend le marketing inutile", correct: false },
      { text: "Produire plus vite, tout en gardant authenticité, justesse et contrôle humain", correct: true },
      { text: "Publier sans jamais relire", correct: false },
      { text: "Elle ne sert qu'au design", correct: false },
    ],
    explanation: "L'IA accélère la production (textes, visuels, idées) mais pose la question de l'authenticité et de la qualité. Le marketeur la pilote et garde l'œil critique.",
    tip: "L'IA assiste la création ; l'humain garde la direction.",
  },
  {
    ...base, id: 'mkt-ac-2', type: 'actu', difficulty: 3,
    situation: "Évolution du référencement.",
    question: "Que désigne le « GEO » (Generative Engine Optimization) ?",
    options: [
      { text: "La géolocalisation des clients", correct: false },
      { text: "Optimiser sa présence pour être cité par les moteurs de réponse IA", correct: true },
      { text: "Un nouveau réseau social", correct: false },
      { text: "Un format de fichier", correct: false },
    ],
    explanation: "Avec les réponses générées par IA (ChatGPT, recherches IA), le GEO complète le SEO : être visible et cité dans les réponses des moteurs génératifs devient un nouvel enjeu.",
    tip: "Le SEO évolue vers le GEO à l'ère des réponses IA.",
  },
  {
    ...base, id: 'mkt-ac-3', type: 'actu', difficulty: 2,
    situation: "Formats de contenu.",
    question: "Pourquoi la vidéo courte (Reels, TikTok, Shorts) est-elle incontournable ?",
    options: [
      { text: "Elle ne touche personne", correct: false },
      { text: "Elle capte fortement l'attention et est poussée par les algorithmes", correct: true },
      { text: "Elle est interdite aux marques", correct: false },
      { text: "Elle coûte toujours très cher", correct: false },
    ],
    explanation: "La vidéo courte domine l'engagement et la portée organique. Couplée à l'UGC (contenu créé par les utilisateurs), c'est un levier majeur en 2026.",
    tip: "Pense « vidéo courte + UGC » pour la portée.",
  },
  {
    ...base, id: 'mkt-ac-4', type: 'actu', difficulty: 3,
    situation: "Données et vie privée.",
    question: "Quelle conséquence a la fin des cookies tiers ?",
    options: [
      { text: "Aucune", correct: false },
      { text: "Les marques misent sur la « first-party data » (données collectées directement et consenties)", correct: true },
      { text: "Le marketing digital disparaît", correct: false },
      { text: "On peut suivre les gens sans limite", correct: false },
    ],
    explanation: "La disparition des cookies tiers pousse à collecter ses propres données (newsletter, compte client) avec consentement. La first-party data devient un actif stratégique.",
    tip: "First-party data = l'or du marketing post-cookies.",
  },
  {
    ...base, id: 'mkt-ac-5', type: 'actu', difficulty: 2,
    situation: "Marketing d'influence.",
    question: "Pourquoi les « nano » et « micro-influenceurs » montent-ils ?",
    options: [
      { text: "Ils n'ont aucun intérêt", correct: false },
      { text: "Audience plus petite mais très engagée et authentique, à moindre coût", correct: true },
      { text: "Ils coûtent toujours plus cher que les stars", correct: false },
      { text: "Ils sont interdits", correct: false },
    ],
    explanation: "Les petits influenceurs offrent une communauté de niche, engagée et crédible, souvent plus rentable qu'une grosse star. L'authenticité prime sur la taille.",
    tip: "Engagement et authenticité > nombre d'abonnés.",
  },
  {
    ...base, id: 'mkt-ac-6', type: 'actu', difficulty: 2,
    situation: "Responsabilité des marques.",
    question: "Qu'est-ce que le « greenwashing » qu'il faut éviter ?",
    options: [
      { text: "Une technique de design écolo", correct: false },
      { text: "Se prétendre écoresponsable sans preuves réelles — risqué juridiquement et réputationnel", correct: true },
      { text: "Recycler ses visuels", correct: false },
      { text: "Une couleur de charte graphique", correct: false },
    ],
    explanation: "Le greenwashing (allégations écologiques trompeuses) est de plus en plus sanctionné et détecté par le public. Le marketing responsable exige des preuves et de la sincérité.",
    tip: "Pas d'allégation écolo sans preuve : sinon, greenwashing.",
  },
  {
    ...base, id: 'mkt-ac-7', type: 'actu', difficulty: 2,
    situation: "Expérience client.",
    question: "Qu'apporte la « personnalisation » dans le marketing ?",
    options: [
      { text: "Rien d'utile", correct: false },
      { text: "Adapter messages et offres à chaque profil grâce à la donnée, pour plus de pertinence", correct: true },
      { text: "Envoyer le même message à tous", correct: false },
      { text: "Supprimer toute communication", correct: false },
    ],
    explanation: "Grâce à la data, on personnalise les messages (recommandations, segmentation, automation). Bien faite et respectueuse de la vie privée, elle booste l'engagement.",
    tip: "Personnalisation pertinente = plus d'engagement (sans être intrusif).",
  },
  {
    ...base, id: 'mkt-ac-8', type: 'actu', difficulty: 2,
    situation: "Nouveaux modes d'achat.",
    question: "Que désigne le « social commerce » ?",
    options: [
      { text: "Vendre uniquement en boutique physique", correct: false },
      { text: "Acheter directement depuis les réseaux sociaux (live shopping, boutiques intégrées)", correct: true },
      { text: "Échanger des produits entre amis", correct: false },
      { text: "Un type de comptabilité", correct: false },
    ],
    explanation: "Le social commerce fond l'inspiration et l'achat dans les réseaux (boutiques Instagram/TikTok, live shopping). Le parcours d'achat se raccourcit fortement.",
    tip: "Réduire le parcours d'achat : tendance forte du social commerce.",
  },
];
