/**
 * Secteur « Marketing / Communication » — parcours (4 couches).
 *
 * sector:'marketing', type ∈ {comportemental, technique, situation, actu}.
 * Une seule option correct:true, + explanation + tip. `context` optionnel.
 */
const base = { sector: 'marketing' };

export default [
  // ══════════════ 🧠 COMPORTEMENTAL ══════════════
  {
    ...base, id: 'mkt-cp-1', type: 'comportemental', difficulty: 1,
    situation: "« Pourquoi le marketing / la communication vous attire-t-il ? »",
    question: "La motivation la plus crédible :",
    options: [
      { text: "« Pour faire de jolis visuels toute la journée »", correct: false },
      { text: "Allier créativité et stratégie pour faire connaître et vendre une offre", correct: true },
      { text: "« Parce que c'est facile »", correct: false },
      { text: "« Pour être célèbre sur les réseaux »", correct: false },
    ],
    explanation: "Le marketing mêle créativité ET stratégie orientée résultats. On valorise l'envie de comprendre une cible et de générer de l'impact, pas seulement « faire du beau ».",
    tip: "Montre que tu relies créativité et objectifs business.",
  },
  {
    ...base, id: 'mkt-cp-2', type: 'comportemental', difficulty: 2,
    situation: "« Créativité ou analyse de données : que privilégiez-vous ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« La créativité seule, les chiffres m'ennuient »", correct: false },
      { text: "Les deux : la créativité propose, la donnée valide et optimise", correct: true },
      { text: "« Les chiffres seuls, la créa ne sert à rien »", correct: false },
      { text: "« Ni l'un ni l'autre »", correct: false },
    ],
    explanation: "Le marketing moderne est « data-créatif » : on imagine, puis on mesure et on ajuste. Opposer créa et data est dépassé ; les meilleurs combinent les deux.",
    tip: "« Créer puis mesurer » : la posture gagnante.",
  },
  {
    ...base, id: 'mkt-cp-3', type: 'comportemental', difficulty: 2,
    situation: "Un de vos visuels est critiqué par le client ou la direction.",
    question: "La meilleure attitude :",
    options: [
      { text: "Se vexer et défendre sa création coûte que coûte", correct: false },
      { text: "Écouter le retour, questionner l'objectif et ajuster sans ego", correct: true },
      { text: "Refaire au hasard sans comprendre", correct: false },
      { text: "Abandonner le projet", correct: false },
    ],
    explanation: "En création, le feedback fait partie du jeu. On sépare l'ego du travail : on cherche à comprendre l'objectif et on itère. La maturité prime sur la susceptibilité.",
    tip: "Un bon créatif accueille le feedback sans se braquer.",
  },
  {
    ...base, id: 'mkt-cp-4', type: 'comportemental', difficulty: 2,
    situation: "« Comment gérez-vous les deadlines serrées de campagne ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Je travaille mieux dans la panique de dernière minute »", correct: false },
      { text: "Je planifie en amont, je rétro-planne et je garde une marge", correct: true },
      { text: "« Je rends en retard, ce n'est pas grave »", correct: false },
      { text: "« J'ignore les délais »", correct: false },
    ],
    explanation: "Le marketing vit au rythme des lancements. La capacité à planifier (rétroplanning) et tenir les délais sans sacrifier la qualité est très recherchée.",
    tip: "Parle de rétroplanning : ça rassure sur ta fiabilité.",
  },
  {
    ...base, id: 'mkt-cp-5', type: 'comportemental', difficulty: 2,
    situation: "« Le marketing évolue très vite. Comment restez-vous à jour ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Je ne fais pas de veille »", correct: false },
      { text: "Veille régulière : tendances, outils, concurrents, formats émergents", correct: true },
      { text: "« J'attends qu'on me forme »", correct: false },
      { text: "« Le marketing ne change jamais »", correct: false },
    ],
    explanation: "Curiosité et veille sont vitales dans un secteur qui bouge en permanence (IA, formats, plateformes). Montrer une routine de veille est un vrai signal positif.",
    tip: "Cite tes sources de veille : newsletters, comptes, blogs.",
  },
  {
    ...base, id: 'mkt-cp-6', type: 'comportemental', difficulty: 2,
    situation: "Le marketing travaille avec la vente, la direction, la technique…",
    question: "Quelle qualité est clé dans ce rôle transverse ?",
    options: [
      { text: "Travailler seul dans son coin", correct: false },
      { text: "Savoir collaborer et communiquer avec des interlocuteurs variés", correct: true },
      { text: "Imposer ses idées sans écouter", correct: false },
      { text: "Éviter les autres services", correct: false },
    ],
    explanation: "Le marketing est par nature transverse. Savoir dialoguer avec les ventes, la direction ou la technique et aligner tout le monde est une compétence centrale.",
    tip: "Mets en avant ton sens de la collaboration transverse.",
  },

  // ══════════════ 🛠️ TECHNIQUE MÉTIER ══════════════
  {
    ...base, id: 'mkt-te-1', type: 'technique', difficulty: 1,
    situation: "Notions de base.",
    question: "Quelle est la différence entre marketing et communication ?",
    options: [
      { text: "Ce sont des synonymes", correct: false },
      { text: "Le marketing définit l'offre et la stratégie ; la com diffuse le message", correct: true },
      { text: "La com s'occupe des ventes uniquement", correct: false },
      { text: "Le marketing ne sert qu'aux grandes entreprises", correct: false },
    ],
    explanation: "Le marketing analyse le marché et bâtit l'offre/la stratégie (produit, prix, cible) ; la communication porte le message vers le public. Complémentaires mais distincts.",
    tip: "Marketing = stratégie ; communication = diffusion.",
  },
  {
    ...base, id: 'mkt-te-2', type: 'technique', difficulty: 2,
    situation: "Référencement.",
    question: "Qu'est-ce que le SEO ?",
    options: [
      { text: "De la publicité payante", correct: false },
      { text: "L'optimisation pour apparaître haut dans les résultats naturels des moteurs de recherche", correct: true },
      { text: "Un réseau social", correct: false },
      { text: "Un logiciel de design", correct: false },
    ],
    explanation: "Le SEO (référencement naturel) vise à être bien positionné gratuitement sur Google via le contenu, les mots-clés et la technique. À distinguer du SEA (payant).",
    tip: "SEO = naturel/gratuit ; SEA = payant (Google Ads).",
  },
  {
    ...base, id: 'mkt-te-3', type: 'technique', difficulty: 2,
    situation: "Parcours client.",
    question: "Qu'est-ce qu'un « tunnel de conversion » (funnel) ?",
    options: [
      { text: "Un outil de design", correct: false },
      { text: "Le parcours du prospect, de la découverte jusqu'à l'achat (et la fidélisation)", correct: true },
      { text: "Un type de publicité TV", correct: false },
      { text: "Une réunion d'équipe", correct: false },
    ],
    explanation: "Le funnel décrit les étapes : notoriété → intérêt → considération → conversion → fidélité. L'analyser permet de repérer où l'on perd des prospects.",
    tip: "TOFU / MOFU / BOFU = haut, milieu, bas de tunnel.",
  },
  {
    ...base, id: 'mkt-te-4', type: 'technique', difficulty: 2,
    situation: "Connaissance de l'audience.",
    question: "Qu'est-ce qu'un « persona » ?",
    options: [
      { text: "Un vrai client unique", correct: false },
      { text: "Un portrait-type représentant un segment de cible (besoins, freins, habitudes)", correct: true },
      { text: "Un logiciel marketing", correct: false },
      { text: "Le nom d'une campagne", correct: false },
    ],
    explanation: "Le persona est une représentation fictive mais réaliste d'un client cible. Il guide les messages, les canaux et le ton. Mal cibler, c'est gaspiller son budget.",
    tip: "Bien connaître son persona = des messages qui touchent juste.",
  },
  {
    ...base, id: 'mkt-te-5', type: 'technique', difficulty: 3,
    situation: "Mesure de la performance.",
    question: "Que mesure le « taux de conversion » ?",
    options: [
      { text: "Le nombre de likes", correct: false },
      { text: "La part de visiteurs ayant réalisé l'action voulue (achat, inscription…)", correct: true },
      { text: "Le nombre d'abonnés", correct: false },
      { text: "La durée d'une vidéo", correct: false },
    ],
    explanation: "Le taux de conversion rapporte les actions réalisées au nombre de visiteurs. C'est un KPI central, plus parlant que les seuls « likes » (vanity metrics).",
    tip: "Distingue vanity metrics (likes) et vrais KPI (conversion, ROI).",
  },
  {
    ...base, id: 'mkt-te-6', type: 'technique', difficulty: 2,
    situation: "Acquisition payante.",
    question: "Que désigne le « SEA » ?",
    options: [
      { text: "Le référencement naturel", correct: false },
      { text: "La publicité payante sur les moteurs de recherche (ex : Google Ads)", correct: true },
      { text: "Un réseau social", correct: false },
      { text: "Un logiciel de mailing", correct: false },
    ],
    explanation: "Le SEA (Search Engine Advertising) achète de la visibilité sur les moteurs, souvent au coût par clic (CPC). Il complète le SEO pour des résultats rapides.",
    tip: "SEA = résultats rapides mais payants au clic.",
  },
  {
    ...base, id: 'mkt-te-7', type: 'technique', difficulty: 2,
    situation: "Stratégie de contenu.",
    question: "Quel est le principe de l'« inbound marketing » ?",
    options: [
      { text: "Harceler les prospects par téléphone", correct: false },
      { text: "Attirer le client avec du contenu utile plutôt que de le solliciter de force", correct: true },
      { text: "Acheter des listes d'emails", correct: false },
      { text: "Faire uniquement de la pub TV", correct: false },
    ],
    explanation: "L'inbound attire naturellement via du contenu de valeur (articles, guides, vidéos) qui répond aux besoins de la cible. Le prospect vient à soi.",
    tip: "Inbound = créer de la valeur pour attirer, pas interrompre.",
  },
  {
    ...base, id: 'mkt-te-8', type: 'technique', difficulty: 2,
    situation: "Email marketing.",
    question: "Que mesure le « taux d'ouverture » d'une newsletter ?",
    options: [
      { text: "Le nombre d'emails envoyés", correct: false },
      { text: "La part de destinataires ayant ouvert l'email", correct: true },
      { text: "Le nombre de désabonnements", correct: false },
      { text: "Le poids du fichier", correct: false },
    ],
    explanation: "Le taux d'ouverture (ouvertures / envois délivrés) reflète surtout l'efficacité de l'objet et la qualité de la base. Le taux de clic mesure ensuite l'engagement.",
    tip: "L'objet fait le taux d'ouverture ; le contenu fait le clic.",
  },
  {
    ...base, id: 'mkt-te-9', type: 'technique', difficulty: 2,
    situation: "Réseaux sociaux.",
    question: "Quelle est la différence entre portée « organique » et « payante » ?",
    options: [
      { text: "Organique = gratuite (sans pub) ; payante = via budget publicitaire", correct: true },
      { text: "Organique = sur mobile ; payante = sur ordinateur", correct: false },
      { text: "Ce sont des synonymes", correct: false },
      { text: "Organique = en vidéo ; payante = en photo", correct: false },
    ],
    explanation: "La portée organique vient des publications non sponsorisées ; la payante est obtenue via de la publicité. Les deux sont complémentaires dans une stratégie sociale.",
    tip: "Stratégie social media = mix organique + payant.",
  },

  // ══════════════ 🎭 MISE EN SITUATION ══════════════
  {
    ...base, id: 'mkt-si-1', type: 'situation', difficulty: 3,
    context: "Un post de la marque déclenche un flot de commentaires négatifs : c'est le début d'un bad buzz.",
    situation: "Bad buzz naissant sur les réseaux.",
    question: "La meilleure réaction :",
    options: [
      { text: "Supprimer le post en cachette et faire comme si de rien n'était", correct: false },
      { text: "Analyser vite, répondre avec transparence et, si erreur, l'assumer", correct: true },
      { text: "Répondre agressivement aux internautes", correct: false },
      { text: "Ignorer totalement et laisser enfler", correct: false },
    ],
    explanation: "Face à un bad buzz : réactivité, transparence et ton mesuré. Supprimer en douce ou s'énerver aggrave. Reconnaître une erreur sincèrement désamorce souvent la crise.",
    tip: "Transparence + réactivité > silence ou suppression.",
  },
  {
    ...base, id: 'mkt-si-2', type: 'situation', difficulty: 2,
    context: "Budget de communication limité. Vous devez choisir où le concentrer.",
    situation: "Arbitrage budgétaire entre canaux.",
    question: "La meilleure approche :",
    options: [
      { text: "Répartir un peu partout au hasard", correct: false },
      { text: "Prioriser les canaux où se trouve la cible et qui ont prouvé leur ROI", correct: true },
      { text: "Tout mettre sur le canal à la mode sans réfléchir", correct: false },
      { text: "Ne rien dépenser", correct: false },
    ],
    explanation: "Avec un budget serré, on concentre sur les canaux où la cible est présente et performants (ROI mesuré), plutôt que de saupoudrer. La donnée guide l'arbitrage.",
    tip: "Va là où est ta cible, pas où est la hype.",
  },
  {
    ...base, id: 'mkt-si-3', type: 'situation', difficulty: 2,
    context: "Votre responsable veut « un visuel qui claque » pour demain, sans plus de précisions.",
    situation: "Brief créatif trop vague.",
    question: "Le bon réflexe :",
    options: [
      { text: "Foncer sans poser de questions", correct: false },
      { text: "Reformuler le besoin : objectif, cible, message, support, contraintes", correct: true },
      { text: "Copier un visuel d'un concurrent", correct: false },
      { text: "Refuser la tâche", correct: false },
    ],
    explanation: "Sans brief clair, on produit à l'aveugle. Reformuler l'objectif, la cible et le message évite les allers-retours et garantit un résultat utile.",
    tip: "Pas de bon visuel sans bon brief : pose les questions.",
  },
  {
    ...base, id: 'mkt-si-4', type: 'situation', difficulty: 3,
    context: "Une campagne publicitaire en cours ne génère presque aucune conversion.",
    situation: "Campagne qui sous-performe.",
    question: "La meilleure démarche :",
    options: [
      { text: "Attendre la fin sans rien changer", correct: false },
      { text: "Analyser les données (ciblage, message, page d'arrivée) et tester des ajustements", correct: true },
      { text: "Doubler le budget sans rien changer", correct: false },
      { text: "Arrêter tout le marketing", correct: false },
    ],
    explanation: "On diagnostique : le ciblage est-il bon ? le message ? la landing page ? Puis on teste (A/B). Le marketing data-driven optimise en continu plutôt que de subir.",
    tip: "Mesurer, identifier le maillon faible, tester, recommencer.",
  },
  {
    ...base, id: 'mkt-si-5', type: 'situation', difficulty: 2,
    context: "Un internaute laisse un commentaire négatif mais légitime sous une publication de la marque.",
    situation: "Commentaire négatif public.",
    question: "La meilleure réponse en community management :",
    options: [
      { text: "Supprimer le commentaire", correct: false },
      { text: "Répondre poliment, publiquement, et proposer de régler le problème", correct: true },
      { text: "Répondre avec ironie", correct: false },
      { text: "Bloquer la personne", correct: false },
    ],
    explanation: "Une réponse publique, calme et orientée solution montre que la marque écoute. Supprimer ou ironiser nuit à l'image. On peut basculer en privé pour les détails.",
    tip: "Réponse publique + solution = image soignée.",
  },
  {
    ...base, id: 'mkt-si-6', type: 'situation', difficulty: 3,
    context: "Un influenceur partenaire publie un contenu maladroit qui ne respecte pas le brief et choque une partie de l'audience.",
    situation: "Dérapage d'un influenceur partenaire.",
    question: "La meilleure réaction :",
    options: [
      { text: "Faire comme si tout allait bien", correct: false },
      { text: "Échanger rapidement avec lui pour corriger/retirer et clarifier le cadre", correct: true },
      { text: "L'insulter publiquement", correct: false },
      { text: "Diffuser encore plus le contenu", correct: false },
    ],
    explanation: "On gère vite et professionnellement : contact direct, correction ou retrait, rappel du cadre. La marque reste responsable de ce que publient ses partenaires.",
    tip: "Cadre clair en amont, réaction rapide en cas de dérapage.",
  },
  {
    ...base, id: 'mkt-si-7', type: 'situation', difficulty: 3,
    context: "🏆 BOSS — On te confie le lancement d'une nouvelle offre. Tu pars d'une page blanche.",
    situation: "Construire une campagne de A à Z.",
    question: "Dans quel ordre raisonner ?",
    options: [
      { text: "Choisir un visuel d'abord, réfléchir au reste après", correct: false },
      { text: "Objectif → cible → message → canaux → budget → mesure", correct: true },
      { text: "Publier partout puis voir ce qui marche", correct: false },
      { text: "Copier la campagne d'un concurrent", correct: false },
    ],
    explanation: "Une campagne se construit dans l'ordre : fixer l'objectif, définir la cible, bâtir le message, choisir les canaux, allouer le budget et prévoir la mesure. Le visuel vient après la stratégie.",
    tip: "La stratégie d'abord, l'exécution ensuite.",
  },

  // ══════════════ 📰 ACTU & TENDANCES (2026) ══════════════
  {
    ...base, id: 'mkt-ac-1', type: 'actu', difficulty: 3,
    situation: "L'IA dans le marketing.",
    question: "Quel est l'enjeu de l'IA générative pour le contenu marketing ?",
    options: [
      { text: "Elle rend le marketing inutile", correct: false },
      { text: "Produire plus vite, tout en gardant authenticité, justesse et contrôle humain", correct: true },
      { text: "Publier sans jamais relire", correct: false },
      { text: "Elle ne sert qu'au design", correct: false },
    ],
    explanation: "L'IA accélère la production (textes, visuels, idées) mais pose la question de l'authenticité et de la qualité. Le marketeur la pilote et garde l'œil critique.",
    tip: "L'IA assiste la création ; l'humain garde la direction.",
  },
  {
    ...base, id: 'mkt-ac-2', type: 'actu', difficulty: 3,
    situation: "Évolution du référencement.",
    question: "Que désigne le « GEO » (Generative Engine Optimization) ?",
    options: [
      { text: "La géolocalisation des clients", correct: false },
      { text: "Optimiser sa présence pour être cité par les moteurs de réponse IA", correct: true },
      { text: "Un nouveau réseau social", correct: false },
      { text: "Un format de fichier", correct: false },
    ],
    explanation: "Avec les réponses générées par IA (ChatGPT, recherches IA), le GEO complète le SEO : être visible et cité dans les réponses des moteurs génératifs devient un nouvel enjeu.",
    tip: "Le SEO évolue vers le GEO à l'ère des réponses IA.",
  },
  {
    ...base, id: 'mkt-ac-3', type: 'actu', difficulty: 2,
    situation: "Formats de contenu.",
    question: "Pourquoi la vidéo courte (Reels, TikTok, Shorts) est-elle incontournable ?",
    options: [
      { text: "Elle ne touche personne", correct: false },
      { text: "Elle capte fortement l'attention et est poussée par les algorithmes", correct: true },
      { text: "Elle est interdite aux marques", correct: false },
      { text: "Elle coûte toujours très cher", correct: false },
    ],
    explanation: "La vidéo courte domine l'engagement et la portée organique. Couplée à l'UGC (contenu créé par les utilisateurs), c'est un levier majeur en 2026.",
    tip: "Pense « vidéo courte + UGC » pour la portée.",
  },
  {
    ...base, id: 'mkt-ac-4', type: 'actu', difficulty: 3,
    situation: "Données et vie privée.",
    question: "Quelle conséquence a la fin des cookies tiers ?",
    options: [
      { text: "Aucune", correct: false },
      { text: "Les marques misent sur la « first-party data » (données collectées directement et consenties)", correct: true },
      { text: "Le marketing digital disparaît", correct: false },
      { text: "On peut suivre les gens sans limite", correct: false },
    ],
    explanation: "La disparition des cookies tiers pousse à collecter ses propres données (newsletter, compte client) avec consentement. La first-party data devient un actif stratégique.",
    tip: "First-party data = l'or du marketing post-cookies.",
  },
  {
    ...base, id: 'mkt-ac-5', type: 'actu', difficulty: 2,
    situation: "Marketing d'influence.",
    question: "Pourquoi les « nano » et « micro-influenceurs » montent-ils ?",
    options: [
      { text: "Ils n'ont aucun intérêt", correct: false },
      { text: "Audience plus petite mais très engagée et authentique, à moindre coût", correct: true },
      { text: "Ils coûtent toujours plus cher que les stars", correct: false },
      { text: "Ils sont interdits", correct: false },
    ],
    explanation: "Les petits influenceurs offrent une communauté de niche, engagée et crédible, souvent plus rentable qu'une grosse star. L'authenticité prime sur la taille.",
    tip: "Engagement et authenticité > nombre d'abonnés.",
  },
  {
    ...base, id: 'mkt-ac-6', type: 'actu', difficulty: 2,
    situation: "Responsabilité des marques.",
    question: "Qu'est-ce que le « greenwashing » qu'il faut éviter ?",
    options: [
      { text: "Une technique de design écolo", correct: false },
      { text: "Se prétendre écoresponsable sans preuves réelles — risqué juridiquement et réputationnel", correct: true },
      { text: "Recycler ses visuels", correct: false },
      { text: "Une couleur de charte graphique", correct: false },
    ],
    explanation: "Le greenwashing (allégations écologiques trompeuses) est de plus en plus sanctionné et détecté par le public. Le marketing responsable exige des preuves et de la sincérité.",
    tip: "Pas d'allégation écolo sans preuve : sinon, greenwashing.",
  },
  {
    ...base, id: 'mkt-ac-7', type: 'actu', difficulty: 2,
    situation: "Expérience client.",
    question: "Qu'apporte la « personnalisation » dans le marketing ?",
    options: [
      { text: "Rien d'utile", correct: false },
      { text: "Adapter messages et offres à chaque profil grâce à la donnée, pour plus de pertinence", correct: true },
      { text: "Envoyer le même message à tous", correct: false },
      { text: "Supprimer toute communication", correct: false },
    ],
    explanation: "Grâce à la data, on personnalise les messages (recommandations, segmentation, automation). Bien faite et respectueuse de la vie privée, elle booste l'engagement.",
    tip: "Personnalisation pertinente = plus d'engagement (sans être intrusif).",
  },
  {
    ...base, id: 'mkt-ac-8', type: 'actu', difficulty: 2,
    situation: "Nouveaux modes d'achat.",
    question: "Que désigne le « social commerce » ?",
    options: [
      { text: "Vendre uniquement en boutique physique", correct: false },
      { text: "Acheter directement depuis les réseaux sociaux (live shopping, boutiques intégrées)", correct: true },
      { text: "Échanger des produits entre amis", correct: false },
      { text: "Un type de comptabilité", correct: false },
    ],
    explanation: "Le social commerce fond l'inspiration et l'achat dans les réseaux (boutiques Instagram/TikTok, live shopping). Le parcours d'achat se raccourcit fortement.",
    tip: "Réduire le parcours d'achat : tendance forte du social commerce.",
  },

  // ── 🧠 COMPORTEMENTAL (suite) ──
  {
    ...base, id: 'mkt-cp-7', type: 'comportemental', difficulty: 1,
    situation: "« Qu'est-ce qui vous attire dans le marketing ? »",
    question: "La motivation la plus convaincante :",
    options: [
      { text: "« Poster des photos sympas »", correct: false },
      { text: "Allier créativité et analyse pour faire connaître et vendre un produit", correct: true },
      { text: "« Être célèbre »", correct: false },
      { text: "« Ne rien faire de technique »", correct: false },
    ],
    explanation: "Le marketing mêle création et données : on conçoit des messages ET on mesure leur impact. Afficher cet équilibre est plus solide que « j'aime les réseaux ».",
    tip: "Montre que tu aimes créer ET analyser.",
  },
  {
    ...base, id: 'mkt-cp-8', type: 'comportemental', difficulty: 2,
    situation: "Votre belle création est critiquée par le client.",
    question: "La bonne réaction :",
    options: [
      { text: "Se braquer et défendre son ego", correct: false },
      { text: "Écouter le retour, comprendre l'objectif et ajuster", correct: true },
      { text: "Refuser toute modification", correct: false },
      { text: "« Vous n'y connaissez rien »", correct: false },
    ],
    explanation: "En création, le feedback fait partie du jeu : on sert l'objectif du client, pas son ego. Savoir accueillir la critique est une vraie maturité pro.",
    tip: "Ta création sert un objectif, pas ton ego.",
  },
  {
    ...base, id: 'mkt-cp-9', type: 'comportemental', difficulty: 2,
    situation: "Une tendance virale émerge sur les réseaux.",
    question: "La qualité valorisée :",
    options: [
      { text: "L'ignorer par principe", correct: false },
      { text: "La réactivité et la curiosité : savoir rebondir vite quand c'est pertinent", correct: true },
      { text: "Copier sans réfléchir à la marque", correct: false },
      { text: "Attendre 3 mois pour réagir", correct: false },
    ],
    explanation: "Le marketing récompense la veille et la réactivité : surfer à propos sur une tendance peut booster la visibilité, à condition que ce soit cohérent avec la marque.",
    tip: "Réactif oui, mais toujours cohérent avec la marque.",
  },
  {
    ...base, id: 'mkt-cp-10', type: 'comportemental', difficulty: 2,
    situation: "Vous gérez plusieurs campagnes en parallèle avec des deadlines.",
    question: "La qualité-clé :",
    options: [
      { text: "Tout faire à la dernière minute", correct: false },
      { text: "L'organisation : planifier, prioriser et tenir les échéances", correct: true },
      { text: "Ignorer les délais", correct: false },
      { text: "Ne traiter qu'une campagne", correct: false },
    ],
    explanation: "Derrière la créativité, le marketing exige rigueur et respect des deadlines (sorties, événements). L'organisation est aussi importante que les idées.",
    tip: "La créativité ne dispense pas du rétroplanning.",
  },
  {
    ...base, id: 'mkt-cp-11', type: 'comportemental', difficulty: 2,
    situation: "Une campagne n'a pas atteint ses objectifs.",
    question: "La bonne attitude :",
    options: [
      { text: "Cacher les mauvais chiffres", correct: false },
      { text: "Analyser les data, comprendre pourquoi et ajuster la prochaine fois", correct: true },
      { text: "Blâmer l'algorithme", correct: false },
      { text: "Ne rien changer", correct: false },
    ],
    explanation: "L'esprit d'analyse est central : on apprend des résultats, bons ou mauvais, pour optimiser. Un marketeur pilote par la donnée, pas par l'intuition seule.",
    tip: "Chaque campagne est un test : mesure et apprends.",
  },
  {
    ...base, id: 'mkt-cp-12', type: 'comportemental', difficulty: 1,
    situation: "On vous propose de tester un nouvel outil/réseau.",
    question: "La bonne posture :",
    options: [
      { text: "Refuser par habitude", correct: false },
      { text: "Faire preuve de curiosité et tester pour évaluer l'intérêt", correct: true },
      { text: "« Trop compliqué »", correct: false },
      { text: "Attendre que tout le monde l'utilise", correct: false },
    ],
    explanation: "La curiosité digitale est essentielle dans un domaine qui évolue sans cesse. Tester (sans tout adopter) permet de rester pertinent.",
    tip: "Teste les nouveautés, garde celles qui servent.",
  },
  {
    ...base, id: 'mkt-cp-13', type: 'comportemental', difficulty: 2,
    situation: "Votre manager attend des idées pour relancer une marque.",
    question: "La qualité attendue :",
    options: [
      { text: "Attendre qu'on vous dise quoi faire", correct: false },
      { text: "La force de proposition : arriver avec des idées argumentées", correct: true },
      { text: "Copier la concurrence à l'identique", correct: false },
      { text: "Critiquer sans proposer", correct: false },
    ],
    explanation: "Être force de proposition (idées étayées par une logique et des exemples) est très recherché en marketing. La passivité n'a pas sa place.",
    tip: "Arrive avec des idées, pas seulement des constats.",
  },
  {
    ...base, id: 'mkt-cp-14', type: 'comportemental', difficulty: 2,
    situation: "Vous travaillez avec le design, la vente et la direction.",
    question: "La compétence relationnelle clé :",
    options: [
      { text: "Travailler isolé dans son coin", correct: false },
      { text: "Collaborer et communiquer clairement entre services", correct: true },
      { text: "Imposer ses vues à tous", correct: false },
      { text: "Éviter les autres équipes", correct: false },
    ],
    explanation: "Le marketing est transversal : il coordonne créa, commercial, produit, direction. La collaboration et la communication sont déterminantes.",
    tip: "Le marketeur est un chef d'orchestre entre services.",
  },
  {
    ...base, id: 'mkt-cp-15', type: 'comportemental', difficulty: 2,
    situation: "Vous devez écrire un post engageant en peu de temps.",
    question: "La qualité utile :",
    options: [
      { text: "L'autonomie et l'efficacité créative", correct: true },
      { text: "Attendre une validation pour chaque mot", correct: false },
      { text: "Recopier un ancien post sans adaptation", correct: false },
      { text: "Repousser indéfiniment", correct: false },
    ],
    explanation: "Savoir produire vite et bien, en autonomie, est précieux dans le rythme du marketing digital, tout en respectant la ligne éditoriale.",
    tip: "Autonomie + efficacité dans le cadre de la marque.",
  },
  {
    ...base, id: 'mkt-cp-16', type: 'comportemental', difficulty: 1,
    situation: "Un détail (faute, mauvais lien) traîne dans une publication.",
    question: "La qualité requise :",
    options: [
      { text: "« On s'en fiche »", correct: false },
      { text: "Le sens du détail : relire et vérifier avant publication", correct: true },
      { text: "Publier sans relire", correct: false },
      { text: "Laisser les autres corriger", correct: false },
    ],
    explanation: "Une faute ou un lien cassé nuit à la crédibilité de la marque. La relecture et le souci du détail sont indispensables avant toute diffusion.",
    tip: "Relis toujours : la marque se juge aussi sur les détails.",
  },
  {
    ...base, id: 'mkt-cp-17', type: 'comportemental', difficulty: 2,
    situation: "« Êtes-vous à l'aise avec les chiffres ? »",
    question: "La réponse attendue d'un marketeur :",
    options: [
      { text: "« Non, je suis créatif, pas matheux »", correct: false },
      { text: "Oui : j'aime mesurer mes actions (clics, conversions) pour les améliorer", correct: true },
      { text: "« Les chiffres ne servent à rien »", correct: false },
      { text: "« Je regarde juste les likes »", correct: false },
    ],
    explanation: "Le marketing moderne est piloté par la data. Être à l'aise avec les indicateurs (et pas seulement les likes) est désormais incontournable.",
    tip: "Créatif ET data-friendly : le duo gagnant.",
  },
  {
    ...base, id: 'mkt-cp-18', type: 'comportemental', difficulty: 2,
    situation: "Le marché et les algorithmes changent fréquemment.",
    question: "La qualité indispensable :",
    options: [
      { text: "Refuser tout changement", correct: false },
      { text: "L'adaptabilité et l'apprentissage continu", correct: true },
      { text: "Faire toujours pareil", correct: false },
      { text: "Ignorer les évolutions", correct: false },
    ],
    explanation: "Les plateformes et usages évoluent vite ; se former en continu et s'adapter est vital pour rester efficace en marketing digital.",
    tip: "Se former en continu n'est pas optionnel en digital.",
  },
  {
    ...base, id: 'mkt-cp-19', type: 'comportemental', difficulty: 1,
    situation: "On vous confie la gestion d'une communauté en ligne.",
    question: "La posture adaptée :",
    options: [
      { text: "Ignorer les commentaires", correct: false },
      { text: "Être réactif, à l'écoute et bienveillant, même face aux critiques", correct: true },
      { text: "Supprimer tout avis négatif", correct: false },
      { text: "Répondre agressivement", correct: false },
    ],
    explanation: "Le community management demande écoute, réactivité et diplomatie : on anime, on répond, on gère les critiques avec professionnalisme.",
    tip: "Une communauté se nourrit d'écoute et de réactivité.",
  },
  {
    ...base, id: 'mkt-cp-20', type: 'comportemental', difficulty: 2,
    situation: "« Quelle est votre principale force en marketing ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "Une force utile au poste illustrée par un projet concret", correct: true },
      { text: "« Je suis créatif » sans exemple", correct: false },
      { text: "« J'ai beaucoup d'abonnés perso »", correct: false },
      { text: "Une liste de 10 qualités", correct: false },
    ],
    explanation: "On choisit une force pertinente (créativité, analyse, organisation) et on la prouve par un projet réel. La preuve concrète vaut mieux que l'affirmation.",
    tip: "Appuie ta force par un projet que tu as mené.",
  },

  // ── 🛠️ TECHNIQUE (suite) ──
  {
    ...base, id: 'mkt-te-10', type: 'technique', difficulty: 2,
    situation: "Avant toute campagne, on définit la cible.",
    question: "Qu'est-ce qu'un « persona » ?",
    options: [
      { text: "Un personnage de jeu vidéo", correct: false },
      { text: "Un portrait-type du client idéal (besoins, habitudes, freins)", correct: true },
      { text: "Le nom d'un logiciel", correct: false },
      { text: "Une police d'écriture", correct: false },
    ],
    explanation: "Le persona représente le client cible (profil, besoins, motivations, freins). Il guide le message, les canaux et le ton de la campagne.",
    tip: "Pas de bon message sans cible bien définie.",
  },
  {
    ...base, id: 'mkt-te-11', type: 'technique', difficulty: 2,
    situation: "Vous animez les réseaux sociaux de la marque.",
    question: "L'outil d'organisation essentiel :",
    options: [
      { text: "Poster au hasard quand on y pense", correct: false },
      { text: "Un calendrier éditorial planifiant thèmes, formats et dates", correct: true },
      { text: "Ne rien planifier", correct: false },
      { text: "Copier les posts des concurrents", correct: false },
    ],
    explanation: "Le calendrier éditorial structure la prise de parole (thèmes, formats, fréquence) pour une présence cohérente et régulière.",
    tip: "Planifie tes contenus, n'improvise pas au jour le jour.",
  },
  {
    ...base, id: 'mkt-te-12', type: 'technique', difficulty: 2,
    situation: "On veut être mieux référencé sur Google.",
    question: "De quoi parle-t-on ?",
    options: [
      { text: "Du SEO (référencement naturel)", correct: true },
      { text: "Du montage vidéo", correct: false },
      { text: "De la comptabilité", correct: false },
      { text: "Du service client", correct: false },
    ],
    explanation: "Le SEO optimise un site pour les moteurs de recherche (mots-clés, contenu, technique, liens) afin de gagner en visibilité gratuite et durable.",
    tip: "SEO = visibilité durable ; SEA = visibilité payante.",
  },
  {
    ...base, id: 'mkt-te-13', type: 'technique', difficulty: 2,
    situation: "Vous lancez une campagne d'emailing.",
    question: "Un indicateur clé à suivre :",
    options: [
      { text: "La couleur du bouton uniquement", correct: false },
      { text: "Le taux d'ouverture et le taux de clic", correct: true },
      { text: "Le nombre de mots", correct: false },
      { text: "Rien, l'email c'est dépassé", correct: false },
    ],
    explanation: "L'emailing se mesure (taux d'ouverture, de clic, de conversion, désabonnement) pour optimiser objet, contenu et ciblage. Il reste un canal très rentable.",
    tip: "Soigne l'objet : il décide du taux d'ouverture.",
  },
  {
    ...base, id: 'mkt-te-14', type: 'technique', difficulty: 3,
    situation: "On vous demande le ROI d'une action publicitaire.",
    question: "Ce que mesure le ROI :",
    options: [
      { text: "Le nombre de likes", correct: false },
      { text: "Le retour sur investissement : gains générés rapportés aux dépenses", correct: true },
      { text: "La taille du logo", correct: false },
      { text: "Le nombre d'abonnés", correct: false },
    ],
    explanation: "Le ROI relie les résultats (ventes, leads) au budget engagé. C'est l'indicateur de rentabilité qui justifie les investissements marketing.",
    tip: "Likes ≠ ventes : c'est le ROI qui compte pour la direction.",
  },
  {
    ...base, id: 'mkt-te-15', type: 'technique', difficulty: 2,
    situation: "Vous créez une publicité payante sur les réseaux.",
    question: "Le levier principal de performance :",
    options: [
      { text: "Diffuser à tout le monde sans ciblage", correct: false },
      { text: "Cibler précisément l'audience et tester plusieurs visuels (A/B)", correct: true },
      { text: "Mettre tout le budget d'un coup sans test", correct: false },
      { text: "Copier une pub au hasard", correct: false },
    ],
    explanation: "Les social ads performent par un ciblage précis et l'A/B testing des créations. On optimise en continu selon les résultats.",
    tip: "Teste plusieurs versions (A/B) avant de scaler le budget.",
  },
  {
    ...base, id: 'mkt-te-16', type: 'technique', difficulty: 2,
    situation: "Un graphiste va réaliser un visuel pour vous.",
    question: "Que doit contenir un bon brief créatif ?",
    options: [
      { text: "« Fais un truc joli »", correct: false },
      { text: "Objectif, cible, message clé, ton, contraintes et formats", correct: true },
      { text: "Rien, il devinera", correct: false },
      { text: "Seulement la deadline", correct: false },
    ],
    explanation: "Un brief clair (objectif, cible, message, ton, formats, contraintes) évite les allers-retours et garantit un résultat aligné. Le flou coûte du temps.",
    tip: "Un bon brief = moins d'allers-retours.",
  },
  {
    ...base, id: 'mkt-te-17', type: 'technique', difficulty: 2,
    situation: "La marque doit être reconnaissable partout.",
    question: "L'outil qui le garantit :",
    options: [
      { text: "Improviser à chaque support", correct: false },
      { text: "La charte graphique (logo, couleurs, typo, ton)", correct: true },
      { text: "Changer de logo souvent", correct: false },
      { text: "Copier d'autres marques", correct: false },
    ],
    explanation: "La charte graphique assure la cohérence visuelle et verbale de la marque sur tous les supports, condition de sa reconnaissance.",
    tip: "Cohérence = la marque se reconnaît au premier coup d'œil.",
  },
  {
    ...base, id: 'mkt-te-18', type: 'technique', difficulty: 2,
    situation: "Vous analysez le trafic d'un site.",
    question: "Un outil de référence :",
    options: [
      { text: "Un tableur vide", correct: false },
      { text: "Un outil d'analytics (ex. Google Analytics) pour visites, sources, conversions", correct: true },
      { text: "Le compteur de likes", correct: false },
      { text: "L'horloge", correct: false },
    ],
    explanation: "Les outils d'analytics mesurent l'audience, les sources de trafic et les conversions, base de toute optimisation digitale.",
    tip: "Regarde d'où vient le trafic et ce qu'il fait sur le site.",
  },
  {
    ...base, id: 'mkt-te-19', type: 'technique', difficulty: 2,
    situation: "Vous rédigez un texte publicitaire (copywriting).",
    question: "Le principe efficace :",
    options: [
      { text: "Décrire seulement les caractéristiques techniques", correct: false },
      { text: "Accroche forte, bénéfice clair et appel à l'action (CTA)", correct: true },
      { text: "Le plus de texte possible", correct: false },
      { text: "Un texte sans aucun objectif", correct: false },
    ],
    explanation: "Un bon copy capte (accroche), donne envie (bénéfice) et incite à agir (CTA). On parle au lecteur et à son besoin, pas au produit.",
    tip: "Toujours finir par un appel à l'action clair.",
  },
  {
    ...base, id: 'mkt-te-20', type: 'technique', difficulty: 2,
    situation: "On vous demande de définir des objectifs de campagne.",
    question: "La bonne méthode :",
    options: [
      { text: "Des objectifs vagues (« faire le buzz »)", correct: false },
      { text: "Des objectifs SMART (spécifiques, mesurables, atteignables, datés)", correct: true },
      { text: "Aucun objectif", correct: false },
      { text: "Des objectifs impossibles", correct: false },
    ],
    explanation: "Des objectifs SMART rendent la campagne pilotable et évaluable. « Faire le buzz » n'est ni mesurable ni actionnable.",
    tip: "Un objectif SMART se mesure : +20 % de leads en 3 mois.",
  },

  // ── 🎭 MISE EN SITUATION (suite) ──
  {
    ...base, id: 'mkt-si-8', type: 'situation', difficulty: 3,
    context: "Un commentaire négatif sous votre post prend de l'ampleur (début de bad buzz).",
    situation: "Une critique virale enfle sur les réseaux.",
    question: "La meilleure réaction :",
    options: [
      { text: "Supprimer le commentaire et ignorer", correct: false },
      { text: "Répondre calmement, avec transparence, et traiter le fond du problème", correct: true },
      { text: "Répondre avec agressivité", correct: false },
      { text: "Faire le mort en espérant que ça passe", correct: false },
    ],
    explanation: "Supprimer attise souvent la colère (effet Streisand). Une réponse posée, transparente et orientée solution désamorce et protège la réputation.",
    tip: "Face au bad buzz : transparence et réponse au fond.",
  },
  {
    ...base, id: 'mkt-si-9', type: 'situation', difficulty: 2,
    context: "Lancement produit dans 3 jours, la campagne n'est pas prête.",
    situation: "Deadline de campagne très serrée.",
    question: "La meilleure approche :",
    options: [
      { text: "Tout sortir bâclé", correct: false },
      { text: "Prioriser l'essentiel diffusable et alerter sur ce qui suivra", correct: true },
      { text: "Repousser sans prévenir", correct: false },
      { text: "Abandonner la campagne", correct: false },
    ],
    explanation: "Sous deadline, on sécurise le minimum viable de qualité et on planifie la suite, en communiquant clairement avec l'équipe et la direction.",
    tip: "Mieux vaut un lancement minimal soigné qu'un tout bâclé.",
  },
  {
    ...base, id: 'mkt-si-10', type: 'situation', difficulty: 2,
    situation: "Le client veut un visuel qui va, selon vous, contre l'image de marque.",
    question: "La bonne attitude :",
    options: [
      { text: "Exécuter sans rien dire", correct: false },
      { text: "Expliquer avec arguments le risque pour la marque et proposer une alternative", correct: true },
      { text: "Refuser net sans alternative", correct: false },
      { text: "Faire l'inverse en cachette", correct: false },
    ],
    explanation: "On conseille le client en expert : exposer le risque avec des arguments et proposer une option cohérente. La décision finale lui revient, mais éclairée.",
    tip: "Conseille avec arguments, propose une alternative.",
  },
  {
    ...base, id: 'mkt-si-11', type: 'situation', difficulty: 2,
    situation: "Le budget de la campagne est réduit de moitié.",
    question: "La meilleure réaction :",
    options: [
      { text: "Annuler toute action", correct: false },
      { text: "Reprioriser sur les canaux les plus rentables et les actions à fort ROI", correct: true },
      { text: "Dépenser quand même comme prévu", correct: false },
      { text: "Se plaindre sans rien adapter", correct: false },
    ],
    explanation: "Avec moins de budget, on concentre les moyens sur les leviers les plus efficaces (ciblage fin, canaux performants) plutôt que de tout saupoudrer.",
    tip: "Moins de budget = plus de ciblage et de priorisation.",
  },
  {
    ...base, id: 'mkt-si-12', type: 'situation', difficulty: 2,
    situation: "Un post important ne génère aucun engagement.",
    question: "La bonne démarche :",
    options: [
      { text: "Conclure que les réseaux « ne marchent pas »", correct: false },
      { text: "Analyser (horaire, format, message), tester une variante et ajuster", correct: true },
      { text: "Republier exactement le même", correct: false },
      { text: "Tout arrêter", correct: false },
    ],
    explanation: "Un échec ponctuel s'analyse : timing, format, accroche, cible. On teste une nouvelle approche plutôt que de répéter ou d'abandonner.",
    tip: "Teste un autre format/horaire avant de conclure.",
  },
  {
    ...base, id: 'mkt-si-13', type: 'situation', difficulty: 3,
    context: "Un influenceur partenaire tient des propos polémiques qui rejaillissent sur la marque.",
    situation: "Partenariat influenceur qui dérape.",
    question: "La meilleure réaction :",
    options: [
      { text: "Ignorer totalement", correct: false },
      { text: "Évaluer la gravité, se positionner clairement et, si besoin, suspendre le partenariat", correct: true },
      { text: "Soutenir aveuglément l'influenceur", correct: false },
      { text: "Attaquer publiquement les internautes", correct: false },
    ],
    explanation: "Un partenariat engage la marque. Face à un dérapage, on évalue, on se positionne par rapport à ses valeurs et on agit (recadrage ou rupture) pour protéger sa réputation.",
    tip: "Choisis tes partenaires selon tes valeurs, et assume.",
  },
  {
    ...base, id: 'mkt-si-14', type: 'situation', difficulty: 2,
    situation: "La direction demande « du contenu viral » sans budget ni précision.",
    question: "La bonne réponse :",
    options: [
      { text: "Promettre du viral garanti", correct: false },
      { text: "Cadrer des objectifs réalistes et expliquer ce qui favorise la viralité", correct: true },
      { text: "Refuser sèchement", correct: false },
      { text: "Copier une vidéo virale au hasard", correct: false },
    ],
    explanation: "La viralité ne se garantit pas. On recadre vers des objectifs atteignables et on explique les ingrédients (émotion, format, timing) qui augmentent les chances.",
    tip: "Le viral se favorise, il ne se promet pas.",
  },
  {
    ...base, id: 'mkt-si-15', type: 'situation', difficulty: 2,
    situation: "Deux services veulent des messages contradictoires dans la même campagne.",
    question: "La bonne démarche :",
    options: [
      { text: "Mettre les deux messages en vrac", correct: false },
      { text: "Réunir les parties, clarifier l'objectif prioritaire et arbitrer un message clair", correct: true },
      { text: "Choisir au hasard", correct: false },
      { text: "Abandonner la campagne", correct: false },
    ],
    explanation: "Un message clair suppose un objectif unique prioritaire. On aligne les parties prenantes plutôt que d'empiler des messages qui se neutralisent.",
    tip: "Un message confus ne convertit pas : un objectif à la fois.",
  },
  {
    ...base, id: 'mkt-si-16', type: 'situation', difficulty: 2,
    situation: "Vous repérez une faute dans une pub déjà en ligne.",
    question: "La bonne réaction :",
    options: [
      { text: "Laisser, « personne ne verra »", correct: false },
      { text: "Corriger au plus vite et vérifier les autres supports", correct: true },
      { text: "Tout supprimer dans la panique", correct: false },
      { text: "Accuser un collègue", correct: false },
    ],
    explanation: "Une erreur publiée se corrige rapidement et on vérifie les déclinaisons. La réactivité limite l'impact sur l'image.",
    tip: "Corrige vite et contrôle les autres supports.",
  },
  {
    ...base, id: 'mkt-si-17', type: 'situation', difficulty: 2,
    situation: "Un abonné pose une question SAV en commentaire d'un post.",
    question: "La bonne gestion :",
    options: [
      { text: "Ignorer le commentaire", correct: false },
      { text: "Répondre rapidement et, si besoin, basculer en message privé pour résoudre", correct: true },
      { text: "Supprimer le commentaire", correct: false },
      { text: "Répondre « ce n'est pas le bon endroit » sèchement", correct: false },
    ],
    explanation: "Sur les réseaux, le SAV se joue en public : une réponse rapide et le passage en privé pour les détails montrent du sérieux et rassurent les autres lecteurs.",
    tip: "Réponds vite en public, résous en privé.",
  },
  {
    ...base, id: 'mkt-si-18', type: 'situation', difficulty: 3,
    context: "Crise : un défaut produit est massivement signalé en ligne.",
    situation: "Gérer une crise de réputation.",
    question: "La meilleure posture :",
    options: [
      { text: "Nier le problème", correct: false },
      { text: "Communiquer vite, reconnaître les faits et annoncer les mesures prises", correct: true },
      { text: "Supprimer tous les messages négatifs", correct: false },
      { text: "Disparaître des réseaux", correct: false },
    ],
    explanation: "En gestion de crise, la rapidité et la transparence priment : reconnaître, informer et montrer qu'on agit. Le déni ou le silence amplifient la défiance.",
    tip: "En crise : vite, vrai, et oriente vers les solutions.",
  },
  {
    ...base, id: 'mkt-si-19', type: 'situation', difficulty: 2,
    situation: "On vous demande une campagne pour une cible que vous connaissez mal.",
    question: "La bonne première étape :",
    options: [
      { text: "Foncer sur vos habitudes perso", correct: false },
      { text: "Se documenter sur la cible (données, personas, tendances) avant de créer", correct: true },
      { text: "Copier une autre campagne", correct: false },
      { text: "Deviner au hasard", correct: false },
    ],
    explanation: "On ne crée pas sans connaître sa cible. La recherche (données, personas, insights) garantit un message pertinent et évite les clichés.",
    tip: "Comprends la cible avant de créer pour elle.",
  },
  {
    ...base, id: 'mkt-si-20', type: 'situation', difficulty: 2,
    situation: "Une idée créative séduisante n'est pas conforme à la loi (allégation interdite).",
    question: "La bonne décision :",
    options: [
      { text: "La diffuser quand même", correct: false },
      { text: "Renoncer ou adapter pour rester conforme (publicité, mentions légales)", correct: true },
      { text: "Cacher les mentions légales", correct: false },
      { text: "Mentir sur le produit", correct: false },
    ],
    explanation: "La créativité s'exerce dans le cadre légal (allégations, mentions obligatoires, droit de la pub). Une infraction expose la marque à des sanctions et à une perte de confiance.",
    tip: "La conformité prime sur l'effet créatif.",
  },

  // ── 📰 ACTU & TENDANCES (suite) ──
  {
    ...base, id: 'mkt-ac-9', type: 'actu', difficulty: 2,
    situation: "L'IA générative produit textes et visuels.",
    question: "Le bon usage en marketing :",
    options: [
      { text: "Tout publier sans relecture", correct: false },
      { text: "Accélérer la production (idées, brouillons, visuels) en gardant relecture et ton de marque", correct: true },
      { text: "Remplacer toute réflexion stratégique", correct: false },
      { text: "Copier d'autres marques avec l'IA", correct: false },
    ],
    explanation: "L'IA générative booste la production de contenu, mais l'humain garde la stratégie, la relecture et la cohérence de marque. La qualité et l'authenticité restent décisives.",
    tip: "L'IA accélère ; toi tu gardes la stratégie et le ton.",
  },
  {
    ...base, id: 'mkt-ac-10', type: 'actu', difficulty: 2,
    situation: "Le format vidéo court (TikTok, Reels, Shorts) domine.",
    question: "La bonne approche :",
    options: [
      { text: "Ne faire que de longues vidéos", correct: false },
      { text: "Capter l'attention dès les premières secondes avec un format vertical dynamique", correct: true },
      { text: "Ignorer la vidéo", correct: false },
      { text: "Reposter des pubs TV telles quelles", correct: false },
    ],
    explanation: "La vidéo courte verticale capte vite ou perd l'audience. Les premières secondes (hook), le rythme et le natif au format sont déterminants.",
    tip: "Accroche dans les 3 premières secondes.",
  },
  {
    ...base, id: 'mkt-ac-11', type: 'actu', difficulty: 2,
    situation: "Le marketing d'influence est devenu central.",
    question: "Le critère de choix d'un influenceur :",
    options: [
      { text: "Le plus gros nombre d'abonnés, point", correct: false },
      { text: "L'adéquation à la cible et l'engagement réel de sa communauté", correct: true },
      { text: "Le moins cher", correct: false },
      { text: "Au hasard", correct: false },
    ],
    explanation: "L'efficacité d'un influenceur tient à la pertinence de son audience et à l'engagement, pas seulement au volume d'abonnés. Les micro-influenceurs convertissent souvent mieux.",
    tip: "Engagement et pertinence > nombre d'abonnés.",
  },
  {
    ...base, id: 'mkt-ac-12', type: 'actu', difficulty: 3,
    situation: "La fin des cookies tiers bouleverse le ciblage publicitaire.",
    question: "La réponse adaptée :",
    options: [
      { text: "Continuer comme avant", correct: false },
      { text: "Miser sur les données first-party (collectées avec consentement) et le contenu", correct: true },
      { text: "Pister les gens illégalement", correct: false },
      { text: "Abandonner le digital", correct: false },
    ],
    explanation: "Avec la disparition des cookies tiers, la valeur se déplace vers les données first-party (newsletter, compte client) et le marketing de contenu, dans le respect du consentement.",
    tip: "Construis ta base first-party (emails, comptes) dès maintenant.",
  },
  {
    ...base, id: 'mkt-ac-13', type: 'actu', difficulty: 2,
    situation: "Les consommateurs se méfient du « greenwashing ».",
    question: "La bonne pratique en communication responsable :",
    options: [
      { text: "Surjouer l'écologie sans preuve", correct: false },
      { text: "Communiquer des engagements réels, prouvés et mesurables", correct: true },
      { text: "Cacher l'impact environnemental", correct: false },
      { text: "Mettre du vert partout", correct: false },
    ],
    explanation: "Le greenwashing (vert sans preuve) est sanctionné par les consommateurs et la loi. La communication responsable repose sur des faits vérifiables.",
    tip: "Pas d'allégation écolo sans preuve.",
  },
  {
    ...base, id: 'mkt-ac-14', type: 'actu', difficulty: 2,
    situation: "Le contenu généré par les utilisateurs (UGC) explose.",
    question: "Son intérêt marketing :",
    options: [
      { text: "Aucun, ce n'est pas pro", correct: false },
      { text: "De l'authenticité et de la preuve sociale qui renforcent la confiance", correct: true },
      { text: "Remplacer toute la marque", correct: false },
      { text: "Voler le contenu sans autorisation", correct: false },
    ],
    explanation: "L'UGC (avis, photos, vidéos de clients) apporte authenticité et preuve sociale, très efficaces pour convaincre — à condition d'obtenir l'autorisation.",
    tip: "Encourage et republie l'UGC (avec accord).",
  },
  {
    ...base, id: 'mkt-ac-15', type: 'actu', difficulty: 2,
    situation: "La personnalisation des messages progresse.",
    question: "La bonne pratique :",
    options: [
      { text: "Le même message générique pour tous", correct: false },
      { text: "Adapter le contenu selon les segments/comportements, dans le respect du RGPD", correct: true },
      { text: "Utiliser les données sans consentement", correct: false },
      { text: "Sur-personnaliser au point de paraître intrusif", correct: false },
    ],
    explanation: "La personnalisation pertinente (segmentation, comportements) augmente l'efficacité, à condition de respecter la vie privée et de ne pas franchir la ligne de l'intrusif.",
    tip: "Personnalise utile, sans devenir intrusif.",
  },
  {
    ...base, id: 'mkt-ac-16', type: 'actu', difficulty: 2,
    situation: "Le marketing automation se répand.",
    question: "Ce qu'il permet :",
    options: [
      { text: "Supprimer toute stratégie", correct: false },
      { text: "Automatiser des scénarios (emails, relances) déclenchés par le comportement", correct: true },
      { text: "Spammer en masse", correct: false },
      { text: "Remplacer les marketeurs", correct: false },
    ],
    explanation: "Le marketing automation déclenche des actions personnalisées selon le parcours (bienvenue, panier abandonné, relance), gain d'efficacité énorme s'il est bien pensé.",
    tip: "Automatise des scénarios utiles, pas du spam.",
  },
  {
    ...base, id: 'mkt-ac-17', type: 'actu', difficulty: 2,
    situation: "Les podcasts et l'audio gagnent du terrain.",
    question: "L'intérêt pour une marque :",
    options: [
      { text: "Aucun, c'est de niche", correct: false },
      { text: "Créer un lien de proximité et toucher une audience attentive et fidèle", correct: true },
      { text: "Remplacer tous les autres canaux", correct: false },
      { text: "Diffuser de la pub agressive non-stop", correct: false },
    ],
    explanation: "L'audio (podcasts) crée une relation intime et capte une audience engagée. C'est un canal de contenu de marque en croissance.",
    tip: "L'audio crée de la proximité avec l'audience.",
  },
  {
    ...base, id: 'mkt-ac-18', type: 'actu', difficulty: 2,
    situation: "L'attention des audiences est de plus en plus rare.",
    question: "La conséquence pour les contenus :",
    options: [
      { text: "Faire plus long et plus dense", correct: false },
      { text: "Aller à l'essentiel, capter vite et apporter de la valeur", correct: true },
      { text: "Multiplier les pop-ups", correct: false },
      { text: "Publier sans relâche n'importe quoi", correct: false },
    ],
    explanation: "Dans l'économie de l'attention, les contenus clairs, rapides et utiles l'emportent. La quantité sans valeur lasse l'audience.",
    tip: "Capte vite et apporte de la valeur, sinon on scrolle.",
  },
  {
    ...base, id: 'mkt-ac-19', type: 'actu', difficulty: 3,
    situation: "On vous demande de prouver l'impact du marketing sur les ventes.",
    question: "La bonne démarche :",
    options: [
      { text: "Montrer seulement les likes", correct: false },
      { text: "Relier les actions aux conversions via le tracking et l'attribution", correct: true },
      { text: "Dire « ça marche, faites-moi confiance »", correct: false },
      { text: "Inventer des chiffres", correct: false },
    ],
    explanation: "Prouver la contribution marketing passe par le suivi des conversions et l'attribution (quel canal a généré quoi). C'est ce qui justifie les budgets.",
    tip: "Relie tes actions aux conversions, pas aux vanity metrics.",
  },
  {
    ...base, id: 'mkt-ac-20', type: 'actu', difficulty: 2,
    situation: "La protection de la vie privée devient un argument.",
    question: "L'attitude marketing pertinente :",
    options: [
      { text: "Collecter un maximum de données en douce", correct: false },
      { text: "Être transparent sur l'usage des données et respecter le consentement", correct: true },
      { text: "Ignorer le RGPD", correct: false },
      { text: "Revendre les données", correct: false },
    ],
    explanation: "La confiance se gagne par la transparence sur les données et le respect du consentement (RGPD). La privacy est devenue un facteur de réputation.",
    tip: "La transparence sur les données renforce la confiance.",
  },
];
