/**
 * Thème « Motivation » — 30 scénarios.
 * Une seule option correct:true par question, + explanation + tip.
 */
export default [
  {
    id: 'moti-1', category: 'motivation', difficulty: 1,
    situation: "« Pourquoi voulez-vous ce poste ? »",
    question: "La réponse la plus convaincante :",
    options: [
      { text: "« J'ai besoin d'un travail / d'un salaire »", correct: false },
      { text: "Relier ses compétences au poste ET montrer qu'on connaît l'entreprise", correct: true },
      { text: "« Parce que vous recrutez »", correct: false },
      { text: "« C'est près de chez moi »", correct: false },
    ],
    explanation: "On attend un lien explicite entre TES atouts et LEURS besoins, plus une vraie connaissance de l'entreprise. La motivation se prouve, elle ne se déclare pas.",
    tip: "Cite un élément précis et récent sur l'entreprise.",
  },
  {
    id: 'moti-2', category: 'motivation', difficulty: 2,
    situation: "« Pourquoi avez-vous quitté votre poste précédent ? »",
    question: "Quelle attitude adopter ?",
    options: [
      { text: "Critiquer son ancien manager et ses collègues", correct: false },
      { text: "Rester factuel et tourner vers l'avenir (évolution, nouveau défi)", correct: true },
      { text: "Dire « Je me suis fait virer, c'était injuste »", correct: false },
      { text: "Refuser de répondre", correct: false },
    ],
    explanation: "Ne jamais dénigrer : c'est rédhibitoire. On reste positif et orienté projet, même si le départ s'est mal passé.",
    tip: "Formule en positif : « je recherche » plutôt que « je fuyais ».",
  },
  {
    id: 'moti-3', category: 'motivation', difficulty: 2,
    situation: "« Pourquoi ce secteur d'activité en particulier ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Je n'ai pas vraiment de préférence »", correct: false },
      { text: "Exprimer un intérêt sincère et argumenté pour le secteur", correct: true },
      { text: "« C'est le seul qui recrute »", correct: false },
      { text: "« Pour l'argent, c'est tout »", correct: false },
    ],
    explanation: "Le recruteur veut sentir un intérêt réel pour le domaine. Un argument personnel et concret (enjeux, évolution, sens) montre que tu t'inscris durablement.",
    tip: "Relie le secteur à une conviction ou une expérience.",
  },
  {
    id: 'moti-4', category: 'motivation', difficulty: 3,
    situation: "« Vous postulez aussi chez nos concurrents. Pourquoi nous ? »",
    question: "La réponse qui fait la différence :",
    options: [
      { text: "« Vous êtes tous pareils »", correct: false },
      { text: "Citer ce qui distingue précisément CETTE entreprise (valeurs, projet, produits)", correct: true },
      { text: "« Vous payez mieux »", correct: false },
      { text: "Nier postuler ailleurs alors que c'est le cas", correct: false },
    ],
    explanation: "On valorise un élément différenciant et spécifique à l'entreprise. C'est ce qui prouve que ta candidature n'est pas un simple envoi de masse.",
    tip: "Prépare un argument propre à chaque entreprise.",
  },
  {
    id: 'moti-5', category: 'motivation', difficulty: 2,
    situation: "« Où vous voyez-vous dans 5 ans ? »",
    question: "La meilleure approche :",
    options: [
      { text: "« Je n'en ai aucune idée »", correct: false },
      { text: "Une projection réaliste, cohérente avec le poste et l'entreprise", correct: true },
      { text: "« À votre place, à diriger l'entreprise »", correct: false },
      { text: "« Ailleurs, dans un autre métier »", correct: false },
    ],
    explanation: "On montre de l'ambition réaliste et alignée avec ce que l'entreprise peut offrir (évolution, expertise), sans paraître flou ni menaçant.",
    tip: "Montre une trajectoire, pas un plan rigide année par année.",
  },
  {
    id: 'moti-6', category: 'motivation', difficulty: 1,
    situation: "« Qu'est-ce qui vous motive au travail ? »",
    question: "La réponse la plus solide :",
    options: [
      { text: "« Surtout les congés et la pause déjeuner »", correct: false },
      { text: "Des moteurs concrets (apprendre, relever des défis, l'impact, l'équipe)", correct: true },
      { text: "« Rien de particulier »", correct: false },
      { text: "« Finir le plus vite possible »", correct: false },
    ],
    explanation: "On attend des moteurs professionnels authentiques et positifs. Ils en disent long sur ton implication et ta façon de travailler.",
    tip: "Choisis des moteurs cohérents avec le poste proposé.",
  },
  {
    id: 'moti-7', category: 'motivation', difficulty: 3,
    situation: "Vous êtes très motivé mais le salaire affiché est en dessous de vos attentes.",
    question: "Comment exprimer votre motivation sans vous brader ?",
    options: [
      { text: "Cacher totalement la question du salaire", correct: false },
      { text: "Affirmer son intérêt réel tout en abordant la rémunération au bon moment", correct: true },
      { text: "« Le salaire, je m'en fiche complètement »", correct: false },
      { text: "Commencer l'entretien en exigeant une augmentation", correct: false },
    ],
    explanation: "Motivation et rémunération ne s'opposent pas : on montre un intérêt sincère pour le poste, et la question salariale se traite au moment opportun, sereinement.",
    tip: "L'intérêt d'abord, la négociation ensuite.",
  },
  {
    id: 'moti-8', category: 'motivation', difficulty: 3,
    context: "Ancien commercial, vous vous reconvertissez en chef de projet. Le recruteur veut comprendre la solidité de votre motivation pour ce virage.",
    situation: "« Qu'est-ce qui vous pousse vraiment à changer de métier ? »",
    question: "La réponse la plus crédible :",
    options: [
      { text: "« Mon métier actuel m'ennuie, je tente autre chose »", correct: false },
      { text: "Une motivation réfléchie : déclic, démarche concrète déjà engagée, projet clair", correct: true },
      { text: "« Je ne sais pas trop, on verra bien »", correct: false },
      { text: "« C'était ça ou le chômage »", correct: false },
    ],
    explanation: "Une reconversion solide se prouve par des actes (formation, projets, réseau) et un projet clair. Le recruteur cherche à éviter le candidat qui fuit plutôt qu'il ne choisit.",
    tip: "Montre les démarches déjà entreprises pour ton nouveau métier.",
  },
  {
    id: 'moti-9', category: 'motivation', difficulty: 2,
    situation: "Le poste implique de la mobilité géographique.",
    question: "Comment montrer votre motivation sur ce point ?",
    options: [
      { text: "Dire oui à tout, même ce qu'on ne pourra pas tenir", correct: false },
      { text: "Être honnête sur ses possibilités réelles de mobilité", correct: true },
      { text: "Refuser net sans discuter", correct: false },
      { text: "Éluder la question", correct: false },
    ],
    explanation: "Mieux vaut une réponse honnête et claire qu'un faux oui qui posera problème plus tard. La sincérité sur la mobilité protège les deux parties.",
    tip: "Si tu as des contraintes, dis-le, mais propose des solutions.",
  },
  {
    id: 'moti-10', category: 'motivation', difficulty: 2,
    situation: "Le poste est un peu en dessous de vos qualifications.",
    question: "Comment exprimer une motivation crédible ?",
    options: [
      { text: "« Je prends ça en attendant mieux »", correct: false },
      { text: "Expliquer ce que ce poste vous apporte concrètement aujourd'hui", correct: true },
      { text: "Faire semblant de ne pas être qualifié", correct: false },
      { text: "Montrer du mépris pour le poste", correct: false },
    ],
    explanation: "Le recruteur craint un candidat qui partira vite. On rassure en expliquant pourquoi ce poste a du sens maintenant (secteur, équipe, apprentissage, équilibre).",
    tip: "Donne une raison positive et durable de vouloir CE poste.",
  },
  {
    id: 'moti-11', category: 'motivation', difficulty: 3,
    situation: "Vous enchaînez les refus depuis des semaines et le moral est bas.",
    question: "Comment aborder l'entretien malgré tout ?",
    options: [
      { text: "Montrer son découragement et sa lassitude", correct: false },
      { text: "Arriver avec énergie et motivation, sans étaler ses échecs", correct: true },
      { text: "Supplier qu'on vous prenne", correct: false },
      { text: "Dire « Vous êtes ma dernière chance »", correct: false },
    ],
    explanation: "Le recruteur ne doit pas porter ton historique de refus. On se présente avec une énergie neuve : chaque entretien est une page blanche.",
    tip: "Le moral se travaille avant d'entrer dans la pièce.",
  },
  {
    id: 'moti-12', category: 'motivation', difficulty: 1,
    situation: "« Qu'attendez-vous de ce poste ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Un salaire et c'est tout »", correct: false },
      { text: "Des attentes réalistes alignées avec ce que le poste peut offrir", correct: true },
      { text: "« Que vous me formiez à tout sans rien faire »", correct: false },
      { text: "« Aucune attente particulière »", correct: false },
    ],
    explanation: "On exprime des attentes professionnelles cohérentes (missions, apprentissage, évolution) qui montrent que tu as réfléchi à l'adéquation poste/projet.",
    tip: "Équilibre ce que tu attends et ce que tu apportes.",
  },
  {
    id: 'moti-13', category: 'motivation', difficulty: 3,
    situation: "Vous revenez dans un secteur que vous aviez quitté il y a quelques années.",
    question: "Comment justifier ce retour ?",
    options: [
      { text: "« Je n'ai rien trouvé d'autre »", correct: false },
      { text: "Expliquer ce qui vous y ramène volontairement et ce que vous avez gagné entre-temps", correct: true },
      { text: "Critiquer le secteur où vous étiez parti", correct: false },
      { text: "Éviter d'expliquer le détour", correct: false },
    ],
    explanation: "Un retour assumé et argumenté (recul pris, compétences acquises ailleurs, attrait renouvelé) est rassurant et montre de la cohérence.",
    tip: "Valorise ce que ton « détour » t'a appris.",
  },
  {
    id: 'moti-14', category: 'motivation', difficulty: 2,
    situation: "Le poste est principalement en télétravail.",
    question: "Comment montrer que cela vous motive ET que vous saurez gérer ?",
    options: [
      { text: "« Je préfère parce que je n'aime pas les gens »", correct: false },
      { text: "Mettre en avant son autonomie, sa rigueur et son organisation à distance", correct: true },
      { text: "« Comme ça je pourrai faire autre chose à côté »", correct: false },
      { text: "Avouer qu'on a du mal à se concentrer seul", correct: false },
    ],
    explanation: "Le télétravail exige autonomie et discipline. On rassure en montrant qu'on sait s'organiser et rester impliqué sans supervision directe.",
    tip: "Donne un exemple concret de travail mené en autonomie.",
  },
  {
    id: 'moti-15', category: 'motivation', difficulty: 2,
    situation: "« Qu'est-ce qui vous fait vous lever le matin ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Le réveil qui sonne »", correct: false },
      { text: "Un moteur sincère lié au sens, au défi ou à l'utilité de son travail", correct: true },
      { text: "« Rien, j'y vais par obligation »", correct: false },
      { text: "Une réponse toute faite sans conviction", correct: false },
    ],
    explanation: "Cette question cherche ta source d'énergie profonde. Une réponse authentique et alignée avec le poste révèle un engagement durable.",
    tip: "Sois sincère : l'authenticité s'entend.",
  },
  {
    id: 'moti-16', category: 'motivation', difficulty: 3,
    situation: "« Pourquoi nous, et pas une entreprise plus grande et plus connue ? »",
    question: "La réponse la plus pertinente :",
    options: [
      { text: "« Faute de mieux »", correct: false },
      { text: "Valoriser ce que cette structure offre (proximité, polyvalence, impact, projet)", correct: true },
      { text: "« Les grandes ne m'ont pas pris »", correct: false },
      { text: "« La taille m'est égale, peu importe »", correct: false },
    ],
    explanation: "Chaque taille d'entreprise a ses atouts. Montrer qu'on a choisi celle-ci pour ses avantages spécifiques prouve une motivation réfléchie.",
    tip: "Dans une PME, valorise polyvalence et impact direct.",
  },
  {
    id: 'moti-17', category: 'motivation', difficulty: 2,
    situation: "Le recruteur teste si votre motivation est sincère ou opportuniste.",
    question: "Qu'est-ce qui rend une motivation crédible ?",
    options: [
      { text: "Des superlatifs « j'adore tout chez vous »", correct: false },
      { text: "Des arguments précis, documentés et reliés à votre parcours", correct: true },
      { text: "Répéter le mot « motivé » plusieurs fois", correct: false },
      { text: "Flatter le recruteur sans rapport avec le poste", correct: false },
    ],
    explanation: "La motivation crédible repose sur du concret (faits sur l'entreprise, lien avec ton projet), pas sur des déclarations enthousiastes mais creuses.",
    tip: "Une preuve vaut dix superlatifs.",
  },
  {
    id: 'moti-18', category: 'motivation', difficulty: 2,
    situation: "Le poste comporte des horaires décalés ou du travail le week-end.",
    question: "Comment réagir si cela vous est présenté ?",
    options: [
      { text: "Cacher que ça pose un vrai problème pour l'accepter quand même", correct: false },
      { text: "Évaluer honnêtement sa compatibilité et le dire clairement", correct: true },
      { text: "Râler immédiatement", correct: false },
      { text: "Promettre une disponibilité totale impossible à tenir", correct: false },
    ],
    explanation: "Accepter des contraintes qu'on ne pourra pas assumer mène à l'échec rapide. L'honnêteté sur sa disponibilité réelle est un gage de fiabilité.",
    tip: "Mieux vaut un non clair qu'un oui intenable.",
  },
  {
    id: 'moti-19', category: 'motivation', difficulty: 1,
    situation: "« Pourquoi avoir choisi ce métier précis ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Par hasard »", correct: false },
      { text: "Un déclic ou un intérêt concret, illustré par un exemple", correct: true },
      { text: "« Parce que ça paie bien »", correct: false },
      { text: "« Mes parents m'ont poussé »", correct: false },
    ],
    explanation: "Une histoire d'engagement (rencontre, expérience, passion) rend ta motivation tangible et mémorable, bien plus qu'une raison purement matérielle.",
    tip: "Raconte le moment où ce métier t'a attiré.",
  },
  {
    id: 'moti-20', category: 'motivation', difficulty: 3,
    situation: "« Comment gardez-vous votre motivation sur la durée ? »",
    question: "La réponse la plus mature :",
    options: [
      { text: "« Je ne sais pas, ça dépend des jours »", correct: false },
      { text: "Citer des leviers concrets (objectifs, apprentissage continu, sens)", correct: true },
      { text: "« Je change de job dès que je m'ennuie »", correct: false },
      { text: "« La motivation, ça ne se contrôle pas »", correct: false },
    ],
    explanation: "Savoir entretenir sa motivation (se fixer des objectifs, apprendre, donner du sens) rassure sur ta stabilité et ta maturité professionnelle.",
    tip: "Montre que tu es acteur de ta motivation.",
  },
  {
    id: 'moti-21', category: 'motivation', difficulty: 2,
    situation: "Le poste comporte une part de tâches répétitives.",
    question: "Comment montrer que cela ne vous démotivera pas ?",
    options: [
      { text: "« Je déteste la routine, ça me tuera »", correct: false },
      { text: "Reconnaître la part de routine et montrer comment on y trouve de la rigueur/du sens", correct: true },
      { text: "Prétendre adorer la monotonie", correct: false },
      { text: "Dire qu'on bâclera ces tâches", correct: false },
    ],
    explanation: "Tout poste a sa part de répétitif. Montrer qu'on l'accepte avec sérieux, tout en cherchant à l'optimiser, est rassurant et réaliste.",
    tip: "Valorise ta capacité à fiabiliser les tâches récurrentes.",
  },
  {
    id: 'moti-22', category: 'motivation', difficulty: 3,
    situation: "« Qu'est-ce qui vous démotive ou vous déçoit au travail ? »",
    question: "Comment répondre habilement ?",
    options: [
      { text: "Faire une longue liste de récriminations", correct: false },
      { text: "Citer un point de manière mesurée et dire comment on le gère", correct: true },
      { text: "« Rien ne me démotive jamais »", correct: false },
      { text: "Dénigrer ses anciens employeurs", correct: false },
    ],
    explanation: "On reste lucide mais constructif : nommer un facteur (ex. manque de feedback) et expliquer comment on y fait face montre maturité et recul.",
    tip: "Tourne le négatif vers une solution.",
  },
  {
    id: 'moti-23', category: 'motivation', difficulty: 2,
    situation: "« Pourquoi changer maintenant, après plusieurs années au même poste ? »",
    question: "La meilleure justification :",
    options: [
      { text: "« Je m'ennuie, c'est tout »", correct: false },
      { text: "Un besoin d'évolution ou de nouveau défi, présenté positivement", correct: true },
      { text: "« On m'a poussé vers la sortie »", correct: false },
      { text: "« Pour gagner plus, uniquement »", correct: false },
    ],
    explanation: "Le timing du changement doit sembler réfléchi : recherche d'évolution, nouveau cap, montée en compétences. On évite l'amertume ou la seule motivation financière.",
    tip: "« J'ai fait le tour de mon poste, je veux progresser. »",
  },
  {
    id: 'moti-24', category: 'motivation', difficulty: 2,
    situation: "On vous propose un CDD alors que vous cherchiez un CDI.",
    question: "Comment exprimer votre motivation ?",
    options: [
      { text: "Accepter en cachant sa déception puis partir au premier CDI venu", correct: false },
      { text: "Montrer son intérêt réel et voir le CDD comme une opportunité de faire ses preuves", correct: true },
      { text: "Refuser avec mépris", correct: false },
      { text: "Exiger un CDI immédiat sous peine de refus", correct: false },
    ],
    explanation: "Un CDD peut être un tremplin. Montrer qu'on s'y investira pleinement, tout en restant transparent sur ses objectifs, est une posture gagnante.",
    tip: "Un CDD bien mené débouche souvent sur un CDI.",
  },
  {
    id: 'moti-25', category: 'motivation', difficulty: 2,
    situation: "« Si une autre entreprise vous proposait plus, partiriez-vous ? »",
    question: "La réponse la plus habile :",
    options: [
      { text: "« Oui, évidemment, je suis là pour l'argent »", correct: false },
      { text: "Rappeler que le salaire compte mais que l'intérêt et le projet priment", correct: true },
      { text: "« Jamais, je resterai à vie quoi qu'il arrive »", correct: false },
      { text: "Se montrer offensé par la question", correct: false },
    ],
    explanation: "On évite les extrêmes : reconnaître que la rémunération compte, mais souligner que l'intérêt du poste, l'équipe et le projet pèsent dans la balance.",
    tip: "Montre que tu cherches plus qu'un chiffre.",
  },
  {
    id: 'moti-26', category: 'motivation', difficulty: 2,
    situation: "« Quelles sont vos priorités : équilibre vie pro/perso ou carrière ? »",
    question: "La meilleure manière de répondre :",
    options: [
      { text: "« La vie perso avant tout, le travail je m'en moque »", correct: false },
      { text: "Assumer un équilibre tout en montrant son engagement professionnel", correct: true },
      { text: "« La carrière, je sacrifie tout le reste »", correct: false },
      { text: "Éviter la question", correct: false },
    ],
    explanation: "On peut assumer vouloir un équilibre sain — c'est légitime et gage de durabilité — tout en démontrant son sérieux et son implication au travail.",
    tip: "Équilibre n'est pas désengagement : explique-le.",
  },
  {
    id: 'moti-27', category: 'motivation', difficulty: 3,
    situation: "« Souhaitez-vous évoluer vers du management ? »",
    question: "Vous n'êtes pas certain. Comment répondre ?",
    options: [
      { text: "Mentir en disant un oui catégorique pour plaire", correct: false },
      { text: "Répondre honnêtement selon son projet, en restant ouvert", correct: true },
      { text: "« Surtout pas, jamais de la vie »", correct: false },
      { text: "« Je veux votre poste rapidement »", correct: false },
    ],
    explanation: "Pas besoin de feindre une ambition managériale. Une réponse honnête et ouverte (envie de progresser, à voir selon les opportunités) est plus crédible qu'un faux oui.",
    tip: "Reste sincère sur tes aspirations réelles.",
  },
  {
    id: 'moti-28', category: 'motivation', difficulty: 1,
    situation: "« Qu'est-ce qui vous attire le plus dans cette offre ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Tout, en général »", correct: false },
      { text: "Cibler 1-2 aspects précis de l'offre qui résonnent avec son profil", correct: true },
      { text: "« Le fait que ce soit un emploi »", correct: false },
      { text: "« Les avantages et les congés »", correct: false },
    ],
    explanation: "Citer des éléments précis de l'offre (missions, techno, périmètre) prouve qu'on l'a lue attentivement et qu'on s'y projette vraiment.",
    tip: "Reprends un mot exact de l'annonce qui t'a parlé.",
  },
  {
    id: 'moti-29', category: 'motivation', difficulty: 3,
    situation: "« Si vous gagniez au loto, continueriez-vous à travailler ? »",
    question: "La réponse qui révèle une bonne motivation :",
    options: [
      { text: "« Non, j'arrêterais immédiatement »", correct: false },
      { text: "Montrer que le travail apporte aussi du sens, du lien, de l'accomplissement", correct: true },
      { text: "« Je ne sais pas, je n'y ai jamais pensé »", correct: false },
      { text: "Éluder par une blague et ne rien dire", correct: false },
    ],
    explanation: "Cette question piège évalue ton rapport au travail. Reconnaître qu'il a une valeur au-delà de l'argent (utilité, lien social, réalisation) révèle une motivation profonde.",
    tip: "Le travail n'est pas qu'un salaire : montre-le.",
  },
  {
    id: 'moti-30', category: 'motivation', difficulty: 2,
    situation: "On vous demande de conclure sur votre motivation en fin d'entretien.",
    question: "Comment finir fort ?",
    options: [
      { text: "« Bon, voilà, j'espère que ça ira »", correct: false },
      { text: "Réaffirmer clairement son intérêt pour le poste et sa valeur ajoutée", correct: true },
      { text: "Répéter qu'on a vraiment besoin du job", correct: false },
      { text: "Ne rien ajouter et partir", correct: false },
    ],
    explanation: "La phrase de clôture est une dernière chance de marquer. Une réaffirmation sincère et synthétique de ta motivation et de ton apport laisse une forte impression.",
    tip: "Prépare une phrase de clôture percutante.",
  },
];
