/**
 * Thème « Parcours (méthode STAR) » — 20 scénarios.
 * Raconter ses expériences, réussites et échecs de façon structurée et crédible.
 * Chaque question : exactement une option correct:true, + explanation + tip.
 */
export default [
  {
    id: 'star-1', category: 'parcours', difficulty: 2,
    situation: "« Donnez-moi un exemple d'un problème que vous avez résolu. »",
    question: "Comment structurer une réponse percutante ?",
    options: [
      { text: "Méthode STAR : Situation, Tâche, Action, Résultat", correct: true },
      { text: "Rester vague pour ne pas se tromper", correct: false },
      { text: "Parler du problème sans dire comment on l'a résolu", correct: false },
      { text: "Dire « Je n'ai jamais eu de problème »", correct: false },
    ],
    explanation: "La méthode STAR rend une anecdote claire et mémorable, et met en valeur ton action et le résultat chiffré obtenu.",
    tip: "Termine toujours par un résultat concret, si possible chiffré.",
  },
  {
    id: 'star-2', category: 'parcours', difficulty: 3,
    situation: "Vous décrivez une réussite d'équipe à laquelle vous avez participé.",
    question: "Quelle formulation est la plus juste ?",
    options: [
      { text: "Tout attribuer à soi : « j'ai tout fait »", correct: false },
      { text: "Dire « on a fait » sans jamais préciser son rôle", correct: false },
      { text: "Valoriser le collectif ET clarifier sa contribution personnelle", correct: true },
      { text: "Minimiser son rôle par modestie", correct: false },
    ],
    explanation: "Le recruteur évalue TA contribution. On crédite l'équipe mais on précise ce qu'on a personnellement apporté.",
    tip: "« Mon rôle a été de… » est une formule clé.",
  },
  {
    id: 'mes-1', category: 'parcours', difficulty: 3,
    context: "Vous postulez comme chargé(e) de clientèle dans une banque. Le recruteur, directeur d'agence, cherche quelqu'un capable de gérer la pression d'un guichet. Il se penche en avant : « Racontez-moi une fois où un client était furieux. »",
    situation: "Un client mécontent hausse le ton devant les autres clients.",
    question: "Quelle réponse démontre le mieux votre sang-froid ?",
    options: [
      { text: "« Je l'aurais ignoré, ce n'est pas mon problème »", correct: false },
      { text: "Décrire (STAR) comment vous l'avez isolé, écouté, puis proposé une solution concrète", correct: true },
      { text: "« Je serais allé chercher mon manager immédiatement »", correct: false },
      { text: "« Je lui aurais dit de se calmer ou de partir »", correct: false },
    ],
    explanation: "Face à un conflit client, on attend de l'écoute active, de la désescalade (isoler, reformuler) et une solution. La méthode STAR rend l'exemple crédible.",
    tip: "Montre que tu gardes le client ET l'image de l'entreprise.",
  },
  {
    id: 'parc-4', category: 'parcours', difficulty: 1,
    situation: "« Quel est l'élément le plus important d'une bonne anecdote en entretien ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "Un résultat concret et mesurable à la fin", correct: true },
      { text: "Une histoire la plus longue possible", correct: false },
      { text: "Beaucoup de détails techniques sans rapport", correct: false },
      { text: "Le nom de tous les collègues impliqués", correct: false },
    ],
    explanation: "Le résultat est ce qui prouve ta valeur. Sans résultat, l'anecdote reste une intention. Chiffre-le quand c'est possible (temps gagné, clients satisfaits, erreurs évitées).",
    tip: "Pas de chiffre ? Décris l'impact concret : « le client est revenu », « le projet a été livré à temps ».",
  },
  {
    id: 'parc-5', category: 'parcours', difficulty: 2,
    situation: "« Parlez-moi d'un échec que vous avez vécu. »",
    question: "La meilleure stratégie :",
    options: [
      { text: "« Je n'ai jamais échoué »", correct: false },
      { text: "Raconter un vrai échec, ce que vous en avez appris et ce que vous faites différemment depuis", correct: true },
      { text: "Citer un échec catastrophique non assumé", correct: false },
      { text: "Accuser les autres de l'échec", correct: false },
    ],
    explanation: "Le recruteur teste ta lucidité et ta capacité à rebondir. Un échec assumé + une leçon tirée montre de la maturité. Nier ou blâmer les autres sonne faux.",
    tip: "La structure gagnante : ce qui s'est passé → ma part de responsabilité → ce que j'ai changé.",
  },
  {
    id: 'parc-6', category: 'parcours', difficulty: 2,
    situation: "Vous voulez illustrer votre esprit d'initiative.",
    question: "Quel exemple est le plus convaincant ?",
    options: [
      { text: "« En vrai j'ai pas trop d'exemple, je fais juste ce qu'on me demande »", correct: false },
      { text: "Une situation où vous avez repéré un problème et proposé une amélioration sans qu'on vous le demande", correct: true },
      { text: "« J'arrive toujours à l'heure »", correct: false },
      { text: "Une initiative inventée pour l'occasion", correct: false },
    ],
    explanation: "L'initiative se prouve par un fait : tu as vu quelque chose, tu as agi de toi-même, ça a eu un effet. La ponctualité est attendue, ce n'est pas une initiative.",
    tip: "Prépare 2-3 anecdotes « j'ai pris les devants » avant l'entretien.",
  },
  {
    id: 'parc-7', category: 'parcours', difficulty: 2,
    situation: "« Racontez-moi une fois où vous avez travaillé sous pression. »",
    question: "Quelle réponse valorise le mieux votre profil ?",
    options: [
      { text: "« La pression je gère pas trop, ça me stresse »", correct: false },
      { text: "Décrire une période chargée, comment vous avez priorisé, et le résultat tenu malgré tout", correct: true },
      { text: "« J'ai craqué et tout abandonné »", correct: false },
      { text: "Dire que vous n'avez jamais été sous pression", correct: false },
    ],
    explanation: "On veut voir ta méthode face au stress : prioriser, organiser, demander de l'aide si besoin, et tenir l'objectif. C'est la méthode qui rassure, pas le fait de « ne jamais stresser ».",
    tip: "Montre comment tu organises (liste de priorités, étapes) plutôt que de dire « je gère ».",
  },
  {
    id: 'parc-8', category: 'parcours', difficulty: 1,
    situation: "Vous racontez une expérience mais le recruteur semble perdu.",
    question: "Quelle est probablement l'erreur ?",
    options: [
      { text: "Vous avez sauté le contexte (le « S » et le « T » de STAR)", correct: true },
      { text: "Vous avez été trop clair", correct: false },
      { text: "Vous avez donné un résultat", correct: false },
      { text: "Vous avez parlé trop lentement", correct: false },
    ],
    explanation: "Sans poser la situation et la tâche, l'interlocuteur ne comprend pas l'enjeu de ton action. Toujours planter le décor en une phrase avant de raconter ce que tu as fait.",
    tip: "Une phrase de contexte suffit : « À mon stage, on avait perdu un fournisseur clé… ».",
  },
  {
    id: 'parc-9', category: 'parcours', difficulty: 3,
    context: "Poste en restauration rapide, manager de shift. Le recruteur veut un profil capable de tenir un coup de feu. « Une fois où tout est parti en vrille, racontez. »",
    situation: "Service du midi, deux équipiers absents, file qui s'allonge.",
    question: "La réponse qui impressionne :",
    options: [
      { text: "« On a fermé une caisse et tant pis pour les clients »", correct: false },
      { text: "Expliquer comment vous avez réparti les rôles, communiqué avec les clients sur l'attente, et limité la casse", correct: true },
      { text: "« J'ai paniqué et appelé mon responsable »", correct: false },
      { text: "« C'était le bordel, on a fait ce qu'on a pu »", correct: false },
    ],
    explanation: "Dans l'urgence, on attend de l'organisation (répartir, prioriser) et de la communication (rassurer les clients). Le langage relâché (« le bordel ») casse l'image de sang-froid.",
    tip: "Même dans le chaos, montre une décision structurée : « j'ai d'abord… puis… ».",
  },
  {
    id: 'parc-10', category: 'parcours', difficulty: 2,
    situation: "« Donnez-moi un exemple de travail en équipe difficile. »",
    question: "La meilleure approche :",
    options: [
      { text: "Critiquer ouvertement un ancien collègue « incompétent »", correct: false },
      { text: "Décrire la difficulté avec neutralité et comment vous avez fait avancer le groupe", correct: true },
      { text: "Dire que vous préférez travailler seul", correct: false },
      { text: "« Les gens sont nuls, c'est tout »", correct: false },
    ],
    explanation: "Le recruteur observe comment tu parles des autres. Reste factuel, sans dénigrer, et montre ce que TU as fait pour débloquer la situation (dialogue, répartition, compromis).",
    tip: "Ne jamais casser un ancien collègue : ça en dit plus sur toi que sur lui.",
  },
  {
    id: 'parc-11', category: 'parcours', difficulty: 2,
    situation: "« Quelle est votre plus grande réussite professionnelle ? »",
    question: "Si vous débutez et avez peu d'expérience :",
    options: [
      { text: "Dire que vous n'avez rien réussi d'important", correct: false },
      { text: "Valoriser une réussite de stage, d'alternance, de projet d'école ou associatif", correct: true },
      { text: "Inventer une réussite spectaculaire", correct: false },
      { text: "Parler d'un exploit personnel sans lien avec le travail", correct: false },
    ],
    explanation: "Une réussite n'a pas besoin d'être un exploit : un projet mené à bien, un objectif de stage atteint, une responsabilité associative comptent. L'important est de la raconter avec méthode.",
    tip: "Un projet d'école bien expliqué vaut une expérience pro.",
  },
  {
    id: 'parc-12', category: 'parcours', difficulty: 1,
    situation: "Le recruteur demande « et ensuite ? » après votre anecdote.",
    question: "Que cherche-t-il ?",
    options: [
      { text: "Le résultat et l'impact de votre action", correct: true },
      { text: "Que vous changiez complètement de sujet", correct: false },
      { text: "Que vous répétiez le début", correct: false },
      { text: "Que vous disiez « je sais plus »", correct: false },
    ],
    explanation: "« Et ensuite ? » est une invitation à conclure sur le résultat. C'est le moment de chiffrer ou de décrire l'effet concret de ce que tu as fait.",
    tip: "Garde toujours la « chute » de ton histoire pour la fin : le résultat.",
  },
  {
    id: 'parc-13', category: 'parcours', difficulty: 2,
    situation: "« Une fois où vous avez dû apprendre quelque chose très vite. »",
    question: "La meilleure réponse met en avant :",
    options: [
      { text: "Votre méthode pour monter en compétence rapidement", correct: true },
      { text: "Le fait que vous savez déjà tout", correct: false },
      { text: "Que vous détestez apprendre de nouvelles choses", correct: false },
      { text: "Que vous avez attendu qu'on vous forme", correct: false },
    ],
    explanation: "L'employabilité repose sur la capacité d'apprentissage. Décris ta démarche : tuto, observation d'un collègue, essais, prise de notes. La méthode prouve l'autonomie.",
    tip: "Montre que tu sais te débrouiller pour apprendre seul.",
  },
  {
    id: 'parc-14', category: 'parcours', difficulty: 3,
    situation: "« Racontez une situation où vous étiez en désaccord avec un responsable. »",
    question: "La réponse la plus mature :",
    options: [
      { text: "« Je me suis écrasé, on dit rien au chef »", correct: false },
      { text: "Avoir exposé votre point de vue avec respect, puis suivi la décision finale", correct: true },
      { text: "« J'ai claqué la porte »", correct: false },
      { text: "« J'avais raison et je lui ai bien fait comprendre »", correct: false },
    ],
    explanation: "On valorise l'assertivité respectueuse : oser donner son avis avec des arguments, tout en sachant se ranger à la décision hiérarchique. Ni soumission, ni rébellion.",
    tip: "« J'ai partagé mon avis, puis j'ai soutenu la décision prise » : la formule idéale.",
  },
  {
    id: 'parc-15', category: 'parcours', difficulty: 2,
    situation: "« Une fois où vous avez dépassé les attentes. »",
    question: "Quel exemple choisir ?",
    options: [
      { text: "Une situation où vous en avez fait un peu plus, avec un effet positif visible", correct: true },
      { text: "« J'ai fait le minimum mais c'était suffisant »", correct: false },
      { text: "Un exemple où vous avez surtout cherché à être vu du chef", correct: false },
      { text: "« Genre une fois j'ai fini plus tôt »", correct: false },
    ],
    explanation: "Dépasser les attentes, c'est apporter une valeur que personne n'exigeait : aider un collègue débordé, améliorer un process, soigner un détail client. L'effet doit être concret.",
    tip: "L'intention compte : on aide pour le résultat, pas pour être remarqué.",
  },
  {
    id: 'parc-16', category: 'parcours', difficulty: 1,
    situation: "Vous préparez vos anecdotes avant l'entretien.",
    question: "La bonne pratique :",
    options: [
      { text: "Préparer 4-5 histoires couvrant équipe, conflit, réussite, échec, initiative", correct: true },
      { text: "Tout improviser le jour J", correct: false },
      { text: "Apprendre un seul exemple par cœur mot à mot", correct: false },
      { text: "Ne rien préparer pour rester « naturel »", correct: false },
    ],
    explanation: "Quelques anecdotes solides et polyvalentes te permettent de répondre à la plupart des questions comportementales. On les prépare sans les réciter, pour rester naturel.",
    tip: "Une même anecdote peut servir à plusieurs questions selon l'angle choisi.",
  },
  {
    id: 'parc-17', category: 'parcours', difficulty: 2,
    situation: "« Une décision difficile que vous avez dû prendre. »",
    question: "La meilleure structure de réponse :",
    options: [
      { text: "Le dilemme → les options pesées → votre choix et pourquoi → le résultat", correct: true },
      { text: "« J'ai choisi au pif »", correct: false },
      { text: "Dire que vous évitez toujours de décider", correct: false },
      { text: "Raconter sans jamais dire ce que vous avez décidé", correct: false },
    ],
    explanation: "Une décision difficile montre ton raisonnement. On veut voir que tu as pesé le pour et le contre puis assumé un choix, avec un résultat. Le raisonnement compte autant que le résultat.",
    tip: "Explique POURQUOI tu as tranché : c'est ça qui révèle ton jugement.",
  },
  {
    id: 'parc-18', category: 'parcours', difficulty: 2,
    situation: "« Parlez-moi d'une critique que vous avez reçue. »",
    question: "La réaction qui rassure le recruteur :",
    options: [
      { text: "« On m'a jamais rien reproché »", correct: false },
      { text: "Accueillir l'exemple, montrer que vous avez écouté et ajusté votre travail", correct: true },
      { text: "« La critique était injuste, la personne avait tort »", correct: false },
      { text: "Dire que vous détestez qu'on vous critique", correct: false },
    ],
    explanation: "Savoir recevoir un feedback est une compétence clé. Montre que tu écoutes sans te braquer et que tu transformes la remarque en amélioration concrète.",
    tip: "« Sur le coup ça pique, mais ça m'a fait progresser sur… » fonctionne très bien.",
  },
  {
    id: 'parc-19', category: 'parcours', difficulty: 1,
    situation: "Votre anecdote dure depuis 4 minutes.",
    question: "Quel est le risque ?",
    options: [
      { text: "Perdre l'attention du recruteur en noyant l'essentiel", correct: true },
      { text: "Être trop synthétique", correct: false },
      { text: "Donner trop peu d'informations", correct: false },
      { text: "Paraître trop préparé", correct: false },
    ],
    explanation: "Une bonne anecdote tient en 1 à 2 minutes. Trop longue, elle dilue le message et lasse. Va à l'essentiel : contexte rapide, action, résultat.",
    tip: "Si le recruteur veut plus de détails, il te le demandera.",
  },
  {
    id: 'parc-20', category: 'parcours', difficulty: 3,
    context: "Poste d'assistant(e) commercial(e). La recruteuse, exigeante, cherche de la fiabilité. « Une fois où vous avez raté une échéance. »",
    situation: "Un dossier rendu en retard à cause d'une mauvaise estimation du temps.",
    question: "La meilleure façon de le raconter :",
    options: [
      { text: "« C'était la faute des autres, pas la mienne »", correct: false },
      { text: "Assumer, expliquer ce que vous avez mis en place pour ne plus que ça arrive", correct: true },
      { text: "« Un retard c'est pas grave, ça arrive »", correct: false },
      { text: "Cacher le retard et changer de sujet", correct: false },
    ],
    explanation: "Reconnaître un manquement et montrer le correctif (meilleure planification, alertes anticipées) inspire confiance. Banaliser le retard ou se défausser inquiète sur ta fiabilité.",
    tip: "Termine sur le système que tu as mis en place : c'est ça qui rassure.",
  },
];
