/**
 * Thème « Savoir-être & posture » — 20 scénarios.
 * Codes de l'entreprise, langage, attitude et comportement en entretien.
 * Chaque question : exactement une option correct:true, + explanation + tip.
 */
export default [
  {
    id: 'post-1', category: 'posture', difficulty: 1,
    situation: "Vous arrivez à l'entretien.",
    question: "Quel comportement fait la meilleure première impression ?",
    options: [
      { text: "Arriver pile à l'heure ou 5-10 min en avance, sourire, poignée franche", correct: true },
      { text: "Arriver 20 min en retard sans prévenir", correct: false },
      { text: "Garder son téléphone à la main", correct: false },
      { text: "S'asseoir avant d'y être invité", correct: false },
    ],
    explanation: "La première impression se joue en quelques secondes : ponctualité, sourire, contact visuel et politesse posent immédiatement le ton.",
    tip: "Coupe ton téléphone AVANT d'entrer.",
  },
  {
    id: 'post-2', category: 'posture', difficulty: 2,
    situation: "Le recruteur pose une question dont vous ignorez la réponse.",
    question: "Que faire ?",
    options: [
      { text: "Inventer une réponse au culot", correct: false },
      { text: "Rester honnête, montrer son raisonnement ou sa capacité à apprendre", correct: true },
      { text: "Rester muet et paniquer", correct: false },
      { text: "Changer de sujet brutalement", correct: false },
    ],
    explanation: "Personne ne sait tout. L'honnêteté et la capacité à réfléchir à voix haute valent mieux qu'un bluff qui s'effondre à la question suivante.",
    tip: "« Je ne maîtrise pas encore, mais voici comment j'aborderais… »",
  },
  {
    id: 'post-3', category: 'posture', difficulty: 2,
    situation: "Entretien en visioconférence.",
    question: "Quel est le point le plus important à soigner ?",
    options: [
      { text: "Cadre, lumière, connexion stable et regard vers la caméra", correct: true },
      { text: "Être allongé dans son lit", correct: false },
      { text: "Multiplier les onglets ouverts pour lire ses notes", correct: false },
      { text: "Couper sa caméra pour être à l'aise", correct: false },
    ],
    explanation: "En visio, l'environnement technique fait partie du professionnalisme : bonne lumière, fond neutre, connexion testée et regard caméra pour créer le contact.",
    tip: "Teste ton matériel 10 min avant le rendez-vous.",
  },
  {
    id: 'post-4', category: 'posture', difficulty: 1,
    situation: "Vous hésitez sur la tenue à porter.",
    question: "La règle la plus sûre :",
    options: [
      { text: "Une tenue propre, soignée et adaptée au secteur visé", correct: true },
      { text: "Un jogging, « pour être à l'aise »", correct: false },
      { text: "La tenue la plus chère possible", correct: false },
      { text: "Peu importe, on ne regarde pas", correct: false },
    ],
    explanation: "La tenue se cale sur les codes du secteur : plutôt formelle en banque, plus souple en start-up, mais toujours propre et soignée. En cas de doute, vaut mieux un cran trop habillé que trop relâché.",
    tip: "Regarde comment s'habillent les salariés de l'entreprise (photos, réseaux).",
  },
  {
    id: 'post-5', category: 'posture', difficulty: 2,
    situation: "Le recruteur vous serre la main et se présente.",
    question: "La meilleure réponse :",
    options: [
      { text: "Le regarder, sourire, donner votre nom et le remercier de l'accueil", correct: true },
      { text: "Regarder par terre en marmonnant", correct: false },
      { text: "Donner une poignée molle sans un mot", correct: false },
      { text: "« Yo, ça va ? »", correct: false },
    ],
    explanation: "Le contact initial donne le ton. Regard, sourire, voix claire et politesse créent une impression de confiance et de respect. Le langage trop familier casse immédiatement cette image.",
    tip: "Une poignée de main franche + un regard = confiance instantanée.",
  },
  {
    id: 'post-6', category: 'posture', difficulty: 2,
    situation: "Pendant l'entretien, vous utilisez souvent « euh », « genre », « du coup ».",
    question: "Pourquoi y faire attention ?",
    options: [
      { text: "Ces tics de langage nuisent à la clarté et à l'image de sérieux", correct: true },
      { text: "Ça n'a aucune importance", correct: false },
      { text: "Ça rend plus sympathique", correct: false },
      { text: "Il faut au contraire en mettre plus", correct: false },
    ],
    explanation: "Les tics de langage (« genre », « du coup », « voilà ») répétés brouillent le message et donnent une impression d'hésitation. Quelques silences valent mieux qu'un flot de mots parasites.",
    tip: "Mieux vaut une courte pause qu'un « euh » : le silence fait réfléchi, pas le « euh ».",
  },
  {
    id: 'post-7', category: 'posture', difficulty: 1,
    situation: "Vous êtes assis face au recruteur.",
    question: "Quelle posture corporelle adopter ?",
    options: [
      { text: "Dos droit, légèrement penché en avant, mains posées, regard ouvert", correct: true },
      { text: "Avachi dans le fauteuil, bras croisés", correct: false },
      { text: "Se balancer sur la chaise", correct: false },
      { text: "Jouer avec son stylo en permanence", correct: false },
    ],
    explanation: "Le langage corporel parle autant que les mots. Une posture droite et ouverte traduit l'engagement et l'écoute. Être avachi ou agité envoie un message de désintérêt ou de nervosité.",
    tip: "Pose tes mains sur la table : ça calme les gestes parasites.",
  },
  {
    id: 'post-8', category: 'posture', difficulty: 2,
    situation: "Le recruteur fait une blague.",
    question: "La bonne réaction :",
    options: [
      { text: "Sourire avec naturel, rester soi-même sans en faire trop", correct: true },
      { text: "Rester totalement de marbre", correct: false },
      { text: "Surenchérir avec une blague déplacée", correct: false },
      { text: "Rire de façon exagérée et forcée", correct: false },
    ],
    explanation: "Un peu d'humour détend l'échange et montre de l'aisance relationnelle. On y répond avec naturel, sans se forcer ni glisser vers le familier ou le déplacé.",
    tip: "Reste détendu mais professionnel : la convivialité, oui ; la familiarité, non.",
  },
  {
    id: 'post-9', category: 'posture', difficulty: 1,
    situation: "Vous tutoyez spontanément le recruteur.",
    question: "Quelle est la bonne règle ?",
    options: [
      { text: "Vouvoyer par défaut, sauf si on vous invite clairement à tutoyer", correct: true },
      { text: "Tutoyer tout le monde, c'est plus cool", correct: false },
      { text: "Alterner tu et vous au hasard", correct: false },
      { text: "Ne jamais s'adresser directement au recruteur", correct: false },
    ],
    explanation: "Le vouvoiement est la norme professionnelle de départ. On passe au tutoiement seulement si l'interlocuteur le propose. Tutoyer d'emblée peut être perçu comme un manque de respect des codes.",
    tip: "Dans le doute, vouvoie : tu ne te tromperas jamais.",
  },
  {
    id: 'post-10', category: 'posture', difficulty: 2,
    situation: "Le recruteur parle ; vous avez envie d'enchaîner sur votre idée.",
    question: "Quelle attitude adopter ?",
    options: [
      { text: "Écouter jusqu'au bout avant de répondre", correct: true },
      { text: "Couper la parole dès qu'une idée vous vient", correct: false },
      { text: "Finir ses phrases à sa place", correct: false },
      { text: "Hocher la tête sans écouter", correct: false },
    ],
    explanation: "L'écoute active est une compétence très observée. Laisser l'autre finir, puis rebondir avec pertinence, montre du respect et de la maîtrise. Couper la parole agace et trahit l'impatience.",
    tip: "Laisse toujours une demi-seconde de silence avant de répondre.",
  },
  {
    id: 'post-11', category: 'posture', difficulty: 3,
    context: "Entretien dans un cabinet d'avocats, environnement très formel. L'associé observe chaque détail de votre comportement.",
    situation: "Vous recevez un appel personnel pendant l'entretien (téléphone resté allumé).",
    question: "La bonne réaction :",
    options: [
      { text: "Cela n'aurait pas dû arriver : couper sans regarder et s'excuser brièvement", correct: true },
      { text: "Répondre « deux secondes, c'est important »", correct: false },
      { text: "Lire le message puis reprendre", correct: false },
      { text: "Laisser sonner jusqu'au bout", correct: false },
    ],
    explanation: "Le téléphone doit être éteint ou en silencieux avant d'entrer. Si l'erreur arrive, on coupe immédiatement sans regarder l'écran et on s'excuse. Répondre serait perçu comme un manque total de respect.",
    tip: "Éteins complètement ton téléphone, pas juste « vibreur ».",
  },
  {
    id: 'post-12', category: 'posture', difficulty: 1,
    situation: "On vous propose un café ou un verre d'eau.",
    question: "La bonne attitude :",
    options: [
      { text: "Accepter ou refuser poliment, avec un merci", correct: true },
      { text: "Se servir soi-même sans demander", correct: false },
      { text: "Demander autre chose qui n'est pas proposé", correct: false },
      { text: "Ignorer la proposition", correct: false },
    ],
    explanation: "Un détail simple mais révélateur : répondre poliment (oui ou non, avec un merci) montre du savoir-vivre. Accepter un verre d'eau peut même aider si tu as la gorge sèche par le stress.",
    tip: "Accepter un verre d'eau est une bonne idée : utile si le stress assèche la voix.",
  },
  {
    id: 'post-13', category: 'posture', difficulty: 2,
    situation: "Vous parlez de votre ancien employeur.",
    question: "La règle d'or :",
    options: [
      { text: "Rester correct et factuel, même en cas de mauvaise expérience", correct: true },
      { text: "Le critiquer ouvertement pour expliquer votre départ", correct: false },
      { text: "Révéler des informations confidentielles", correct: false },
      { text: "« C'était une boîte de nuls »", correct: false },
    ],
    explanation: "Casser un ancien employeur en dit plus long sur toi que sur lui : le recruteur se demande ce que tu diras de LUI demain. Reste factuel et tourné vers l'avenir, même après une mauvaise expérience.",
    tip: "Parle de ce que tu cherches désormais, pas de ce que tu fuis.",
  },
  {
    id: 'post-14', category: 'posture', difficulty: 2,
    situation: "Le recruteur reste silencieux quelques secondes après votre réponse.",
    question: "La meilleure réaction :",
    options: [
      { text: "Garder son calme : le silence est souvent une technique, pas un piège", correct: true },
      { text: "Combler à tout prix en parlant sans fin", correct: false },
      { text: "Paniquer et se contredire", correct: false },
      { text: "Demander « j'ai dit une bêtise ? »", correct: false },
    ],
    explanation: "Certains recruteurs laissent un silence pour voir si tu te déstabilises et en dis trop. Rester serein, voire conclure calmement, montre de l'assurance. Inutile de meubler nerveusement.",
    tip: "Si tu as fini ta réponse, assume le silence : tu n'as pas à tout combler.",
  },
  {
    id: 'post-15', category: 'posture', difficulty: 1,
    situation: "Vous prenez des notes pendant l'entretien.",
    question: "Est-ce une bonne idée ?",
    options: [
      { text: "Oui, un carnet et un stylo pour noter l'essentiel montrent du sérieux", correct: true },
      { text: "Non, c'est impoli", correct: false },
      { text: "Seulement sur son téléphone", correct: false },
      { text: "Noter absolument chaque mot, tête baissée", correct: false },
    ],
    explanation: "Venir avec un carnet et noter quelques points clés montre de l'organisation et de l'intérêt. On garde toutefois le contact visuel : on note l'essentiel, sans rester la tête plongée dans ses notes.",
    tip: "Un carnet papier fait meilleur effet que des notes sur smartphone.",
  },
  {
    id: 'post-16', category: 'posture', difficulty: 2,
    situation: "Vous sentez le stress monter et votre voix trembler.",
    question: "La meilleure technique sur le moment :",
    options: [
      { text: "Respirer lentement, ralentir le débit et prendre une gorgée d'eau", correct: true },
      { text: "Parler encore plus vite pour en finir", correct: false },
      { text: "S'excuser longuement d'être stressé", correct: false },
      { text: "Se figer et ne plus rien dire", correct: false },
    ],
    explanation: "Le stress se gère par le souffle et le rythme : respirer, ralentir, faire une courte pause. Un peu de stress est normal et le recruteur le sait ; l'important est de ne pas se laisser emporter.",
    tip: "Ralentir ton débit calme aussi ton rythme cardiaque.",
  },
  {
    id: 'post-17', category: 'posture', difficulty: 1,
    situation: "Vous croisez l'assistant(e) ou l'agent d'accueil avant l'entretien.",
    question: "Quelle attitude adopter ?",
    options: [
      { text: "Être tout aussi poli et aimable qu'avec le recruteur", correct: true },
      { text: "L'ignorer, ce n'est pas le décideur", correct: false },
      { text: "Être sec pour montrer qu'on est pressé", correct: false },
      { text: "Lui demander de prévenir qu'on est là, sans bonjour", correct: false },
    ],
    explanation: "Ton comportement avec TOUT le monde compte : l'accueil et les assistants donnent souvent leur ressenti au recruteur. La politesse n'est pas à géométrie variable.",
    tip: "On t'évalue dès le hall d'entrée, pas seulement dans le bureau.",
  },
  {
    id: 'post-18', category: 'posture', difficulty: 2,
    situation: "Le recruteur vous demande si vous avez bien trouvé les locaux.",
    question: "La meilleure réponse :",
    options: [
      { text: "Répondre brièvement et positivement, puis se rendre disponible", correct: true },
      { text: "Se plaindre longuement des transports", correct: false },
      { text: "Raconter toute sa matinée en détail", correct: false },
      { text: "Répondre sèchement « oui »", correct: false },
    ],
    explanation: "C'est une question de mise à l'aise, pas une vraie demande d'information. Une réponse brève et positive suffit, avant d'entrer dans le vif du sujet. Se plaindre démarre l'échange sur une note négative.",
    tip: "Réponds court et positif, puis laisse l'entretien commencer.",
  },
  {
    id: 'post-19', category: 'posture', difficulty: 2,
    situation: "Vous ne comprenez pas une question du recruteur.",
    question: "La bonne attitude :",
    options: [
      { text: "Demander poliment une précision ou reformuler pour vérifier", correct: true },
      { text: "Répondre à côté en espérant que ça passe", correct: false },
      { text: "Faire répéter sur un ton agacé", correct: false },
      { text: "Rester silencieux longtemps", correct: false },
    ],
    explanation: "Demander une précision n'est pas un aveu de faiblesse, au contraire : ça montre que tu veux bien répondre. Reformuler la question (« si je comprends bien… ») confirme aussi ton écoute.",
    tip: "« Pour être sûr de bien répondre, vous parlez de… ? » est toujours bien perçu.",
  },
  {
    id: 'post-20', category: 'posture', difficulty: 1,
    situation: "L'entretien se termine.",
    question: "La meilleure façon de partir :",
    options: [
      { text: "Remercier, dire votre intérêt pour le poste, saluer et partir posément", correct: true },
      { text: "Se lever d'un bond et filer sans un mot", correct: false },
      { text: "S'attarder longuement à discuter de tout", correct: false },
      { text: "Demander « alors, je suis pris ? » avec insistance", correct: false },
    ],
    explanation: "La sortie compte autant que l'entrée : un remerciement, une phrase d'intérêt sincère et un au revoir clair laissent une dernière impression positive. Partir précipitamment ou réclamer une réponse immédiate dénote.",
    tip: "Termine sur ta motivation : c'est la dernière chose dont le recruteur se souviendra.",
  },
];
