/**
 * Thème « Présentation » — 30 scénarios.
 * Chaque question : exactement une option correct:true, + explanation + tip.
 * `context` (optionnel) = mise en situation immersive.
 */
export default [
  {
    id: 'pres-1', category: 'presentation', difficulty: 1,
    situation: "Le recruteur ouvre l'entretien : « Parlez-moi de vous. »",
    question: "Quelle est la meilleure approche ?",
    options: [
      { text: "Raconter sa vie personnelle depuis l'enfance", correct: false },
      { text: "Un pitch de 1-2 min : qui je suis, mon parcours clé, ce que je cherche", correct: true },
      { text: "Répondre « Tout est sur mon CV »", correct: false },
      { text: "Lister tous ses emplois un par un dans le détail", correct: false },
    ],
    explanation: "C'est une question d'accroche : on attend un pitch structuré (présent → parcours → projet), orienté vers le poste, pas une autobiographie.",
    tip: "Prépare un pitch de 90 secondes et entraîne-toi à voix haute.",
  },
  {
    id: 'pres-2', category: 'presentation', difficulty: 2,
    situation: "Vous débutez et avez peu d'expérience professionnelle.",
    question: "Comment vous présenter sans paraître « vide » ?",
    options: [
      { text: "S'excuser de son manque d'expérience d'entrée de jeu", correct: false },
      { text: "Valoriser formation, projets, stages et soft skills concrètes", correct: true },
      { text: "Exagérer ou inventer des expériences", correct: false },
      { text: "Parler surtout de ses loisirs", correct: false },
    ],
    explanation: "Un profil junior se vend sur le potentiel : projets d'école, stages, alternance, qualités démontrées. Jamais s'excuser ni mentir.",
    tip: "Un projet d'école bien raconté vaut une expérience.",
  },
  {
    id: 'pres-3', category: 'presentation', difficulty: 2,
    situation: "Votre présentation dure depuis 5 minutes et le recruteur regarde sa montre.",
    question: "Qu'auriez-vous dû faire ?",
    options: [
      { text: "Continuer pour tout dire coûte que coûte", correct: false },
      { text: "Synthétiser : un pitch se tient en 1 à 2 minutes maximum", correct: true },
      { text: "Parler encore plus vite", correct: false },
      { text: "Recommencer depuis le début", correct: false },
    ],
    explanation: "Un pitch trop long perd l'attention. La concision est une compétence : on va à l'essentiel et on laisse le recruteur creuser.",
    tip: "Chronomètre-toi : vise 90 secondes.",
  },
  {
    id: 'pres-4', category: 'presentation', difficulty: 3,
    context: "Vous étiez aide-soignant et vous reconvertissez dans le développement web après une formation. Le recruteur, DSI, s'interroge sur ce grand écart.",
    situation: "« Votre parcours est atypique… expliquez-moi. »",
    question: "La meilleure façon de présenter sa reconversion :",
    options: [
      { text: "Minimiser son passé comme une erreur", correct: false },
      { text: "Assumer le fil rouge : compétences transférables + motivation réfléchie", correct: true },
      { text: "Dire qu'on a choisi au hasard", correct: false },
      { text: "Éviter de parler de l'ancien métier", correct: false },
    ],
    explanation: "Une reconversion bien racontée montre maturité et cohérence : on relie l'ancien et le nouveau (rigueur, relation humaine, gestion du stress) et on prouve que le choix est mûri.",
    tip: "Transforme ton passé en atout, pas en excuse.",
  },
  {
    id: 'pres-5', category: 'presentation', difficulty: 3,
    situation: "Votre CV montre un trou de 8 mois que le recruteur remarque.",
    question: "Comment l'aborder en présentation ?",
    options: [
      { text: "Mentir sur les dates", correct: false },
      { text: "Expliquer honnêtement et factuellement, et ce que cette période a apporté", correct: true },
      { text: "Espérer qu'il ne le remarque pas", correct: false },
      { text: "Se braquer et refuser d'en parler", correct: false },
    ],
    explanation: "Un trou n'est pas rédhibitoire : l'honnêteté et une explication sereine (formation, projet, raison personnelle assumée) rassurent bien plus que l'évitement.",
    tip: "Montre ce que tu as fait ou appris pendant cette période.",
  },
  {
    id: 'pres-6', category: 'presentation', difficulty: 2,
    situation: "Vous rédigez l'accroche de votre mail de candidature.",
    question: "Quelle première phrase capte le mieux l'attention ?",
    options: [
      { text: "« Je me permets de vous écrire concernant votre offre… »", correct: false },
      { text: "Une accroche personnalisée reliant votre atout-clé au besoin du poste", correct: true },
      { text: "« Bonjour, voici mon CV. »", correct: false },
      { text: "Un copier-coller générique envoyé à tous", correct: false },
    ],
    explanation: "À l'écrit comme à l'oral, l'accroche doit être personnalisée et orientée valeur. Les formules creuses passent inaperçues.",
    tip: "Mentionne l'entreprise ou le poste dès la première ligne.",
  },
  {
    id: 'pres-7', category: 'presentation', difficulty: 2,
    situation: "« Où vous voyez-vous, quel est votre projet professionnel ? »",
    question: "La présentation de projet la plus solide :",
    options: [
      { text: "« Je ne sais pas trop encore »", correct: false },
      { text: "Un cap clair et réaliste, cohérent avec le poste visé", correct: true },
      { text: "« Votre poste n'est qu'une étape avant de partir ailleurs »", correct: false },
      { text: "« Je veux votre poste à vous »", correct: false },
    ],
    explanation: "Un projet professionnel clair et aligné avec le poste rassure sur ta motivation et ta stabilité, sans paraître arriviste ni flou.",
    tip: "Montre une direction, pas une liste de rêves.",
  },
  {
    id: 'pres-8', category: 'presentation', difficulty: 1,
    situation: "« Décrivez-vous en trois mots. »",
    question: "La meilleure réponse :",
    options: [
      { text: "Trois adjectifs choisis et illustrés par un mini-exemple", correct: true },
      { text: "Dix qualités d'affilée", correct: false },
      { text: "« Je n'aime pas me résumer »", correct: false },
      { text: "Trois mots négatifs par fausse modestie", correct: false },
    ],
    explanation: "L'exercice teste ta capacité de synthèse et ta connaissance de toi. Trois mots pertinents, idéalement reliés au poste et appuyés d'un exemple, marquent les esprits.",
    tip: "Prépare-les à l'avance, avec une preuve pour chacun.",
  },
  {
    id: 'pres-9', category: 'presentation', difficulty: 2,
    situation: "Jeune diplômé, on vous demande de présenter vos études.",
    question: "Comment les valoriser ?",
    options: [
      { text: "Réciter la liste des matières du programme", correct: false },
      { text: "Mettre en avant projets, spécialisation et compétences concrètes acquises", correct: true },
      { text: "Dire « C'était une formation comme une autre »", correct: false },
      { text: "Parler uniquement de ses notes", correct: false },
    ],
    explanation: "Le recruteur veut savoir ce que tu sais FAIRE, pas le détail du programme. On illustre par des projets et des compétences applicables au poste.",
    tip: "Relie un projet d'études à une mission du poste.",
  },
  {
    id: 'pres-10', category: 'presentation', difficulty: 3,
    situation: "Vous passez d'un secteur (ex. retail) à un autre (ex. tech).",
    question: "Comment présenter ce changement de secteur ?",
    options: [
      { text: "Faire comme si l'expérience passée ne comptait pas", correct: false },
      { text: "Mettre en avant les compétences transférables et l'apport d'un regard neuf", correct: true },
      { text: "Critiquer son ancien secteur", correct: false },
      { text: "Cacher d'où l'on vient", correct: false },
    ],
    explanation: "Les compétences transférables (relation client, gestion, organisation) et la fraîcheur de regard sont des atouts. On construit un pont, on ne renie pas son passé.",
    tip: "« Ce que j'apporte de mon ancien secteur, c'est… »",
  },
  {
    id: 'pres-11', category: 'presentation', difficulty: 2,
    situation: "Le recruteur a sûrement regardé votre profil en ligne avant l'entretien.",
    question: "Quel réflexe de présentation est le plus pro ?",
    options: [
      { text: "Ignorer totalement sa présence en ligne", correct: false },
      { text: "Soigner son LinkedIn pour qu'il soit cohérent avec son discours", correct: true },
      { text: "Avoir un profil public avec des photos de soirée", correct: false },
      { text: "Mentir en entretien en espérant qu'il n'a rien vu", correct: false },
    ],
    explanation: "Ton e-réputation fait partie de ta présentation. Un LinkedIn cohérent et propre prolonge ton pitch ; des réseaux publics négligés le sabotent.",
    tip: "Vérifie ce qui ressort en googlant ton nom.",
  },
  {
    id: 'pres-12', category: 'presentation', difficulty: 2,
    situation: "Vous avez une expérience à l'étranger sur votre CV.",
    question: "Comment la présenter au mieux ?",
    options: [
      { text: "La survoler comme une parenthèse touristique", correct: false },
      { text: "Valoriser l'autonomie, l'adaptation et les compétences (langue, interculturel)", correct: true },
      { text: "Ne pas en parler de peur de paraître instable", correct: false },
      { text: "Insister uniquement sur les voyages et loisirs", correct: false },
    ],
    explanation: "Une expérience à l'étranger démontre adaptabilité, débrouillardise et ouverture. Bien présentée, c'est un différenciateur fort.",
    tip: "Quantifie : durée, langue parlée, missions réalisées.",
  },
  {
    id: 'pres-13', category: 'presentation', difficulty: 3,
    situation: "« Pourquoi devrais-je vous choisir vous, plutôt qu'un autre candidat ? »",
    question: "La meilleure posture :",
    options: [
      { text: "Dénigrer les autres candidats", correct: false },
      { text: "Mettre en avant sa combinaison unique de compétences + sa motivation", correct: true },
      { text: "« Je ne sais pas, c'est vous qui décidez »", correct: false },
      { text: "« Parce que je suis le meilleur, point. »", correct: false },
    ],
    explanation: "On répond sur SA valeur (mix de compétences, expériences, état d'esprit) sans jamais rabaisser les autres. Confiance, pas arrogance.",
    tip: "Une phrase : « Ce que je combine et qui est rare, c'est… »",
  },
  {
    id: 'pres-14', category: 'presentation', difficulty: 3,
    context: "Vous avez 20 ans d'expérience et postulez à un poste un cran en dessous de votre dernier rôle. Le recruteur craint que vous soyez « surqualifié » et vite parti.",
    situation: "« N'êtes-vous pas surqualifié pour ce poste ? »",
    question: "La réponse qui rassure :",
    options: [
      { text: "« Oui, mais je prends ce que je trouve »", correct: false },
      { text: "Expliquer un choix assumé et l'envie réelle de contribuer à ce poste", correct: true },
      { text: "Se vexer de la question", correct: false },
      { text: "Cacher une partie de son expérience", correct: false },
    ],
    explanation: "La crainte du recruteur est légitime : on la désamorce en expliquant sincèrement pourquoi ce poste a du sens MAINTENANT (équilibre, intérêt, transmission) et son engagement.",
    tip: "Montre que ton choix est réfléchi et durable.",
  },
  {
    id: 'pres-15', category: 'presentation', difficulty: 1,
    situation: "Vous devez ouvrir votre présentation.",
    question: "Quelle entrée en matière est la plus efficace ?",
    options: [
      { text: "Une phrase d'accroche claire qui pose qui vous êtes et votre fil conducteur", correct: true },
      { text: "« Euh… par où commencer… »", correct: false },
      { text: "Un long silence pour réfléchir", correct: false },
      { text: "Commencer par ses points faibles", correct: false },
    ],
    explanation: "Les premières secondes donnent le ton. Une accroche posée et assurée installe la confiance ; l'hésitation la sape immédiatement.",
    tip: "Apprends ta première phrase par cœur.",
  },
  {
    id: 'pres-16', category: 'presentation', difficulty: 2,
    situation: "Vous voulez mentionner vos qualités humaines (soft skills).",
    question: "Comment les présenter sans tomber dans le creux ?",
    options: [
      { text: "Lister « sérieux, motivé, dynamique » sans preuve", correct: false },
      { text: "Choisir 2-3 soft skills et les prouver par une situation vécue", correct: true },
      { text: "Affirmer qu'on a toutes les qualités", correct: false },
      { text: "Les citer en anglais pour faire moderne", correct: false },
    ],
    explanation: "Une soft skill non illustrée ne convainc personne. La preuve par l'exemple (« quand j'ai dû… ») rend la qualité crédible.",
    tip: "Pas de qualité sans anecdote.",
  },
  {
    id: 'pres-17', category: 'presentation', difficulty: 2,
    situation: "Le recruteur vous laisse raconter votre parcours librement.",
    question: "Quelle structure rend le récit mémorable ?",
    options: [
      { text: "Un fil narratif logique : déclic → étapes → projet actuel", correct: true },
      { text: "Énumérer les dates dans le désordre", correct: false },
      { text: "Sauter d'un sujet à l'autre sans lien", correct: false },
      { text: "Ne raconter que la dernière expérience", correct: false },
    ],
    explanation: "Un storytelling clair (un fil conducteur, des étapes qui s'enchaînent) aide le recruteur à te suivre et à retenir l'essentiel.",
    tip: "Donne du sens : pourquoi chaque étape a mené à la suivante.",
  },
  {
    id: 'pres-18', category: 'presentation', difficulty: 3,
    situation: "Vous avez changé de voie après une première orientation qui n'a pas marché.",
    question: "Comment présenter ce « faux départ » ?",
    options: [
      { text: "Le cacher complètement", correct: false },
      { text: "L'assumer comme une étape qui a clarifié votre vrai projet", correct: true },
      { text: "En parler avec amertume", correct: false },
      { text: "Blâmer l'école ou les profs", correct: false },
    ],
    explanation: "Un changement de cap assumé montre de la lucidité et du courage. On le présente comme un apprentissage, pas comme un échec subi.",
    tip: "« Cette première voie m'a appris que… »",
  },
  {
    id: 'pres-19', category: 'presentation', difficulty: 3,
    situation: "Vous enchaînez un entretien RH puis un entretien avec le manager opérationnel.",
    question: "Faut-il adapter sa présentation selon l'interlocuteur ?",
    options: [
      { text: "Non, le même discours mot pour mot partout", correct: false },
      { text: "Oui : plus culture/soft skills avec le RH, plus concret/technique avec l'opérationnel", correct: true },
      { text: "Tout miser sur la technique avec le RH", correct: false },
      { text: "Improviser totalement à chaque fois", correct: false },
    ],
    explanation: "Le RH évalue l'adéquation culturelle et le savoir-être ; l'opérationnel veut du concret métier. Adapter l'angle (pas le fond) montre de l'intelligence de situation.",
    tip: "Garde le même socle, ajuste les exemples mis en avant.",
  },
  {
    id: 'pres-20', category: 'presentation', difficulty: 3,
    situation: "« Pouvez-vous vous présenter en anglais ? »",
    question: "Vous n'êtes pas parfaitement bilingue. Que faire ?",
    options: [
      { text: "Paniquer et refuser", correct: false },
      { text: "Se lancer avec un pitch simple et assumé, sans viser la perfection", correct: true },
      { text: "Répondre en français en faisant semblant de ne pas comprendre", correct: false },
      { text: "Prétendre un niveau bilingue qu'on n'a pas", correct: false },
    ],
    explanation: "On valorise le fait d'essayer avec un anglais clair et structuré. L'aisance et l'attitude comptent souvent plus qu'un accent parfait — mais mentir sur son niveau se paie cher.",
    tip: "Prépare une version courte de ton pitch en anglais.",
  },
  {
    id: 'pres-21', category: 'presentation', difficulty: 2,
    situation: "Pendant que vous vous présentez, votre langage corporel parle aussi.",
    question: "Quelle posture renforce le mieux votre présentation ?",
    options: [
      { text: "Bras croisés, regard fuyant", correct: false },
      { text: "Posture ouverte, contact visuel, voix posée", correct: true },
      { text: "Gesticuler sans arrêt", correct: false },
      { text: "Regarder son téléphone en parlant", correct: false },
    ],
    explanation: "Le non-verbal (regard, posture, voix) représente une grande part du message. Une attitude ouverte et calme crédibilise tes propos.",
    tip: "Respire, ralentis le débit, regarde ton interlocuteur.",
  },
  {
    id: 'pres-22', category: 'presentation', difficulty: 1,
    situation: "« Décrivez-moi une de vos journées type au travail. »",
    question: "La meilleure approche :",
    options: [
      { text: "Décrire concrètement missions et organisation, en valorisant son rôle", correct: true },
      { text: "« Je fais un peu de tout »", correct: false },
      { text: "Se plaindre de sa charge de travail", correct: false },
      { text: "Inventer une journée idéalisée et irréaliste", correct: false },
    ],
    explanation: "Cette question évalue ta réalité opérationnelle. Une description concrète et structurée montre que tu maîtrises ton poste et ton organisation.",
    tip: "Donne 2-3 activités clés plutôt qu'une liste exhaustive.",
  },
  {
    id: 'pres-23', category: 'presentation', difficulty: 2,
    situation: "Vous avez mené un projet personnel (side project) en lien avec le poste.",
    question: "Comment le présenter ?",
    options: [
      { text: "Ne pas en parler car ce n'est pas « du travail »", correct: false },
      { text: "Le valoriser comme preuve de passion, d'initiative et de compétences", correct: true },
      { text: "En faire des heures au détriment du reste", correct: false },
      { text: "Le mentionner sans expliquer ce qu'il démontre", correct: false },
    ],
    explanation: "Un side project pertinent prouve la motivation et des compétences réelles, souvent plus qu'un diplôme. On explique ce qu'il démontre pour le poste.",
    tip: "Relie explicitement le projet aux besoins du poste.",
  },
  {
    id: 'pres-24', category: 'presentation', difficulty: 3,
    situation: "Vous revenez sur le marché après une longue période sans emploi.",
    question: "Comment vous présenter avec confiance ?",
    options: [
      { text: "S'excuser en boucle de son absence", correct: false },
      { text: "Présenter ce qu'on a fait/appris et son énergie à reprendre", correct: true },
      { text: "Cacher la durée réelle", correct: false },
      { text: "Adopter un ton défaitiste", correct: false },
    ],
    explanation: "On reprend la main en montrant qu'on est resté actif (formation, bénévolat, veille) et motivé. L'attitude positive fait toute la différence.",
    tip: "Oriente vers l'avenir : « Aujourd'hui, je suis prêt à… »",
  },
  {
    id: 'pres-25', category: 'presentation', difficulty: 2,
    context: "Vous êtes en alternance chez Talia et passez un entretien pour votre entreprise d'accueil. Le tuteur veut comprendre votre démarche.",
    situation: "« Présentez-moi votre formation en alternance. »",
    question: "La présentation la plus convaincante :",
    options: [
      { text: "« C'est juste un diplôme à obtenir »", correct: false },
      { text: "Expliquer le rythme école/entreprise et la valeur d'apprendre en faisant", correct: true },
      { text: "Dire qu'on a choisi l'alternance pour l'argent uniquement", correct: false },
      { text: "Présenter l'école sans parler de l'entreprise", correct: false },
    ],
    explanation: "L'alternance se valorise par la complémentarité théorie/pratique et l'opérationnalité immédiate qu'elle donne. C'est un argument fort pour l'employeur.",
    tip: "Mets en avant ce que tu apportes DÈS le premier jour.",
  },
  {
    id: 'pres-26', category: 'presentation', difficulty: 2,
    situation: "Vous sentez le trac monter au moment de vous présenter.",
    question: "Le bon réflexe :",
    options: [
      { text: "Parler très vite pour en finir", correct: false },
      { text: "Respirer, ralentir, s'appuyer sur son pitch préparé", correct: true },
      { text: "S'excuser d'être stressé", correct: false },
      { text: "Annuler l'entretien", correct: false },
    ],
    explanation: "Le trac est normal. La préparation et la respiration le canalisent : un pitch répété devient un point d'appui rassurant quand le stress monte.",
    tip: "Quelques respirations lentes avant d'entrer dans la pièce.",
  },
  {
    id: 'pres-27', category: 'presentation', difficulty: 2,
    situation: "Vous voulez prouver votre impact dans vos expériences passées.",
    question: "Comment présenter vos résultats ?",
    options: [
      { text: "Rester vague : « j'ai aidé à améliorer les choses »", correct: false },
      { text: "Chiffrer ses réalisations quand c'est possible (%, montants, délais)", correct: true },
      { text: "Gonfler artificiellement les chiffres", correct: false },
      { text: "Ne parler que des tâches, jamais des résultats", correct: false },
    ],
    explanation: "Les chiffres rendent l'impact tangible et crédible. « +20 % de ventes » marque plus que « j'ai contribué aux ventes ».",
    tip: "Prépare 2-3 résultats chiffrés et vérifiables.",
  },
  {
    id: 'pres-28', category: 'presentation', difficulty: 2,
    situation: "« Qu'est-ce qui vous rend unique ? »",
    question: "La meilleure manière de répondre :",
    options: [
      { text: "Une qualité ultra-générique partagée par tous", correct: false },
      { text: "Une combinaison distinctive de compétences/expériences propre à vous", correct: true },
      { text: "« Rien de spécial »", correct: false },
      { text: "Une affirmation invérifiable et grandiloquente", correct: false },
    ],
    explanation: "L'unicité vient souvent du croisement de plusieurs atouts (double compétence, parcours, vécu). On l'exprime de façon concrète et crédible.",
    tip: "Pense « intersection » : ce que peu de gens combinent.",
  },
  {
    id: 'pres-29', category: 'presentation', difficulty: 3,
    context: "Entretien collectif : vous êtes 6 candidats autour d'une table, chacun doit se présenter à tour de rôle.",
    situation: "Vient votre tour de vous présenter devant le groupe.",
    question: "Quelle attitude est la plus efficace ?",
    options: [
      { text: "Réciter mécaniquement en ignorant les autres", correct: false },
      { text: "Être concis, authentique, à l'écoute des autres et rebondir si pertinent", correct: true },
      { text: "Écraser les autres pour se démarquer", correct: false },
      { text: "Copier mot pour mot le candidat précédent", correct: false },
    ],
    explanation: "En collectif, on évalue aussi le savoir-être en groupe : concision, écoute et capacité à interagir comptent autant que le contenu.",
    tip: "Montre que tu écoutes : c'est aussi observé.",
  },
  {
    id: 'pres-30', category: 'presentation', difficulty: 2,
    situation: "Vous arrivez à la fin de votre présentation.",
    question: "Comment bien conclure ?",
    options: [
      { text: "S'arrêter net sans transition", correct: false },
      { text: "Conclure sur sa motivation pour CE poste et inviter à l'échange", correct: true },
      { text: "« Voilà, j'ai fini » en regardant ses pieds", correct: false },
      { text: "Relancer un nouveau sujet sans fin", correct: false },
    ],
    explanation: "Une bonne conclusion relie ton parcours au poste et ouvre le dialogue. Elle laisse une dernière impression positive et dynamique.",
    tip: "Termine par : « C'est pour ça que ce poste m'intéresse. »",
  },
];
