/**
 * Secteur « Ressources Humaines » — parcours (4 couches).
 *
 * sector:'rh', type ∈ {comportemental, technique, situation, actu}.
 * Une seule option correct:true, + explanation + tip. `context` optionnel.
 */
const base = { sector: 'rh' };

export default [
  // ══════════════ 🧠 COMPORTEMENTAL ══════════════
  {
    ...base, id: 'rh-cp-1', type: 'comportemental', difficulty: 1,
    situation: "« Pourquoi voulez-vous travailler dans les RH ? »",
    question: "La motivation la plus convaincante :",
    options: [
      { text: "« Pour avoir du pouvoir sur les autres »", correct: false },
      { text: "L'intérêt pour l'humain, l'accompagnement et le rôle stratégique des RH", correct: true },
      { text: "« Pour licencier des gens »", correct: false },
      { text: "« Parce qu'il n'y a pas de chiffres »", correct: false },
    ],
    explanation: "Les RH allient dimension humaine et enjeux stratégiques (talents, climat social, performance). On valorise l'intérêt pour l'humain et le sens du collectif.",
    tip: "Parle d'accompagnement et de contribution à la performance.",
  },
  {
    ...base, id: 'rh-cp-2', type: 'comportemental', difficulty: 2,
    situation: "En RH, vous accédez à des informations très sensibles.",
    question: "Quelle qualité est indispensable ?",
    options: [
      { text: "Le goût des ragots", correct: false },
      { text: "Une confidentialité et une discrétion irréprochables", correct: true },
      { text: "Le besoin de tout partager", correct: false },
      { text: "L'indifférence", correct: false },
    ],
    explanation: "Salaires, contrats, dossiers disciplinaires, santé… Les RH manipulent du très sensible. La confidentialité est une exigence absolue et un gage de confiance.",
    tip: "La discrétion est le socle de la crédibilité RH.",
  },
  {
    ...base, id: 'rh-cp-3', type: 'comportemental', difficulty: 2,
    situation: "« Comment réagissez-vous face à un salarié en détresse ? »",
    question: "La meilleure posture :",
    options: [
      { text: "Couper court, ce n'est pas votre rôle", correct: false },
      { text: "Écouter avec empathie, sans juger, puis orienter vers les bons relais", correct: true },
      { text: "Donner des conseils personnels intrusifs", correct: false },
      { text: "Minimiser ses difficultés", correct: false },
    ],
    explanation: "L'écoute active et l'empathie, sans jugement, sont au cœur du métier. On accompagne et on oriente (manager, médecine du travail, dispositifs) sans se substituer à un spécialiste.",
    tip: "Écouter et orienter, sans jouer au psychologue.",
  },
  {
    ...base, id: 'rh-cp-4', type: 'comportemental', difficulty: 3,
    situation: "« Comment gérez-vous le fait d'être entre la direction et les salariés ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Je suis toujours du côté de la direction »", correct: false },
      { text: "Je cherche l'équilibre : porter les enjeux de l'entreprise ET être à l'écoute des salariés", correct: true },
      { text: "« Je suis uniquement du côté des salariés »", correct: false },
      { text: "« Je ne prends jamais position »", correct: false },
    ],
    explanation: "Le RH est un trait d'union : il relaie la stratégie de l'entreprise tout en étant à l'écoute du social. Cet équilibre, parfois inconfortable, est le cœur du métier.",
    tip: "Positionne-toi en facilitateur, pas en camp.",
  },
  {
    ...base, id: 'rh-cp-5', type: 'comportemental', difficulty: 2,
    situation: "« L'objectivité et l'équité, qu'en pensez-vous en RH ? »",
    question: "La meilleure posture :",
    options: [
      { text: "Avoir des préférés et les favoriser", correct: false },
      { text: "Traiter chacun avec équité et fonder ses décisions sur des critères objectifs", correct: true },
      { text: "Décider à l'instinct, sans critères", correct: false },
      { text: "Se laisser influencer par les rumeurs", correct: false },
    ],
    explanation: "L'équité et l'objectivité protègent l'entreprise (non-discrimination) et la confiance des salariés. Les décisions RH doivent reposer sur des critères clairs et justifiables.",
    tip: "Décisions RH = critères objectifs, jamais l'arbitraire.",
  },
  {
    ...base, id: 'rh-cp-6', type: 'comportemental', difficulty: 2,
    situation: "« Le métier RH peut être stressant (conflits, urgences sociales). Comment gérez-vous ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Je fuis les conflits »", correct: false },
      { text: "Je garde mon calme, je prends du recul et je traite les situations avec méthode", correct: true },
      { text: "« Je m'emporte avec les gens »", correct: false },
      { text: "« Je laisse les problèmes s'aggraver »", correct: false },
    ],
    explanation: "Le sang-froid et le recul sont essentiels en RH, souvent en première ligne sur les tensions. On montre une gestion posée et méthodique des situations difficiles.",
    tip: "Calme et méthode désamorcent la plupart des tensions.",
  },

  // ══════════════ 🛠️ TECHNIQUE MÉTIER ══════════════
  {
    ...base, id: 'rh-te-1', type: 'technique', difficulty: 1,
    situation: "Vocabulaire du recrutement.",
    question: "Que désigne le « sourcing » ?",
    options: [
      { text: "Le calcul des salaires", correct: false },
      { text: "La recherche et l'identification de candidats potentiels", correct: true },
      { text: "La rédaction des contrats", correct: false },
      { text: "La gestion des congés", correct: false },
    ],
    explanation: "Le sourcing consiste à chercher activement des candidats (CVthèques, LinkedIn, cooptation) avant même qu'ils postulent. C'est une compétence clé du recrutement moderne.",
    tip: "Cite LinkedIn Recruiter ou la cooptation comme canaux.",
  },
  {
    ...base, id: 'rh-te-2', type: 'technique', difficulty: 2,
    situation: "Outils RH.",
    question: "Qu'est-ce qu'un SIRH ?",
    options: [
      { text: "Un type de contrat de travail", correct: false },
      { text: "Un Système d'Information RH : logiciel qui gère paie, congés, dossiers, recrutement…", correct: true },
      { text: "Une réunion syndicale", correct: false },
      { text: "Un indicateur financier", correct: false },
    ],
    explanation: "Le SIRH centralise et automatise la gestion administrative RH (paie, absences, formation, recrutement). Sa maîtrise est très recherchée.",
    tip: "Connaître un SIRH (ex : Lucca, PayFit) est un atout.",
  },
  {
    ...base, id: 'rh-te-3', type: 'technique', difficulty: 2,
    situation: "Cycle de vie du salarié.",
    question: "Que désigne l'« onboarding » ?",
    options: [
      { text: "Le licenciement d'un salarié", correct: false },
      { text: "Le parcours d'intégration d'un nouvel arrivant", correct: true },
      { text: "Le calcul de la prime annuelle", correct: false },
      { text: "Le départ en retraite", correct: false },
    ],
    explanation: "L'onboarding (intégration) couvre les premiers jours/semaines d'un nouveau salarié : accueil, formation, suivi. Un bon onboarding réduit fortement les départs précoces.",
    tip: "Un onboarding réussi = rétention et engagement.",
  },
  {
    ...base, id: 'rh-te-4', type: 'technique', difficulty: 2,
    situation: "Droit du travail de base.",
    question: "Quelle est la principale différence entre CDD et CDI ?",
    options: [
      { text: "Le CDD est mieux payé par nature", correct: false },
      { text: "Le CDD a un terme (durée/objet) défini ; le CDI est sans date de fin", correct: true },
      { text: "Le CDI est réservé aux cadres", correct: false },
      { text: "Il n'y a aucune différence", correct: false },
    ],
    explanation: "Le CDD est conclu pour une durée ou un objet précis et encadré par la loi ; le CDI est la forme normale et durable du contrat. Une base à connaître absolument en RH.",
    tip: "Maîtrise les bases du droit du travail (CDD/CDI, période d'essai).",
  },
  {
    ...base, id: 'rh-te-5', type: 'technique', difficulty: 3,
    situation: "Développement des compétences.",
    question: "Qu'est-ce que la GPEC ?",
    options: [
      { text: "Un logiciel de paie", correct: false },
      { text: "La Gestion Prévisionnelle des Emplois et des Compétences : anticiper les besoins en compétences", correct: true },
      { text: "Un type de prime", correct: false },
      { text: "Une instance syndicale", correct: false },
    ],
    explanation: "La GPEC (ou GEPP) vise à anticiper l'évolution des métiers et compétences pour adapter formation et recrutement. C'est un sujet RH stratégique.",
    tip: "GPEC = anticiper les compétences de demain.",
  },
  {
    ...base, id: 'rh-te-6', type: 'technique', difficulty: 2,
    situation: "Entretien de recrutement.",
    question: "Quelle question est INTERDITE (discriminatoire) en entretien ?",
    options: [
      { text: "« Parlez-moi de votre expérience »", correct: false },
      { text: "« Comptez-vous avoir des enfants ? »", correct: true },
      { text: "« Quelles sont vos compétences clés ? »", correct: false },
      { text: "« Pourquoi ce poste vous intéresse ? »", correct: false },
    ],
    explanation: "Les questions sur la vie privée, la grossesse, l'origine, la religion, etc. sont discriminatoires et illégales. Le recruteur ne doit évaluer que les compétences liées au poste.",
    tip: "On évalue les compétences, jamais la vie privée.",
  },
  {
    ...base, id: 'rh-te-7', type: 'technique', difficulty: 2,
    situation: "Suivi de la performance.",
    question: "À quoi sert l'entretien annuel d'évaluation ?",
    options: [
      { text: "À sanctionner le salarié", correct: false },
      { text: "À faire le bilan, fixer des objectifs et identifier les besoins de développement", correct: true },
      { text: "À fixer les congés", correct: false },
      { text: "À calculer la paie", correct: false },
    ],
    explanation: "L'entretien annuel est un moment d'échange : bilan de l'année, objectifs, souhaits d'évolution et besoins de formation. C'est un outil de management, pas une sanction.",
    tip: "Ne confonds pas entretien annuel et entretien professionnel.",
  },
  {
    ...base, id: 'rh-te-8', type: 'technique', difficulty: 3,
    situation: "Pilotage RH.",
    question: "Que mesure le « taux de turnover » ?",
    options: [
      { text: "Le chiffre d'affaires", correct: false },
      { text: "Le taux de rotation du personnel (départs rapportés à l'effectif)", correct: true },
      { text: "Le nombre de réunions", correct: false },
      { text: "Le temps de pause", correct: false },
    ],
    explanation: "Le turnover indique la rotation des effectifs. Un taux élevé signale souvent un problème (climat, rémunération, management). C'est un indicateur RH central.",
    tip: "Turnover élevé = signal d'alerte sur l'engagement.",
  },
  {
    ...base, id: 'rh-te-9', type: 'technique', difficulty: 2,
    situation: "Marque employeur.",
    question: "Qu'est-ce que la « marque employeur » ?",
    options: [
      { text: "Le logo de l'entreprise", correct: false },
      { text: "L'image et la réputation de l'entreprise en tant qu'employeur, pour attirer et fidéliser", correct: true },
      { text: "Un type de contrat", correct: false },
      { text: "Le nom du dirigeant", correct: false },
    ],
    explanation: "La marque employeur, c'est ce qui donne envie de rejoindre et de rester dans une entreprise (valeurs, conditions, réputation). Elle est devenue un levier RH majeur face à la pénurie de talents.",
    tip: "Marque employeur forte = recrutement plus facile.",
  },

  // ══════════════ 🎭 MISE EN SITUATION ══════════════
  {
    ...base, id: 'rh-si-1', type: 'situation', difficulty: 3,
    context: "Deux collègues d'un même service se disputent ouvertement, l'ambiance se dégrade et leur manager vous sollicite.",
    situation: "Conflit entre deux salariés.",
    question: "La meilleure approche RH :",
    options: [
      { text: "Donner raison au plus sympathique", correct: false },
      { text: "Écouter chaque partie séparément, rester neutre et chercher une solution commune", correct: true },
      { text: "Ignorer, ça finira par passer", correct: false },
      { text: "Sanctionner les deux immédiatement", correct: false },
    ],
    explanation: "On reste neutre et factuel : écoute individuelle, recherche des causes, puis médiation vers une solution. Prendre parti ou ignorer aggrave le conflit.",
    tip: "Neutralité + écoute des deux côtés = base de la médiation.",
  },
  {
    ...base, id: 'rh-si-2', type: 'situation', difficulty: 2,
    context: "Un manager veut recruter « quelqu'un comme lui, jeune et dynamique » et écarter les candidats plus âgés.",
    situation: "Un manager exprime un critère discriminatoire.",
    question: "La bonne réaction RH :",
    options: [
      { text: "Obéir et écarter les profils seniors", correct: false },
      { text: "Rappeler le cadre légal (non-discrimination) et recentrer sur les compétences", correct: true },
      { text: "Faire semblant de ne pas avoir entendu", correct: false },
      { text: "Diffuser une offre mentionnant « jeune »", correct: false },
    ],
    explanation: "L'âge est un critère discriminatoire interdit. Le rôle du RH est de protéger l'entreprise et l'équité en recentrant le manager sur les compétences requises.",
    tip: "Le RH est le garant du recrutement non discriminatoire.",
  },
  {
    ...base, id: 'rh-si-3', type: 'situation', difficulty: 2,
    context: "Un nouveau salarié vous confie, après deux semaines, qu'il se sent perdu et mal intégré.",
    situation: "Échec d'intégration signalé.",
    question: "La meilleure réaction :",
    options: [
      { text: "Lui dire de se débrouiller", correct: false },
      { text: "Prendre le temps d'écouter, ajuster son parcours d'intégration et impliquer son manager", correct: true },
      { text: "Conclure tout de suite qu'il n'est pas fait pour le poste", correct: false },
      { text: "Ne rien faire", correct: false },
    ],
    explanation: "Un onboarding raté est une cause majeure de départ précoce. On écoute, on corrige le parcours (parrain, points réguliers) et on mobilise le manager.",
    tip: "Les premières semaines décident souvent de la suite.",
  },
  {
    ...base, id: 'rh-si-4', type: 'situation', difficulty: 3,
    context: "Vous recevez 150 candidatures pour un poste et devez présélectionner rapidement.",
    situation: "Tri d'un grand volume de candidatures.",
    question: "La méthode la plus juste et efficace :",
    options: [
      { text: "Choisir au hasard pour aller vite", correct: false },
      { text: "Définir des critères objectifs liés au poste et filtrer sur cette base", correct: true },
      { text: "Écarter selon la photo ou le nom", correct: false },
      { text: "Ne garder que les candidats de sa ville", correct: false },
    ],
    explanation: "On présélectionne sur des critères objectifs et pertinents (compétences, expérience requise), jamais sur des critères discriminatoires. Cela garantit équité et qualité du tri.",
    tip: "Des critères clairs = un tri rapide ET défendable.",
  },
  {
    ...base, id: 'rh-si-5', type: 'situation', difficulty: 3,
    context: "Plusieurs salariés se plaignent d'une surcharge de travail et d'un manque de reconnaissance.",
    situation: "Signaux de désengagement dans une équipe.",
    question: "La meilleure démarche RH :",
    options: [
      { text: "Minimiser et dire que tout le monde est surchargé", correct: false },
      { text: "Objectiver la situation (échanges, enquête) et construire un plan d'action avec le management", correct: true },
      { text: "Sanctionner ceux qui se plaignent", correct: false },
      { text: "Attendre que les gens démissionnent", correct: false },
    ],
    explanation: "On prend le signal au sérieux : recueillir les faits, mesurer (enquête, indicateurs) et agir avec les managers sur la charge et la reconnaissance. Ignorer alimente le turnover.",
    tip: "Le désengagement se traite tôt, par des faits puis des actions.",
  },
  {
    ...base, id: 'rh-si-6', type: 'situation', difficulty: 3,
    context: "🏆 BOSS — Vous devez annoncer à un candidat très motivé, reçu deux fois, que sa candidature n'est pas retenue.",
    situation: "Faire un retour négatif à un candidat.",
    question: "La meilleure manière de procéder :",
    options: [
      { text: "Ne jamais le rappeler (ghosting)", correct: false },
      { text: "Donner un retour personnalisé, respectueux et constructif", correct: true },
      { text: "Envoyer un mail type sec et impersonnel", correct: false },
      { text: "Lui dire qu'il était nul", correct: false },
    ],
    explanation: "Un refus bien fait préserve la marque employeur : retour personnalisé, respectueux, avec si possible des axes d'amélioration. Le ghosting nuit durablement à la réputation.",
    tip: "Un bon refus se retient ; le ghosting se paie en réputation.",
  },

  // ══════════════ 📰 ACTU & TENDANCES (2026) ══════════════
  {
    ...base, id: 'rh-ac-1', type: 'actu', difficulty: 3,
    situation: "L'IA dans le recrutement.",
    question: "Quel est l'enjeu majeur de l'IA dans le tri des candidatures ?",
    options: [
      { text: "Elle est toujours 100 % neutre", correct: false },
      { text: "Gagner du temps tout en surveillant les biais pour éviter la discrimination", correct: true },
      { text: "Remplacer totalement le jugement humain", correct: false },
      { text: "Elle est interdite partout", correct: false },
    ],
    explanation: "L'IA accélère le sourcing et le tri, mais peut reproduire des biais des données. L'enjeu 2026 : l'utiliser comme aide tout en gardant un contrôle humain et éthique.",
    tip: "IA utile, mais vigilance sur les biais et l'éthique.",
  },
  {
    ...base, id: 'rh-ac-2', type: 'actu', difficulty: 2,
    situation: "Évolution du recrutement.",
    question: "Que signifie le recrutement « par compétences » (skills-based) ?",
    options: [
      { text: "Recruter uniquement sur le diplôme", correct: false },
      { text: "Évaluer ce que la personne sait faire, au-delà du seul diplôme", correct: true },
      { text: "Recruter sans aucun critère", correct: false },
      { text: "Ne recruter que des seniors", correct: false },
    ],
    explanation: "Face à la pénurie de talents, on évalue de plus en plus les compétences réelles (tests, mises en situation) plutôt que le seul diplôme. Cela ouvre à des profils atypiques.",
    tip: "« Compétences > diplôme » : une tendance forte en 2026.",
  },
  {
    ...base, id: 'rh-ac-3', type: 'actu', difficulty: 2,
    situation: "Bien-être au travail.",
    question: "Que recouvre la QVCT ?",
    options: [
      { text: "Un type de contrat", correct: false },
      { text: "La Qualité de Vie et des Conditions de Travail : santé, charge, sens, conditions", correct: true },
      { text: "Un logiciel de paie", correct: false },
      { text: "Une prime exceptionnelle", correct: false },
    ],
    explanation: "La QVCT (ex-QVT) englobe les conditions de travail, la santé, la charge et le sens. C'est un levier majeur d'attractivité et de réduction du turnover.",
    tip: "QVCT = un argument clé de la marque employeur.",
  },
  {
    ...base, id: 'rh-ac-4', type: 'actu', difficulty: 2,
    situation: "Phénomène social.",
    question: "Que désigne le « quiet quitting » (démission silencieuse) ?",
    options: [
      { text: "Démissionner sans prévenir", correct: false },
      { text: "Faire le strict minimum, sans s'investir au-delà de sa fiche de poste", correct: true },
      { text: "Partir en pleine nuit", correct: false },
      { text: "Un type de licenciement", correct: false },
    ],
    explanation: "Le quiet quitting traduit un désengagement : le salarié reste mais se limite au minimum. C'est un signal RH d'un manque de sens ou de reconnaissance à adresser.",
    tip: "Le quiet quitting est un symptôme, pas une fatalité.",
  },
  {
    ...base, id: 'rh-ac-5', type: 'actu', difficulty: 3,
    situation: "Organisation du temps de travail.",
    question: "Que teste-t-on avec la « semaine de 4 jours » ?",
    options: [
      { text: "Travailler 4 jours pour le même résultat, en visant bien-être et productivité", correct: true },
      { text: "Supprimer les salaires un jour par semaine", correct: false },
      { text: "Travailler le week-end", correct: false },
      { text: "Fermer l'entreprise 4 jours", correct: false },
    ],
    explanation: "De plus en plus d'entreprises expérimentent la semaine de 4 jours pour améliorer l'équilibre et l'attractivité, sans perte de performance. Un sujet RH très discuté en 2026.",
    tip: "Sache en parler : c'est un débat RH d'actualité.",
  },
  {
    ...base, id: 'rh-ac-6', type: 'actu', difficulty: 2,
    situation: "Attentes des candidats.",
    question: "Pourquoi l'« expérience candidat » est-elle devenue clé ?",
    options: [
      { text: "Elle n'a aucun impact", correct: false },
      { text: "Un processus respectueux et fluide renforce l'image employeur et l'acceptation des offres", correct: true },
      { text: "Elle sert à allonger les délais", correct: false },
      { text: "Elle ne concerne que les stagiaires", correct: false },
    ],
    explanation: "Dans un marché en tension, la façon dont on traite les candidats (réactivité, transparence, respect) influence directement l'attractivité et le taux d'acceptation.",
    tip: "Un candidat mal traité parle ; un bien traité recommande.",
  },
  {
    ...base, id: 'rh-ac-7', type: 'actu', difficulty: 3,
    situation: "Reporting d'entreprise.",
    question: "Quel volet de la CSRD concerne directement les RH ?",
    options: [
      { text: "Le volet social : emploi, conditions de travail, égalité, formation", correct: true },
      { text: "Uniquement le bilan carbone", correct: false },
      { text: "Le calcul de la TVA", correct: false },
      { text: "La publicité de l'entreprise", correct: false },
    ],
    explanation: "La CSRD impose aux entreprises de publier des données extra-financières, dont un volet social (égalité, conditions de travail, formation). Les RH sont en première ligne pour les produire.",
    tip: "CSRD : les RH fournissent les indicateurs sociaux.",
  },
  {
    ...base, id: 'rh-ac-8', type: 'actu', difficulty: 2,
    situation: "Développement des talents.",
    question: "Pourquoi le « reskilling / upskilling » est-il stratégique ?",
    options: [
      { text: "Pour occuper les salariés inutilement", correct: false },
      { text: "Pour adapter les compétences aux métiers qui évoluent (IA, numérique) et fidéliser", correct: true },
      { text: "Pour remplacer la paie", correct: false },
      { text: "Ça n'a aucun intérêt", correct: false },
    ],
    explanation: "Reskilling (changer de métier) et upskilling (monter en compétences) répondent à l'évolution rapide des métiers. Former en interne fidélise et comble la pénurie de talents.",
    tip: "Former plutôt que remplacer : une réponse à la pénurie.",
  },
];
