/**
 * Secteur « Ressources Humaines » — parcours (4 couches).
 *
 * sector:'rh', type ∈ {comportemental, technique, situation, actu}.
 * Une seule option correct:true, + explanation + tip. `context` optionnel.
 */
const base = { sector: 'rh' };

export default [
  // ══════════════ 🧠 COMPORTEMENTAL ══════════════
  {
    ...base, id: 'rh-cp-1', type: 'comportemental', difficulty: 1,
    situation: "« Pourquoi voulez-vous travailler dans les RH ? »",
    question: "La motivation la plus convaincante :",
    options: [
      { text: "« Pour avoir du pouvoir sur les autres »", correct: false },
      { text: "L'intérêt pour l'humain, l'accompagnement et le rôle stratégique des RH", correct: true },
      { text: "« Pour licencier des gens »", correct: false },
      { text: "« Parce qu'il n'y a pas de chiffres »", correct: false },
    ],
    explanation: "Les RH allient dimension humaine et enjeux stratégiques (talents, climat social, performance). On valorise l'intérêt pour l'humain et le sens du collectif.",
    tip: "Parle d'accompagnement et de contribution à la performance.",
  },
  {
    ...base, id: 'rh-cp-2', type: 'comportemental', difficulty: 2,
    situation: "En RH, vous accédez à des informations très sensibles.",
    question: "Quelle qualité est indispensable ?",
    options: [
      { text: "Le goût des ragots", correct: false },
      { text: "Une confidentialité et une discrétion irréprochables", correct: true },
      { text: "Le besoin de tout partager", correct: false },
      { text: "L'indifférence", correct: false },
    ],
    explanation: "Salaires, contrats, dossiers disciplinaires, santé… Les RH manipulent du très sensible. La confidentialité est une exigence absolue et un gage de confiance.",
    tip: "La discrétion est le socle de la crédibilité RH.",
  },
  {
    ...base, id: 'rh-cp-3', type: 'comportemental', difficulty: 2,
    situation: "« Comment réagissez-vous face à un salarié en détresse ? »",
    question: "La meilleure posture :",
    options: [
      { text: "Couper court, ce n'est pas votre rôle", correct: false },
      { text: "Écouter avec empathie, sans juger, puis orienter vers les bons relais", correct: true },
      { text: "Donner des conseils personnels intrusifs", correct: false },
      { text: "Minimiser ses difficultés", correct: false },
    ],
    explanation: "L'écoute active et l'empathie, sans jugement, sont au cœur du métier. On accompagne et on oriente (manager, médecine du travail, dispositifs) sans se substituer à un spécialiste.",
    tip: "Écouter et orienter, sans jouer au psychologue.",
  },
  {
    ...base, id: 'rh-cp-4', type: 'comportemental', difficulty: 3,
    situation: "« Comment gérez-vous le fait d'être entre la direction et les salariés ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Je suis toujours du côté de la direction »", correct: false },
      { text: "Je cherche l'équilibre : porter les enjeux de l'entreprise ET être à l'écoute des salariés", correct: true },
      { text: "« Je suis uniquement du côté des salariés »", correct: false },
      { text: "« Je ne prends jamais position »", correct: false },
    ],
    explanation: "Le RH est un trait d'union : il relaie la stratégie de l'entreprise tout en étant à l'écoute du social. Cet équilibre, parfois inconfortable, est le cœur du métier.",
    tip: "Positionne-toi en facilitateur, pas en camp.",
  },
  {
    ...base, id: 'rh-cp-5', type: 'comportemental', difficulty: 2,
    situation: "« L'objectivité et l'équité, qu'en pensez-vous en RH ? »",
    question: "La meilleure posture :",
    options: [
      { text: "Avoir des préférés et les favoriser", correct: false },
      { text: "Traiter chacun avec équité et fonder ses décisions sur des critères objectifs", correct: true },
      { text: "Décider à l'instinct, sans critères", correct: false },
      { text: "Se laisser influencer par les rumeurs", correct: false },
    ],
    explanation: "L'équité et l'objectivité protègent l'entreprise (non-discrimination) et la confiance des salariés. Les décisions RH doivent reposer sur des critères clairs et justifiables.",
    tip: "Décisions RH = critères objectifs, jamais l'arbitraire.",
  },
  {
    ...base, id: 'rh-cp-6', type: 'comportemental', difficulty: 2,
    situation: "« Le métier RH peut être stressant (conflits, urgences sociales). Comment gérez-vous ? »",
    question: "La meilleure réponse :",
    options: [
      { text: "« Je fuis les conflits »", correct: false },
      { text: "Je garde mon calme, je prends du recul et je traite les situations avec méthode", correct: true },
      { text: "« Je m'emporte avec les gens »", correct: false },
      { text: "« Je laisse les problèmes s'aggraver »", correct: false },
    ],
    explanation: "Le sang-froid et le recul sont essentiels en RH, souvent en première ligne sur les tensions. On montre une gestion posée et méthodique des situations difficiles.",
    tip: "Calme et méthode désamorcent la plupart des tensions.",
  },

  // ══════════════ 🛠️ TECHNIQUE MÉTIER ══════════════
  {
    ...base, id: 'rh-te-1', type: 'technique', difficulty: 1,
    situation: "Vocabulaire du recrutement.",
    question: "Que désigne le « sourcing » ?",
    options: [
      { text: "Le calcul des salaires", correct: false },
      { text: "La recherche et l'identification de candidats potentiels", correct: true },
      { text: "La rédaction des contrats", correct: false },
      { text: "La gestion des congés", correct: false },
    ],
    explanation: "Le sourcing consiste à chercher activement des candidats (CVthèques, LinkedIn, cooptation) avant même qu'ils postulent. C'est une compétence clé du recrutement moderne.",
    tip: "Cite LinkedIn Recruiter ou la cooptation comme canaux.",
  },
  {
    ...base, id: 'rh-te-2', type: 'technique', difficulty: 2,
    situation: "Outils RH.",
    question: "Qu'est-ce qu'un SIRH ?",
    options: [
      { text: "Un type de contrat de travail", correct: false },
      { text: "Un Système d'Information RH : logiciel qui gère paie, congés, dossiers, recrutement…", correct: true },
      { text: "Une réunion syndicale", correct: false },
      { text: "Un indicateur financier", correct: false },
    ],
    explanation: "Le SIRH centralise et automatise la gestion administrative RH (paie, absences, formation, recrutement). Sa maîtrise est très recherchée.",
    tip: "Connaître un SIRH (ex : Lucca, PayFit) est un atout.",
  },
  {
    ...base, id: 'rh-te-3', type: 'technique', difficulty: 2,
    situation: "Cycle de vie du salarié.",
    question: "Que désigne l'« onboarding » ?",
    options: [
      { text: "Le licenciement d'un salarié", correct: false },
      { text: "Le parcours d'intégration d'un nouvel arrivant", correct: true },
      { text: "Le calcul de la prime annuelle", correct: false },
      { text: "Le départ en retraite", correct: false },
    ],
    explanation: "L'onboarding (intégration) couvre les premiers jours/semaines d'un nouveau salarié : accueil, formation, suivi. Un bon onboarding réduit fortement les départs précoces.",
    tip: "Un onboarding réussi = rétention et engagement.",
  },
  {
    ...base, id: 'rh-te-4', type: 'technique', difficulty: 2,
    situation: "Droit du travail de base.",
    question: "Quelle est la principale différence entre CDD et CDI ?",
    options: [
      { text: "Le CDD est mieux payé par nature", correct: false },
      { text: "Le CDD a un terme (durée/objet) défini ; le CDI est sans date de fin", correct: true },
      { text: "Le CDI est réservé aux cadres", correct: false },
      { text: "Il n'y a aucune différence", correct: false },
    ],
    explanation: "Le CDD est conclu pour une durée ou un objet précis et encadré par la loi ; le CDI est la forme normale et durable du contrat. Une base à connaître absolument en RH.",
    tip: "Maîtrise les bases du droit du travail (CDD/CDI, période d'essai).",
  },
  {
    ...base, id: 'rh-te-5', type: 'technique', difficulty: 3,
    situation: "Développement des compétences.",
    question: "Qu'est-ce que la GPEC ?",
    options: [
      { text: "Un logiciel de paie", correct: false },
      { text: "La Gestion Prévisionnelle des Emplois et des Compétences : anticiper les besoins en compétences", correct: true },
      { text: "Un type de prime", correct: false },
      { text: "Une instance syndicale", correct: false },
    ],
    explanation: "La GPEC (ou GEPP) vise à anticiper l'évolution des métiers et compétences pour adapter formation et recrutement. C'est un sujet RH stratégique.",
    tip: "GPEC = anticiper les compétences de demain.",
  },
  {
    ...base, id: 'rh-te-6', type: 'technique', difficulty: 2,
    situation: "Entretien de recrutement.",
    question: "Quelle question est INTERDITE (discriminatoire) en entretien ?",
    options: [
      { text: "« Parlez-moi de votre expérience »", correct: false },
      { text: "« Comptez-vous avoir des enfants ? »", correct: true },
      { text: "« Quelles sont vos compétences clés ? »", correct: false },
      { text: "« Pourquoi ce poste vous intéresse ? »", correct: false },
    ],
    explanation: "Les questions sur la vie privée, la grossesse, l'origine, la religion, etc. sont discriminatoires et illégales. Le recruteur ne doit évaluer que les compétences liées au poste.",
    tip: "On évalue les compétences, jamais la vie privée.",
  },
  {
    ...base, id: 'rh-te-7', type: 'technique', difficulty: 2,
    situation: "Suivi de la performance.",
    question: "À quoi sert l'entretien annuel d'évaluation ?",
    options: [
      { text: "À sanctionner le salarié", correct: false },
      { text: "À faire le bilan, fixer des objectifs et identifier les besoins de développement", correct: true },
      { text: "À fixer les congés", correct: false },
      { text: "À calculer la paie", correct: false },
    ],
    explanation: "L'entretien annuel est un moment d'échange : bilan de l'année, objectifs, souhaits d'évolution et besoins de formation. C'est un outil de management, pas une sanction.",
    tip: "Ne confonds pas entretien annuel et entretien professionnel.",
  },
  {
    ...base, id: 'rh-te-8', type: 'technique', difficulty: 3,
    situation: "Pilotage RH.",
    question: "Que mesure le « taux de turnover » ?",
    options: [
      { text: "Le chiffre d'affaires", correct: false },
      { text: "Le taux de rotation du personnel (départs rapportés à l'effectif)", correct: true },
      { text: "Le nombre de réunions", correct: false },
      { text: "Le temps de pause", correct: false },
    ],
    explanation: "Le turnover indique la rotation des effectifs. Un taux élevé signale souvent un problème (climat, rémunération, management). C'est un indicateur RH central.",
    tip: "Turnover élevé = signal d'alerte sur l'engagement.",
  },
  {
    ...base, id: 'rh-te-9', type: 'technique', difficulty: 2,
    situation: "Marque employeur.",
    question: "Qu'est-ce que la « marque employeur » ?",
    options: [
      { text: "Le logo de l'entreprise", correct: false },
      { text: "L'image et la réputation de l'entreprise en tant qu'employeur, pour attirer et fidéliser", correct: true },
      { text: "Un type de contrat", correct: false },
      { text: "Le nom du dirigeant", correct: false },
    ],
    explanation: "La marque employeur, c'est ce qui donne envie de rejoindre et de rester dans une entreprise (valeurs, conditions, réputation). Elle est devenue un levier RH majeur face à la pénurie de talents.",
    tip: "Marque employeur forte = recrutement plus facile.",
  },

  // ══════════════ 🎭 MISE EN SITUATION ══════════════
  {
    ...base, id: 'rh-si-1', type: 'situation', difficulty: 3,
    context: "Deux collègues d'un même service se disputent ouvertement, l'ambiance se dégrade et leur manager vous sollicite.",
    situation: "Conflit entre deux salariés.",
    question: "La meilleure approche RH :",
    options: [
      { text: "Donner raison au plus sympathique", correct: false },
      { text: "Écouter chaque partie séparément, rester neutre et chercher une solution commune", correct: true },
      { text: "Ignorer, ça finira par passer", correct: false },
      { text: "Sanctionner les deux immédiatement", correct: false },
    ],
    explanation: "On reste neutre et factuel : écoute individuelle, recherche des causes, puis médiation vers une solution. Prendre parti ou ignorer aggrave le conflit.",
    tip: "Neutralité + écoute des deux côtés = base de la médiation.",
  },
  {
    ...base, id: 'rh-si-2', type: 'situation', difficulty: 2,
    context: "Un manager veut recruter « quelqu'un comme lui, jeune et dynamique » et écarter les candidats plus âgés.",
    situation: "Un manager exprime un critère discriminatoire.",
    question: "La bonne réaction RH :",
    options: [
      { text: "Obéir et écarter les profils seniors", correct: false },
      { text: "Rappeler le cadre légal (non-discrimination) et recentrer sur les compétences", correct: true },
      { text: "Faire semblant de ne pas avoir entendu", correct: false },
      { text: "Diffuser une offre mentionnant « jeune »", correct: false },
    ],
    explanation: "L'âge est un critère discriminatoire interdit. Le rôle du RH est de protéger l'entreprise et l'équité en recentrant le manager sur les compétences requises.",
    tip: "Le RH est le garant du recrutement non discriminatoire.",
  },
  {
    ...base, id: 'rh-si-3', type: 'situation', difficulty: 2,
    context: "Un nouveau salarié vous confie, après deux semaines, qu'il se sent perdu et mal intégré.",
    situation: "Échec d'intégration signalé.",
    question: "La meilleure réaction :",
    options: [
      { text: "Lui dire de se débrouiller", correct: false },
      { text: "Prendre le temps d'écouter, ajuster son parcours d'intégration et impliquer son manager", correct: true },
      { text: "Conclure tout de suite qu'il n'est pas fait pour le poste", correct: false },
      { text: "Ne rien faire", correct: false },
    ],
    explanation: "Un onboarding raté est une cause majeure de départ précoce. On écoute, on corrige le parcours (parrain, points réguliers) et on mobilise le manager.",
    tip: "Les premières semaines décident souvent de la suite.",
  },
  {
    ...base, id: 'rh-si-4', type: 'situation', difficulty: 3,
    context: "Vous recevez 150 candidatures pour un poste et devez présélectionner rapidement.",
    situation: "Tri d'un grand volume de candidatures.",
    question: "La méthode la plus juste et efficace :",
    options: [
      { text: "Choisir au hasard pour aller vite", correct: false },
      { text: "Définir des critères objectifs liés au poste et filtrer sur cette base", correct: true },
      { text: "Écarter selon la photo ou le nom", correct: false },
      { text: "Ne garder que les candidats de sa ville", correct: false },
    ],
    explanation: "On présélectionne sur des critères objectifs et pertinents (compétences, expérience requise), jamais sur des critères discriminatoires. Cela garantit équité et qualité du tri.",
    tip: "Des critères clairs = un tri rapide ET défendable.",
  },
  {
    ...base, id: 'rh-si-5', type: 'situation', difficulty: 3,
    context: "Plusieurs salariés se plaignent d'une surcharge de travail et d'un manque de reconnaissance.",
    situation: "Signaux de désengagement dans une équipe.",
    question: "La meilleure démarche RH :",
    options: [
      { text: "Minimiser et dire que tout le monde est surchargé", correct: false },
      { text: "Objectiver la situation (échanges, enquête) et construire un plan d'action avec le management", correct: true },
      { text: "Sanctionner ceux qui se plaignent", correct: false },
      { text: "Attendre que les gens démissionnent", correct: false },
    ],
    explanation: "On prend le signal au sérieux : recueillir les faits, mesurer (enquête, indicateurs) et agir avec les managers sur la charge et la reconnaissance. Ignorer alimente le turnover.",
    tip: "Le désengagement se traite tôt, par des faits puis des actions.",
  },
  {
    ...base, id: 'rh-si-6', type: 'situation', difficulty: 3,
    context: "🏆 BOSS — Vous devez annoncer à un candidat très motivé, reçu deux fois, que sa candidature n'est pas retenue.",
    situation: "Faire un retour négatif à un candidat.",
    question: "La meilleure manière de procéder :",
    options: [
      { text: "Ne jamais le rappeler (ghosting)", correct: false },
      { text: "Donner un retour personnalisé, respectueux et constructif", correct: true },
      { text: "Envoyer un mail type sec et impersonnel", correct: false },
      { text: "Lui dire qu'il était nul", correct: false },
    ],
    explanation: "Un refus bien fait préserve la marque employeur : retour personnalisé, respectueux, avec si possible des axes d'amélioration. Le ghosting nuit durablement à la réputation.",
    tip: "Un bon refus se retient ; le ghosting se paie en réputation.",
  },

  // ══════════════ 📰 ACTU & TENDANCES (2026) ══════════════
  {
    ...base, id: 'rh-ac-1', type: 'actu', difficulty: 3,
    situation: "L'IA dans le recrutement.",
    question: "Quel est l'enjeu majeur de l'IA dans le tri des candidatures ?",
    options: [
      { text: "Elle est toujours 100 % neutre", correct: false },
      { text: "Gagner du temps tout en surveillant les biais pour éviter la discrimination", correct: true },
      { text: "Remplacer totalement le jugement humain", correct: false },
      { text: "Elle est interdite partout", correct: false },
    ],
    explanation: "L'IA accélère le sourcing et le tri, mais peut reproduire des biais des données. L'enjeu 2026 : l'utiliser comme aide tout en gardant un contrôle humain et éthique.",
    tip: "IA utile, mais vigilance sur les biais et l'éthique.",
  },
  {
    ...base, id: 'rh-ac-2', type: 'actu', difficulty: 2,
    situation: "Évolution du recrutement.",
    question: "Que signifie le recrutement « par compétences » (skills-based) ?",
    options: [
      { text: "Recruter uniquement sur le diplôme", correct: false },
      { text: "Évaluer ce que la personne sait faire, au-delà du seul diplôme", correct: true },
      { text: "Recruter sans aucun critère", correct: false },
      { text: "Ne recruter que des seniors", correct: false },
    ],
    explanation: "Face à la pénurie de talents, on évalue de plus en plus les compétences réelles (tests, mises en situation) plutôt que le seul diplôme. Cela ouvre à des profils atypiques.",
    tip: "« Compétences > diplôme » : une tendance forte en 2026.",
  },
  {
    ...base, id: 'rh-ac-3', type: 'actu', difficulty: 2,
    situation: "Bien-être au travail.",
    question: "Que recouvre la QVCT ?",
    options: [
      { text: "Un type de contrat", correct: false },
      { text: "La Qualité de Vie et des Conditions de Travail : santé, charge, sens, conditions", correct: true },
      { text: "Un logiciel de paie", correct: false },
      { text: "Une prime exceptionnelle", correct: false },
    ],
    explanation: "La QVCT (ex-QVT) englobe les conditions de travail, la santé, la charge et le sens. C'est un levier majeur d'attractivité et de réduction du turnover.",
    tip: "QVCT = un argument clé de la marque employeur.",
  },
  {
    ...base, id: 'rh-ac-4', type: 'actu', difficulty: 2,
    situation: "Phénomène social.",
    question: "Que désigne le « quiet quitting » (démission silencieuse) ?",
    options: [
      { text: "Démissionner sans prévenir", correct: false },
      { text: "Faire le strict minimum, sans s'investir au-delà de sa fiche de poste", correct: true },
      { text: "Partir en pleine nuit", correct: false },
      { text: "Un type de licenciement", correct: false },
    ],
    explanation: "Le quiet quitting traduit un désengagement : le salarié reste mais se limite au minimum. C'est un signal RH d'un manque de sens ou de reconnaissance à adresser.",
    tip: "Le quiet quitting est un symptôme, pas une fatalité.",
  },
  {
    ...base, id: 'rh-ac-5', type: 'actu', difficulty: 3,
    situation: "Organisation du temps de travail.",
    question: "Que teste-t-on avec la « semaine de 4 jours » ?",
    options: [
      { text: "Travailler 4 jours pour le même résultat, en visant bien-être et productivité", correct: true },
      { text: "Supprimer les salaires un jour par semaine", correct: false },
      { text: "Travailler le week-end", correct: false },
      { text: "Fermer l'entreprise 4 jours", correct: false },
    ],
    explanation: "De plus en plus d'entreprises expérimentent la semaine de 4 jours pour améliorer l'équilibre et l'attractivité, sans perte de performance. Un sujet RH très discuté en 2026.",
    tip: "Sache en parler : c'est un débat RH d'actualité.",
  },
  {
    ...base, id: 'rh-ac-6', type: 'actu', difficulty: 2,
    situation: "Attentes des candidats.",
    question: "Pourquoi l'« expérience candidat » est-elle devenue clé ?",
    options: [
      { text: "Elle n'a aucun impact", correct: false },
      { text: "Un processus respectueux et fluide renforce l'image employeur et l'acceptation des offres", correct: true },
      { text: "Elle sert à allonger les délais", correct: false },
      { text: "Elle ne concerne que les stagiaires", correct: false },
    ],
    explanation: "Dans un marché en tension, la façon dont on traite les candidats (réactivité, transparence, respect) influence directement l'attractivité et le taux d'acceptation.",
    tip: "Un candidat mal traité parle ; un bien traité recommande.",
  },
  {
    ...base, id: 'rh-ac-7', type: 'actu', difficulty: 3,
    situation: "Reporting d'entreprise.",
    question: "Quel volet de la CSRD concerne directement les RH ?",
    options: [
      { text: "Le volet social : emploi, conditions de travail, égalité, formation", correct: true },
      { text: "Uniquement le bilan carbone", correct: false },
      { text: "Le calcul de la TVA", correct: false },
      { text: "La publicité de l'entreprise", correct: false },
    ],
    explanation: "La CSRD impose aux entreprises de publier des données extra-financières, dont un volet social (égalité, conditions de travail, formation). Les RH sont en première ligne pour les produire.",
    tip: "CSRD : les RH fournissent les indicateurs sociaux.",
  },
  {
    ...base, id: 'rh-ac-8', type: 'actu', difficulty: 2,
    situation: "Développement des talents.",
    question: "Pourquoi le « reskilling / upskilling » est-il stratégique ?",
    options: [
      { text: "Pour occuper les salariés inutilement", correct: false },
      { text: "Pour adapter les compétences aux métiers qui évoluent (IA, numérique) et fidéliser", correct: true },
      { text: "Pour remplacer la paie", correct: false },
      { text: "Ça n'a aucun intérêt", correct: false },
    ],
    explanation: "Reskilling (changer de métier) et upskilling (monter en compétences) répondent à l'évolution rapide des métiers. Former en interne fidélise et comble la pénurie de talents.",
    tip: "Former plutôt que remplacer : une réponse à la pénurie.",
  },

  // ── 🧠 COMPORTEMENTAL (suite) ──
  {
    ...base, id: 'rh-cp-7', type: 'comportemental', difficulty: 2,
    situation: "« Pourquoi les RH plutôt qu'un autre métier ? »",
    question: "La motivation la plus convaincante :",
    options: [
      { text: "« Pour avoir du pouvoir sur les salariés »", correct: false },
      { text: "L'intérêt pour l'humain, l'accompagnement et l'équilibre entreprise/salariés", correct: true },
      { text: "« Parce que c'est tranquille »", correct: false },
      { text: "« Pour licencier des gens »", correct: false },
    ],
    explanation: "Les RH concilient performance de l'entreprise et bien-être des salariés. La motivation attendue est l'intérêt sincère pour l'humain et l'accompagnement.",
    tip: "Parle d'humain et d'équilibre, pas de pouvoir.",
  },
  {
    ...base, id: 'rh-cp-8', type: 'comportemental', difficulty: 3,
    situation: "Vous accédez aux salaires et dossiers personnels de tous.",
    question: "La règle fondamentale :",
    options: [
      { text: "En discuter avec ses amis du bureau", correct: false },
      { text: "Confidentialité totale, aucune information divulguée", correct: true },
      { text: "Partager « entre RH » sans précaution", correct: false },
      { text: "Laisser les dossiers ouverts", correct: false },
    ],
    explanation: "La confidentialité est une obligation déontologique majeure en RH. Une fuite (salaire, santé, sanction) détruit la confiance et engage la responsabilité.",
    tip: "En RH, la discrétion n'a aucune exception.",
  },
  {
    ...base, id: 'rh-cp-9', type: 'comportemental', difficulty: 2,
    situation: "Deux salariés en conflit viennent se plaindre l'un de l'autre.",
    question: "La posture attendue :",
    options: [
      { text: "Prendre parti pour le plus sympathique", correct: false },
      { text: "Rester neutre, écouter les deux et chercher une solution équitable", correct: true },
      { text: "Ignorer le conflit", correct: false },
      { text: "Sanctionner au hasard", correct: false },
    ],
    explanation: "La neutralité et l'impartialité sont essentielles : le RH écoute toutes les parties sans préjugé pour traiter équitablement.",
    tip: "Écoute les deux versions avant tout jugement.",
  },
  {
    ...base, id: 'rh-cp-10', type: 'comportemental', difficulty: 2,
    situation: "Un salarié vient vous voir, visiblement bouleversé.",
    question: "La bonne attitude :",
    options: [
      { text: "L'expédier rapidement", correct: false },
      { text: "Faire preuve d'écoute et d'empathie, dans un cadre confidentiel", correct: true },
      { text: "Minimiser son problème", correct: false },
      { text: "En rire", correct: false },
    ],
    explanation: "L'empathie et l'écoute active sont au cœur du métier RH. Accueillir l'émotion sans la juger crée un climat de confiance.",
    tip: "Écoute d'abord, conseille ensuite.",
  },
  {
    ...base, id: 'rh-cp-11', type: 'comportemental', difficulty: 2,
    situation: "Vous expliquez une nouvelle procédure complexe aux équipes.",
    question: "La qualité valorisée :",
    options: [
      { text: "Utiliser un maximum de jargon juridique", correct: false },
      { text: "La pédagogie : rendre l'information claire et accessible à tous", correct: true },
      { text: "Envoyer un document sans explication", correct: false },
      { text: "« Débrouillez-vous »", correct: false },
    ],
    explanation: "Le RH traduit des règles complexes (droit, paie) en messages compréhensibles. La pédagogie favorise l'adhésion et limite les erreurs.",
    tip: "Si personne ne comprend, le message a échoué.",
  },
  {
    ...base, id: 'rh-cp-12', type: 'comportemental', difficulty: 2,
    situation: "Vous devez annoncer une décision impopulaire (gel des primes).",
    question: "La bonne approche :",
    options: [
      { text: "Cacher l'information", correct: false },
      { text: "Communiquer avec transparence, tact et explication du contexte", correct: true },
      { text: "Annoncer brutalement sans explication", correct: false },
      { text: "Laisser circuler la rumeur", correct: false },
    ],
    explanation: "La diplomatie et la transparence désamorcent les tensions : expliquer le pourquoi d'une décision difficile aide à l'accepter.",
    tip: "Explique le contexte : une décision comprise est mieux acceptée.",
  },
  {
    ...base, id: 'rh-cp-13', type: 'comportemental', difficulty: 1,
    situation: "« La rigueur administrative est-elle importante en RH ? »",
    question: "La réponse juste :",
    options: [
      { text: "« Non, l'humain suffit »", correct: false },
      { text: "Oui : contrats, paie et déclarations n'admettent pas d'erreur", correct: true },
      { text: "« On peut approximer »", correct: false },
      { text: "« C'est secondaire »", correct: false },
    ],
    explanation: "Le RH allie relationnel ET rigueur : une erreur de contrat, de paie ou de déclaration a des conséquences légales et financières.",
    tip: "En RH, l'humain ET la rigueur, jamais l'un sans l'autre.",
  },
  {
    ...base, id: 'rh-cp-14', type: 'comportemental', difficulty: 3,
    context: "Un manager vous demande d'écarter discrètement un candidat à cause de son âge.",
    situation: "On vous pousse vers une discrimination.",
    question: "La bonne réaction :",
    options: [
      { text: "Obéir sans rien dire", correct: false },
      { text: "Refuser : la discrimination est illégale, et rappeler les critères objectifs", correct: true },
      { text: "Le faire en cachette", correct: false },
      { text: "Laisser le manager décider seul", correct: false },
    ],
    explanation: "La discrimination (âge, origine, sexe…) est interdite par la loi. Le RH garantit l'équité et doit s'y opposer en s'appuyant sur des critères objectifs.",
    tip: "Recrutement = compétences, jamais critères discriminatoires.",
  },
  {
    ...base, id: 'rh-cp-15', type: 'comportemental', difficulty: 2,
    situation: "Vous gérez des sujets parfois lourds (licenciements, conflits).",
    question: "La qualité nécessaire :",
    options: [
      { text: "Se laisser submerger émotionnellement", correct: false },
      { text: "Garder la juste distance professionnelle tout en restant humain", correct: true },
      { text: "Devenir totalement insensible", correct: false },
      { text: "Fuir les sujets difficiles", correct: false },
    ],
    explanation: "Le RH doit gérer des situations sensibles avec recul : ni froideur, ni débordement émotionnel. L'équilibre protège le professionnel et la qualité du traitement.",
    tip: "Empathie oui, mais avec la juste distance.",
  },
  {
    ...base, id: 'rh-cp-16', type: 'comportemental', difficulty: 1,
    situation: "Un salarié vous pose une question dont vous ignorez la réponse juridique.",
    question: "La bonne attitude :",
    options: [
      { text: "Inventer une réponse", correct: false },
      { text: "Dire que vous vérifiez et revenez vers lui avec une réponse fiable", correct: true },
      { text: "« Je ne sais pas, débrouillez-vous »", correct: false },
      { text: "Changer de sujet", correct: false },
    ],
    explanation: "En droit social, une réponse erronée peut coûter cher. Mieux vaut vérifier et répondre juste que bluffer.",
    tip: "Sur le droit, on vérifie avant d'affirmer.",
  },
  {
    ...base, id: 'rh-cp-17', type: 'comportemental', difficulty: 2,
    situation: "Vous représentez les RH lors d'un échange avec les représentants du personnel.",
    question: "La posture adaptée :",
    options: [
      { text: "Les considérer comme des adversaires", correct: false },
      { text: "Dialoguer avec respect et chercher un terrain d'entente constructif", correct: true },
      { text: "Refuser tout échange", correct: false },
      { text: "Mentir pour gagner", correct: false },
    ],
    explanation: "Le dialogue social repose sur le respect mutuel et la recherche de compromis. Une relation constructive avec les représentants prévient les conflits.",
    tip: "Le dialogue social se construit dans le respect.",
  },
  {
    ...base, id: 'rh-cp-18', type: 'comportemental', difficulty: 2,
    situation: "Les priorités RH changent souvent (urgences, imprévus sociaux).",
    question: "La qualité-clé :",
    options: [
      { text: "Refuser tout changement de plan", correct: false },
      { text: "L'adaptabilité : réorganiser ses priorités sans perdre en fiabilité", correct: true },
      { text: "Paniquer à chaque imprévu", correct: false },
      { text: "Ignorer les urgences", correct: false },
    ],
    explanation: "Le RH jongle entre projets de fond et urgences humaines. Savoir se réorganiser tout en restant fiable est indispensable.",
    tip: "Flexibilité sans perdre la rigueur.",
  },
  {
    ...base, id: 'rh-cp-19', type: 'comportemental', difficulty: 1,
    situation: "Un candidat refusé demande un retour sur sa candidature.",
    question: "La bonne attitude :",
    options: [
      { text: "L'ignorer", correct: false },
      { text: "Donner un retour respectueux et constructif", correct: true },
      { text: "« Vous n'étiez pas bien »", correct: false },
      { text: "Mentir totalement", correct: false },
    ],
    explanation: "Soigner l'expérience candidat, même en cas de refus, protège la marque employeur. Un retour respectueux laisse une bonne image.",
    tip: "Un candidat refusé reste un ambassadeur potentiel.",
  },
  {
    ...base, id: 'rh-cp-20', type: 'comportemental', difficulty: 2,
    situation: "« Quelle est la qualité n°1 d'un bon RH selon vous ? »",
    question: "La réponse la plus pertinente :",
    options: [
      { text: "« Savoir dire non à tout le monde »", correct: false },
      { text: "L'équilibre entre écoute humaine et sens des intérêts de l'entreprise", correct: true },
      { text: "« Être copain avec tout le monde »", correct: false },
      { text: "« Faire de la paperasse »", correct: false },
    ],
    explanation: "Le RH est à l'interface : il défend l'humain ET la performance. Cet équilibre, plus que la sympathie ou l'autorité, fait un bon professionnel.",
    tip: "RH = pont entre les salariés et l'entreprise.",
  },

  // ── 🛠️ TECHNIQUE (suite) ──
  {
    ...base, id: 'rh-te-10', type: 'technique', difficulty: 2,
    situation: "Vous devez recruter pour un poste difficile à pourvoir.",
    question: "La bonne démarche de sourcing :",
    options: [
      { text: "Attendre passivement les candidatures", correct: false },
      { text: "Multiplier les canaux (jobboards, LinkedIn, cooptation) et chasser activement", correct: true },
      { text: "Ne publier que sur un seul site", correct: false },
      { text: "Recruter le premier venu", correct: false },
    ],
    explanation: "Sur un poste en tension, le sourcing actif (approche directe, réseaux, cooptation) est plus efficace que la simple publication d'annonce.",
    tip: "Diversifie les canaux et va chercher les profils.",
  },
  {
    ...base, id: 'rh-te-11', type: 'technique', difficulty: 2,
    situation: "Vous menez un entretien de recrutement.",
    question: "La bonne pratique :",
    options: [
      { text: "Poser des questions discriminatoires (situation familiale…)", correct: false },
      { text: "Évaluer les compétences via des questions ouvertes et des cas concrets", correct: true },
      { text: "Parler tout le temps sans écouter", correct: false },
      { text: "Décider sur la première impression", correct: false },
    ],
    explanation: "Un entretien structuré évalue les compétences (questions comportementales, mises en situation) sur des critères objectifs, sans questions interdites.",
    tip: "Questions ouvertes + exemples concrets = évaluation fiable.",
  },
  {
    ...base, id: 'rh-te-12', type: 'technique', difficulty: 3,
    situation: "Un nouveau salarié arrive lundi.",
    question: "Les formalités d'embauche incontournables :",
    options: [
      { text: "Rien, on verra plus tard", correct: false },
      { text: "DPAE, contrat signé, registre du personnel et visite médicale", correct: true },
      { text: "Seulement lui montrer son bureau", correct: false },
      { text: "Le payer sans contrat", correct: false },
    ],
    explanation: "L'embauche impose des formalités légales : DPAE (avant l'arrivée), contrat de travail, registre unique du personnel, suivi médical. Les omettre expose à des sanctions.",
    tip: "La DPAE se fait AVANT la prise de poste.",
  },
  {
    ...base, id: 'rh-te-13', type: 'technique', difficulty: 2,
    situation: "On vous interroge sur la période d'essai.",
    question: "Ce qu'il faut savoir :",
    options: [
      { text: "Elle est définitive et non renouvelable jamais", correct: false },
      { text: "Elle permet à chaque partie de rompre selon des délais légaux de prévenance", correct: true },
      { text: "Elle n'existe pas en CDI", correct: false },
      { text: "Elle dure toujours 2 ans", correct: false },
    ],
    explanation: "La période d'essai permet d'évaluer mutuellement, avec des durées encadrées et un délai de prévenance à respecter pour rompre. Sa maîtrise évite les contentieux.",
    tip: "Respecte toujours le délai de prévenance.",
  },
  {
    ...base, id: 'rh-te-14', type: 'technique', difficulty: 3,
    situation: "Un salarié et l'employeur veulent se séparer à l'amiable.",
    question: "Le dispositif adapté :",
    options: [
      { text: "Le licenciement sans motif", correct: false },
      { text: "La rupture conventionnelle (accord mutuel, homologuée)", correct: true },
      { text: "La démission forcée", correct: false },
      { text: "Le renvoi verbal immédiat", correct: false },
    ],
    explanation: "La rupture conventionnelle organise une séparation d'un commun accord, avec indemnité et homologation administrative. C'est le cadre légal de la séparation amiable en CDI.",
    tip: "Séparation à l'amiable = rupture conventionnelle, pas démission « forcée ».",
  },
  {
    ...base, id: 'rh-te-15', type: 'technique', difficulty: 2,
    situation: "Vous préparez les variables de paie du mois.",
    question: "La rigueur attendue :",
    options: [
      { text: "Estimer les heures au feeling", correct: false },
      { text: "Collecter et vérifier absences, heures sup, primes avant transmission", correct: true },
      { text: "Copier le mois précédent sans vérifier", correct: false },
      { text: "Laisser le salarié calculer", correct: false },
    ],
    explanation: "La paie ne tolère pas l'erreur : variables (absences, heures sup, primes) collectées et vérifiées avant traitement. Une erreur de paie démotive et peut être illégale.",
    tip: "Vérifie les variables AVANT la clôture de paie.",
  },
  {
    ...base, id: 'rh-te-16', type: 'technique', difficulty: 2,
    situation: "Vous organisez l'intégration des nouveaux (onboarding).",
    question: "Un bon onboarding :",
    options: [
      { text: "Laisser le nouveau seul le premier jour", correct: false },
      { text: "Préparer poste, accès, parcours d'accueil et points de suivi", correct: true },
      { text: "Tout improviser", correct: false },
      { text: "Donner 200 pages à lire sans accompagnement", correct: false },
    ],
    explanation: "Un onboarding structuré (matériel prêt, accueil, parrain, points réguliers) accélère la prise de poste et réduit le turnover précoce.",
    tip: "Les premières semaines décident souvent de la fidélité.",
  },
  {
    ...base, id: 'rh-te-17', type: 'technique', difficulty: 2,
    situation: "Vous devez bâtir le plan de développement des compétences.",
    question: "La bonne approche :",
    options: [
      { text: "Choisir des formations au hasard", correct: false },
      { text: "Partir des besoins (entreprise + salariés) et prioriser selon les enjeux", correct: true },
      { text: "Ne former personne", correct: false },
      { text: "Former uniquement les managers", correct: false },
    ],
    explanation: "Le plan de formation s'appuie sur l'analyse des besoins (stratégie, entretiens) pour développer les compétences utiles. C'est un investissement, pas une dépense.",
    tip: "Relie chaque formation à un besoin identifié.",
  },
  {
    ...base, id: 'rh-te-18', type: 'technique', difficulty: 2,
    situation: "On vous demande de suivre des indicateurs RH.",
    question: "Des KPI RH pertinents :",
    options: [
      { text: "La météo du jour", correct: false },
      { text: "Turnover, absentéisme, délai de recrutement, masse salariale", correct: true },
      { text: "Le nombre de cafés bus", correct: false },
      { text: "Aucun, les chiffres ne servent à rien", correct: false },
    ],
    explanation: "Les indicateurs RH (turnover, absentéisme, time-to-hire, masse salariale) pilotent la fonction et alertent sur les problèmes. Le reporting est devenu central.",
    tip: "Mesurer pour piloter : turnover et absentéisme en tête.",
  },
  {
    ...base, id: 'rh-te-19', type: 'technique', difficulty: 2,
    situation: "Un salarié pose des congés sur une période chargée.",
    question: "La gestion adaptée :",
    options: [
      { text: "Refuser sans explication", correct: false },
      { text: "Appliquer les règles de pose et arbitrer selon les nécessités de service", correct: true },
      { text: "Accepter tout sans regarder le planning", correct: false },
      { text: "Décider selon ses préférences personnelles", correct: false },
    ],
    explanation: "La gestion des congés concilie droit du salarié et continuité de service, selon des règles connues et équitables. L'arbitraire crée des tensions.",
    tip: "Des règles claires de pose évitent les conflits.",
  },
  {
    ...base, id: 'rh-te-20', type: 'technique', difficulty: 2,
    situation: "L'entreprise s'équipe d'un SIRH (logiciel RH).",
    question: "Son intérêt principal :",
    options: [
      { text: "Compliquer le travail pour rien", correct: false },
      { text: "Centraliser et fiabiliser données, paie, congés et reporting", correct: true },
      { text: "Remplacer toute la fonction RH", correct: false },
      { text: "Supprimer les salariés", correct: false },
    ],
    explanation: "Un SIRH centralise les données et automatise des process (congés, paie, reporting), fiabilisant l'information et libérant du temps pour l'accompagnement.",
    tip: "Le SIRH fiabilise les données et fait gagner du temps.",
  },

  // ── 🎭 MISE EN SITUATION (suite) ──
  {
    ...base, id: 'rh-si-7', type: 'situation', difficulty: 2,
    context: "Un manager veut licencier un salarié « parce qu'il ne l'aime pas », sans motif réel.",
    situation: "Demande de licenciement sans motif valable.",
    question: "La bonne réponse RH :",
    options: [
      { text: "Lancer la procédure quand même", correct: false },
      { text: "Rappeler qu'un licenciement exige un motif réel et sérieux, et explorer d'autres pistes", correct: true },
      { text: "Refuser sans rien expliquer", correct: false },
      { text: "Pousser le salarié à démissionner par la pression", correct: false },
    ],
    explanation: "Un licenciement sans cause réelle et sérieuse est illégal et coûteux (prud'hommes). Le RH protège l'entreprise en cadrant juridiquement et en cherchant des alternatives.",
    tip: "Pas de motif réel = pas de licenciement légal.",
  },
  {
    ...base, id: 'rh-si-8', type: 'situation', difficulty: 3,
    context: "Une salariée vous confie en pleurs qu'elle subit du harcèlement de son chef.",
    situation: "Un signalement de harcèlement vous est confié.",
    question: "La bonne réaction :",
    options: [
      { text: "Minimiser et lui dire de prendre sur elle", correct: false },
      { text: "Écouter, prendre au sérieux, garantir la confidentialité et déclencher la procédure", correct: true },
      { text: "En parler à tout le monde", correct: false },
      { text: "Ne rien faire", correct: false },
    ],
    explanation: "Tout signalement de harcèlement doit être pris au sérieux : écoute, confidentialité, enquête et protection. L'employeur a une obligation de sécurité.",
    tip: "Un signalement se traite toujours, jamais ne s'étouffe.",
  },
  {
    ...base, id: 'rh-si-9', type: 'situation', difficulty: 2,
    situation: "Un bon élément annonce sa démission.",
    question: "La meilleure démarche :",
    options: [
      { text: "Le laisser partir sans un mot", correct: false },
      { text: "Mener un entretien de départ pour comprendre et, si pertinent, tenter de le retenir", correct: true },
      { text: "Le dénigrer auprès des autres", correct: false },
      { text: "Bloquer son départ illégalement", correct: false },
    ],
    explanation: "L'entretien de départ révèle des causes utiles (management, salaire, évolution) et peut parfois retenir un talent. Il améliore aussi la rétention future.",
    tip: "Chaque départ est une source d'apprentissage.",
  },
  {
    ...base, id: 'rh-si-10', type: 'situation', difficulty: 2,
    situation: "Un salarié demande une augmentation que le budget ne permet pas.",
    question: "La bonne réponse :",
    options: [
      { text: "Promettre sans pouvoir tenir", correct: false },
      { text: "Écouter, expliquer la contrainte et explorer d'autres leviers (évolution, formation)", correct: true },
      { text: "Refuser sèchement sans explication", correct: false },
      { text: "Ignorer la demande", correct: false },
    ],
    explanation: "On traite la demande avec considération : transparence sur les contraintes et alternatives (perspectives, avantages). Promettre l'impossible détruit la confiance.",
    tip: "Pas d'augmentation possible ? Propose d'autres leviers.",
  },
  {
    ...base, id: 'rh-si-11', type: 'situation', difficulty: 2,
    situation: "Un manager vous demande le salaire d'un autre salarié, par curiosité.",
    question: "La bonne réponse :",
    options: [
      { text: "Le lui communiquer", correct: false },
      { text: "Refuser : c'est une donnée confidentielle non justifiée par son besoin", correct: true },
      { text: "Le dire « entre nous »", correct: false },
      { text: "L'écrire sur un post-it", correct: false },
    ],
    explanation: "Les rémunérations sont confidentielles et ne se partagent qu'avec les personnes habilitées et pour un motif légitime. La curiosité n'en est pas un.",
    tip: "Donnée confidentielle = accès strictement justifié.",
  },
  {
    ...base, id: 'rh-si-12', type: 'situation', difficulty: 2,
    context: "Vous menez un entretien et le candidat ment manifestement sur une expérience.",
    situation: "Un candidat exagère/ment sur son CV.",
    question: "La bonne réaction :",
    options: [
      { text: "L'accuser frontalement", correct: false },
      { text: "Creuser avec des questions précises et factuelles pour vérifier", correct: true },
      { text: "Faire comme si de rien n'était et le recruter", correct: false },
      { text: "Se moquer de lui", correct: false },
    ],
    explanation: "Plutôt qu'accuser, on creuse par des questions concrètes (exemples, chiffres, mises en situation) qui révèlent vite le réel niveau, sans agresser.",
    tip: "Les détails concrets démasquent les exagérations.",
  },
  {
    ...base, id: 'rh-si-13', type: 'situation', difficulty: 3,
    context: "Plan de réorganisation : plusieurs postes sont menacés et la rumeur enfle.",
    situation: "Climat anxiogène et rumeurs dans l'entreprise.",
    question: "La meilleure posture RH :",
    options: [
      { text: "Nier en bloc et laisser la rumeur enfler", correct: false },
      { text: "Communiquer de façon claire et cadrée sur ce qui est connu, avec empathie", correct: true },
      { text: "Annoncer brutalement sans accompagnement", correct: false },
      { text: "Disparaître", correct: false },
    ],
    explanation: "Le silence nourrit les rumeurs et l'anxiété. Une communication maîtrisée, honnête sur ce qui peut être dit, et de l'écoute apaisent le climat.",
    tip: "Contre la rumeur : information claire et écoute.",
  },
  {
    ...base, id: 'rh-si-14', type: 'situation', difficulty: 2,
    situation: "Un salarié multiplie les arrêts maladie courts.",
    question: "La bonne approche :",
    options: [
      { text: "Le sanctionner immédiatement", correct: false },
      { text: "Mener un entretien bienveillant pour comprendre l'éventuel mal-être", correct: true },
      { text: "L'ignorer", correct: false },
      { text: "Le dénigrer", correct: false },
    ],
    explanation: "Un absentéisme répété est souvent un signal (santé, conditions de travail, démotivation). L'entretien de retour, bienveillant, aide à en comprendre la cause.",
    tip: "L'absentéisme est un symptôme à comprendre, pas juste à punir.",
  },
  {
    ...base, id: 'rh-si-15', type: 'situation', difficulty: 2,
    situation: "Une offre d'emploi reçoit 200 candidatures.",
    question: "La gestion efficace :",
    options: [
      { text: "Prendre la première venue", correct: false },
      { text: "Présélectionner sur critères objectifs liés au poste, puis approfondir", correct: true },
      { text: "Choisir selon la photo", correct: false },
      { text: "Tout refuser", correct: false },
    ],
    explanation: "Un tri structuré sur des critères liés au poste (compétences, expérience) garantit équité et efficacité face à un grand volume de candidatures.",
    tip: "Des critères objectifs = tri rapide ET équitable.",
  },
  {
    ...base, id: 'rh-si-16', type: 'situation', difficulty: 2,
    situation: "Un manager refuse d'appliquer une règle RH (ex. entretiens annuels).",
    question: "La bonne démarche :",
    options: [
      { text: "Laisser tomber", correct: false },
      { text: "Lui rappeler l'enjeu/obligation et l'accompagner pour faciliter la mise en œuvre", correct: true },
      { text: "Le dénoncer publiquement", correct: false },
      { text: "Faire les entretiens à sa place", correct: false },
    ],
    explanation: "Le RH obtient l'adhésion des managers par la pédagogie et l'accompagnement, en rappelant les enjeux (et parfois l'obligation légale), plutôt que par le conflit.",
    tip: "Convaincre le manager > le contraindre.",
  },
  {
    ...base, id: 'rh-si-17', type: 'situation', difficulty: 1,
    situation: "Un salarié ne comprend pas sa fiche de paie.",
    question: "La bonne attitude :",
    options: [
      { text: "« Ce n'est pas mon problème »", correct: false },
      { text: "Lui expliquer clairement les lignes concernées avec patience", correct: true },
      { text: "Lui dire de chercher seul", correct: false },
      { text: "Le rembarrer", correct: false },
    ],
    explanation: "Expliquer une fiche de paie avec pédagogie fait partie du rôle RH et entretient la confiance des salariés.",
    tip: "La pédagogie sur la paie évite bien des tensions.",
  },
  {
    ...base, id: 'rh-si-18', type: 'situation', difficulty: 2,
    context: "Vous recrutez deux profils équivalents pour un seul poste.",
    situation: "Départager deux excellents candidats.",
    question: "Le bon critère final :",
    options: [
      { text: "Le hasard ou l'affinité personnelle", correct: false },
      { text: "L'adéquation au poste/équipe et le potentiel d'évolution, sur critères objectifs", correct: true },
      { text: "L'apparence", correct: false },
      { text: "Le lieu d'habitation", correct: false },
    ],
    explanation: "À compétences égales, on départage sur l'adéquation au besoin (équipe, culture, potentiel) avec des critères objectifs, jamais sur des éléments discriminatoires.",
    tip: "Objective ton choix final, ne te fie pas au feeling seul.",
  },
  {
    ...base, id: 'rh-si-19', type: 'situation', difficulty: 2,
    situation: "Un salarié vous signale une erreur sur son solde de congés.",
    question: "La bonne réaction :",
    options: [
      { text: "Nier sans vérifier", correct: false },
      { text: "Vérifier le décompte et corriger si l'erreur est avérée", correct: true },
      { text: "Lui dire qu'il se trompe forcément", correct: false },
      { text: "Ignorer", correct: false },
    ],
    explanation: "On traite tout signalement par une vérification factuelle et une correction si nécessaire. La rigueur et l'écoute préservent la confiance.",
    tip: "Vérifie d'abord, corrige ensuite si besoin.",
  },
  {
    ...base, id: 'rh-si-20', type: 'situation', difficulty: 3,
    context: "Un salarié performant menace de partir s'il n'obtient pas une évolution.",
    situation: "Risque de perdre un talent clé.",
    question: "La meilleure démarche :",
    options: [
      { text: "Le laisser partir sans discuter", correct: false },
      { text: "Évaluer objectivement sa demande et construire un plan d'évolution réaliste", correct: true },
      { text: "Promettre n'importe quoi pour le retenir", correct: false },
      { text: "Le menacer en retour", correct: false },
    ],
    explanation: "On répond par une analyse objective (mérite, possibilités) et un plan réaliste. Promettre l'impossible ou ignorer le risque sont deux erreurs symétriques.",
    tip: "Retiens par un plan crédible, pas par des promesses en l'air.",
  },

  // ── 📰 ACTU & TENDANCES (suite) ──
  {
    ...base, id: 'rh-ac-9', type: 'actu', difficulty: 2,
    situation: "La « marque employeur » est sur toutes les lèvres.",
    question: "De quoi s'agit-il ?",
    options: [
      { text: "Le logo de l'entreprise", correct: false },
      { text: "L'image de l'entreprise en tant qu'employeur, pour attirer et fidéliser", correct: true },
      { text: "Une marque de produits", correct: false },
      { text: "Le nom du DRH", correct: false },
    ],
    explanation: "La marque employeur est la réputation de l'entreprise auprès des candidats et salariés. Elle est devenue clé pour attirer les talents dans un marché tendu.",
    tip: "Une bonne marque employeur attire sans surenchère salariale.",
  },
  {
    ...base, id: 'rh-ac-10', type: 'actu', difficulty: 2,
    situation: "La QVT/QVCT (qualité de vie au travail) est une priorité.",
    question: "Un levier de QVT pertinent :",
    options: [
      { text: "Augmenter la charge de travail", correct: false },
      { text: "Agir sur l'organisation, le sens, l'équilibre et la reconnaissance", correct: true },
      { text: "Installer un babyfoot et tout est réglé", correct: false },
      { text: "Ignorer le bien-être", correct: false },
    ],
    explanation: "La QVCT touche l'organisation, la charge, le sens et la reconnaissance — bien au-delà des gadgets. Elle réduit l'absentéisme et le turnover.",
    tip: "QVT réelle = organisation et reconnaissance, pas babyfoot.",
  },
  {
    ...base, id: 'rh-ac-11', type: 'actu', difficulty: 2,
    situation: "Le télétravail soulève la question du droit à la déconnexion.",
    question: "Ce que cela implique :",
    options: [
      { text: "Être joignable 24h/24", correct: false },
      { text: "Respecter des plages sans sollicitation pour préserver l'équilibre", correct: true },
      { text: "Interdire le télétravail", correct: false },
      { text: "Supprimer les horaires", correct: false },
    ],
    explanation: "Le droit à la déconnexion protège l'équilibre vie pro/perso en limitant les sollicitations hors temps de travail. C'est un enjeu RH et légal.",
    tip: "Déconnexion = santé des salariés ET obligation employeur.",
  },
  {
    ...base, id: 'rh-ac-12', type: 'actu', difficulty: 3,
    situation: "L'IA est utilisée pour trier les CV.",
    question: "Le risque principal à surveiller :",
    options: [
      { text: "Qu'elle aille trop vite", correct: false },
      { text: "Les biais discriminatoires reproduits par l'algorithme", correct: true },
      { text: "Qu'elle soit trop juste", correct: false },
      { text: "Aucun risque", correct: false },
    ],
    explanation: "Un outil d'IA mal conçu peut reproduire et amplifier des biais (genre, origine). Le RH doit garder un contrôle humain et veiller à l'équité.",
    tip: "IA dans le recrutement : garde l'humain et surveille les biais.",
  },
  {
    ...base, id: 'rh-ac-13', type: 'actu', difficulty: 2,
    situation: "La diversité et l'inclusion sont des priorités affichées.",
    question: "Une action RH concrète :",
    options: [
      { text: "Recruter toujours le même profil", correct: false },
      { text: "Objectiver les recrutements et sensibiliser aux biais pour élargir les profils", correct: true },
      { text: "Afficher un slogan sans rien changer", correct: false },
      { text: "Discriminer « positivement » au hasard", correct: false },
    ],
    explanation: "La diversité se construit par des process objectivés et la sensibilisation aux biais, pas par des slogans. Elle enrichit la performance collective.",
    tip: "Diversité = process objectifs + lutte contre les biais.",
  },
  {
    ...base, id: 'rh-ac-14', type: 'actu', difficulty: 2,
    situation: "Le marché du travail connaît une pénurie de talents.",
    question: "Une réponse RH adaptée :",
    options: [
      { text: "Baisser les exigences sans rien changer d'autre", correct: false },
      { text: "Soigner marque employeur, fidélisation et formation interne (reskilling)", correct: true },
      { text: "Ne plus recruter", correct: false },
      { text: "Maltraiter les salariés en place", correct: false },
    ],
    explanation: "Face à la pénurie, attirer (marque employeur), garder (fidélisation) et former en interne (reskilling) sont plus durables que la seule surenchère.",
    tip: "Former et fidéliser autant que recruter.",
  },
  {
    ...base, id: 'rh-ac-15', type: 'actu', difficulty: 2,
    situation: "On entend parler de « quiet quitting » (désengagement).",
    question: "La bonne lecture RH :",
    options: [
      { text: "Ce sont juste des paresseux", correct: false },
      { text: "Un signal de démotivation à comprendre (sens, reconnaissance, charge)", correct: true },
      { text: "Un phénomène sans importance", correct: false },
      { text: "Une raison de licencier en masse", correct: false },
    ],
    explanation: "Le désengagement (faire le minimum) traduit souvent un manque de sens ou de reconnaissance. Le RH agit sur les causes plutôt que de blâmer.",
    tip: "Le désengagement est un symptôme managérial, pas une fatalité.",
  },
  {
    ...base, id: 'rh-ac-16', type: 'actu', difficulty: 2,
    situation: "La semaine de 4 jours est expérimentée par des entreprises.",
    question: "L'attitude RH pertinente :",
    options: [
      { text: "Rejeter sans réflexion", correct: false },
      { text: "Étudier impacts (organisation, productivité, équité) avant de trancher", correct: true },
      { text: "L'imposer du jour au lendemain", correct: false },
      { text: "Réduire le salaire en douce", correct: false },
    ],
    explanation: "Les nouvelles organisations du temps se pilotent par l'analyse d'impact et l'expérimentation, en veillant à l'équité entre métiers.",
    tip: "Teste et mesure avant de généraliser une nouvelle organisation.",
  },
  {
    ...base, id: 'rh-ac-17', type: 'actu', difficulty: 3,
    situation: "Les données RH se multiplient (people analytics).",
    question: "Le bon usage :",
    options: [
      { text: "Surveiller les salariés en continu", correct: false },
      { text: "Éclairer les décisions (turnover, formation) dans le respect du RGPD", correct: true },
      { text: "Vendre les données", correct: false },
      { text: "Ignorer toute donnée", correct: false },
    ],
    explanation: "Le people analytics aide à décider (prévenir le turnover, cibler la formation) à condition de respecter l'éthique et le RGPD. Ce n'est pas un outil de flicage.",
    tip: "Data RH au service des décisions, pas de la surveillance.",
  },
  {
    ...base, id: 'rh-ac-18', type: 'actu', difficulty: 2,
    situation: "Les candidats sont aussi protégés par le RGPD.",
    question: "Le bon réflexe :",
    options: [
      { text: "Garder les CV indéfiniment", correct: false },
      { text: "Informer, limiter la durée de conservation et sécuriser les candidatures", correct: true },
      { text: "Partager les CV librement", correct: false },
      { text: "Revendre les coordonnées", correct: false },
    ],
    explanation: "Les données des candidats sont personnelles : information, durée de conservation limitée et sécurité s'imposent au recruteur.",
    tip: "Les CV ne se conservent pas éternellement.",
  },
  {
    ...base, id: 'rh-ac-19', type: 'actu', difficulty: 2,
    situation: "Les salariés attendent du sens et des valeurs (RSE).",
    question: "L'impact pour les RH :",
    options: [
      { text: "Aucun, seul le salaire compte", correct: false },
      { text: "Intégrer sens, engagement et RSE dans l'attractivité et la fidélisation", correct: true },
      { text: "Interdire de parler de valeurs", correct: false },
      { text: "Faire du « social washing »", correct: false },
    ],
    explanation: "Le sens et l'engagement RSE pèsent de plus en plus dans le choix et la fidélité des salariés, surtout des jeunes générations. La sincérité est clé.",
    tip: "Le sens fidélise autant que le salaire pour beaucoup.",
  },
  {
    ...base, id: 'rh-ac-20', type: 'actu', difficulty: 2,
    situation: "L'expérience collaborateur devient un sujet stratégique.",
    question: "Ce qu'elle recouvre :",
    options: [
      { text: "Uniquement le jour de l'embauche", correct: false },
      { text: "L'ensemble du parcours salarié, du recrutement au départ", correct: true },
      { text: "Seulement la pause déjeuner", correct: false },
      { text: "Rien de concret", correct: false },
    ],
    explanation: "L'expérience collaborateur englobe tout le cycle de vie (recrutement, intégration, évolution, départ). La soigner améliore engagement et marque employeur.",
    tip: "Soigne chaque étape du parcours, pas seulement l'arrivée.",
  },
];
