/**
 * Thème « Négociation salaire » — 20 scénarios.
 * Aborder la rémunération avec préparation, justesse et professionnalisme.
 * Chaque question : exactement une option correct:true, + explanation + tip.
 */
export default [
  {
    id: 'sal-1', category: 'salaire', difficulty: 3,
    situation: "« Quelles sont vos prétentions salariales ? »",
    question: "La meilleure stratégie :",
    options: [
      { text: "Donner un chiffre au hasard", correct: false },
      { text: "Annoncer une fourchette préparée selon le marché et son profil", correct: true },
      { text: "« Je prends ce que vous donnez »", correct: false },
      { text: "Exiger le double sans justification", correct: false },
    ],
    explanation: "Une fourchette argumentée (étude du marché + ton niveau) montre que tu connais ta valeur sans bloquer la discussion. Ni se brader, ni être déconnecté.",
    tip: "Renseigne-toi sur les grilles du secteur avant l'entretien.",
  },
  {
    id: 'sal-2', category: 'salaire', difficulty: 2,
    situation: "On vous propose un salaire un peu en dessous de vos attentes.",
    question: "La bonne réaction :",
    options: [
      { text: "Accepter immédiatement sans discuter", correct: false },
      { text: "Négocier calmement ou évoquer les avantages annexes", correct: true },
      { text: "Se vexer et quitter l'entretien", correct: false },
      { text: "Mentir sur son salaire actuel", correct: false },
    ],
    explanation: "La négociation est attendue et professionnelle. On peut discuter le fixe, mais aussi les avantages (primes, télétravail, formation, évolution).",
    tip: "Le package total compte autant que le salaire brut.",
  },
  {
    id: 'sal-3', category: 'salaire', difficulty: 1,
    situation: "Avant l'entretien, vous préparez votre prétention salariale.",
    question: "Sur quoi vous appuyer ?",
    options: [
      { text: "Les grilles du secteur, le poste, votre niveau et votre région", correct: true },
      { text: "Le salaire de votre voisin", correct: false },
      { text: "Ce dont vous rêvez, sans rapport avec le marché", correct: false },
      { text: "Rien, vous verrez sur le moment", correct: false },
    ],
    explanation: "Une prétention crédible se construit sur des données : enquêtes de rémunération, offres similaires, ton expérience et la zone géographique. Improviser te fait viser trop haut ou trop bas.",
    tip: "Compare plusieurs annonces du même poste pour situer la fourchette du marché.",
  },
  {
    id: 'sal-4', category: 'salaire', difficulty: 2,
    situation: "Vous ne savez pas du tout combien demander.",
    question: "La meilleure réponse en attendant d'avoir la fourchette de l'entreprise :",
    options: [
      { text: "« Je suis ouvert, mais j'aimerais connaître la fourchette prévue pour ce poste »", correct: true },
      { text: "« Aucune idée, mettez ce que vous voulez »", correct: false },
      { text: "Donner un chiffre énorme au hasard", correct: false },
      { text: "Refuser de parler salaire", correct: false },
    ],
    explanation: "Renvoyer poliment la question pour connaître la fourchette est une tactique valable, tant que tu as quand même une idée en tête. « Mettez ce que vous voulez » te dévalorise.",
    tip: "Tu peux demander la fourchette, mais aie toujours ton propre chiffre prêt.",
  },
  {
    id: 'sal-5', category: 'salaire', difficulty: 1,
    situation: "Brut ou net : on vous demande votre prétention.",
    question: "Quelle précision apporter ?",
    options: [
      { text: "Toujours raisonner et annoncer en brut annuel (la référence en entreprise)", correct: true },
      { text: "Donner un chiffre sans préciser brut ou net", correct: false },
      { text: "Parler uniquement en net mensuel", correct: false },
      { text: "Éviter de préciser pour rester vague", correct: false },
    ],
    explanation: "En France, les salaires se discutent en brut annuel. Annoncer un chiffre sans préciser crée des malentendus. Maîtriser la conversion brut/net montre aussi ton sérieux.",
    tip: "Mémorise l'ordre de grandeur : le net ≈ 78 % du brut pour un non-cadre.",
  },
  {
    id: 'sal-6', category: 'salaire', difficulty: 2,
    situation: "« Combien gagnez-vous actuellement ? »",
    question: "La meilleure attitude :",
    options: [
      { text: "Répondre honnêtement, ou recentrer sur vos attentes pour le nouveau poste", correct: true },
      { text: "Gonfler fortement votre salaire actuel", correct: false },
      { text: "Refuser sèchement de répondre", correct: false },
      { text: "« Ça ne vous regarde pas »", correct: false },
    ],
    explanation: "On peut rester factuel sur le salaire actuel, ou rediriger poliment vers ses attentes pour le poste visé. Mentir est risqué (justificatifs possibles) et un refus agressif braque le recruteur.",
    tip: "« Aujourd'hui je suis à X, et pour ce poste je vise Y » est une transition fluide.",
  },
  {
    id: 'sal-7', category: 'salaire', difficulty: 2,
    situation: "Au-delà du salaire fixe, l'entreprise propose des avantages.",
    question: "Lesquels comptent dans la négociation ?",
    options: [
      { text: "Primes, télétravail, tickets resto, mutuelle, formation, évolution", correct: true },
      { text: "Seul le fixe compte, le reste est inutile", correct: false },
      { text: "Uniquement la machine à café", correct: false },
      { text: "Rien d'autre que le brut ne mérite attention", correct: false },
    ],
    explanation: "Le package global peut largement compenser un fixe légèrement plus bas : primes, avantages, télétravail, formations, perspectives d'évolution ont une vraie valeur.",
    tip: "Calcule la valeur réelle des avantages avant de juger une offre « trop basse ».",
  },
  {
    id: 'sal-8', category: 'salaire', difficulty: 3,
    context: "Premier emploi après l'alternance. Le manager apprécie votre profil. « Vous débutez, donc on partirait sur le bas de la grille. Ça vous va ? »",
    situation: "On vous pousse vers le bas de la fourchette au motif du manque d'expérience.",
    question: "La réponse la plus juste :",
    options: [
      { text: "Reconnaître votre niveau tout en valorisant vos atouts pour viser le milieu de fourchette", correct: true },
      { text: "« Oui oui, ce que vous voulez »", correct: false },
      { text: "Exiger le haut de la grille avec agressivité", correct: false },
      { text: "Vous braquer et rompre l'échange", correct: false },
    ],
    explanation: "Débuter ne veut pas dire tout accepter. Reconnais ton niveau, mais mets en avant ce qui te démarque (alternance dans le métier, compétences déjà opérationnelles) pour négocier un cran au-dessus.",
    tip: "Une alternance dans le métier = de l'expérience réelle à faire valoir.",
  },
  {
    id: 'sal-9', category: 'salaire', difficulty: 1,
    situation: "À quel moment aborder le salaire ?",
    question: "La règle générale :",
    options: [
      { text: "Quand le recruteur l'aborde, ou en fin de process une fois l'intérêt mutuel établi", correct: true },
      { text: "Dès la première minute, avant de se présenter", correct: false },
      { text: "Jamais, c'est tabou", correct: false },
      { text: "Par SMS la veille", correct: false },
    ],
    explanation: "Le salaire se discute une fois que l'intérêt mutuel est posé, souvent à l'initiative du recruteur ou en fin d'entretien. L'aborder trop tôt donne l'impression que seul l'argent t'intéresse.",
    tip: "Laisse d'abord l'entreprise se convaincre de ta valeur.",
  },
  {
    id: 'sal-10', category: 'salaire', difficulty: 2,
    situation: "Le recruteur annonce une fourchette : 26-30 k€.",
    question: "Si votre profil est solide, que viser ?",
    options: [
      { text: "Plutôt le haut de la fourchette, en justifiant par vos atouts", correct: true },
      { text: "Le minimum, par peur de déranger", correct: false },
      { text: "Bien au-dessus du haut annoncé", correct: false },
      { text: "Refuser la fourchette en bloc", correct: false },
    ],
    explanation: "Une fourchette annoncée est une marge de négociation. Avec un bon profil, vise le haut en l'argumentant. Demander le minimum par timidité, c'est laisser de l'argent sur la table.",
    tip: "On négocie à l'intérieur de la fourchette : justifie pourquoi tu mérites le haut.",
  },
  {
    id: 'sal-11', category: 'salaire', difficulty: 2,
    situation: "« Votre prétention est trop élevée pour nous. »",
    question: "La meilleure réaction :",
    options: [
      { text: "Demander la fourchette possible et explorer les avantages avant de décider", correct: true },
      { text: "Baisser immédiatement de moitié", correct: false },
      { text: "Insister sans bouger ni écouter", correct: false },
      { text: "Quitter l'entretien vexé", correct: false },
    ],
    explanation: "Garder le dialogue ouvert est clé : demande leur marge réelle et regarde le package complet. Tu peux ajuster, mais une concession énorme et immédiate dévalue ta première annonce.",
    tip: "Avant de baisser, demande ce qui est possible et ce que couvrent les avantages.",
  },
  {
    id: 'sal-12', category: 'salaire', difficulty: 1,
    situation: "Vous recevez une proposition d'embauche par écrit.",
    question: "La bonne pratique :",
    options: [
      { text: "Prendre le temps de la lire en entier avant de répondre", correct: true },
      { text: "Signer dans la seconde sans rien lire", correct: false },
      { text: "Ignorer le document et appeler pour négocier au téléphone", correct: false },
      { text: "Répondre « non » par réflexe", correct: false },
    ],
    explanation: "Une proposition se lit attentivement : salaire, statut, période d'essai, avantages, horaires. Tu peux demander un délai raisonnable pour réfléchir avant de t'engager.",
    tip: "Il est normal de demander 24 à 48 h de réflexion avant de signer.",
  },
  {
    id: 'sal-13', category: 'salaire', difficulty: 2,
    situation: "Vous voulez négocier mais vous avez peur de « passer pour quelqu'un de vénal ».",
    question: "La bonne perspective :",
    options: [
      { text: "Négocier avec tact est normal et attendu, ça n'a rien de déplacé", correct: true },
      { text: "Ne jamais négocier pour rester sympathique", correct: false },
      { text: "Négocier de façon agressive pour s'imposer", correct: false },
      { text: "Accepter toute offre par politesse", correct: false },
    ],
    explanation: "Les recruteurs s'attendent à une négociation et la respectent quand elle est posée et argumentée. Ne rien oser demander n'est pas vu comme une qualité, plutôt comme un manque de confiance.",
    tip: "Négocier sur des arguments (pas sur l'émotion) reste toujours professionnel.",
  },
  {
    id: 'sal-14', category: 'salaire', difficulty: 2,
    situation: "« Pourquoi demandez-vous ce salaire ? »",
    question: "La meilleure justification :",
    options: [
      { text: "Vos compétences, le marché et la valeur que vous apporterez au poste", correct: true },
      { text: "« Parce que j'ai des crédits à rembourser »", correct: false },
      { text: "« Parce que mon ami gagne ça »", correct: false },
      { text: "« Comme ça, sans raison »", correct: false },
    ],
    explanation: "On justifie une prétention par sa valeur professionnelle et le marché, jamais par ses besoins personnels. L'entreprise paie une contribution, pas des charges privées.",
    tip: "Parle de ce que tu apportes, pas de ce dont tu as besoin.",
  },
  {
    id: 'sal-15', category: 'salaire', difficulty: 1,
    situation: "L'offre vous convient parfaitement.",
    question: "Faut-il quand même négocier à tout prix ?",
    options: [
      { text: "Non : si l'offre est juste et vous satisfait, l'accepter est tout à fait pro", correct: true },
      { text: "Toujours négocier, même une offre excellente", correct: false },
      { text: "Refuser une première fois par principe", correct: false },
      { text: "Demander plus juste pour tester", correct: false },
    ],
    explanation: "Négocier n'est pas une obligation. Si l'offre correspond au marché et à tes attentes, l'accepter avec enthousiasme est parfaitement professionnel. Négocier « pour le sport » peut agacer.",
    tip: "Négocie quand c'est justifié, pas par automatisme.",
  },
  {
    id: 'sal-16', category: 'salaire', difficulty: 3,
    context: "Vous avez deux offres en main. La recruteuse de l'entreprise que vous préférez vous demande vos attentes.",
    situation: "Vous disposez d'une offre concurrente comme levier.",
    question: "Comment l'utiliser ?",
    options: [
      { text: "Mentionner avec tact l'autre offre comme repère, sans menacer ni bluffer", correct: true },
      { text: "Brandir l'autre offre comme un ultimatum", correct: false },
      { text: "Inventer une offre concurrente plus élevée", correct: false },
      { text: "Cacher totalement que vous avez une alternative", correct: false },
    ],
    explanation: "Une offre concurrente réelle est un bon argument si on l'évoque avec tact (« j'ai une proposition à X, mais votre poste m'intéresse davantage »). Bluffer ou menacer peut se retourner contre toi.",
    tip: "Un levier ne fonctionne que s'il reste courtois et vrai.",
  },
  {
    id: 'sal-17', category: 'salaire', difficulty: 2,
    situation: "On vous propose un fixe modeste mais une part variable (commissions).",
    question: "Que vérifier avant d'accepter ?",
    options: [
      { text: "Comment le variable est calculé, s'il est réaliste et atteignable", correct: true },
      { text: "Rien, le variable est forcément un bonus", correct: false },
      { text: "Uniquement le montant maximum théorique", correct: false },
      { text: "Le refuser systématiquement", correct: false },
    ],
    explanation: "Un variable n'a de valeur que s'il est atteignable. Demande les conditions de déclenchement, des exemples réels et la part que touchent les gens en place. Le « maximum théorique » est rarement la réalité.",
    tip: "Demande combien gagnent réellement les salariés du poste, variable inclus.",
  },
  {
    id: 'sal-18', category: 'salaire', difficulty: 1,
    situation: "Pendant la négociation, le ton monte légèrement.",
    question: "La meilleure posture :",
    options: [
      { text: "Rester calme, factuel et courtois quoi qu'il arrive", correct: true },
      { text: "Hausser le ton pour s'imposer", correct: false },
      { text: "Céder immédiatement pour éviter le conflit", correct: false },
      { text: "Faire du chantage", correct: false },
    ],
    explanation: "La négociation reste un échange professionnel. Garder son calme et s'appuyer sur des faits inspire le respect, alors que l'agressivité ou la capitulation desservent toutes les deux ta position.",
    tip: "Respire, reste factuel : le calme est une force en négociation.",
  },
  {
    id: 'sal-19', category: 'salaire', difficulty: 2,
    situation: "Vous décrochez le poste mais le salaire est ferme et non négociable.",
    question: "Sur quoi pouvez-vous encore discuter ?",
    options: [
      { text: "Une révision à échéance, des jours de télétravail, une formation, des congés", correct: true },
      { text: "Rien, tout est bloqué", correct: false },
      { text: "Le salaire, encore et encore", correct: false },
      { text: "Le salaire des collègues", correct: false },
    ],
    explanation: "Si le fixe est gelé, d'autres leviers restent négociables : clause de revoyure (révision après X mois), télétravail, formation, congés. On élargit la discussion au-delà du seul chiffre.",
    tip: "Une clause de révision à 6 mois est souvent acceptée quand le salaire est figé.",
  },
  {
    id: 'sal-20', category: 'salaire', difficulty: 1,
    situation: "Vous acceptez l'offre finale.",
    question: "La bonne manière de conclure :",
    options: [
      { text: "Confirmer clairement, remercier et demander la suite (contrat, date)", correct: true },
      { text: "Disparaître sans répondre", correct: false },
      { text: "Continuer à négocier après avoir dit oui", correct: false },
      { text: "Accepter du bout des lèvres en montrant sa déception", correct: false },
    ],
    explanation: "Conclure proprement laisse une excellente dernière impression : confirme ton accord, remercie et clarifie les prochaines étapes. Revenir négocier après un « oui » abîme la relation qui démarre.",
    tip: "Une fois d'accord, montre ton enthousiasme : ta première impression d'employé démarre ici.",
  },
];
